### ISSUE TITLE
Exercise 3: Unable to pass test case 5

### ISSUE THREAD

**Issue by eesean** [nus-cs2030/2223-s2#101]
Hi all, 

I did not pass the last test case (shape = solid) due to incompatible types, as Solid cannot be converted to Shape3D. Would like to ask if anyone else has encountered a similar problem, as well as advice on how I could resolve it? So far my consensus is that this occurred because there is no relationship between Shape3D and Solid in my implementation.

**Comment by VanyaPriscillia** [comment]
Use inheritance to make relationship between them.

**Comment by eesean** [comment]
Thanks for the advice! Managed to solve it.
