### ISSUE TITLE
Unable to call certain methods in class PQ

### ISSUE THREAD

**Issue by YanQin-Liu** [nus-cs2030/2223-s2#105]
I realised that some methods are not implemented in class PQ:
<img width="548" alt="Screenshot 2023-02-11 at 10 22 39 PM" src="https://user-images.githubusercontent.com/123805062/218263540-969e0a41-0bbf-40b9-a766-f223aa9b6a04.png">

Am I allowed to add additional methods to the PQ class? It does not make sense for PQ, which has a PriorityQueue, to be able to call isEmpty() but not size()

**Comment by eesean** [comment]
Hi, the PQ class we are given is immutable and unbounded, I have checked with my TA and yea we can only refer to methods in the PQ class provided, even though the PQ class in the java documentation has the size( ) method.

On that note I would like to ask if there is a way to check the length of a priority queue? SInce we can't use the size( ) method for the PQ class we were given.

**Comment by guanquann** [comment]
From lab 2, to view documentation:

The given programs PQ.java, Pair.java and ImList.java include javadoc comments. To automatically generate HTML documentation from the comments, issue the command:

> $ javadoc -d doc Pair.java PQ.java ImList.java

You may then navigate through the documentation from allclasses-index.html found in the doc directory.

**Comment by 0liverkong** [comment]
you can do something like class yourQueue, which has pq as a private final attribute. then you can track the size of the pq by adding more functionality to yourQueue.
that being said im not too sure if you need a customQueue to track the size of your eventQueue....

**Comment by aowz** [comment]
I don't think we should add new methods to the PQ class. You can look at the PQ.class documentation using this method shown on CodeCrunch in the Lab #2 page. 
![image](https://user-images.githubusercontent.com/125140598/218269461-dea67ef2-187e-45db-bcac-5e8ffd6916d4.png)

**Comment by territxl** [comment]
I think to track the size, you can introduce new attributes as a way to keep track and hence retrieve the information of the length of the priority queue

**Comment by SimonSeeYongsheng** [comment]
You can try creating your own PQ generic type data structure just like how the Prof did for his ImList.
