### ISSUE TITLE
Test Case 4: Accounting for Additional Waiting Time

### ISSUE THREAD

**Issue by trwstin** [nus-cs2030/2223-s2#106]
# Summary

Unable to account for additional waiting time when there is more than one customer in the queue.

## Description:

Trying to figure out how to account for the additional waiting time required when there is already a customer in queue. I.e. if Customer A is in the queue for Server 1, when Customer B joins the queue their time of service during the Serve Event should be Server 1's finish time + Customer A's service time.

For example in my screenshot below, Customer 4 and 6 are added to the queue while the Server 1 is still serving Customer 3, whose finish time is 2.500. However, since my code does not account for the additional waiting time, it leads to Customer 4 and 6 coming at the same time (2.500) during the Serve Event (Customer 6 should only come in at 3.500 after Customer 4 is done being served).

My original plan was to add customer 4's .getServiceTime() when updating the arrivalTime of Customer A. If I use this method, I can get the correct output. However, since we are recommended to only have getServiceTime() in one location (which I believe means one **method**), I'm stumped as to how to account for the additional waiting time in Customer B.

Any thoughts? :(

## Screenshots
![image](https://user-images.githubusercontent.com/68576751/218267324-6ae96b68-6c72-47e8-8149-cd2d330145ae.png)

**Comment by fy17ohhh** [comment]
Hi, I have encountered the same issue, and when I tried calling getServiceTime() in arrive events only, there are some mismatches for servicetime. (customers get unmatched servicetime other than expected). Seems like we need to find a way to invoke getServiceTime() only in Serve class. still managing to solve the issue :(

**Comment by leezhanpeng** [comment]
The hint that my TA provided was to allow for perpetual wait events. For example the test case in your screenshot, the "wait event" for both customers 4 and 6 are placed in the PQ and both are expected to be served at 2.500. When the time comes, customer 4 checks his expected service time with Server 1's finish time, and both timings should be the same(2.500). That's where Customer 4 is served, and Server 1's finish time is updated to 3.500.

Now that Customer 4 is served, the next in line which is Customer 6 will now check with Server 1. But in this case, its expected service time of 2.500 now clashes with Server 1's end time of 3.500, so a new wait event of customer 6 will be added to the PQ with the new timing of 3.500, replacing the old 2.500. That's where the perpetual "wait event" happens.

Based on your implementation, I would assume you immediately added a "serving event" or equivalent into your PQ immediately after adding customers 4 and 6 in the queue, thus facing this issue. There may be other methods other than the "perpetual waits" that will better suit your current implementation, but nevertheless, I hope it can give you some inspiration!

**Comment by zxciisdbniel** [comment]
I faced the same issues. Here are some of my considerations: 
1. Have to call getServiceTime() in the order they are served in i.e. only should call it just before they are served-> This means that when processing a Wait event, you cannot return a Serve event because you would not be able to determine the time the customer will be served (since you would need to know the service times of all the other customers in the queue)

2. The earliest you will know the Serve timing will be when the Customer just infront of you in the queue gets Served (since I can call getServiceTime() for that Customer) => can only return Serve event & add into PQ when previous Customer in queue processes his Serve event

3. The only definite timing we know is the time when the associated Server is done with their current Customer, we don't know any other timings because we cannot call getServiceTime() for other Customers in the queue

**Comment by guanquann** [comment]
What I did was that at my wait event, I will only return the serve event only if the customer is at the start of  the queue. Else, return the wait event again

**Comment by granolaluvr69** [comment]
> The hint that my TA provided was to allow for perpetual wait events. For example the test case in your screenshot, the "wait event" for both customers 4 and 6 are placed in the PQ and both are expected to be served at 2.500. When the time comes, customer 4 checks his expected service time with Server 1's finish time, and both timings should be the same(2.500). That's where Customer 4 is served, and Server 1's finish time is updated to 3.500.
> 
> Now that Customer 4 is served, the next in line which is Customer 6 will now check with Server 1. But in this case, its expected service time of 2.500 now clashes with Server 1's end time of 3.500, so a new wait event of customer 6 will be added to the PQ with the new timing of 3.500, replacing the old 2.500. That's where the perpetual "wait event" happens.
> 
> Based on your implementation, I would assume you immediately added a "serving event" or equivalent into your PQ immediately after adding customers 4 and 6 in the queue, thus facing this issue. There may be other methods other than the "perpetual waits" that will better suit your current implementation, but nevertheless, I hope it can give you some inspiration!

@leezhanpeng this is actually quite smart, thinking of implementing this, but need to iron out the details first. Would you suggest creating a new event type that is an intermediate step between wait and serve for this?

**Comment by leezhanpeng** [comment]
> @leezhanpeng this is actually quite smart, thinking of implementing this, but need to iron out the details first. Would you suggest creating a new event type that is an intermediate step between wait and serve for this?

@granolaluvr69 I did not create any intermediate event. My wait event just generates itself until the customer can be served. The issue I had with this is that I had to control the number of "X waits at X" being added to the output. If you can implement your wait event to identify whether it was the first time the customer got into the queue then it should be straightforward. Personally, I wouldn't create any additional events, just in case it overcomplicates things when we move on to future labs. Good luck!

**Comment by trwstin** [comment]
Thanks for your input guys. Managed to solve it with @leezhanpeng and @guanquann 's suggestion of returning a Wait event based on the customer's position in the queue. Hopefully it passes the codecrunch private test cases!

**Comment by joshuagohez** [comment]
> 

Can i ask how you would go about managing the number of wait event's toString? Seem to be stuck since we are restricted from using class type identifiers.

**Comment by joshuagohez** [comment]
> > @leezhanpeng this is actually quite smart, thinking of implementing this, but need to iron out the details first. Would you suggest creating a new event type that is an intermediate step between wait and serve for this?
> 
> @granolaluvr69 I did not create any intermediate event. My wait event just generates itself until the customer can be served. The issue I had with this is that I had to control the number of "X waits at X" being added to the output. If you can implement your wait event to identify whether it was the first time the customer got into the queue then it should be straightforward. Personally, I wouldn't create any additional events, just in case it overcomplicates things when we move on to future labs. Good luck!

Can i ask how you would go about managing the number of wait event's toString? Seem to be stuck since we are restricted from using class type identifiers.

**Comment by guanquann** [comment]
> > > @leezhanpeng this is actually quite smart, thinking of implementing this, but need to iron out the details first. Would you suggest creating a new event type that is an intermediate step between wait and serve for this?
> > 
> > 
> > @granolaluvr69 I did not create any intermediate event. My wait event just generates itself until the customer can be served. The issue I had with this is that I had to control the number of "X waits at X" being added to the output. If you can implement your wait event to identify whether it was the first time the customer got into the queue then it should be straightforward. Personally, I wouldn't create any additional events, just in case it overcomplicates things when we move on to future labs. Good luck!
> 
> Can i ask how you would go about managing the number of wait event's toString? Seem to be stuck since we are restricted from using class type identifiers.

Add another parameter called hasPrinted (boolean) to WaitEvent. If it is printed previously, hasPrinted should be true, and toString method will not be called again.

**Comment by joshuagohez** [comment]
> > > > @leezhanpeng this is actually quite smart, thinking of implementing this, but need to iron out the details first. Would you suggest creating a new event type that is an intermediate step between wait and serve for this?
> > > 
> > > 
> > > @granolaluvr69 I did not create any intermediate event. My wait event just generates itself until the customer can be served. The issue I had with this is that I had to control the number of "X waits at X" being added to the output. If you can implement your wait event to identify whether it was the first time the customer got into the queue then it should be straightforward. Personally, I wouldn't create any additional events, just in case it overcomplicates things when we move on to future labs. Good luck!
> > 
> > 
> > Can i ask how you would go about managing the number of wait event's toString? Seem to be stuck since we are restricted from using class type identifiers.
> 
> Add another parameter called hasPrinted (boolean) to WaitEvent. If it is printed previously, hasPrinted should be true, and toString method will not be called again.

Gotcha. Was thinking along those lines too, thought it was too much of a stretch. Cheers.

**Comment by fy17ohhh** [comment]
> I faced the same issues. Here are some of my considerations:
> 
> 1. Have to call getServiceTime() in the order they are served in i.e. only should call it just before they are served-> This means that when processing a Wait event, you cannot return a Serve event because you would not be able to determine the time the customer will be served (since you would need to know the service times of all the other customers in the queue)
> 2. The earliest you will know the Serve timing will be when the Customer just infront of you in the queue gets Served (since I can call getServiceTime() for that Customer) => can only return Serve event & add into PQ when previous Customer in queue processes his Serve event
> 3. The only definite timing we know is the time when the associated Server is done with their current Customer, we don't know any other timings because we cannot call getServiceTime() for other Customers in the queue



> What I did was that at my wait event, I will only return the serve event only if the customer is at the start of the queue. Else, return the wait event again

thx for these ideas guys, after reading these comments I considered more about real life examples when designing (i.e. if you are a customer in queue, you donot rlly know when u will be served until ppl in front of u is SERVED and DONE (after these two events). When doing future designs we could consider more real life exmaples and this would make more sense!

**Comment by j0205m** [comment]
> > @leezhanpeng this is actually quite smart, thinking of implementing this, but need to iron out the details first. Would you suggest creating a new event type that is an intermediate step between wait and serve for this?
> 
> @granolaluvr69 I did not create any intermediate event. My wait event just generates itself until the customer can be served. The issue I had with this is that I had to control the number of "X waits at X" being added to the output. If you can implement your wait event to identify whether it was the first time the customer got into the queue then it should be straightforward. Personally, I wouldn't create any additional events, just in case it overcomplicates things when we move on to future labs. Good luck!

Hi! Can I ask how do you go about updating the new WaitEvent timing without using getServiceTime() from the previous customer? I have thought of this method but I now run into the trouble of having multiple service times generated : (
