### ISSUE TITLE
Too many service times generated debugging

### ISSUE THREAD

**Issue by YanQin-Liu** [nus-cs2030/2223-s2#109]
May I know how to debug this error?
<img width="466" alt="Screenshot 2023-02-12 at 12 24 30 PM" src="https://user-images.githubusercontent.com/123805062/218292940-56183b39-f545-494b-a550-0c455a55cda6.png">
I called getServiceTime() and serviceTime.get() only once in my entire code and it is still giving me this error. Does anyone know what is CodeCrunch actually checking for?

Edit:
Is codecrunch checking for invocation of getserviceTime() or serviceTime.get() method?
Is it checking for invocation for EVERY Customer or every Customer that is SERVED?

**Comment by guanquann** [comment]
You can print out getServiceTime() to see how many times u are actually calling it. If you have 5 customers, getServiceTime() should only be called 5 times, 1 for each customer

**Comment by VanyaPriscillia** [comment]
I also face that issue. I have checked that the number of occurrences of “getservicetime” was the same as the number of customers who were served. However, when I submit in codecrunch, the “Too many service times generated” occurs.

**Comment by YanQin-Liu** [comment]
> You can print out getServiceTime() to see how many times u are actually calling it. If you have 5 customers, getServiceTime() should only be called 5 times, 1 for each customer
> 
> You can refer to: #100, I believe it’s the exact same issue as u

I have checked, it is only called once per customer. Now my question is :
Is codecrunch checking for invocation of getserviceTime() or serviceTime.get() method?
Is it checking for invocation for EVERY Customer or every Customer that is SERVED?

**Comment by jhsoh** [comment]
> > You can print out getServiceTime() to see how many times u are actually calling it. If you have 5 customers, getServiceTime() should only be called 5 times, 1 for each customer
> > You can refer to: #100, I believe it’s the exact same issue as u
> 
> I have checked, it is only called once per customer. Now my question is : Is codecrunch checking for invocation of getserviceTime() or serviceTime.get() method? Is it checking for invocation for EVERY Customer or every Customer that is SERVED?

You should only invoke it for x times if there are x customers being served. So if there are 10 customers but only 8 are being served, it should only be invoked for 8 times.

**Comment by zxciisdbniel** [comment]
I believe strictly speaking it is serviceTime.get(), not whatever getServiceTime() method that you implemented.

**Comment by shuyaoao** [comment]
I also faced the same issue :(( I only used serviceTime.get() in my Arrival class getNextEvent method twice under two mutually exclusive conditions so it should only call once for every Arrival event initialised, not sure why it doesn't work...

**Comment by jhsoh** [comment]
> I also faced the same issue :(( I only used serviceTime.get() in my Arrival class getNextEvent method twice under two mutually exclusive conditions so it should only call once for every Arrival event initialised, not sure why it doesn't work...

You shouldnt be using the servicetime.get() in arrival class, otherwise you would be generating service time for customers who eventually leaves and are not served, which shouldnt be the case. It should only be invoked in the serve class

**Comment by shuyaoao** [comment]
> > I also faced the same issue :(( I only used serviceTime.get() in my Arrival class getNextEvent method twice under two mutually exclusive conditions so it should only call once for every Arrival event initialised, not sure why it doesn't work...
> 
> You shouldnt be using the servicetime.get() in arrival class, otherwise you would be generating service time for customers who eventually leaves and are not served, which shouldnt be the case. It should only be invoked in the serve class

But I only call get() after I checked whether customer could be served(either one server is free or one queue is not full), and if cannot be served I do not call get().

**Comment by jhsoh** [comment]
> > > I also faced the same issue :(( I only used serviceTime.get() in my Arrival class getNextEvent method twice under two mutually exclusive conditions so it should only call once for every Arrival event initialised, not sure why it doesn't work...
> > 
> > 
> > You shouldnt be using the servicetime.get() in arrival class, otherwise you would be generating service time for customers who eventually leaves and are not served, which shouldnt be the case. It should only be invoked in the serve class
> 
> But I only call get() after I checked whether customer could be served(either one server is free or one queue is not full), and if cannot be served I do not call get().

Did you try to print the get() method and check that it is only printed x number of times, if only x customers are served?

**Comment by shuyaoao** [comment]
> > > > I also faced the same issue :(( I only used serviceTime.get() in my Arrival class getNextEvent method twice under two mutually exclusive conditions so it should only call once for every Arrival event initialised, not sure why it doesn't work...
> > > 
> > > 
> > > You shouldnt be using the servicetime.get() in arrival class, otherwise you would be generating service time for customers who eventually leaves and are not served, which shouldnt be the case. It should only be invoked in the serve class
> > 
> > 
> > But I only call get() after I checked whether customer could be served(either one server is free or one queue is not full), and if cannot be served I do not call get().
> 
> Did you try to print the get() method and check that it is only printed x number of times, if only x customers are served?

I did, truly it did get() more times than necessary but I'm not sure why and how to fix the logic

**Comment by jhsoh** [comment]
> > > > > I also faced the same issue :(( I only used serviceTime.get() in my Arrival class getNextEvent method twice under two mutually exclusive conditions so it should only call once for every Arrival event initialised, not sure why it doesn't work...
> > > > 
> > > > 
> > > > You shouldnt be using the servicetime.get() in arrival class, otherwise you would be generating service time for customers who eventually leaves and are not served, which shouldnt be the case. It should only be invoked in the serve class
> > > 
> > > 
> > > But I only call get() after I checked whether customer could be served(either one server is free or one queue is not full), and if cannot be served I do not call get().
> > 
> > 
> > Did you try to print the get() method and check that it is only printed x number of times, if only x customers are served?
> 
> I did, truly it did get() more times than necessary but I'm not sure why and how to fix the logic

Maybe you cant call it in 2 different conditions, you can try to remove the get() in 1 of the condition and see if it prints the correct number of times
