### ISSUE TITLE
Issues Setting up Docker Desktop

### ISSUE THREAD

**Issue by displeasedcat** [nus-cs2030/2223-s2#11]
Hi, I am facing issues setting up the Docker Desktop while following the guide. 
I am running Windows 11, my Docker version is 20.10.22, build 3a2c30b. I have tried installing WSL but it did not resolve the problem. I have also tried reinstalling the docker a few times.

When I run the line in terminal : docker pull ghcr.io/nus-cs2030/cs2030:latest
I get the error message as below:

C:\Users\senin>docker pull ghcr.io/nus-cs2030/cs2030:latest
error during connect: This error may indicate that the docker daemon is not running.: Post "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/images/create?fromImage=ghcr.io%2Fnus-cs2030%2Fcs2030&tag=latest": open //./pipe/docker_engine: The system cannot find the file specified.

My Docker desktop is also stuck on Docker Desktop starting...

How should I proceed?

**Comment by danqiye1** [comment]
Hi, issue #9 seem to be a similar issue. See if that helps.

**Comment by displeasedcat** [comment]
Thanks, I fixed the issue by changing virtualisation options in the BIOS
