### ISSUE TITLE
Checkstyle  [EmptyLineSeparator]

### ISSUE THREAD

**Issue by kayeugenia** [nus-cs2030/2223-s2#113]
Hi guys! when i'm trying to create an interface, i did not leave a space before specifying my method. I changed it already to leaving one line space before and after method specification but i still got this error: 

[WARN] /tmp/home/Solid.java:3:5: 'METHOD_DEF' should be separated from previous line. [EmptyLineSeparator]

Anyone knows how to fix this issue?

**Comment by poon-zx** [comment]
i think maybe you did not separate the different methods that you implemented in your interface, there should be one empty line gap between them!

**Comment by granolaluvr69** [comment]
Remember to leave a line after your first line.
```java
interface Event {

double getTimestamp();

Customer getCustomer();
}
```
Like this, for example.
