### ISSUE TITLE
Lab 3 formatting issue of double when double value is 0.0

### ISSUE THREAD

**Issue by ianwonghanli** [nus-cs2030/2223-s2#114]
Hi all. Faced this issue when the double value is 0.0 and is passed through String.format("%3.f", doubleValue). Attached is the screenshot of the issue im facing in codecrunch. Anyone has any idea on how to properly format the doubleValue? Help is much appreciated!

![Screenshot 2023-02-12 172959](https://user-images.githubusercontent.com/99638949/218303163-3cde54c7-9659-4d3e-9186-a08920be0f6b.png)

**Comment by jhsoh** [comment]
If the number of served customers is 0, then division by 0 will give nan. You need to check if number of served customers is 0, then return 0

**Comment by ianwonghanli** [comment]
> If the number of served customers is 0, then division by 0 will give nan. You need to check if number of served customers is 0, then return 0

thanks jhsoh! i figured out that i was blindly dividing the waiting time average with the number of customers served blindly without considering the edgecase when the customers served is 0.
