### ISSUE TITLE
[Lab 3] Error Messages during Test Runs

### ISSUE THREAD

**Issue by cweisong** [nus-cs2030/2223-s2#116]
Several error messages appeared after calling test cases for Lab 3 (as seen in the screenshot below)
Would like to clarify those error messages and possible solutions to it.

Thank you in advance!

![Screenshot 2023-02-12 at 8 46 04 PM Small](https://user-images.githubusercontent.com/122463025/218312346-99cd5416-f5bb-4af9-ae36-7d0eb0712999.jpeg)

**Comment by cweisong** [comment]
Nope, I have already updated all test inputs as shown in CodeCrunch Lab 3

**Comment by cweisong** [comment]
Nope, I have already updated all test inputs as shown in CodeCrunch Lab 3

**Comment by guanquann** [comment]
Either you are using old 3.in or old Main.java

**Comment by cweisong** [comment]
Solved the issue. 
Thanks both!
