### ISSUE TITLE
Ex2 Level 4 private cases

### ISSUE THREAD

**Issue by syafiq9326** [nus-cs2030/2223-s2#117]
# Summary

Hi, I am having some issues clearing ex2 level 4 private cases, was wondering if anyone had the same issue.

## Description:

The gist of the issue is my loader id is jumping as shown in the ss below.

## Code Snippets
I have 3 lists (arrive, expired and output), output essentially being the list to track my events. A loader_Id is initialised as 1. Each time (2) and (3) loops runs, loaderId is incremented by 1 and loaderQty deduced by 1.

My logic is pseudocode is as such:

For every cruiseObj in cruiselist, a loaderQty is fetched based off the cruiseObj.

1) i first look thru services in arriveList, if done put to expiredList, remove from arriveList.

2) Using a for loop with range being size of expiredList and where loaderQty is more than 0 and , I will then look thru the expiredList. A loader is then taken out of the expired list and used for our incoming cruiseobj. A service is then initialised and added to the output and active lists.

3) While the loaders needed are more than 0, i create new serve events based off the loaderId at that point of time and cruiseobj and add it to activelist and outputlist

To take care of iterating through both lists and changing its size , I did an i-- each time. It seems to work out fine for all the pdf cases so I can't seem to wrap my head around this, was hoping to see if anyone had a similar issue.

Thanks in advance!

## Screenshots

![ex2](https://user-images.githubusercontent.com/50677984/218318065-6bd1c705-9139-4e5b-9934-0e81ff7ba890.png)

**Comment by aa01xx** [comment]
Hi, I think maybe your total number of loaders used is not tracked correctly? This will affect the loader num added to New serve when more loaders are needed. Make sure your algorithm only add to TotalNumOfLoaders when new loaders are made under point 3.

**Comment by syafiq9326** [comment]
Ah okay I spot it, thanks!
