### ISSUE TITLE
Exercise 1 Test Case 5

### ISSUE THREAD

**Issue by tjdbryan** [nus-cs2030/2223-s2#118]
Hi guys!

I'm unable to pass test case 5 as shown below... I have changed the logic in main.jsh (distPQ <**=** 2.0 + epsilon) and in Circle.java under the contains() method but the output is still incorrect.

![image](https://user-images.githubusercontent.com/122286169/218319943-a5899b6d-6a98-48c9-bd6b-a6d29abe05e4.png)

Anyone experiencing the same issue and managed to solve it? 

Thanks! 😀

**Comment by geoffong11** [comment]
May not be related to your issue, but I think it might be < 2 + epsilon, not <=. I think there may be an issue with createUnitCircle. Check if you add the angle with pi/2 instead of minus (I faced errors when doing that because I pressed wrong).

**Comment by tjdbryan** [comment]
Hi, you're right! It works when I replace the whole chunk of code in main.jsh with createUnitCircle. Thanks!

**Comment by Adem121** [comment]
I am also failing test cases 5_3, 5_4 and 5_6. Can you elaborate more on what did you replace and how?

**Comment by tjdbryan** [comment]
Hi, if you follow the question, you should have created a createUnitCircle method in main.jsh. The original code given in main.jsh has a chunk of code that is very similar to main.jsh. Basically, you just need to delete that chunk of code and replace it with a method call to invoke createUnitCircle. It should work if your createUnitCircle method is correct.

**Comment by Adem121** [comment]
Yup you are right, I have replaced calculations with createUnitCircle and it worked. Thankss!
