### ISSUE TITLE
handling wait/queue events

### ISSUE THREAD

**Issue by ringleading** [nus-cs2030/2223-s2#119]
# Summary

got stuck on handling wait/queue events

## Description:

finding it hard to properly time the wait/queue event when there is already another person in the queue, given the restriction to only generate service times once

currently initialising Wait events while handling arrivals and can't seem to figure out how to increment the server's `NextAvailableTime` without generating an additional service time.

essentially if there's 2 in the queue, they both get served at the same time

attached a screenshot below as to the test case fail to better describe my issue 

## Screenshots
![image](https://user-images.githubusercontent.com/101489033/218331623-86efd07f-69a2-4dcc-b273-0ac54e93dee0.png)

**Comment by j0205m** [comment]
> # Summary
> got stuck on handling wait/queue events
> 
> ## Description:
> finding it hard to properly time the wait/queue event when there is already another person in the queue, given the restriction to only generate service times once
> 
> currently initialising Wait events while handling arrivals and can't seem to figure out how to increment the server's `NextAvailableTime` without generating an additional service time.
> 
> essentially if there's 2 in the queue, they both get served at the same time
> 
> attached a screenshot below as to the test case fail to better describe my issue
> 
> ## Screenshots
> ![image](https://user-images.githubusercontent.com/101489033/218331623-86efd07f-69a2-4dcc-b273-0ac54e93dee0.png)

Hi! Can I know how did you manage to solve this issue? currently facing the same problem with initialising my WaitEvent when there is more than one in the queue : (
