### ISSUE TITLE
Clarification regarding setting up of checkstyle

### ISSUE THREAD

**Issue by eesean** [nus-cs2030/2223-s2#12]
Hi, I would like to clarify the following with regards to the setting up of checkstyle:

1. For the downloading of checkstyle files in the first part (see screenshot attached), are the following commands to be executed on Windows Command Prompt (as I am using Windows laptop), or can this be done on Ubuntu?
2. How do I check whether the checkstyle files are in the folder that is mounted to my docker container's /workspace? I have downloaded both files as per part 1 via Ubuntu, however the folder mounted to my docker container's /workspace remains empty.

Edit: I have moved both files manually to the desired folder instead, however I am not able to access the checkstyle file.

<img width="959" alt="checkstyle" src="https://user-images.githubusercontent.com/110977266/212520288-bdc7e96c-8dc5-4a70-bdb6-9caa443b9059.png">

**Comment by JYeoZS** [comment]
Hi, 

Am assuming you've gone to stage of adding files to docker workspace folder...

1. Go to containers in Docker, click run.
2. Create a java file in same folder as 2 checkstyle files. Add some java into the file. [simple hello world code, etc. something to audit.]

3. Go to windows command line, fire up docker:

 docker exec -it -w /workspace [container name] /bin/bash

4. run checkstyle command as per point 3 in your photo.

Hope it works now. Suspect maybe you left out step of running docker or executing docker on command line. Either that or there's no java files to audit in checkstyle folder hence no effect observed.

Cheers.

**Comment by eesean** [comment]
Hi,

Thanks for the insight, is this the output that I should be see (screenshot attached)?

<img width="948" alt="Screenshot 2023-01-16 172338" src="https://user-images.githubusercontent.com/110977266/212643264-24d0e0ea-c6d7-4bc9-8e49-47b47a38f55b.png">

**Comment by danqiye1** [comment]
Yep. That would be checkstyle telling you about coding style violations.

**Comment by eesean** [comment]
Thanks for the help!
