### ISSUE TITLE
Ex 3 immutable class

### ISSUE THREAD

**Issue by yuzujy** [nus-cs2030/2223-s2#120]
Hi can i ask does an immutable class mean that it cannot be extended and that it must have a "final" ?
so for eg for level 2 it should be final Cuboid class { ..... and that SolidCuboid cannot be a child class of Cuboid?

**Comment by weitatftw** [comment]
an immutable class can be extended by a child class. its properties needs to be set to private final for it to be immutable and you need to return a new child class object if you intend to change any of its properties
