### ISSUE TITLE
Help clearing test case 5

### ISSUE THREAD

**Issue by limrik** [nus-cs2030/2223-s2#125]
![photo_2023-02-13 17 06 07](https://user-images.githubusercontent.com/64995992/218415922-be575a63-0651-4250-802d-34770c80d241.jpeg)]

Hi guys, having difficulties clearing test case 5, would appreciate some help, thanks!

**Comment by weitatftw** [comment]
the order in which you process the events appears to be incorrect. i faced the same issue and i solved it after identifying the code that was causing the defective ordering of events

**Comment by limrik** [comment]
thanks! @weitatftw
