### ISSUE TITLE
Javadoc comments 

### ISSUE THREAD

**Issue by shionhigashi** [nus-cs2030/2223-s2#127]
When do we have to include javadoc comments? Checkstyle only flags out some methods/ constructors/ classes for me when i miss out javadoc comments so is there a general rule of when we have to write them in?

**Comment by Lofthesaver** [comment]
Hi, If I'm not mistaken, there shouldn't be a need to include any Javadoc comments; if Checkstyle states that you are missing Javadoc comments, it may mean that you have declared a class `public`, just remove the `public` and it should be fine.
