### ISSUE TITLE
Server Serves Multiple People

### ISSUE THREAD

**Issue by weitatftw** [nus-cs2030/2223-s2#128]
# Summary

I've been trying to implement an intermediate event that will determine whether a customer is ready to be served after queueing and my server starts to serve multiple people. Can anyone help me with this issue? 

## Screenshots
<img width="144" alt="Screenshot 2023-02-14 at 1 37 58 PM" src="https://user-images.githubusercontent.com/79369027/218649128-8efee569-0512-4237-8056-622279390304.png">

**Comment by timothysashimi** [comment]
maybe you can include a boolean in the server? If it is false then the server is not available and not able to serve anyone else. Just a suggestion!

**Comment by weitatftw** [comment]
i've tried to use a boolean operator like you suggested but then my server stops serving after the server is done serving a customer, can anyone help me with this too?
<img width="180" alt="Screenshot 2023-02-14 at 3 57 08 PM" src="https://user-images.githubusercontent.com/79369027/218674442-67c42c45-6caa-4650-b5e5-137d96886838.png">

**Comment by weitatftw** [comment]
hi, thanks for the help so far! now i'm stuck since the server will finish serving the customer at the same time as the time which it begins serving that same customer. Can anyone help me with this?
<img width="183" alt="Screenshot 2023-02-14 at 5 05 40 PM" src="https://user-images.githubusercontent.com/79369027/218689634-7a87bf48-0626-47db-9ae4-bd7801db2e8e.png">

**Comment by granolaluvr69** [comment]
What I did to circumvent this was to have wait generate an intermediate event in the case that the customer's position was not the first in the queue, and it has an empty toString, so your customer 6 would be served at the correct time after checking against the server's updated time available.

**Comment by JYeoZS** [comment]
@granolaluvr69 Hi, for your method, would there be problem of exceeding time limit?

For example, if there are 10 customers ahead of you, wouldn't the system throw 9 empty toString events before one can finally be served? [exponentially increased by number of people in queue?]

Thanks.

**Comment by weitatftw** [comment]
@JYeoZS I used the intermediate event method and it didn't exceed the time limit

**Comment by weitatftw** [comment]
thank you all for the help! i've managed to debug my code
