### ISSUE TITLE
Lab 3 - Test Case 7

### ISSUE THREAD

**Issue by hhuilingg** [nus-cs2030/2223-s2#130]
I'm not sure why the issue occurs. It seems that the getServiceTime is incorrect when 2.958 6 serves by 2 and ends up 3.373 6 done serving by 2, but should be 3.222 instead. Does anybody have any idea what causes this issue? (but my previous few serves and done serving timing are correct.)

<img width="292" alt="image" src="https://user-images.githubusercontent.com/66964985/218720068-e394321f-071a-430b-ad7c-50de152b8e9f.png">

**Comment by granolaluvr69** [comment]
This is a issue which is likely tied to the number of times you call customer.getServiceTime() in your main method. To debug this, you can put a println statement in your customer's getServiceTime() method to check the number of times that it is called, and if the number of lines printed out does not correspond to the number of customers, that is the error you should aim to remedy.

**Comment by hhuilingg** [comment]
> This is a issue which is likely tied to the number of times you call customer.getServiceTime() in your main method. To debug this, you can put a println statement in your customer's getServiceTime() method to check the number of times that it is called, and if the number of lines printed out does not correspond to the number of customers, that is the error you should aim to remedy.

thankyou so much!! but is there any chance if you know what test case can track this? as I have checked all the test case given, the number of lines printed out is correspond to the number of customers

**Comment by granolaluvr69** [comment]
I think this test case is a test case where they start to use the supplier interface to supply service times which are no longer constant, so I'm not entirely sure how you could emulate that on your own.

**Comment by hhuilingg** [comment]
> I think this test case is a test case where they start to use the supplier interface to supply service times which are no longer constant, so I'm not entirely sure how you could emulate that on your own.

hmm yeap seems so... thankyou so much for your help! i will try figure out!

**Comment by Jovan131** [comment]
Are you calling getServiceTime() in Arrive class? Because I did the same and ended up with a similar error, think the only way to fix it is to call getServiceTime() in only Serve class.

**Comment by hhuilingg** [comment]
> Are you calling getServiceTime() in Arrive class? Because I did the same and ended up with a similar error, think the only way to fix it is to call getServiceTime() in only Serve class. 

oo alright! thankyou!
