### ISSUE TITLE
Can i change the value of an ImList variable inside my constructor?

### ISSUE THREAD

**Issue by briannoelkesuma** [nus-cs2030/2223-s2#132]
For context, i have an ImList of Customers in my Server as a constructor. e.g. Server(ImList<Customer> ()) but I want to add values to that Imlist and have it attached to the server.
I have tried to create a new instance but it did not work.

**Comment by trwstin** [comment]
after creating a new instance, did you ensure that it was properly assigned back to the serverlist where your servers are stored?

**Comment by JYeoZS** [comment]
1. Create new customer
2. create new ImList of customer, with new customer involved.
3. create new server with new ImList of customer.

Something wrong with your assignment hierarchy?

Cheers.

**Comment by cocopear** [comment]
Have you tried creating a new instance of ImList<Customer> and assigning the ImList back to the Server?
