### ISSUE TITLE
Wait event implementation

### ISSUE THREAD

**Issue by sethteo** [nus-cs2030/2223-s2#134]
hi guys has anyone tried not using creating a new kind of waitevent like a continuewaiting event and instead just use 1 waitevent, can anyone share like the main idea of such an implementation (just having 1 waitevent class)

**Comment by trwstin** [comment]
Hi, I'm assuming you mean like a Wait event which returns a new Wait event if it's not the customer's turn?

The wait event should take in attributes which point to a customer, server and a boolean. The purpose of this boolean is to prevent repeated printing of toString.

in the execute method, I first ensure that the server's queue is not empty. Afterwards, I check if the customer ID is first in queue. If so, I update this customer's arrival time to match the server's next available time. Then I create a Serve event with the respective details.

Otherwise, if the customer is not first in queue, I return a Wait event again, but still update its arrival time to the server's next available time. This is also where your boolean comes in to ensure that the toString() of this event is not re-printed.

**Comment by JYeoZS** [comment]
to add on, your toString() for waitEvent can still have an output for case where one is not next in line, but somehow, you have to filter off those outputs for your final string output.

Cheers.

**Comment by sethteo** [comment]
> Hi, I'm assuming you mean like a Wait event which returns a new Wait event if it's not the customer's turn?
> 
> The wait event should take in attributes which point to a customer, server and a boolean. The purpose of this boolean is to prevent repeated printing of toString.
> 
> in the execute method, I first ensure that the server's queue is not empty. Afterwards, I check if the customer ID is first in queue. If so, I update this customer's arrival time to match the server's next available time. Then I create a Serve event with the respective details.
> 
> Otherwise, if the customer is not first in queue, I return a Wait event again, but still update its arrival time to the server's next available time. This is also where your boolean comes in to ensure that the toString() of this event is not re-printed.

Thank you :)

**Comment by sethteo** [comment]
> to add on, your toString() for waitEvent can still have an output for case where one is not next in line, but somehow, you have to filter off those outputs for your final string output.
> 
> Cheers.

Thank you!!

**Comment by SimonSeeYongsheng** [comment]
There is one way where you don't have to keep throwing wait events.

In the serve event, if you find that the server has another waiting customer other than the customer to be served,
You can input two serve events in the PQ, one for the customer to be served and the next waiting customer.
(This can be done because you already know the end time of the customer to be served, which is also the arrival time of the next waiting customer)

In the wait event, if you find that the server is occupied, but there are no waiting customers in the server.
You can input a serve event into the PQ. 
(This can be done because the occupied server has an ending time, which is also the arrival time of the waiting customer to be served)

Hope this helps

**Comment by cocopear** [comment]
> Hi, I'm assuming you mean like a Wait event which returns a new Wait event if it's not the customer's turn?
> 
> The wait event should take in attributes which point to a customer, server and a boolean. The purpose of this boolean is to prevent repeated printing of toString.
> 
> in the execute method, I first ensure that the server's queue is not empty. Afterwards, I check if the customer ID is first in queue. If so, I update this customer's arrival time to match the server's next available time. Then I create a Serve event with the respective details.
> 
> Otherwise, if the customer is not first in queue, I return a Wait event again, but still update its arrival time to the server's next available time. This is also where your boolean comes in to ensure that the toString() of this event is not re-printed.

hi, i tried this method but ended up with an infinite loop when trying to return a Wait event with updated arrival time. any tips on how to fix this issue?

**Comment by trwstin** [comment]
> > Hi, I'm assuming you mean like a Wait event which returns a new Wait event if it's not the customer's turn?
> > The wait event should take in attributes which point to a customer, server and a boolean. The purpose of this boolean is to prevent repeated printing of toString.
> > in the execute method, I first ensure that the server's queue is not empty. Afterwards, I check if the customer ID is first in queue. If so, I update this customer's arrival time to match the server's next available time. Then I create a Serve event with the respective details.
> > Otherwise, if the customer is not first in queue, I return a Wait event again, but still update its arrival time to the server's next available time. This is also where your boolean comes in to ensure that the toString() of this event is not re-printed.
> 
> hi, i tried this method but ended up with an infinite loop when trying to return a Wait event with updated arrival time. any tips on how to fix this issue?

What exactly is looping?

**Comment by cocopear** [comment]
> > > Hi, I'm assuming you mean like a Wait event which returns a new Wait event if it's not the customer's turn?
> > > The wait event should take in attributes which point to a customer, server and a boolean. The purpose of this boolean is to prevent repeated printing of toString.
> > > in the execute method, I first ensure that the server's queue is not empty. Afterwards, I check if the customer ID is first in queue. If so, I update this customer's arrival time to match the server's next available time. Then I create a Serve event with the respective details.
> > > Otherwise, if the customer is not first in queue, I return a Wait event again, but still update its arrival time to the server's next available time. This is also where your boolean comes in to ensure that the toString() of this event is not re-printed.
> > 
> > 
> > hi, i tried this method but ended up with an infinite loop when trying to return a Wait event with updated arrival time. any tips on how to fix this issue?
> 
> What exactly is looping?

seems to be the new Wait event with the updated arrival time

**Comment by trwstin** [comment]
> > > > Hi, I'm assuming you mean like a Wait event which returns a new Wait event if it's not the customer's turn?
> > > > The wait event should take in attributes which point to a customer, server and a boolean. The purpose of this boolean is to prevent repeated printing of toString.
> > > > in the execute method, I first ensure that the server's queue is not empty. Afterwards, I check if the customer ID is first in queue. If so, I update this customer's arrival time to match the server's next available time. Then I create a Serve event with the respective details.
> > > > Otherwise, if the customer is not first in queue, I return a Wait event again, but still update its arrival time to the server's next available time. This is also where your boolean comes in to ensure that the toString() of this event is not re-printed.
> > > 
> > > 
> > > hi, i tried this method but ended up with an infinite loop when trying to return a Wait event with updated arrival time. any tips on how to fix this issue?
> > 
> > What exactly is looping?
> 
> seems to be the new Wait event with the updated arrival time

So when you say 'infinite loop', you mean your new Wait event is continuously being removed and added into the PQ? 

Do you do your updating of PQ in Simulator or the Event classes?

**Comment by cocopear** [comment]
> > > > > Hi, I'm assuming you mean like a Wait event which returns a new Wait event if it's not the customer's turn?
> > > > > The wait event should take in attributes which point to a customer, server and a boolean. The purpose of this boolean is to prevent repeated printing of toString.
> > > > > in the execute method, I first ensure that the server's queue is not empty. Afterwards, I check if the customer ID is first in queue. If so, I update this customer's arrival time to match the server's next available time. Then I create a Serve event with the respective details.
> > > > > Otherwise, if the customer is not first in queue, I return a Wait event again, but still update its arrival time to the server's next available time. This is also where your boolean comes in to ensure that the toString() of this event is not re-printed.
> > > > 
> > > > 
> > > > hi, i tried this method but ended up with an infinite loop when trying to return a Wait event with updated arrival time. any tips on how to fix this issue?
> > > 
> > > 
> > > What exactly is looping?
> > 
> > 
> > seems to be the new Wait event with the updated arrival time
> 
> So when you say 'infinite loop', you mean your new Wait event is continuously being removed and added into the PQ?
> 
> Do you do your updating of PQ in Simulator or the Event classes?

yes, when i try to return a new Wait event, its execute method will always skip the if condition (if the customer is next in queue, return Serve event) and return a new Wait event again. 
i add events to my PQ in the execute method, but update the PQ in the simulator class.

**Comment by trwstin** [comment]
> yes, when i try to return a new Wait event, its execute method will always skip the if condition (if the customer is next in queue, return Serve event) and return a new Wait event again. 
> i add events to my PQ in the execute method, but update the PQ in the simulator class.

What are you putting in your if condition? (i.e. how are you checking if a customer is next in queue)

Sounds like that's the issue here 🧐
