### ISSUE TITLE
How to on my autoindentation in vim 

### ISSUE THREAD

**Issue by reinatng10** [nus-cs2030/2223-s2#137]
<img width="560" alt="Screenshot 2023-02-15 at 8 25 37 PM" src="https://user-images.githubusercontent.com/124559667/219026938-00dcb624-69bc-47d7-9bd9-4121371725c5.png">

Hello does anyone know how to fix this issue? Suddenly my vim auto indentation is off with purple ~ at the side

**Comment by sp4ce-cowboy** [comment]
Make a file titled .vimrc in your home directory (/Users/<username>) and then try copying the contents of the .vimrc file from the CS2030 repo and past it into the file. 

Are you using docker or your own terminal? If you're using docker it should already be configured I think.

**Comment by jamiepngg** [comment]
Hi reina, you can try doing this: 
First, esc insert mode. then, in command mode, enter ":set autoindent".

otherwise, you should try opening docker in your terminal first before editing your vim file, it should already have auto indentation set there. cheers
