### ISSUE TITLE
Private Test Case 8 

### ISSUE THREAD

**Issue by syafiq9326** [nus-cs2030/2223-s2#141]
# Summary
Private Test case 8

## Description:
Hi, I am wondering if anyone is failing private test case 8 as well? I am not sure what exactly is causing the error of a blank statement since all pdf and previous private test cases worked fine on codecrunch.  I have already filtered out the outputs for my intermediate event (between Wait and Serve) as well so I can't seem to spot the issue.

Thanks in advance!

## Screenshots

![image](https://user-images.githubusercontent.com/50677984/219161864-6f6fb142-bbe2-495f-aa63-8c200b5f1dae.png)

**Comment by weitatftw** [comment]
i believe it's the division by zero error, you need to account for when the number of customers waiting in a queue is equal to 0

**Comment by jhsoh** [comment]
Does your code works correctly when there are no servers?

**Comment by granolaluvr69** [comment]
Just put an if condition that checks if number of servers is equal to zero, and set average waiting time to zero, customers served to zero, and customers left equal to the size of arrival times.

**Comment by syafiq9326** [comment]
Spot on guys, thanks!
