### ISSUE TITLE
Tried fixing the problem of different servicetime other than 1sec by refering serviceTime to this.serviceTime

### ISSUE THREAD

**Issue by Delocy** [nus-cs2030/2223-s2#143]
# Summary

Description of the question / problem here.

## Description:
UPDATE:
Managed to pass test case 5 and 6 but now have the same error saying too many default service time created
Clarifications or details with respect to the issue you are facing

## Code Snippets

Attach code snippets (if any)

## Screenshots
![IMAGE 2023-02-16 15:09:04](https://user-images.githubusercontent.com/94375191/219293198-10ff9c06-dea7-4041-a84a-8a4de2afff5c.jpg)

Screenshots (if any)

**Comment by Xequil1** [comment]
I think the problem is that you had several classes calling the get method.
You can refer to this post for more clarification #124

**Comment by sethteo** [comment]
What I did was use a get method in your customer which calls the get of the Supplier class.

**Comment by Delocy** [comment]
> I think the problem is that you had several classes calling the get method.
> 
> You can refer to this post for more clarification #124

**Comment by Delocy** [comment]
> I think the problem is that you had several classes calling the get method.
> 
> You can refer to this post for more clarification #124 

I only used getSt once and only in my simulator class where i assigned it to a double variable and used to for the rest but this error still persist

**Comment by Xequil1** [comment]
> > I think the problem is that you had several classes calling the get method.
> > You can refer to this post for more clarification #124
> 
> I only used getSt once and only in my simulator class where i assigned it to a double variable and used to for the rest but this error still persist

Once for each customer that will be served or once for every customer?

**Comment by Delocy** [comment]
> > > I think the problem is that you had several classes calling the get method.
> 
> > > You can refer to this post for more clarification #124
> 
> > 
> 
> > I only used getSt once and only in my simulator class where i assigned it to a double variable and used to for the rest but this error still persist
> 
> 
> 
> Once for each customer that will be served or once for every customer?

I did it for every customer, oh are we supposed to only create for customers that gets served

**Comment by Xequil1** [comment]
> I did it for every customer, oh are we supposed to only create for customers that gets served

Yea only call the method when the customer is getting served.

**Comment by hengbl** [comment]
What I did was to overload my Customer constructor with an extra argument which is the double serviceTime. When a customer is being served, I will create a new Customer with the additional argument by calling the supplier.get(). In this case, the actual serviceTime will be stored as an attribute and I can retrieved it readily without the need for calling get() again.

**Comment by hhuilingg** [comment]
you may also want to just get the servicetime only at serve event class to make sure that it only runs once which is during the serve event
