### ISSUE TITLE
ex 2: use of restricted API detected

### ISSUE THREAD

**Issue by xj8423** [nus-cs2030/2223-s2#144]
hii anyone knows how to resolve this :'(

<img width="605" alt="Screenshot 2023-02-16 at 3 54 33 PM" src="https://user-images.githubusercontent.com/122519244/219302488-2f8c600d-e9ab-44a7-9436-5c3cf9c764db.png">

**Comment by hhuilingg** [comment]
did u use the api? if yes i think u need remove it

**Comment by xj8423** [comment]
> did u use the api? if yes i think u need remove it

ah thanks i got it! turns out i forgot to make my constants private static final
