### ISSUE TITLE
ex3 test case 6 unable to pass it

### ISSUE THREAD

**Issue by sporobolous** [nus-cs2030/2223-s2#146]
# Summary
Unable to pass test case 6, both Solid and Shape are interfaces for me.

## Screenshots (if any): 
<img width="729" alt="Screenshot 2023-02-16 at 10 22 17 PM" src="https://user-images.githubusercontent.com/110991431/219390661-83222854-e9d6-4f8d-a358-21bd739e8c0d.png">

**Comment by hhuilingg** [comment]
hi! yes both solid and shape are interfaces but solid is also inheriting from shape! you may want to look at rec #3 Q1

**Comment by SimonSeeYongsheng** [comment]
I think you need to check if your inheritance and implementation is correct

**Comment by sporobolous** [comment]
I see! thanks for the suggestion, I will look it up

**Comment by leonardwx** [comment]
i think u have to make sure the solid is extending to Shape3D, that will ensure the inheritance will be correct
