### ISSUE TITLE
Step 4 What is the radius of the new circle  I want to create?

### ISSUE THREAD

**Issue by Follow-Mee** [nus-cs2030/2223-s2#16]
"We are now ready to construct a unit circle whose perimeter passes through two given points. By using the mid-point and angle of line pq, move the mid-point to the centre of the circle of radius r whose perimeter coincides with points p and q. You will need to work out the respective angle and distance values." 

How do I construct the new circle if I dont know radius r? is it supposed to be fixed? thanks! 
![image](https://user-images.githubusercontent.com/96849432/213746628-0ff39054-f516-40d0-b12a-d002f6a582ba.png)

**Comment by danqiye1** [comment]
Hi, notice that the radius is an input parameter? It will be supplied by the client and therefore you need to write the class to support this function.

**Comment by Follow-Mee** [comment]
Hi, I am aware that radius is an input parameter for circle class. However, my concern now is writing the function:

Circle createUnitCircle(Point p, Point q) {
    ...
    return new Circle...;
}
 
Im supposed to create a circle with just Point p and Point q? Is there a original circle I am supposed to refer to? or where do I get the radius for the new circle just for writing this function?

**Comment by 0liverkong** [comment]
use the algorithm they state right below the diagram with the circle.

**Comment by Follow-Mee** [comment]
![image](https://user-images.githubusercontent.com/96849432/213847807-e180e45a-40fd-4752-927a-544c86515510.png)
for step 3, is the radius assumed to be 1 based on the diagram?

**Comment by 0liverkong** [comment]
yup.

**Comment by Follow-Mee** [comment]
Do I submit one single file for this assignment or one for each class? If I submit 4 files together I get the following result.
![image](https://user-images.githubusercontent.com/96849432/213877578-ac5ddf6c-eb43-49bb-b2c5-20661ed5b53b.png)
What does it mean?

**Comment by 0liverkong** [comment]
the first 10 lines are variables, and the 11th line is the issue with those 10 variables.

**Comment by danqiye1** [comment]
Hi, I believe lines 11 is because you have class variables that does not `private final` modifier. Remember that in this class all class variables have to be `private final`. Try fixing that first and let's see if the rest of the error messages still show up. I suspect it is telling you a list of fields that are not declared `private final`.

**Comment by SimonSeeYongsheng** [comment]
The radius is assumed to be 1 since you are created a unit circle.

**Comment by Follow-Mee** [comment]
Thanks everyone for your inputs!
