### ISSUE TITLE
Cyclic Dependencies problem

### ISSUE THREAD

**Issue by Delocy** [nus-cs2030/2223-s2#160]
# Summary

Description of the question / problem here.
error on cyclic dependencies
## Description:

Clarifications or details with respect to the issue you are facing

## Code Snippets

Attach code snippets (if any)

## Screenshots
<img width="317" alt="Screenshot 2023-02-17 at 10 26 25 PM" src="https://user-images.githubusercontent.com/94375191/219681697-90fa9161-b9a3-473c-acea-ee49bca422cf.png">

Screenshots (if any)

**Comment by fy17ohhh** [comment]
Check your Server class, if your events contain Server you shouldn't contain Event in Server

**Comment by JustinGohkh** [comment]
Ur event class and server class are cyclic dependent
