### ISSUE TITLE
Lab 3: Time limit exceeded test case 4

### ISSUE THREAD

**Issue by j0205m** [nus-cs2030/2223-s2#161]
# Summary

I can't seem to return a value for test case 4 as somehow my code is running on an infinite loop.

## Description:

I think this has something to do with how I compile the wait time of customers that are not first in the queue. For my nextEvent() method, I have checked that if the customer is first in queue, it will return a serve event with an updated start time, but if the customer is not, it will return a new wait event with the next available time of server. However I can't seem to figure out the reason why. Has anyone faced the same problem and how did you manage to solve it? Thank you for your help!

<img width="726" alt="Screenshot 2023-02-17 at 23 16 42" src="https://user-images.githubusercontent.com/124303065/219694714-359ba8e0-a68a-41dc-a3a9-d10729b30277.png">

**Comment by geoffong11** [comment]
Usually for time limit exceeded for this mod, the problem lies with infinite loops. Maybe somewhere in your code, there is something that keeps going (check all the loops)? Or like your PQ will never be empty.

**Comment by Nicknzk** [comment]
I had the same issue for test case 8, and the issue was that I had a infinite loop created so you might need to check the difference between test case 3 and 4 and see if theres a possible place where it keeps looping

**Comment by j0205m** [comment]
solved the issue! it was helpful to use System.out.println to check for logical flow. thanks everyone for your help : )
