### ISSUE TITLE
need help in only calling .getservicetime() once in serve

### ISSUE THREAD

**Issue by Delocy** [nus-cs2030/2223-s2#162]
# Summary

Description of the question / problem here.

## Description:
i cant think of a way to only call .getservicetime() once in my serve as i need it two times, 1 each for updating my serverlist and execute event. 
Is there a way i can just store the value of the service time as a global variable that can be used anywhere in the class?
Clarifications or details with respect to the issue you are facing

## Code Snippets

Attach code snippets (if any)

## Screenshots
<img width="861" alt="Screenshot 2023-02-18 at 12 05 55 AM" src="https://user-images.githubusercontent.com/94375191/219706148-0063f2b7-bb78-4c12-8b52-d740ccc2720b.png">

Screenshots (if any)

**Comment by EpicSpirito** [comment]
I combined both executeEvent and updateServerList into one method and return a pair.
You can store the value of the service time as a variable in the method.
