### ISSUE TITLE
Ex 2 CruiseLoaders Level 4 and 5 - How to pass Style Check?

### ISSUE THREAD

**Issue by choongzhanhong** [nus-cs2030/2223-s2#163]
Hi, I am having issue passing Style check because of use of magic number. I followed the instructions: 
> For SmallCruise, the arguments of the constructor are its identifier, and time of arrival;
For BigCruise, the arguments of the constructor are its identifier, time of arrival, the length of the cruise, and number of passengers. 

Both extend class Cruise which takes in parameters in its constructor for number of loaders, and service time. So, for small cruise I just pass in 1 loader and 30min, and do some calculation for BigCruise.

However, of course this gets flagged as magic number, but there doesn't seem to be any other location for me to declare the numbers since the first line in constructor HAS to be super constructor. How would this work?

**Comment by trwstin** [comment]
when declaring your constants at the beginning (private static final ...), you can assign values to them

**Comment by choongzhanhong** [comment]
Ah I see, thank you. Turns out `static` is the important modifier as I initially only put `private final` and that wasn't allowed.
