### ISSUE TITLE
Ex 2 : failing test case 4 

### ISSUE THREAD

**Issue by yx420** [nus-cs2030/2223-s2#164]
hi i might need help on why im failing the test case 4 with such an ugly error message:( 
![image](https://user-images.githubusercontent.com/122374639/219712374-164c9693-1238-4bba-8c38-a73727d52d5c.png)

**Comment by trwstin** [comment]
Could be something to do with how you determine if a Loader is part of an active/expired service. 

Comparing the output, it seems like Loaders 6, 7, 1, 2... etc are supposed to be part of an active service elsewhere, but they are assigned to B0420.

Remember that you should be getting Loaders from expired services first, then create new ones if the quota isn't met.

**Comment by geoffong11** [comment]
Did you use a placeholder (other list to keep track) for active services when checking for expired services? Then that means after checking, you have to clear the placeholder list

**Comment by jiangen16** [comment]
one way to ensure that there are enough loaders is to create loaders and add them into the list of expired loaders first. Thereafter based on how many loaders you need, you can "reactivate" them and add them into the list active loader.

for each iteration you will also need to check if active loaders have expired and place them back into the expired list.

**Comment by yx420** [comment]
thank you guys for the suggestions, problem solved. thankss
