### ISSUE TITLE
Jshell error for toString method

### ISSUE THREAD

**Issue by kelleyhan25** [nus-cs2030/2223-s2#17]
Currently working on level one, and am getting this error on jshell. Does anyone know what this means and how to get around it? 

"JShell method names must not match Object methods: getClass wait hashCode equals notifyAll toString notify"

**Comment by andersooi** [comment]
I tried to find out what the error means and apparently, it is telling you that the method you have defined in the Point class, named "toString()", is already a method in the Object class.

Having said that, I didn't face any issues when defining my toString() method according to the lecture notes.

Maybe you might want to check your implementation if it follows the structure of the toString() method as shown in the lectures? Or if you could try to briefly explain what you did, maybe we can find out what's wrong.

**Comment by danqiye1** [comment]
Hi, I would like to check if you encapsulated the methods such as `String toString()` inside a class. I believe this error is presented by Jshell if you define a method that is from the `Object` class in some .jsh file without attaching it to a class.

**Comment by kelleyhan25** [comment]
> Hi, I would like to check if you encapsulated the methods such as `String toString()` inside a class. I believe this error is presented by Jshell if you define a method that is from the `Object` class in some .jsh file without attaching it to a class.

Oh okay! That makes sense, thank you. How would i go about encapsulating it inside say the Point class. I'm having a bit of trouble with using Docker and Jshell. Sorry if this is a silly question.

**Comment by kelleyhan25** [comment]
Oh wait, never mind. I got it, thank you all!
