### ISSUE TITLE
Ex 1 test case 5 fail 

### ISSUE THREAD

**Issue by reinatng10** [nus-cs2030/2223-s2#170]
<img width="358" alt="Screenshot 2023-02-18 at 7 24 30 PM" src="https://user-images.githubusercontent.com/124559667/219857628-f13f3597-015e-4e7c-a174-686ebeb8b587.png">

Hello, Im not sure why my output is so big compared to the expected output although i have already made all the necessary amendments.

**Comment by choongzhanhong** [comment]
Judging by the output, there's a possibility of an extra loop (since you go through each and every pair of points) happening, or your maxDiscCoverage variable may not be re-initialised/reset properly in the loops. 

Otherwise, it's hard to tell based on the output alone, perhaps you could share the logic/pseudocode or a short snippet of the code?

**Comment by reinatng10** [comment]
> possibility
<img width="463" alt="Screenshot 2023-02-18 at 10 18 25 PM" src="https://user-images.githubusercontent.com/124559667/219870752-98557d4b-d20c-493f-8a16-041f80ad87ee.png">

**Comment by reinatng10** [comment]
> Judging by the output, there's a possibility of an extra loop (since you go through each and every pair of points) happening, or your maxDiscCoverage variable may not be re-initialised/reset properly in the loops.
> 
> Otherwise, it's hard to tell based on the output alone, perhaps you could share the logic/pseudocode or a short snippet of the code?
@choongzhanhong 

<img width="488" alt="Screenshot 2023-02-18 at 10 23 14 PM" src="https://user-images.githubusercontent.com/124559667/219870973-95266440-aefc-4b84-8965-81889d005f38.png">

**Comment by VanyaPriscillia** [comment]
The line if (circle.contains(p)) is incorrect because circle.contains(p) will always return true. So, your result is the same as numOfPoints
