### ISSUE TITLE
Exercise 2 

### ISSUE THREAD

**Issue by clarwen** [nus-cs2030/2223-s2#171]
hello, I have an issue regarding level 5 on recycled loader. Is the question asking for just loader #3 that is recycled or loaders that are in multiple of 3? I seem to be able to get the output based on the picture but failed the test cases on code crunch as I edited my Service class. Am I suppose to just edit level3.jsh without modification to other classes?

<img width="712" alt="Screenshot 2023-02-18 at 8 16 48 PM" src="https://user-images.githubusercontent.com/119107037/219865278-52ad2b8f-a624-42ae-833f-3a2e0d240018.png">

I also have a compilation error on test case 4.4. I can't seem to find a solution to this. Does anyone have any idea? It does not make any sense that only this particular test case if out of bound when the rest works ><
<img width="685" alt="Screenshot 2023-02-19 at 3 42 44 PM" src="https://user-images.githubusercontent.com/119107037/219935498-b44875a6-359c-49af-ac65-f6d3329ea30f.png">

**Comment by choongzhanhong** [comment]
> Every third loader
Every three loaders, aka loaders that are multiple of 3 would be the case!

This question confused me as well. You're supposed to copy the code level3.jsh to level5.jsh and in level5.jsh, make the change to include RecycledLoader (with minimal changes to the overall algorithm used). In the end you still need to upload both level3 and level5.

**Comment by chewbum** [comment]
You need to modify your other classes and create a separate file for your level3.jsh and then edit from there to suit level5!

**Comment by meljwang** [comment]
You can edit the other classes too.

**Comment by clarwen** [comment]
got it, thanks everyone
