### ISSUE TITLE
Anyone has "Use of restricted API detected" error given by code crunch?

### ISSUE THREAD

**Issue by GreenTea749** [nus-cs2030/2223-s2#172]
Hi guys! When i submitted on codecrunch, I was thrown this error even though I did not import java.util.objects. Anyone knows how to fix this?
![HELP](https://user-images.githubusercontent.com/122426019/219872958-b9718a3e-a40a-42a6-8099-c3ae280e5361.png)

**Comment by hengbl** [comment]
I think so far the only thing we are required to import is java.util.Comparator. Make sure you did not write java.util.* as well!

**Comment by leezhanpeng** [comment]
It could be that you have constants without the static modifier.

**Comment by timothysashimi** [comment]
> I think so far the only thing we are required to import is java.util.Comparator. Make sure you did not write java.util.* as well!

or java.util.function.Supplier!

**Comment by displeasedcat** [comment]
Hi I faced the same issue. In my case I resolved it by declaring constants I used in my classes by using "private static final...."

**Comment by AmanDesai34** [comment]
Maybe you have not used the static keyword, try that out. Worked for me

**Comment by GreenTea749** [comment]
ok thank you!
