### ISSUE TITLE
Test case 7 lab 3

### ISSUE THREAD

**Issue by tanjiajiajun** [nus-cs2030/2223-s2#174]
## Description:
Hi all, I made sure my getServiceTime() is only used at serveEvent, but it seems that there is still a problem with TC 7.
For reference, 
for 1.in -> service generated 2 times
for 2.in -> service generated 3 times
for 3.in -> service generated 6 times
for 4.in -> service generated 6 times

Wondering if anyone else have the same problem? Any help would be appreciated, thank you!

## Screenshots

<img width="447" alt="Screenshot 2023-02-19 at 2 19 43 AM" src="https://user-images.githubusercontent.com/105959828/219882254-40c17703-3dc4-4212-8a18-9727d8a60a9c.png">

**Comment by 0liverkong** [comment]
you might want to check if the serving time was generated for the right customer. it seems like the timing generated for customer 4 and customer 7 were swapped.

**Comment by chewbum** [comment]
Maybe try storing the getServiceTime() as a variable from the start and then from there just pass it on to the other events

**Comment by tanjiajiajun** [comment]
Hi all, managed to fix it. The problem was that I did not update my ImList<Server>> and PQ together as a pair, most likely a implementation problem on my end. Thanks all!
