### ISSUE TITLE
Ex3 level6

### ISSUE THREAD

**Issue by jamiepngg** [nus-cs2030/2223-s2#175]
Hi! i understand that i need to create a new solidimpl object in my solidcuboid's mass() method but how do i go about doing that since the attributes for my cuboid class is private so i cant access them in my solidcuboid class by using super.height, super.length etc.. to create a solidimpl object..? Thanks!

**Comment by jacoblimjy** [comment]
"create a solidImpl object"? you might want to use your SolidImpl here.

**Comment by hengbl** [comment]
You can create getters in your Cuboid class, for eg getHeight().  However, SolidImpl only takes in a Shape3D and density as the argument so there is actually no need to access the Cuboid attributes at all.

**Comment by leonardwx** [comment]
you don't really need a super() overhere while u can access them using getters. Since SolidImpl takes in a normal shape and density, it already has the required properties inside the shape (length, width, height)

**Comment by oofpouf** [comment]
Hi, as mentioned in the comments above, there is  no need to access Cuboid's attributes. Maybe what you can do is to create and initialize the SolidImpl object inside the solidcuboid's constructor. In doing so, you can use the height, width and length arguments to create a new Cuboid object and pass it into the SolidImpl object inside the constructor. That way, when you evoke Mass(), you can directly invoke SolidImpl's mass method using e.g. this.SolidImpl.mass(), without having to use getters.
