### ISSUE TITLE
How to sort Bookings?

### ISSUE THREAD

**Issue by taugwa** [nus-cs2030/2223-s2#179]
Does anyone have any hints on how to sort the bookings using compareTo? Especially by using Comparable
Thanks!

**Comment by weitatftw** [comment]
you can consider using booking1.compareTo(booking2) in your code to compare them using the comparable that is defined in your bookings class

**Comment by taugwa** [comment]
> you can consider using booking1.compareTo(booking2) in your code to compare them using the comparable that is defined in your bookings class

so like we use compareTo and some sort of sorting algorithm?

**Comment by displeasedcat** [comment]
Your compareTo() method should return an int value that is (<0, ==0, >0). Depending on how you wrote the compareTo method, if booking1.compareTo(booking2) < 0, you can take take it that booking1 has a higher priority than booking2

**Comment by weitatftw** [comment]
> > you can consider using booking1.compareTo(booking2) in your code to compare them using the comparable that is defined in your bookings class
> 
> 
> 
> so like we use compareTo and some sort of sorting algorithm?

yes, to sort them in order

**Comment by hengbl** [comment]
> > you can consider using booking1.compareTo(booking2) in your code to compare them using the comparable that is defined in your bookings class
> 
> so like we use compareTo and some sort of sorting algorithm?

I didn't use any complicated algorithm to do this. I just initialised a variable called cheaperFare and they I iterated through the list of bookings using a while loop to find the cheapest fare and println that particular booking. Subsequently, I remove that booking from the list and repeat the whole process until the list is empty. Hope this helps!

**Comment by e0959170** [comment]
i made an imlist of bookings and used imlist.sort() with a new booking comparator

**Comment by taugwa** [comment]
damn ok thanks yall for the ideas 🙏🏻

**Comment by SimonSeeYongsheng** [comment]
Use ImList.sort() by creating a comparator class

**Comment by aldensiol** [comment]
As mentioned, you should create a new Comparator that requires a Booking to be passed in. Compare them that way, and pass it into the .sort(new BookingComparator())
