### ISSUE TITLE
Floating Point Error

### ISSUE THREAD

**Issue by lihongguang00** [nus-cs2030/2223-s2#18]
Hi all, am wondering if anyone else is facing floating point round-off error when executing `p.moveTo(Math.PI / 2, 1.0)` in jshell? Cheers!

![image](https://user-images.githubusercontent.com/84987837/213932420-69dadb3f-f7d9-448d-8321-046ff3f6bd58.png)

**Comment by danqiye1** [comment]
Hi, could you post what is your expected output for your two lines of code? I can't really tell what you are trying to achieve since the code snippet seems to be behaving correctly.

**Comment by lihongguang00** [comment]
> Hi, could you post what is your expected output for your two lines of code? I can't really tell what you are trying to achieve since the code snippet seems to be behaving correctly.

Hi Qiye, expected output is supposed to be Point(0, 1.0), thanks!

![image](https://user-images.githubusercontent.com/84987837/213961678-15b63762-9aa5-443b-9aa6-a3211fce1b43.png)

**Comment by EpicSpirito** [comment]
Hi, I think this will help you.
![Screenshot_20230124_075442](https://user-images.githubusercontent.com/92631089/214285288-eb167205-210b-47c4-8590-9e8f0e9c3e2e.png)

**Comment by lihongguang00** [comment]
> Hi, I think this will help you. ![Screenshot_20230124_075442](https://user-images.githubusercontent.com/92631089/214285288-eb167205-210b-47c4-8590-9e8f0e9c3e2e.png)

Hi EpicSpirito,

Thanks for your input but I'm aware of the tostring method, the issue I have is with the floating point error with Math.cos(Math.Pi/2). Rather than returning 0, it returns a very small floating point number instead.

**Comment by Xequil1** [comment]
I think there could be an issue with your rounding. Maybe check your "%.3f"

![Screenshot (146)](https://user-images.githubusercontent.com/122268182/214744444-79919212-a8d6-4d94-8ce8-19381b500018.png)

**Comment by lihongguang00** [comment]
> I think there could be an issue with your rounding. Maybe check your "%.3f"
> 
> ![Screenshot (146)](https://user-images.githubusercontent.com/122268182/214744444-79919212-a8d6-4d94-8ce8-19381b500018.png)

Hi Xequil1,

I think I understand what you are getting at, and it has been resolved. Thank you!
