### ISSUE TITLE
Self Practice Q3

### ISSUE THREAD

**Issue by AmanDesai34** [nus-cs2030/2223-s2#181]
<img width="1026" alt="Screenshot 2023-02-19 at 6 18 22 PM" src="https://user-images.githubusercontent.com/124550223/219941989-13d1e907-7a04-45bb-afb0-9d8d5f9e9ed9.png">
Hey guys, does anyone know, how i can solve this error??

**Comment by VanyaPriscillia** [comment]
You should delegate the computation of mass in SolidSphere and SolidCuboid to SolidImpl.

**Comment by e0959170** [comment]
it means that when you calculate the mass you should be using solidimpl's mass function instead, hope this helps!

**Comment by geoffong11** [comment]
U have to create a solidImpl object in your SolidCuboid class and use it for calculating mass.

**Comment by sethteo** [comment]
You should create a SolidImpl object in your constructor and in your mass() method of SolidSphere/SolidCuboid you should return the SolidImpl's object's mass()

**Comment by leonardwx** [comment]
U need to create a new SolidImpl that takes in the shape and density, from there you can compute the mass

**Comment by AmanDesai34** [comment]
Thank you so much guys! Figured out my mistake:))
