### ISSUE TITLE
Self Practice Exercise Q1

### ISSUE THREAD

**Issue by AmanDesai34** [nus-cs2030/2223-s2#182]
Hey guys anyone knows how i can solve this issue? Is this a logic error?

<img width="819" alt="Screenshot 2023-02-19 at 6 35 16 PM" src="https://user-images.githubusercontent.com/124550223/219942763-2ac6c65f-0707-4c65-97f5-0d32653cd82e.png">

**Comment by e0969794** [comment]
hi, it does look like a logic problem, but I can't tell exactly from your output. do check your moveTo( ) method in Point.class and the relevant math portions (cos for x, sin for y). hope this helps! :)

**Comment by leonardwx** [comment]
i think you might need to check the createUnitCircle again? the computation may not be correct. look through the formulas such as creating midPoint, angleTo, distance, moveTo(angle + Math.PI/2, distance)

**Comment by Ernestnzx** [comment]
It might be the wrong usage of Math.atan2(y, x). Also take note of the ordering of the subtraction of the points, (point p - point q) vs (point q - point p). Hope this helps!

**Comment by Klowhe** [comment]
I had a similar output because I placed atan2(Xdiff, Ydiff). Just need to flip it and it will work out!

**Comment by AmanDesai34** [comment]
Thank you Guys!! I solved it:)
