### ISSUE TITLE
Cannot find Supplier symbol

### ISSUE THREAD

**Issue by eesean** [nus-cs2030/2223-s2#183]
Hi all,

Would like to clarify whether we are supposed to follow a similar implementation as the one in the screenshot below? I tried using Supplier<Double> for both Simulator and Customer classes and both java files will not compile because Supplier cannot be found.

<img width="279" alt="Screenshot 2023-02-19 210808" src="https://user-images.githubusercontent.com/110977266/219950111-f14c7f58-e698-467b-b669-501795351ede.png">

**Comment by EpicSpirito** [comment]
U need to import Supplier using `import java.util.function.Supplier`
