### ISSUE TITLE
how do you compare and generate all of the possible bookings in level 5?

### ISSUE THREAD

**Issue by weitatftw** [nus-cs2030/2223-s2#184]
# Summary

I'm stuck at level 5 as my compareTo method obtains and compares the lowest fare possible for a particular driver and now I have to compare amongst all possible bookings, can anyone help me with this? I read the thread posted below but I'm still confused with the implementation

**Comment by taugwa** [comment]
not sure if this is the best implementation but for me i created a child class that inherits Booking to deal with all the alternative services that did not have the cheapest fare. hope this helps!

**Comment by weitatftw** [comment]
> not sure if this is the best implementation but for me i created a child class that inherits Booking to deal with all the alternative services that did not have the cheapest fare. hope this helps!

so within the child class you have a method to generate all possibilities? what about the compareTo method?

**Comment by meljwang** [comment]
Hi, I made a post about the same issue earlier. What I did was create another class extending Booking which gives the alternative fare and service, hope it helps.

https://github.com/nus-cs2030/2223-s2/issues/180#issue-1590618537

**Comment by trwstin** [comment]
What about the implementation are you confused about?

Essentially what you need to do is create a class which extends Booking, then reverse the if/else condition in the methods where you do your comparisons.

For this lab it is safe to assume that a driver can only offer 2 services, so you don't have to think too deep about dealing with "all the possibilities".

**Comment by weitatftw** [comment]
> What about the implementation are you confused about?
> 
> Essentially what you need to do is create a class which extends Booking, then reverse the if/else condition in the methods where you do your comparisons.
> 
> For this lab it is safe to assume that a driver can only offer 2 services, so you don't have to think too deep about dealing with "all the possibilities".

Thank you! I realised that I was overthinking this issue and I assumed that a driver could offer more services than the 2. The issue is fixed now

**Comment by weitatftw** [comment]
thank you everyone for the help!
