### ISSUE TITLE
Lab 3: Test Case 7 wrong output

### ISSUE THREAD

**Issue by j0205m** [nus-cs2030/2223-s2#185]
## Description:

For test case 7 my code seems to generate the wrong service time for some customers, but I only call getServiceTime() once in my ServeEvent class and store it as a variable in the ServeEvent. Not sure why this is still an issue : (

## Code Snippets

<img width="752" alt="Screenshot 2023-02-19 at 22 56 52" src="https://user-images.githubusercontent.com/124303065/219956212-34f5ad75-51bb-4513-a187-b97171b3be23.png">

## Screenshots

<img width="469" alt="Screenshot 2023-02-19 at 22 57 18" src="https://user-images.githubusercontent.com/124303065/219956222-2ef52315-338e-4450-b1a6-d86c4025bfd9.png">

**Comment by wongjingwen** [comment]
A suggestion could be to print out the actual ServiceTime of each customer to confirm its correct. If its correct, it could be the server endtime was not updated properly (aka return the same server list without updating.

**Comment by smellystank** [comment]
I believe the problem you are inherently facing is due to the order in which you are calling service time, you should be calling them chronologically, any other order would cause a wrong serve time to be assigned to the customer - I suggest for you to take a look at the order in which you events are getting service time.

**Comment by taugwa** [comment]
^^ If you call getServiceTime() only when creating your serve event, then it may be out of order because the order in which serve is called is different from the order in which the customer arrives

**Comment by j0205m** [comment]
> I believe the problem you are inherently facing is due to the order in which you are calling service time, you should be calling them chronologically, any other order would cause a wrong serve time to be assigned to the customer - I suggest for you to take a look at the order in which you events are getting service time.

hello thanks for your suggestion! however i'm still do not fully understand what you meant by calling them chronologically. i have assigned each customer with Supplier<Double> serviceTime and calls getServiceTime() on the same Supplier<Double> serviceTime that they are tagged with. is this not considered in chronological order?

**Comment by j0205m** [comment]
> ^^ If you call getServiceTime() only when creating your serve event, then it may be out of order because the order in which serve is called is different from the order in which the customer arrives

if i were to call getServiceTime() to the Supplier<Double> serviceTime each customer is assigned to when they first arrive will this be still out of order?

**Comment by smellystank** [comment]
> > I believe the problem you are inherently facing is due to the order in which you are calling service time, you should be calling them chronologically, any other order would cause a wrong serve time to be assigned to the customer - I suggest for you to take a look at the order in which you events are getting service time.
> 
> hello thanks for your suggestion! however i'm still do not fully understand what you meant by calling them chronologically. i have assigned each customer with Supplier serviceTime and calls getServiceTime() on the same Supplier serviceTime that they are tagged with. is this not considered in chronological order?

If you call the service times when each customer first arrives then it goes against the point of calling service times (the point is, if the customer leaves then they would not be served in the first place), additionally, lets consider a scenario to better visualise this:
1 server, max 1 queue
Customer 1 arrival time of 1, service time of 0.5
Customer 2 arrival time of 1, service time of 0.5
Customer 3 arrival time of 1, service time of 0.5

if customer 1 comes in and gets served, the time server is available is now 1.5
customer 2 comes in and cant get served, hence wait until 1.5 to get served
customer 3 comes in and has to leave because the queue is full (if u call service time here, then there would be a flaw because the customer has to leave, i.e. u shouldnt call it here)

This idea also affects the calling of service time in other events too, contemplate the flow of wait and how that links with serve, in the entire flow of events - chronology of events. Hope this helps!

**Comment by j0205m** [comment]
> > > I believe the problem you are inherently facing is due to the order in which you are calling service time, you should be calling them chronologically, any other order would cause a wrong serve time to be assigned to the customer - I suggest for you to take a look at the order in which you events are getting service time.
> > 
> > 
> > hello thanks for your suggestion! however i'm still do not fully understand what you meant by calling them chronologically. i have assigned each customer with Supplier serviceTime and calls getServiceTime() on the same Supplier serviceTime that they are tagged with. is this not considered in chronological order?
> 
> If you call the service times when each customer first arrives then it goes against the point of calling service times (the point is, if the customer leaves then they would not be served in the first place), additionally, lets consider a scenario to better visualise this: 1 server, max 1 queue Customer 1 arrival time of 1, service time of 0.5 Customer 2 arrival time of 1, service time of 0.5 Customer 3 arrival time of 1, service time of 0.5
> 
> if customer 1 comes in and gets served, the time server is available is now 1.5 customer 2 comes in and cant get served, hence wait until 1.5 to get served customer 3 comes in and has to leave because the queue is full (if u call service time here, then there would be a flaw because the customer has to leave, i.e. u shouldnt call it here)
> 
> This idea also affects the calling of service time in other events too, contemplate the flow of wait and how that links with serve, in the entire flow of events - chronology of events. Hope this helps!

thank you for the clarification! i have another question so if we were to assign the Supplier <Double> serviceTime but not call getServiceTime() when they are served, will this still violate the chronological order? or does it only matter where you call getServiceTime()?

**Comment by smellystank** [comment]
> 

Only matters when calling method :)

**Comment by j0205m** [comment]
> Only matters when calling method :)

got it :D thank u so much!

**Comment by tynkyra** [comment]
Hi! I'm facing the exact same problem. Not sure if I misunderstood the above comments but could you share what you did to solve it? I only call the getServiceTime method in the serve class as well
