### ISSUE TITLE
Lab 03 Test case 6

### ISSUE THREAD

**Issue by sethteo** [nus-cs2030/2223-s2#187]
Has anyone encountered the same error where you pass test cases 1-5 but at test case 6 there suddenly is an infinite loop. 
Does anyone have any suggestions on where might the error lie in

<img width="380" alt="Screenshot 2023-02-19 at 11 53 41 PM" src="https://user-images.githubusercontent.com/119569146/219959199-7b66e238-728f-4e11-9239-9256903d13b3.png">

**Comment by SimonSeeYongsheng** [comment]
Where did you invoker your getServiceTime()?

**Comment by sethteo** [comment]
> Reference

I called it in my arrival event

**Comment by sethteo** [comment]
> Where did you invoker your getServiceTime()?

I called it in my ArrivalEvent class

**Comment by SimonSeeYongsheng** [comment]
> > Where did you invoker your getServiceTime()?
> 
> I called it in my ArrivalEvent class

You should be invoking it in the Serve event class
