### ISSUE TITLE
No such method error

### ISSUE THREAD

**Issue by eesean** [nus-cs2030/2223-s2#188]
Hi all,

Would like to ask how I should go about handling this, don't really understand why I'm getting such an exception from the Main file:

Exception in thread "main" java.lang.NoSuchMethodError: 'void Simulator.<init>(int, ImList, ImList)'
        at Main.main(Main.java:15)

**Comment by huwenjie912** [comment]
Perhaps while initialising some of ur classes, the constructors' parameters that were defined are inconsistent with how they were called in other classes. Can check ur simulator class!

**Comment by oofpouf** [comment]
There seems to be a dot "." between Simulator and (int, ImList, ImList) in "Simulator.(int, ImList, ImList)", probably due to a typo. As such, the programme could've thought that simulator is a method. Maybe you can check on this?

**Comment by lkldev** [comment]
Make sure you are using the latest Main.java, seems like you are using the Main.java from lab 2...

**Comment by eesean** [comment]
Hi I have checked my Main.java it's the same as the one provided for lab 3.

**Comment by lkldev** [comment]
Did you modify your Simulator to take in the new constructor? I.e. your constructor for Simulator should be (int, int, ImList, Supplier<Double>)

**Comment by lkldev** [comment]
Did you modify your Simulator to take in the new constructor? I.e. your constructor for Simulator should be (int, int, ImList, Supplier<Double>)

**Comment by eesean** [comment]
I have deleted all previous Main file versions (including those from lab 2) in my computer (physically typed out the Main file in accordance to the one for Lab 3), however the file still cannot be compiled:

Main.java:16: error: incompatible types: Supplier<Double> cannot be converted to DefaultServiceTime
        Simulator sim = new Simulator(numOfServers, qmax, arrivalTimes, serviceTime);

Are we supposed to amend the Main file provided for this lab, or have I received the wrong file for checking test cases?

**Comment by lkldev** [comment]
Your Simulator should be taking in a Supplier<Double> and not DefaultServiceTime. DefaultServiceTime is an example of how the service time can be generated.
