### ISSUE TITLE
Issue with assigning pair.first() and pair.second() to variables 

### ISSUE THREAD

**Issue by calista03** [nus-cs2030/2223-s2#190]
# Summary

Hello, has anybody used an ImList<Pair<Server, ImList<Customer>>> to represent your list of servers as well as the corresponding customer queue of each server? Basically the ImList contains Pairs which each contain a Server and an ImList<Customer> that represents the queue of customers waiting for that particular server. However, when I do pair.first() and pair.second() to my Pairs in the ImList, I am unable to assign a Server and ImList<Customer> variable respectively to the objects in the Pair, even though I already declared at the start that my ImList of servers is ImList<Pair<Server, ImList<Customer>>>.
Has anybody faced a similar issue? If not, is there a better way to represent my list of servers and their corresponding customer queues? Thank you! 

## Screenshots
![Screenshot 2023-02-20 at 10 25 30 AM](https://user-images.githubusercontent.com/124029739/219995540-f7165501-95b6-4973-b593-33aec1e2a41f.png)

Screenshots (if any)

**Comment by huwenjie912** [comment]
You could consider using a Pair of ImList<Server> and PQ<Events> instead!

**Comment by SimonSeeYongsheng** [comment]
This is because the Pair.first() and Pair.second() is returning back an Object class, instead of a Server or ImList class.
And Object class cannot be implicit typecasted to a "narrower" class

**Comment by taugwa** [comment]
not sure if you wrote it this way in your code but maybe try ImList<Pair<Server, ImList<Customer>>> instead of ImList<Pair<Server, ImList>> ?

**Comment by Brendan8899** [comment]
The way I implemented my Server and their respective Customer Queues is to have an attribute in Server called queueList which is an ImList<Customer>. Initialise as empty and add during a wait event.

**Comment by calista03** [comment]
Thank you for all your suggestions! I ended up having an attribute in Server called queue which is an ImList!
