### ISSUE TITLE
Lab 3 Test Case 4

### ISSUE THREAD

**Issue by Brendan8899** [nus-cs2030/2223-s2#191]
# Summary
Hi Guys, Any idea on how to update the serve event time of those ppl in the queue?

Currently, my serve event time is derived from the server next available time. However, this causes problems as for those ppl deeper in the queue, the server next available time is dynamic.

One approach I have thought of taking my Server Status List as an argument, this is not possible as my get time function is also used in my Comparator.

Do advise me on any possible approaches. Thanks.

**Comment by SimonSeeYongsheng** [comment]
You don't have to update every single customer in the queue.

In my solution, I only update the next in line customer i.e. the next customer to be served, with the ending time of the current customer to be served
