### ISSUE TITLE
lab4 lvl 5 error regarding generics

### ISSUE THREAD

**Issue by NwaterM** [nus-cs2030/2223-s2#192]
# Summary
Driver is an interface

Description of the question / problem here.
Can someone explain why List<E> cannot conform to Imlist<Driver> , and what can I do to solve this?

## Description:

Clarifications or details with respect to the issue you are facing

## Code Snippets

Attach code snippets (if any)

## Screenshots

Screenshots (if any)
<img width="846" alt="Screenshot 2023-02-20 at 1 53 37 PM" src="https://user-images.githubusercontent.com/122254436/220021840-05216dcf-59fa-48f8-83d9-d69dc3e6cd18.png">

**Comment by jeffkhong11** [comment]
You'll have to include List<Driver> in your findBestBooking parameters

**Comment by nicholasteow** [comment]
That's right ^^, simply include the List<Driver> in your parameters and it should work

**Comment by leonardwx** [comment]
Try use List instead of ImList

**Comment by viethaaaa** [comment]
You can simply replace ImList<Driver> with List<Driver> in your parameters :)
