### ISSUE TITLE
Issue with Abstract method in Event class

### ISSUE THREAD

**Issue by EmperorAry** [nus-cs2030/2223-s2#193]
I'm using hasLeft() method to indicate if its a leave event, so that I can know the stats of the leaves.

However its giving me an error, which doesn;t show for any other abstract methods in the same class.

![image](https://user-images.githubusercontent.com/64073938/220030182-846792bf-3c95-4819-a3c4-30d3d4e2203b.png)

![image](https://user-images.githubusercontent.com/64073938/220030754-9dad872e-02b5-48ab-93e9-5eb34fed182a.png)

**Comment by SimonSeeYongsheng** [comment]
Did you declare Event class as abstract? abstract class Event?

**Comment by EmperorAry** [comment]
> Did you declare Event class as abstract? abstract class Event?
No, it has a defined methods so that I don't have to repeat them in every event

**Comment by EmperorAry** [comment]
> Make sure that all your subclasses have the hasLeft() method and it is being overridden properly. Alternatively, since I assume this method will only return a different output in your Leave class, you can make it non-abstract in Event class and return say 0 and then in your Leave class you override this method and return 1 instead. This way, you won't have to worry about missing out this method in the other subclasses or accidentally overriding wrongly.

Thanks, I did this and it worked
