### ISSUE TITLE
ex 3 - failing test case 2

### ISSUE THREAD

**Issue by chianxintong** [nus-cs2030/2223-s2#194]
![image](https://user-images.githubusercontent.com/122260095/220037851-9e32c023-23a4-4e88-8dd9-746e1eb2576c.png)

Hi, has anyone encountered such an issue before? How may I approach this problem? 

(I tested the egs provided using jshell and they all seem to work tho)

**Comment by lkldev** [comment]
Can you provide the submission id?

**Comment by chianxintong** [comment]
> Can you provide the submission id?

The submission id is 2466584, thank you!

**Comment by lkldev** [comment]
Thanks, the teaching team will check and get back to you :)

**Comment by lkldev** [comment]
Hi we have fixed the issue and you passed all the test cases :) congrats! Closing this issue now :)
