### ISSUE TITLE
Use of static keyword

### ISSUE THREAD

**Issue by llaamaaa** [nus-cs2030/2223-s2#198]
Hi had an error where CodeCrunch said I used restricted API. 

Use of restricted API detected.
> java.util.Objects

Just curious why after using the static keyword this error disappeared. Thanks in advance!

**Comment by trwstin** [comment]
maybe its some voodoo magic checkstyle thing?

**Comment by stxe09** [comment]
Maybe it was the name you chose for your attribute?

**Comment by geoffong11** [comment]
I think if you caps every letter and did not declare it static, check style will flag an error.

**Comment by taugwa** [comment]
sorry i'm not too sure either and i'm not sure what you added "static" to but here's what google says...perhaps it might help? sounds like it might
 
<img width="685" alt="Screenshot 2023-02-22 at 12 38 27 AM" src="https://user-images.githubusercontent.com/122268711/220406309-4b42b830-9230-4a23-8108-d31e71b1142d.png">

**Comment by AmanDesai34** [comment]
Did you add static to any other variable ?

**Comment by vivyanliew** [comment]
did you use any magic numbers? cos if you do, then adding static will help eliminate magic number error

**Comment by llaamaaa** [comment]
> 

i think it has something to do with magic numbers -.- thanks for the help guys!
