### ISSUE TITLE
Unable to install Docker Desktop 4.15.0

### ISSUE THREAD

**Issue by whsiah** [nus-cs2030/2223-s2#2]
As per title, I am unable to run the installation wizard after downloading the installer itself. I have already tried several solutions found online, including running the installation as administrator, [restarting the WMI through command prompt](https://stackoverflow.com/questions/71095210/installing-docker-desktop-4-5-0-failed-componet-communityinstaller-enablefeatur)  , deleting Docker files before reinstalling, installing older versions of Docker, as well as the steps detailed [here](https://stackoverflow.com/questions/66490624/docker-desktop-installation-failed). 

Each time, the installation hangs after a while with the same error message displayed. How do I fix this issue?

![image](https://user-images.githubusercontent.com/122257619/211360359-af1d3a44-5792-4b04-9786-5096f41e19c3.png)

**Comment by jamiewong1210** [comment]
> @whsiah 

Try running following command from prompt with admin rights:
winmgmt/verifyrepository : Returns either **Repository is either inconsistent** /**Consistent**

I suspect docker is not the issue here, not sure if it helps you can try the following:
[WMI: Missing/Failing WMI Providers /Invalid WMI class](https://techcommunity.microsoft.com/t5/ask-the-performance-team/wmi-missing-or-failing-wmi-providers-or-invalid-wmi-class/ba-p/375485)

**Comment by danqiye1** [comment]
Hi, can I check if this is an issue from a Windows machine?

**Comment by danqiye1** [comment]
Hi, can I check if you are on Windows 10 or Windows 11?

**Comment by whsiah** [comment]
> Try running following command from prompt with admin rights: winmgmt/verifyrepository : Returns either **Repository is either inconsistent** /**Consistent**
Command prompt returns that the repository is consistent for me.

> I suspect docker is not the issue here, not sure if it helps you can try the following: [WMI: Missing/Failing WMI Providers /Invalid WMI class](https://techcommunity.microsoft.com/t5/ask-the-performance-team/wmi-missing-or-failing-wmi-providers-or-invalid-wmi-class/ba-p/375485)
The error message displayed by the installation wizard does not match with any of those stated in this link and I am not sure which scenario to follow

**Comment by whsiah** [comment]
> Hi, can I check if you are on Windows 10 or Windows 11?

I am on Windows 10

**Comment by danqiye1** [comment]
@whsiah, perhaps try upgrading to Windows 11 (or the latest build of Windows 10) will help as it may be the more supported OS version. Sometimes a failed Windows update could cause all kinds of issues. Also, I wonder if you have installed WSL on your machine since some suggest that can also be a cause of this issue.

**Comment by whsiah** [comment]
> @whsiah, perhaps try upgrading to Windows 11 (or the latest build of Windows 10) will help as it may be the more supported OS version. Sometimes a failed Windows update could cause all kinds of issues. Also, I wonder if you have installed WSL on your machine since some suggest that can also be a cause of this issue.

Both attempts at installing WSL through the command prompt and enabling the service through the control panel are met with the same error code, what should I do next? 

![image](https://user-images.githubusercontent.com/122257619/211490627-db4ba08c-2331-4c04-86d1-ce17921036a5.png)

![image](https://user-images.githubusercontent.com/122257619/211490653-086b2d3d-229f-4ab4-9dce-5f8e25fa792d.png)

**Comment by danqiye1** [comment]
Oh no, I think this may be a totally unrelated issue now. Forget about the WSL since by right we should try to run docker desktop without it. Can you print out your first error message for me so that I can copy paste it in google to see what comes up? It's a bit hard to reference from the image.

**Comment by whsiah** [comment]
@danqiye1 the error message is:
Component CommunityInstaller.EnableFeaturesAction failed: 
   at CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()

**Comment by danqiye1** [comment]
Ok thanks. Can you also help me check if your machine satisfies the following requirements:

If you are on WSL 2 backend.
![image](https://user-images.githubusercontent.com/5430399/211566327-6bbf0527-08b7-4a95-85a0-d2bcaaccda72.png)

If you are on HyperV backend.
![image](https://user-images.githubusercontent.com/5430399/211566535-3e4c14e2-a5c7-4ac6-92ca-20ee7972e553.png)

Let me know which of the above backends you are using.

**Comment by whsiah** [comment]
> Let me know which of the above backends you are using.

I'm not sure how to determine which backend I am using but my windows version is 21H1 and the build is 19043.1645.

Following the documentation, when I run `wsl --install` in command prompt / powershell, I will get error 0x8000ffff as shown in the earlier images. When I run `Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All` in powershell, I get the following error: 
Enable-WindowsOptionalFeature : Feature name Microsoft-Hyper-V is unknown.
At line:1 char:1
+ Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Enable-WindowsOptionalFeature], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.EnableWindowsOptionalFeatureCommand

**Comment by danqiye1** [comment]
Ok in that case can you checkout your control panel in Windows, search for "Turn Windows Features on and off" and see if your Virtual Machine Platform or Windows Hypervisor Platform is turned on?

![image](https://user-images.githubusercontent.com/5430399/211815293-bbf08c75-b0ce-4584-8df8-1d709f0ad78f.png)

**Comment by whsiah** [comment]
I have managed to resolve the issue after updating my Windows. Thanks

**Comment by danqiye1** [comment]
Great that it is resolved!
