### ISSUE TITLE
Unable to open Point.java in jshell

### ISSUE THREAD

**Issue by whsiah** [nus-cs2030/2223-s2#20]
I have already downloaded the provided files for the exercise (including Point.java), but when I run /open Point.java in jshell, it says that the file cannot be found. 
![image](https://user-images.githubusercontent.com/122257619/214200216-98555983-ef16-4c38-8fd7-a68f84d7eb68.png)

**Comment by tanjiajiajun** [comment]
Hello! You would need to move to the directory where Point.java is, then run jshell and ` /open Point.java`

You can move using `cd 'NAME_OF_YOUR_FOLDER'` command or `pwd` to check your current directory.

**Comment by whsiah** [comment]
Hi, I am now given the following error when I try to move the directory:

`-bash: cd: C:\Users\weehu\Desktop\Exercises\Exercise 1 - Maximum Disk Coverage: No such file or directory`

**Comment by wjiayis** [comment]
Hi there, your file name contains spaces, so you should enclose your path with quotation marks, i.e., `cd "C:\Users\weehu\Desktop\Exercises\Exercise 1 - Maximum Disk Coverage"`.

**Comment by trwstin** [comment]
Hi @whsiah, here's another method to access the correct directory:

1. Open Terminal
2. Type `cd` , followed by a space
3. Use File Explorer to locate your .java files
4. Drag and drop the path into Terminal
5. Press Enter

I have recorded a short demo below:

![](https://s9.gifyu.com/images/d70oku_1.gif)

Afterwards, you should be able to /open your files without encountering the 'File not found' error.

**Comment by whsiah** [comment]
Hi @wjiayis and @trwstin, I have just tried both of your suggestions but I am still getting the same error as above

**Comment by trwstin** [comment]
> Hi @wjiayis and @trwstin, I have just tried both of your suggestions but I am still getting the same error as above

Are you able to screenshot a step-by-step process of you doing this:
1. Using cd to access the directory where your files are
2. Running jshell in the directory
3. Doing /open Point.java in jshell

**Comment by whsiah** [comment]
@trwstin Yup, here they are. Do let me know if anything is missing
![image](https://user-images.githubusercontent.com/122257619/214268365-f2e73a17-9628-498f-a128-68f889c03c4a.png)
![image](https://user-images.githubusercontent.com/122257619/214268405-a921258e-64d5-4ea2-b294-49900b476841.png)
![image](https://user-images.githubusercontent.com/122257619/214268465-3f4d60c9-59e4-4149-a98d-ec1ed6dc62d1.png)
![image](https://user-images.githubusercontent.com/122257619/214268499-ea330c29-c826-4fcd-8f0a-a4193bbd35d3.png)

**Comment by trwstin** [comment]
> @trwstin Yup, here they are. Do let me know if anything is missing

Ah, it seems like you're using the Ubuntu terminal. I think there are some differences in terms of the cd command and how it handles spaces in file directories, but my knowledge on Ubuntu is limited.

Can you try reproducing the steps on Windows Terminal/PowerShell instead?

**Comment by whsiah** [comment]
> Can you try reproducing the steps on Windows Terminal/PowerShell instead?
It seems to be working as expected on Windows Terminal now, thanks for pointing this out.

Thanks to everyone else for the assistance too!
