### ISSUE TITLE
Generating new event

### ISSUE THREAD

**Issue by eesean** [nus-cs2030/2223-s2#202]
Hi all,

In this lab, we are expected to have a method that can generate the next event, but I would like to clarify whether such a method would cause an error eventually?

If (not my implementation currently) I have an Event interface that has such a method (say the method is Event next( ) ), and for instance I want to generate a Serve event using next( ), wouldn't the type to be returned be Event if I were to generalise an event to be generated? And if that were the case, will an error be generated if for e.g. in the Serve class I use Serve next( ) instead of the method in the interface? Or is there no need for a type to be declared for methods in an interface?

I'm confused as to how a method declared in the interface can be implemented across different classes if we are expected to generate different objects for each scenario, would like to get advice on how I should implement the next method (based on the dilemma mentioned)!

**Comment by hengbl** [comment]
In your event interface your next() method will have a return type Event and so all your event subclasses should also have the same next() method with a return type Event as well. You still have to declare a type in your method in interface. You already know that your next() will always generate another event regardless of the class so why not just leave the return type as Event. This is the whole essence of polymorphism.

**Comment by weitatftw** [comment]
the return type of nextEvent() can be any class that implements the Event interface. it will throw an error if you do not implement the methods specified within the Event interface. you need to declare the type to be returned for nextEvent() within the Event interface.
