### ISSUE TITLE
Member name checkstyle

### ISSUE THREAD

**Issue by veviana** [nus-cs2030/2223-s2#204]
![image](https://user-images.githubusercontent.com/94920324/220265141-3bfed602-6a3c-4984-9db7-f875eccfd30e.png)

When i ran the checkstyle, i was prompted this. What are the restrictions when we create constant variable names, aside from being in caps and in snake case?

**Comment by jorwong** [comment]
Class names are written in UpperCamelCase, method names and field names in lowerCamelCase, and constant names in ALL_CAPS_SNAKE_CASE. Type parameters in single capital letter.

This can be found at https://nus-cs2030.github.io/1718-s2/style/index.html

**Comment by veviana** [comment]
> Class names are written in UpperCamelCase, method names and field names in lowerCamelCase, and constant names in ALL_CAPS_SNAKE_CASE. Type parameters in single capital letter.
> 
> This can be found at https://nus-cs2030.github.io/1718-s2/style/index.html

hello, thankyou! may i check if i want to cube a certain value, i have to create a constant variable '3', i named it CUBE but it causes the member name error as shown above, is it because the 'CUBE' naming is too general or?
