### ISSUE TITLE
Constructing a Customer with ArrivalTime

### ISSUE THREAD

**Issue by tali-a** [nus-cs2030/2223-s2#207]
Hi, I want to instantiate a customer object with just ArrivalTime and create the necessary constructor, but  there isn't a default value I can pass in that's of the Supplier<Double> type. Does this mean it's no longer necessary  to  create a list of customers in the Simulator class? Or is there just no need to instantiate customers from the list of arrivalTimes?

**Comment by xyxyiuxy** [comment]
For me I didn't create any customer list in simulator and I think it is not necessary to do so. I just created a server list in simulator and initialise the service begin time as the customer's arrival time.

**Comment by 0liverkong** [comment]
you need to initiate a list of arrival events so yes the customers need to have a arrivaltime attribute. Supplier is only used for the service duration as of now.

**Comment by SimonSeeYongsheng** [comment]
There is no need to create a list of customers

**Comment by ringleading** [comment]
i left them as the properties of my events when creating the pq so i can j pull them out whenever

**Comment by jianjiezzz** [comment]
In customer list, I created customers with supple<double> time as the property, then I use get.time() only in serve events to get the true serve time.
