### ISSUE TITLE
Level 4 Wrong Output for createUnitCircle

### ISSUE THREAD

**Issue by tali-a** [nus-cs2030/2223-s2#21]
Hi, after following the steps specified in the instructions here:

![image](https://user-images.githubusercontent.com/103631647/214270737-9e8f6fad-d45a-4905-ae52-25c49b71d62a.png)

I get an output of 
![image](https://user-images.githubusercontent.com/103631647/214270865-d05fbed1-1bf2-4a1b-ac48-13d127ee94c3.png)

instead of 

![image](https://user-images.githubusercontent.com/103631647/214270978-d06d0405-72eb-4854-8e9d-707bba9a9cc9.png)

I think it's probably because  only "left" unit circles with respect to traversing from point p to point q" are considered, but I'm not sure how to fix my code. Thanks!

**Comment by trwstin** [comment]
With reference to the diagram provided, can you check that: 
1. You have computed length 'd' correctly (Hint: You can make use of a function provided in main.jsh); 
2. You are moving the **midpoint** between p and q, not any of the individual points

**Comment by SimonSeeYongsheng** [comment]
It has something to do with your calculation, maybe calculate the angle from the perspective of p

**Comment by andersooi** [comment]
If your `moveTo` function works, then there may be an issue with how you obtain your angle, distance or the point which you are trying to move.
