### ISSUE TITLE
Lab 4 - Sorting (Level 5)

### ISSUE THREAD

**Issue by chianxintong** [nus-cs2030/2223-s2#210]
# Summary

Hi, does anyone have any clue what's wrong with the sorting? Thank you so much

## Description:

My approach:
Created a new class called **AltBooking** which takes in the arguments driver, request and service. I redefined a compareTo method here to be used in my **BookingComp** class (sorted according to lowest fare first, then waiting time to break a tie). **BookingComp** implements Comparator<AltBooking> 

In level5.jsh, I used AltBookingComparator to sort my list of AltBooking objects. 

## Code Snippets

![image](https://user-images.githubusercontent.com/122260095/220401731-970069d4-cb2e-48e4-b5fc-398702a65997.png)

## Screenshots

![image](https://user-images.githubusercontent.com/122260095/220400688-e798f8e9-3875-4298-b641-2b0e319a2999.png)

**Comment by ringleading** [comment]
might be your method of getting the fare of a booking that causes your comparator to go haywire? had this issue too

**Comment by trwstin** [comment]
If you do new ImList<>(), then aren't you sorting an empty list?

Try calling .sort() on the original list instead, and assign it back to itself.

**Comment by meljwang** [comment]
You should add all the bookings into the booking list before sorting.

**Comment by Brendan8899** [comment]
Start by creating an empty ImList<Alt Booking> bookingList and add all the AltBooking Objects in. Subsequently, do a bookingList = bookingList.sort(new BookingComp()). That should give u are sorted list.

**Comment by chianxintong** [comment]
Thanks all for your help, i managed to solve it by sorting bookingList that already contains AltBooking objects and reassigning it to bookingList variable. YAY..

**Comment by sporobolous** [comment]
Hi, I also have an alt class similar to `AltBooking` that it gives me the more expensive one, how did u go about to making it in your jsh? 

did u make ur `AltBooking extends Booking`? im having error 

<img width="563" alt="Screenshot 2023-02-24 at 2 42 52 PM" src="https://user-images.githubusercontent.com/110991431/221110275-3152eea8-acd4-4ea6-ad17-2e3031e74e2e.png">
