### ISSUE TITLE
Lab 4: test case 3 error

### ISSUE THREAD

**Issue by j0205m** [nus-cs2030/2223-s2#216]
## Description:

Encountered this error since the start but i'm not sure what it means. Does it have something to do with my level5.jsh?

## Screenshots

<img width="1394" alt="Screenshot 2023-02-22 at 13 33 13" src="https://user-images.githubusercontent.com/124303065/220532036-5d09bc14-2fe2-4d93-be21-d8f853951c63.png">

**Comment by sethteo** [comment]
Your sort should look like "bookings.sort(new BookingComparator())" and in your BookingComparator there should be a compareTo method as well , it should work after this :)

**Comment by j0205m** [comment]
> Your sort should look like "bookings.sort(new BookingComparator())" and in your BookingComparator there should be a compareTo method as well , it should work after this :)

thank you for your help! i am still abit confused about the difference between the purpose of defining a compareTo method in comparator class. does this mean that the compareTo method we defined in Booking is redundant? or how does it all come together

**Comment by sethteo** [comment]
> > Your sort should look like "bookings.sort(new BookingComparator())" and in your BookingComparator there should be a compareTo method as well , it should work after this :)
> 
> thank you for your help! i am still abit confused about the difference between the purpose of defining a compareTo method in comparator class. does this mean that the compareTo method we defined in Booking is redundant? or how does it all come together

I wouldn't say it is redundant as your compareTo method is comparing a booking with another booking using the requirements stated (cost first, time used to break-ties) which can then give you the best booking among the services if you were to call a new Request. 
Whereas the BookingComparator is used by the sort method to sort all possible bookings in an ImList, where the compareTo method in the BookingComparator can actually call the already written compareTo method in your Booking class to compare the Booking b1 and Booking b2 arguments of your BookingComparator's compareTo method (the structure of the Comparator's compareTo method can be found in the slides) . 
Hope this makes sense !

**Comment by kyledilao777** [comment]
actually if u compare the compare method in areaComp and the compareTo method in booking, its almost identical in terms of structure...

so that would be the hint --> the booking compareTo method is similar to the compare method in the areaComp class
