### ISSUE TITLE
Stuck With Ungraded Assignment 1

### ISSUE THREAD

**Issue by weitatftw** [nus-cs2030/2223-s2#217]
does anyone have any idea how to do this qn?? i've been stuck for a few days and i can't decide on the ideal implementation

**Comment by taugwa** [comment]
i have the same issue too...  would love to hear others' inputs on this!

**Comment by aldensiol** [comment]
likewise ^!

**Comment by ayevxn** [comment]
Hello! Not sure which level you guys are talking about but if anyone has any advice for level 2 please do share...

**Comment by xyxyiuxy** [comment]
> Hello! Not sure which level you guys are talking about but if anyone has any advice for level 2 please do share...

For level2 3 4 you can have a subclass of Term and Host, eg ReceivedTransmitter and ReceivedPager, then in the subclass you write the output "pager1 >--snd--> transmitter1" in toString(), and in class Pager and Transmitter you may define a method and return smth like new  ReceivedTransmitter(host, terminal). ----- This is based on the answer provided by my TA.

**Comment by JYeoZS** [comment]
Hi, the problem seems more to do with the rcv() method.

I have a overarching Host class, with child of Transmitter  and transmitter for snd.

Where did your insert the rcv() method such that r1.rcv() has not output but p1.snd(r1).rcv() has output?

Thanks.
