### ISSUE TITLE
method for level 5.jsh 

### ISSUE THREAD

**Issue by ghost1nthemachine** [nus-cs2030/2223-s2#224]
# Summary

im having issues with the method parameters for level 5 jsh

I have it as: findBestBooking(Request request, ImList<Driver> drivers) 

and got this error:
 incompatible types: no instance(s) of type variable(s) E exist so that java.util.List<E> conforms to ImList<Driver>

dont seem to know whats wrong :(

**Comment by ringleading** [comment]
hey, the input params are a Request and a List of Drivers

**Comment by kyledilao777** [comment]
yea List.of generates a list rather than an imlist. but this shouldnt rlly affect ur code in the body, should still w imlists

**Comment by leonardwx** [comment]
It is not ImList but List<Driver>

**Comment by andersooi** [comment]
You can change the second parameter's type to to a List and remeber to declare what it will contain
