### ISSUE TITLE
Exercise 3: Converting Solid to Shape3D

### ISSUE THREAD

**Issue by sp4ce-cowboy** [nus-cs2030/2223-s2#226]
Hi I've been stuck on this for a while, everything else works except for the very last one:

<img width="465" alt="image" src="https://user-images.githubusercontent.com/19762596/220715161-e5e691a4-1551-462c-83ec-29445a8b3532.png">

But I'm getting:

<img width="541" alt="image" src="https://user-images.githubusercontent.com/19762596/220715276-a4bb4047-50c4-4b3f-af2b-baf1eae254a7.png">

In my implementation, Solid is an interface and Shape3D is an abstract class. I'm quite confused as to how the polymorphic behaviour as shown above can be demonstrated in the first place, am I supposed to make my Shape3D an interface?

**Comment by territxl** [comment]
I think it is because your Solid does not extends from Shape3D. Hope this helps!

**Comment by territxl** [comment]
I think you can also consider the differences between an interface and an abstract class. Subsequently, you can then decide if Shape3D should be an interface/abstract class.

**Comment by allnotavailable** [comment]
Yes I think solid should inherit or implement from shape3D so that it can be called as shape

**Comment by territxl** [comment]
I think understanding how polymorphism works (i.e. the relationship between your classes/interfaces) will help you to understand how inheritance (extends/implements) would work and its output.

**Comment by leonardwx** [comment]
u have to figure out a relationship between Solid and Shape3D!

**Comment by sp4ce-cowboy** [comment]
Alright it works, thanks guys.
