### ISSUE TITLE
lab 4 level 3 

### ISSUE THREAD

**Issue by sporobolous** [nus-cs2030/2223-s2#227]
# Summary

Im having a little trouble understanding the requirements 

how do I go about to make NormalCab drivers provide JustRide and TakeACab services?

do I have a method in Normal Cab that compares the prices of both services?

and how do I move on to level 4 where there is another type of driver that takes in different services?

**Comment by sp4ce-cowboy** [comment]
You can try having each type of service inherit from a Parent, and each type of Driver can have an ImList of said Parent objects which you can then iterate from.

**Comment by territxl** [comment]
If in each Driver, as we compare the prices of both services, if both have the same computed fare, do we still need to take into account the waiting time if they actually have the same driver i.e. same waiting time? How do we determine which service is chosen instead?

**Comment by ringleading** [comment]
> If in each Driver, as we compare the prices of both services, if both have the same computed fare, do we still need to take into account the waiting time if they actually have the same driver i.e. same waiting time? How do we determine which service is chosen instead?

In Level 5, it says:
`You may assume that no two bookings have the same fare and the same waiting time.`

to reply to OP's question:
consider a basic Driver implementation, where each Driver has a set of Services that he can perform. obviously, the set will be empty for a basic Driver, but a NormalCab adds JustRide and TakeACab to that set of services etc.

if you find yourself coding in the same methods throughout Drivers/Services, you can probably consider having that method in the parent class instead

**Comment by leonardwx** [comment]
you can create a method within the NormalCab class that compares the prices of TakeACab service and JustRide service. The method can return the fare! You can tehn create another method within normal cab that returns the type of the cheaper service. Then in the constructor of the booking class, it can call both methods to get both the fare type and fare

**Comment by territxl** [comment]
> > If in each Driver, as we compare the prices of both services, if both have the same computed fare, do we still need to take into account the waiting time if they actually have the same driver i.e. same waiting time? How do we determine which service is chosen instead?
> 
> In Level 5, it says: `You may assume that no two bookings have the same fare and the same waiting time.`
> 
> to reply to OP's question: consider a basic Driver implementation, where each Driver has a set of Services that he can perform. obviously, the set will be empty for a basic Driver, but a NormalCab adds JustRide and TakeACab to that set of services etc.
> 
> if you find yourself coding in the same methods throughout Drivers/Services, you can probably consider having that method in the parent class instead

Thanks! I missed that out :(

**Comment by sporobolous** [comment]
> you can create a method within the NormalCab class that compares the prices of TakeACab service and JustRide service. The method can return the fare! You can then create another method within NormalCab that returns the type of the cheaper service. Then in the constructor of the booking class, it can call both methods to get both the fare type and fare
> 
> same as how it works for PrivateCab! hope it helps :)

Hi but my NormalCab only takes in the plate no, and time, how do I make it compare TakeACab and JustRide? 

via NormalCab extends Booking?

**Comment by leonardwx** [comment]
u can create another properties inside the NormalCab such as this.justride and this.takeacab, then compute the fares accordingly. then create a method to compare the fares and  return the service of lower fare(JustRide or TakeACab)! 

u dont have to extend any booking because when it takes in driver and request constructor, it can call the method above to get the type of cheaper service!

**Comment by taugwa** [comment]
> > you can create a method within the NormalCab class that compares the prices of TakeACab service and JustRide service. The method can return the fare! You can then create another method within NormalCab that returns the type of the cheaper service. Then in the constructor of the booking class, it can call both methods to get both the fare type and fare
> > same as how it works for PrivateCab! hope it helps :)
> 
> Hi but my NormalCab only takes in the plate no, and time, how do I make it compare TakeACab and JustRide?
> 
> via NormalCab extends Booking?

for me i have an imlist of relevant services in my privatecar/ normalcab, then my method to compare which service is better in any driver is in my Booking class !

**Comment by sporobolous** [comment]
Thanks everyone for their inputs! I understand my confusion with the question now
