### ISSUE TITLE
using getServiceTime only  in Serve event

### ISSUE THREAD

**Issue by tali-a** [nus-cs2030/2223-s2#228]
Hi, based on what was previously explained by everyone, I understand why it's necessary to only call getServiceTime in the serve event class and not the arrive class. however, since i cant initialise a serve event with an updated server, i;m struggling to update the server list and generate the next event with an updated server, while still only calling getServiceTime once. any advice would be very  very appreciated 

~I also tried using Pair objects , but am running into issues with implentation - it's not possible to override unless the arguments for the methods match - would it be redundant to return Pair objects even where they are not necessary?

**Comment by secretApple** [comment]
if i'm not wrong, you can create an attribute and call getServiceTime once  in your event, and after that in the methods you can just refer to that attribute

**Comment by ayevxn** [comment]
With regard to the question on Pairs, I had some of my events return the same server list in the Pair objects being returned. I believe this is the case even if you don't use Pairs (i.e. if you had separate execute and update methods, all events would need to have these two methods to facilitate the PQ, even if update returns the exact same server list).

**Comment by ringleading** [comment]
once your Serve event is executed, your Server's next available timing will/should be updated accordingly. from there, you can handle the Server's next event(s) through that updated timing with a getter like @secretApple mentioned, since your Comparator sorts the events chronologically/by Customer for you

if you're considering using Pair objects, your Pair object types should be consistent throughout all implementations of it within the method (i.e. should always return the same two types in the Pair)

**Comment by wmingchuan** [comment]
Make sure your server's next available timings are updated each Serve event. When the Server is full and got queue space, Customer will be directed to the Wait event, add the Customer to the queue and let Wait event return a Check event. During the Check event, check if the Customer is the first in queue. If it is, return Serve event with the next available timing. If it is not, return another Check event with the next available timing so you can Check again. Make sure to update the queue in the Serve event.

**Comment by JYeoZS** [comment]
Sounds like problem may lie with Pair's redundancy.

Are you updating server status every round an event is triggered? You would need to return an event every time another event is triggered also.

Suspect some of these may be missing in your Pair. The serviceTime problem could follow naturally...

**Comment by tali-a** [comment]
Thanks everyone! I ended up creating an attribute
