### ISSUE TITLE
main.jsh causing compilation error

### ISSUE THREAD

**Issue by Xequil1** [nus-cs2030/2223-s2#23]
# Summary
The main.jsh file directly accessed the point's private attribute which is causing a compilation error.

Are we supposed to change the functions in main.jsh to circumvent such problems? I am asking because I am unsure if we are allowed to modify functions in main.jsh.

![Screenshot (144)](https://user-images.githubusercontent.com/122268182/214551967-4525ea96-a321-4680-89c4-7d1886b15f2d.png)

**Comment by SimonSeeYongsheng** [comment]
> # Summary
> The main.jsh file directly accessed the point's private attribute which is causing a compilation error.
> 
> Are we supposed to change the functions in main.jsh to circumvent such problems? I am asking because I am unsure if we are allowed to modify functions in main.jsh.
> 
> ![Screenshot (144)](https://user-images.githubusercontent.com/122268182/214551967-4525ea96-a321-4680-89c4-7d1886b15f2d.png)

Just change the functions in main.jsh

**Comment by haqanh** [comment]
> # Summary
> The main.jsh file directly accessed the point's private attribute which is causing a compilation error.
> 
> Are we supposed to change the functions in main.jsh to circumvent such problems? I am asking because I am unsure if we are allowed to modify functions in main.jsh.
> 
> ![Screenshot (144)](https://user-images.githubusercontent.com/122268182/214551967-4525ea96-a321-4680-89c4-7d1886b15f2d.png)

Hi, I think you are supposed to modify the functions in main.jsh such that it will compile without violating the principles that we learned in class.

**Comment by jayson237** [comment]
Hi, I would like to clarify, since we are not suppose to ask but tell instead, Prof Henry also allows us to move the distanceBetween and contains methods to other classes, i.e. Point and Circle, to meet the design criteria.

![Screenshot_20230127_051202](https://user-images.githubusercontent.com/110618399/215049789-58f2aba5-a0e0-4ee1-8a52-7d91ab03fe1a.png)
