### ISSUE TITLE
Ex 2: Recycled loaders only work the first time

### ISSUE THREAD

**Issue by trickypepe** [nus-cs2030/2223-s2#231]
Recycled loader only behaves like a recycled loader when it is created, but behaves like a regular loader afterwards. The output still says recycled loader though. Any help would be appreciated!
![Recycling](https://user-images.githubusercontent.com/122513341/220808501-f9ca2a75-fd9c-417d-aa60-54980b9900c8.png)

**Comment by Ooimax123** [comment]
Without looking at your code, I think its likely that when you create new service with the loader the compile-time type changes and you get a regular loader instead of a recycled one

**Comment by trickypepe** [comment]
Oh wow, you're right, I defined a new method to return a recycled loader and it works now. Thanks!
