### ISSUE TITLE
Test Case 10: Too many service times generated

### ISSUE THREAD

**Issue by haqanh** [nus-cs2030/2223-s2#232]
Hi, I am facing the Too many service times generated error for Test case 10. I had it at first for test case 1, which I fixed but now I am failing test case 10 still. 

Has anyone faced a similar issue?

![IMG_20230223_150117_140](https://user-images.githubusercontent.com/122341707/220839424-5f292908-43e3-4f59-9e5c-5370ec31e37c.jpg)

**Comment by meljwang** [comment]
Either you are calling getServiceTime() outside of Serve Event or you never update your state of servers properly during each event.

**Comment by Yew-Wei** [comment]
I had this issue as well, might want to check how your customer queue is updated. There might be scenarios e.g. where servers serve customers when they should have left as the queue was not updated correctly. Then again, it depends on how your queue is implemented as well. Hope this helps!

**Comment by haqanh** [comment]
> I had this issue as well, might want to check how your customer queue is updated. There might be scenarios e.g. where servers serve customers when they should have left as the queue was not updated correctly. Then again, it depends on how your queue is implemented as well. Hope this helps!

is there anything specific about test case 10 perhaps? since I passed the previous tests except for this one

**Comment by Yew-Wei** [comment]
> > I had this issue as well, might want to check how your customer queue is updated. There might be scenarios e.g. where servers serve customers when they should have left as the queue was not updated correctly. Then again, it depends on how your queue is implemented as well. Hope this helps!
> 
> is there anything specific about test case 10 perhaps? since I passed the previous tests except for this one
Not too sure, it depends on your code design. You could possibly use System.out.println("sth") in your default service supplier to see how many times getServiceTime is called, copy the arrival times of test case 10 and test it out on jshell to see what went wrong.

**Comment by haqanh** [comment]
Thanks guys, managed to figure out the issue, it was with updating the Queue after my Done event :)
