### ISSUE TITLE
What does a docker actually do?

### ISSUE THREAD

**Issue by kciruos** [nus-cs2030/2223-s2#233]
Just curious to know what the actual function is and how it works.

**Comment by jorwong** [comment]
Docker is a containerisation system. Think of it as a separate operating system living in your computer or server whose main purpose is to run a single system. It also allows applications to be easily ported from one operating system to another without considering the host's compatibility. As long as it is able to support virtualisation and installing docker application, it is able to run the images in the docker container system

**Comment by glenn2030** [comment]
To add on, docker is a platform that allows you to run and manage containers, which are lightweight, portable, and self-contained environments that can run applications and services. Docker provides a way to package an application with all its dependencies, such as libraries and runtime environment, into a single container, ensuring that the application will run consistently across different environments.
