### ISSUE TITLE
Exercise 3 

### ISSUE THREAD

**Issue by clarwen** [nus-cs2030/2223-s2#238]
I have some queries regarding the principles in exercise 3. In level 6, code crunch states that "The SolidImpl class can now be an implementation of Solid". Can an interface be a parent of another interface? How does SolidCuboid that implements Solid interface get the properties of mass?

**Comment by ugchongg** [comment]
yes! an interface can extend another interface! for SolidCuboid to get mass, you can try to delegate the computation to SolidImpl as stated in the question! hope this helps!

**Comment by kciruos** [comment]
Also do note,  a concrete class can implement multiple interfaces, but can only extend  a concrete class or a abstract class. Interfaces cannot implement anything, and can only extend interfaces!

**Comment by jamiepngg** [comment]
you can create a SolidImpl object in your constructor, and in your mass() method of SolidCuboid you should be returning the mass() from SolidImpl

**Comment by territxl** [comment]
Yep! Between interfaces, they can extend to one another :)

**Comment by leonardwx** [comment]
yes interface can extend another interface! the solidCuboid can create a solidImpl object and compute the mass from there
