### ISSUE TITLE
Customer queue for each server lab 03

### ISSUE THREAD

**Issue by ghost1nthemachine** [nus-cs2030/2223-s2#239]
# Summary

how should i be managing the queues for each server?

should I be creating the Imlists of customers in the Server class? how would i 'tag' the queue to each server, is making it an attribute of a server a bad idea 

im very unsure of the implementation :( any advice would be appreciated!

**Comment by coderlimjingcheng** [comment]
What I did was to include ImList of customers in the Server class, like you mentioned. I don't understand what you mean when you say 'tag' the queue to each server, but each Server should be an object of its own and hence its own customer queue?
