### ISSUE TITLE
Issues installing and running Docker

### ISSUE THREAD

**Issue by ahndrayo00** [nus-cs2030/2223-s2#24]
# Summary
I am unable to fully install Docker. I am writing with reference to the guide on installing Docker - https://github.com/nus-cs2030/2223-s2/wiki/Setting-Up-Docker-Desktop

## Description 
When I tried to pull the CS2030 image through the command 
`docker pull ghcr.io/nus-cs2030/cs2030:latest`
I encounter the error that Docker is not running. When I open Docker, it is permanently stuck in the state "Docker Desktop starting". (Screenshots attached below)

## Screenshots (if any): 
![image](https://user-images.githubusercontent.com/123559896/214569944-d81cbcbc-52cb-4254-a3d0-262e17e6cc71.png)
![image](https://user-images.githubusercontent.com/123559896/214569994-5137ffe6-1f9b-4958-a14d-cb8b99a61916.png)

**Comment by JYeoZS** [comment]
Hi,

May wanna try: 

"docker login ghcr.io"

Login with github credentials and try again.

Cheers.

**Comment by trwstin** [comment]
Might be an issue with your WSL. Can you try the following steps:
1. Close Docker
2. Open Command Prompt as Admin
3. Type `wsl --update`
4. Restart Docker

If you have yet to install a WSL, Ubuntu is available on the Microsoft Store.

**Comment by ahndrayo00** [comment]
Hi @JYeoZS tried doing that but I am unable to key in my password (when I type, nothing appears on my screen. After pressing enter, same message appears).

Hi @trwstin I just updated my WSL and the same error still appears as seen in the screenshot below

![image](https://user-images.githubusercontent.com/123559896/214865596-9b688465-3870-4841-a40f-c401e18deee5.png)

**Comment by danqiye1** [comment]
Hi if you are in school today you can come to my office at i3-3-18 and I will help you set it up

**Comment by lihongguang00** [comment]
Hi ahndrayo,

It helps to check if CPU visualization is enabled on your set-up.

You can check this by opening task manager -> performance -> CPU -> ensure "virtualization" is enabled.

![image](https://user-images.githubusercontent.com/84987837/214994779-b338f0af-2da1-45c8-b29d-9e75065a2a4d.png)

If it is disabled, you can refer to the following guide to enable it: https://www.simplilearn.com/enable-virtualization-windows-10-article

Do note that your BIOS settings will depend on your machine's motherboard type (AMD/Intel). For Intel, the name of the setting should have "virtualization", but for AMD, I believe it's called SVM mode. Information on this should be readily online.

Hope this helps! Cheers

**Comment by yueqianh** [comment]
When one of my friends had the issue, it was because the WSL 2 prerequisite was not installed on the machine. You may refer here for how to install it: https://docs.microsoft.com/en-us/windows/wsl/install-win10.

**Comment by ahndrayo00** [comment]
@yueqianh @lihongguang00 it's been resolved thank you so much anyway!
@danqiye1 thanks for helping to set up!

**Comment by trwstin** [comment]
> @danqiye1 thanks for helping to set up!

Are you able to briefly explain what was the solution? In case someone else encounters this issue in the future! :)

**Comment by ahndrayo00** [comment]
> > @danqiye1 thanks for helping to set up!
> 
> Are you able to briefly explain what was the solution? In case someone else encounters this issue in the future! :)

The actual issue was never pinpointed, but we tried updating my WSL and installing Ubuntu. Docker still wasn't working initially so we just installed Vim directly through ubuntu.

But when I got back and restarted my computer, Docker was working fine alr!

**Comment by choongzhanhong** [comment]
For those using Windows and face the "Docker desktop starting" issue, I believe you can switch to Windows containers, and it will start as intended. 

![image](https://user-images.githubusercontent.com/65936691/215237323-76d1fd2c-7340-4c5d-af05-131ac1cd9e61.png)

I'm also still facing issue after that, when I try to pull the image or login, namely this error:
`Error response from daemon: open \\.\pipe\docker_engine_windows: The system cannot find the file specified.`

**Comment by choongzhanhong** [comment]
Nevermind, I don't think that's the right way. What worked for me:
1. Uncheck "Use WSL 2" (Use Hyper-V instead, which can be enabled under the "Turn Windows features..." menu.)
2. [Enable virtualisation in BIOS](https://www.simplilearn.com/enable-virtualization-windows-10-article), which seemed to work here #11

**Comment by danqiye1** [comment]
I have updated the wiki to provide some instructions to installing WSL. What @choongzhanhong said works fine too, just that Hyper V was the old engine from last time and this switch from Hyper V to WSL as the default backend of Docker Desktop is causing additional problems for students who have not enabled the WSL feature in their machines.

Hope that all these discussion helps everyone get set up.

**Comment by zozozoes** [comment]
I had the same issue. I reinstalled docker using hyper V instead of WSL and it started working.

**Comment by RussellDash332** [comment]
Apparently, another unorthodox approach is to downgrade your Docker version or reinstalling but you run installer as an administrator (click right + run as admin)

**Comment by mralvern** [comment]
I had this issue too. My fix was to update wsl2 through the command line. Hope this helps!

**Comment by aowz** [comment]
I had to update the WSL2 system through the command line. After that I restarted my computer and docker loaded up. I hope this helps !

**Comment by shannon-jx** [comment]
I have issues with my docker functioning as well but it's not the same as the one mentioned above. After coding for a while, my terminal would freeze and nothing I do, including Ctrl + C, helps. I have attempted to stop/restart the container but it just freezes my docker as well. I would provide a screenshot but it's not very meaningful as it appears to seem like a normal terminal but I am unable to type anything, or there's simply no response from the system. The only thing I can do is to restart my laptop, something that I have to do once every 2-3 days, which is quite inconvenient. Has anyone faced the same issue and has successfully resolved it? Do let me know!
