### ISSUE TITLE
Cuboid Query Exercise 3 

### ISSUE THREAD

**Issue by kciruos** [nus-cs2030/2223-s2#241]
Why can't Cuboid's attribute be **protected final** since the child (CuboidSolid) uses it in the toString method?

**Comment by hhuilingg** [comment]
i think there is no need to have protected final, but private final will do. if u need to use the toString, you can just super.toString()

**Comment by territxl** [comment]
I think for this module, we have to set all the attributes to private final. Moreover, since most or if not all our classes are in the same directory, setting it as protected does not differ from setting it as public. Hope this helps to clarify!

**Comment by leonardwx** [comment]
we try to set everything to private final so that others can't use/edit the code. u can call the parent class of toString using super since it is public!

**Comment by AmanDesai34** [comment]
if you want to call a private final value in another class you can always yse the getterfunction too
