### ISSUE TITLE
Lab4 level 5 : how to sort the services using comparator?

### ISSUE THREAD

**Issue by ngshiyingg** [nus-cs2030/2223-s2#242]
# Summary

Hi, I have created a BookingComp class that implements comparator(Booking), which uses the compareTo() method in the Booking class. I have also created a method in the Booking class that would return an ImLIst of all four possible services from two bookings.  

However, I am now confused about how to use the BookingComp to sort the ImList of services. Any advice would be appreciated, thanks!!

**Comment by haqanh** [comment]
Personally, what I did was redefine the comparator in the BookingComparator (that I would use for sorting of the ImList) as now insetad of just returning the best booking, we need a comparator that looks at the price & wait time of _all_ the booking. 

Hope this helps :)

**Comment by ngshiyingg** [comment]
thanks all for your help!!:)
