### ISSUE TITLE
[Lab 3] Cyclic Dependencies Detected

### ISSUE THREAD

**Issue by cweisong** [nus-cs2030/2223-s2#243]
Cyclic dependencies detected within classes.

Any suggestions/advice to work a way around it and possible to tell which classes are cyclic dependent from the screenshot below?

Thank you in advance!

<img width="327" alt="Screenshot 2023-02-24 at 12 26 26 AM" src="https://user-images.githubusercontent.com/122463025/220969852-99c73b1f-b5f9-4c1a-8240-e0e76389912e.png">

**Comment by weitatftw** [comment]
your SimulationResult.class and Event.class are mutually dependent on one another

**Comment by cweisong** [comment]
Solved it, thank you!
