### ISSUE TITLE
lab 3 test case 7 

### ISSUE THREAD

**Issue by xj8423** [nus-cs2030/2223-s2#244]
hi everyone, my get service time is used only once in the serve class and i am checking through list of servers to get the most updated server (and its end serve time) but my service time still seems to be mixed up? im also using the wait event to only return the serve event when the customer is the first in the wait queue, otherwise another wait event is generated, so im not really sure whats wrong :'( 

am i missing anything else? or do i keep checking these things.. thank you all in advance! any tips will be greatly appreciated :')

<img width="418" alt="Screenshot 2023-02-24 at 12 43 19 AM" src="https://user-images.githubusercontent.com/122519244/220973058-3c2e1178-6bda-49be-bd5f-de73383e180e.png">

**Comment by orangejunhui** [comment]
hi! i had this same error and i realised it was because i was calling getServeTime() multiple times when i thought i was only calling it once. i checked it by putting a print statement System.out.println("servetime generated") - maybe you can try it and see if you are actually only calling it once!

**Comment by tynkyra** [comment]
I faced the same problem when I called getServiceTime in the constructor of the Serve class as well. It worked once i only called it in the addEvent in the serve class

**Comment by xj8423** [comment]
ah okay i resolved it! thank you all :))

**Comment by calista03** [comment]
Hi there! I'm currently facing the exact same problem as you....can I ask how you managed to resolve it in the end? I've tried to only call getServiceTime in the addEvent in the serve class, but then found that I wasn't able to retrieve those values (because I cannot call getServiceTime again) in another method in the Serve class which is supposed to return the updated serverlist... any help will be greatly appreciated!! Thank you so much :)

**Comment by xj8423** [comment]
> Hi there! I'm currently facing the exact same problem as you....can I ask how you managed to resolve it in the end? I've tried to only call getServiceTime in the addEvent in the serve class, but then found that I wasn't able to retrieve those values (because I cannot call getServiceTime again) in another method in the Serve class which is supposed to return the updated serverlist... any help will be greatly appreciated!! Thank you so much :)

hi there! i resolved it by putting my getServiceTime() in my method instead of the constructor! for your case maybe you can consider storing the value of getServiceTime() into a variable then passing this variable into your other method that needs it (to update your serverlist)?  hopefully this helps!

**Comment by Sangobionn** [comment]
@calista03 did you manage to solve it in the end? because i have same output and is facing the same problem... idk how to use the value in my updateServerList method later on. Did you put getServiceTime in attribute/ as a method? Thankyouu
