### ISSUE TITLE
Self-Practice 2 Level 3

### ISSUE THREAD

**Issue by junglebollz** [nus-cs2030/2223-s2#245]
Helloo everyone, for level 3, I am able to pass the first test case when there are no overlaps in service end time and the next service's start time. But for test case 2, in order to tackle the overlap in timing I used an if-else statement within a for loop (but for some reason after the code goes through the if-else statement for the first time, the for loop seems to have been broken :( 

I would like to understand how I can prevent this + if having an if-else statement in a for/while loop would break them ~

Thank you all for your help!

**Comment by victoriamagdalena** [comment]
hello! actually, the given algo is such a big hint! basically, you need to keep track of the ACTIVE and EXPIRED queues. some considerations that you might need to think about: 
1. yes, we need to go through all the services in the ACTIVE queue, but do we need to do that to the EXPIRED queue as well? if not, then when should you stop picking the expired services from the EXPIRED queue? (hint: consider using a "counter" var to control your looping here) 
2. what would be the condition for you to deploy new loaders? when there's no service event in the ACTIVE or EXPIRED queue? 
you may also use other approaches, but i used the approach above and it works:) hope it helps!

**Comment by e0959170** [comment]
unless you're explicitly putting in a break or return statement in your if/else statement, your for loop should not break

unless in your if else statement, you are altering the same list that you are looping through, that might definitely cause it to break

**Comment by junglebollz** [comment]
Thank you all! I realised the error was in one of my for loop statements :")
