### ISSUE TITLE
Ex 1 Last Test Case 

### ISSUE THREAD

**Issue by ghost1nthemachine** [nus-cs2030/2223-s2#246]
<img width="533" alt="Screenshot 2023-02-24 at 3 48 16 AM" src="https://user-images.githubusercontent.com/125187978/221014824-84761a2d-be1b-4a55-9cee-76888efe4f66.png">

Any idea what I missed out? only the last test case seems to mess up

**Comment by leonardwx** [comment]
try using ceateUnitCircle(p,q) and change the distancePQ < 2 to distancePQ <= 2
