### ISSUE TITLE
Cannot find symbol in Jshell but it exists?

### ISSUE THREAD

**Issue by choongzhanhong** [nus-cs2030/2223-s2#248]
# Summary

When trying to open the Java files in Jshell, I get the same error:
```
jshell> /open Driver.java

jshell> /open NormalCab.java
|  Error:
|  cannot find symbol
|    symbol:   class Driver
|  class NormalCab extends Driver {
|                          ^----^
|  Error:
|  method does not override or implement a method from a supertype
|      @Override
|      ^-------^
|  Error:
|  non-static variable super cannot be referenced from a static context
|          return super.toString() + " NormalCab";
|                 ^---^

```
Problem is, Driver does exist!! I also used `/list` to confirm and opened it in order of bottom up dependency so I don't see why it doesn't work. It is definitely not a syntax error, I also checked using other IDEs and as far as I know I am sane.

## Description:

This keeps happening. I even tried to create a new class in Jshell.
```
jshell> class Normal extends Driver {
   ...>     Normal()
   ...>     {
   ...>     }
   ...> }
|  created class Normal, however, it cannot be referenced until class Driver is declared
```
and to add insult to injury...
```
jshell> class Driver
   ...> {
   ...> }
|  replaced class Driver
```

## Screenshots

Screenshots (if any)
![image](https://user-images.githubusercontent.com/65936691/221071873-2a70dc2c-9219-4581-a21d-1e6a61165670.png)
![image](https://user-images.githubusercontent.com/65936691/221071889-f859b932-cb4e-4c41-81b4-5b886e8aa61c.png)

How should I go about this? ._.

**Comment by choongzhanhong** [comment]
I'm unable to resolve this, but as an interim solution I just created a `Main.java` class with a `main()` method to run all the jshell commands which works fine. Using jshell in IntelliJ terminal also doesn't work. This actually also happened during Lab on the PENode as well so it's not unique to my own computer. Weird!

**Comment by WXUXIN** [comment]
I encountered the same issues as well. Here are the things you should check: 
1.) If your .java files are all i the same folder (Most probably yes)
2.) Check if you have all your imports (ie. Comparable etc)
3.) Include ImList, Pair in your javac statement

**Comment by choongzhanhong** [comment]
With regards to the above:

1. Yes, all in the same directory (relative to docker container, `/workspace/Lab4`
2. Yes, double-checked using IntelliJ IDE across the necessary files.
3. Yes, in fact I used `javac *.java` with no issue.

Anyway, I have completed the Lab by just using a Main method to test my code instead of Jshell 😄 I will close this for now, but I suppose anyone can reopen if they find a solution.

**Comment by WXUXIN** [comment]
Lastly check if its cyclic dependent

**Comment by choongzhanhong** [comment]
As far as I know, it is not, my Driver and NormalCab classes both only contain an ImList<Ride> and do not reference each other (except for superclass relationship).

My Ride class also does not interact with Driver class, as it is only handled through booking.

**Comment by choongzhanhong** [comment]
Okay, I feel dumb but I figured out the issue. So, it all compiles but I didn't `/open ImList.java` in Jshell. Hahahahaha.
