### ISSUE TITLE
Level 3 no output from toString( )

### ISSUE THREAD

**Issue by eesean** [nus-cs2030/2223-s2#249]
Hi all,

Would like to ask whether there is a way to convert an integer to 2 decimal places, just as cents can be converted to dollars? I tried using String.format( ) to convert directly from integer to double, but my method was probably wrong as CodeCrunch reported IllegalFormatConversionException, hence no string was generated from toString( ) when I created a booking object. 

<img width="417" alt="Screenshot 2023-02-24 094813" src="https://user-images.githubusercontent.com/110977266/221072169-ff799d49-04c1-450a-a8af-1ae8256dbaa2.png">

**Comment by orangejunhui** [comment]
i think the only way is to: 
fare = computeFare(...); // returns fare in cents e.g. 333
dollars = fare / 100; //integer division returns integer rounded down --> 3
cents = fare % 100;
string = Integer.toString(dollars) + "." + Integer.toString(cents);

or maybe typecast your integer to a double then divide 100.0 to get a double directly. i'm not sure if this will cause an issue on codecrunch though.

**Comment by eesean** [comment]
Yep just tried your method and it works! Thanks for the help.
