### ISSUE TITLE
Not sure how to submit files for Lab 1

### ISSUE THREAD

**Issue by NingXinran** [nus-cs2030/2223-s2#25]
Hi! I'm not sure how to submit my files for Lab 1. The functions run according to whats specified in codecrunch, but when I submit all 4 files (eg Point.java, main.jsh), the number of tests run is 0 and the compilation errors don't look right..? Can someone explain how I'm supposed to go about submitting? Thanks!

![Screenshot 2023-01-26 at 6 30 59 PM](https://user-images.githubusercontent.com/70146427/214814259-0b8c4152-cb1e-4b2b-a3ca-63b000dc7379.png)

**Comment by jorwong** [comment]
Hi, I think what the error messages are trying to say is that you have to set your attributes of the class to private final so as to maintain the abstraction barrier.

**Comment by NingXinran** [comment]
oh i see!! thanks!
