### ISSUE TITLE
Level 5 list of bookings

### ISSUE THREAD

**Issue by veviana** [nus-cs2030/2223-s2#250]
I am quite confused with how i can add new bookings into the imlist. What i did was i create an ImList to store all bookings. I have a for loop to add all the bookings into this ImList, but it produces an empty ImList when i run the program. I kind of followed lecture 5 slide 13 but it still produces an empty list.

**Comment by meljwang** [comment]
Did you assign it back to the bookinglist variable when you do bookinglist.add?

**Comment by veviana** [comment]
> Did you assign it back to the bookinglist variable when you do bookinglist.add?

is it something like bookinglist = bookinglist.add?

**Comment by e0959170** [comment]
> > Did you assign it back to the bookinglist variable when you do bookinglist.add?
> 
> is it something like bookinglist = bookinglist.add?

yup! that;s right. due to immutability, if you don't reassign it back your imlist will not add

**Comment by veviana** [comment]
> > > Did you assign it back to the bookinglist variable when you do bookinglist.add?
> > 
> > 
> > is it something like bookinglist = bookinglist.add?
> 
> yup, that's right! due to immutability, if you don't reassign it back your imlist will not add this is because if you look through the imList class, add() actually returns a new imlist instead of altering the existing one. hope this helps!

i missed out on this! thank you so much!
