### ISSUE TITLE
Lab 3 Test Case 3 - wrong output order 

### ISSUE THREAD

**Issue by emilythx** [nus-cs2030/2223-s2#254]
# Summary
Hi! I'm facing some issues with test case 3. The order of events are incorrect when the arrival time and done events are the same. Attached is an image of my output. Thanks in advance :'))
Description of the question / problem here.

## Description:

Clarifications or details with respect to the issue you are facing

## Code Snippets

Attach code snippets (if any)

## Screenshots

<img width="458" alt="Screenshot 2023-02-24 at 4 30 52 PM" src="https://user-images.githubusercontent.com/122248580/221130317-7d972091-fd64-4b28-af66-f4d0862b1e41.png">

**Comment by sethteo** [comment]
It is probably because your Server is not updating properly, at every iteration you should be fetching the "latest" Server but the way you fetch it depends on how your code is implemented 
Hope this helps !

**Comment by e0959170** [comment]
hi emily! perhaps there is some error in your logic going from wait to serve because it seems that 4 is being served by 2 instead of 1?

**Comment by wmingchuan** [comment]
Make sure your queue and server references are correct, might be indexing the wrong item

**Comment by meljwang** [comment]
You might want to check if, for every new event created, you are using the list of updated stateOfServers and that you are not using 'this.server' (the server attached to the class).

**Comment by emilythx** [comment]
@e0959170 hi yes, thanks for pointing that out! I realised that there is a logic error in my code (updating time for the continue wait event)

**Comment by emilythx** [comment]
@sethteo @wmingchuan @meljwang Thanks for the help! will look into it :')

**Comment by emilythx** [comment]
update: realised that i misinterpreted the entire qn... thanks everyone for the comments!
