### ISSUE TITLE
lab3 what is lab3 talking about?

### ISSUE THREAD

**Issue by sporobolous** [nus-cs2030/2223-s2#255]
# Summary

hi, I have been staring at lab3 for days and its staring back at me. Im kinda lost on how to start. 

if there is any kind souls willing to share what are the steps that will be great, esp the steps after implementing the waitEvent.java

**Comment by wmingchuan** [comment]
Make sure every event returns another event and no cyclic dependencies (other than returning itself). I had waitEvent returning a check event. See #212

**Comment by sporobolous** [comment]
> Make sure every event returns another event and no cyclic dependencies (other than returning itself). I had waitEvent returning a check event. See #212

thanks! I will check it out

**Comment by haqanh** [comment]
I think similiar to Lab 2, you just build on what you have done previously. a particular new thing for Lab 3 would be that there is now a Wait event (that transitions from your Arrive to Serve), and the fact that you can now queue in servers, and you need to implement this also :)

Jiayous you can do this!!

**Comment by territxl** [comment]
I guess like what @haqanh has mentioned, maybe you can try understanding the difference between the problem in lab 3 and lab 2. Subsequently, do spend some time thinking of how the queue is update (Rmb to avoid cyclic dependencies!) Jiayous :D

**Comment by emilythx** [comment]
Hi! You may consider creating a continue wait event to transition from a wait to serve event, and a an abstract getNextEvent() method such that each event will pass on a new event. Do note that the qmax is the queue length of 1 server and not for the entire serverlist (personally made a mistake here...). All the best!

**Comment by Yew-Wei** [comment]
Also depending on your previous implementation, there should be no type checking in your simulator class. (e.g. your .next() method could possibly return a pair containing the serverlist and next event.)

**Comment by sporobolous** [comment]
> Hi! You may consider creating a continue wait event to transition from a wait to serve event, and a an abstract getNextEvent() method such that each event will pass on a new event. Do note that the qmax is the queue length of 1 server and not for the entire serverlist (personally made a mistake here...). All the best!

thanks for the highlight I also thought It was for the entire serverList, thanks everyone I am still trying to code it :(

**Comment by JYeoZS** [comment]
Ok, try think along these few lines:
(1)Arrival-> Serve->Done
(2)Arrival-> Wait->Serve->Done
(3)Arrival-> Leave

1. How many events do you have currently who are polymorphisms of main event class?
2. Each polymorphic event can return another polymorphic event. With this, (1) and (3) should be solvable with no cyclic dependencies.

4. WaitEvent has to return another event that cycles till it's time for customer to be served right? What event should that be? 
5. What are possible conditions under a WaitEvent? Think:
(2.1) I am next customer.
(2.2) I am not next customer.
6. How do I tell when I am next customer? Think something to do with server.

7. Foresee a future problem you may face will be about calling ServiceTime once each customer. How and where should you update your server?

All the best, cheers.

**Comment by rayray39** [comment]
Also remember to compute the statistics. You can do this by having methods in your events to compute them or create an entire new class, which i did, with properties and methods to compute them.

**Comment by sporobolous** [comment]
> Ok, try think along these few lines:
> 
> (1)Arrival-> Serve->Done
> 
> (2)Arrival-> Wait->Serve->Done
> 
> (3)Arrival-> Leave
> 
> 
> 
> 1. How many event classes do you have currently who are polymorphisms of main event class?
> 
> 2. Each polymorphic event can return another polymorphic event. With this, (1) and (3) should be solvable with no cyclic dependencies.
> 
> 
> 
> 4. WaitEvent has to return another event that cycles till it's time for customer to be served right? What event should that be? 
> 
> 5. What are possible conditions under a WaitEvent? Think:
> 
> (2.1) I am next customer.
> 
> (2.2) I am not next customer.
> 
> 6. How do I tell when I am next customer? Think something to do with server.
> 
> 
> 
> 7. Foresee a future problem you may face will be about calling ServiceTime once each customer. How and where should you update your server?
> 
> 
> 
> 8. Once solved 7, consider how you're gonna calculate Serve, Leave and Average Wait Time.
> 
> 
> 
> All the best, cheers.
> 
> 
> 
> 

thanks! I followed these steps but I think I still have some error somewhere oh wells I tried!

**Comment by sporobolous** [comment]
Thanks everyone for your help! Idt I can pass this lab3 on time tho but I appreciate the help!
