### ISSUE TITLE
lab4 testcase 5 fail

### ISSUE THREAD

**Issue by sporobolous** [nus-cs2030/2223-s2#256]
# Summary

getting flagged for test case 5

seems to be an issue with my sorting? 

thanks a lot!
<img width="1236" alt="Screenshot 2023-02-24 at 6 14 03 PM" src="https://user-images.githubusercontent.com/110991431/221152851-ae8f97cf-c62a-4b3a-bea0-f0481417b563.png">

**Comment by ringleading** [comment]
instead of returning the list, have the method be of a void return type and print out each item in the list. also, check that your comparator/comparable methods are properly overridden

**Comment by EmperorAry** [comment]
Your sorting is happening in the opposite order, so you might want to flip your comparator 

Like past labs, instead of returning the ImList, store your output in a string and then return the string

**Comment by leonardwx** [comment]
your return type should not be a ImList. should return as a void and print out the statements instead. check your comparator methods and test it

**Comment by territxl** [comment]
In this case, your output returned is of ImList type which should not be the case since you would like to print lines. Hence, do set your return type of the method as void and use System.out.println() to print out your desired output.

**Comment by haqanh** [comment]
I think you can check your sorting again as the order does not seem to be correct. You should try to implement a Comparator to your ImList that sorts first by Booking Price then Wait Time. Also, your output should not be printing a String, but rather use System.out.println(), as others have pointed out above!

**Comment by viethaaaa** [comment]
You can check your compareTo method/Comparator class again, and for the method in level5.jsh, u should use System.out.println()  inside a loop whereby u iterate through a list of bookings
