### ISSUE TITLE
Ungraded Exercise 1 Level 1

### ISSUE THREAD

**Issue by cocopear** [nus-cs2030/2223-s2#257]
the question states "define an overriding equals method that returns true if any two terminals (not necessarily only pagers; can even be a mix of different types of terminals) have the same identifier, or false otherwise"
does this suggest that the equals method should be in my Term class? if so, how do i implement it? (right now I have implemented it in my Pager class)

**Comment by briannoelkesuma** [comment]
I don't think you can implement it in your Term class because you cannot compare the names as it is defined as an abstract class. What I did was implement it in my Pager class. Not sure if others did differently.

**Comment by granolaluvr69** [comment]
Hello pear, adding on to noel's response, the equals method should be defined in both host and term, and you can check if the identifier attribute of each item that you are trying to compare is identical.

**Comment by timothysashimi** [comment]
Hello! I think you can implement a concrete method equals in ur abstract classes host and term if all the subclasses that inherits from it also contains the field ID. That way you dont have to implement the method equals in all ur subclasses

**Comment by NeoHW** [comment]
also, if you're using an interface, it would mean implementing the same code in all your classes
