### ISSUE TITLE
Private access for accessor method (Exercise 1 on maximum disk coverage)

### ISSUE THREAD

**Issue by eesean** [nus-cs2030/2223-s2#26]
Hi everyone, 

For this exercise I included private accessor methods (e.g. x and y) for Point class, however when I attempt to open main.jsh on jshell most of the errors that appeared were private access errors, particularly for within same classes (e.g. 2 points).

For such errors, would the best option still be to modify main.jsh such that the methods belong to the respective classes? Is it wrong if I were to for instance set my accessor method as protected instead of private, such that the methods can be seen by objects of the same class?

**Comment by jhsoh** [comment]
only the attributes of the class(x and y) should be made private, the accessor methods should be public so that you can call the methods outside of the class

**Comment by Huiling88** [comment]
does that mean we will be violating the Tell-Don’t-Ask principle?

**Comment by granolaluvr69** [comment]
Yes, I had to modify main.jsh so that multiple methods with the same functionality do not show up in multiple classes. It also helps you to adhere to the principle of encapsulation, which ensures that functionality which uses data from a class is kept in that class, which is more organised.
