### ISSUE TITLE
Exercise 2 Graded Self-Practice Failure of Test Case 4

### ISSUE THREAD

**Issue by shannon-jx** [nus-cs2030/2223-s2#262]
Here are some snippets of the error I received for test case 4. Anyone has any clue which part of my code causes this error to come about? My code manually worked for the provided test cases but I have no idea why my Loader #1 and #2 can serve the next cruise when it is still in the active queue for test case 4. We have no information for the test cases too so I'm not too sure how to go about debugging this.
![image](https://user-images.githubusercontent.com/108858861/221274800-847c75c0-e5c8-4e20-8f60-304bf1844e24.png)
![image](https://user-images.githubusercontent.com/108858861/221274866-43e27bf9-784d-4a73-89d2-5c6e8f4aacca.png)

**Comment by Ernestnzx** [comment]
For this in `BigCruise`, what I did for mine was that I used `(int)Math.ceil()` for the `time` taken to serve all the passengers. Afterwards I manage to pass this test case. Hope this helps!

**Comment by shannon-jx** [comment]
> For this in `BigCruise`, what I did for mine was that I used `(int)Math.ceil()` for calculating the `time` taken to serve all the passengers. Afterwards I manage to pass this test case. Hope this helps!

thank you so much omg it worked! didn't know it was "part thereof" for this one too thank youuuu
