### ISSUE TITLE
lab3 test case 10: who should remove customer from wait list?

### ISSUE THREAD

**Issue by Leeeef552** [nus-cs2030/2223-s2#263]
Can anyone suggest if removing a customer from the wait list, should this be done in serve or done event? Or if you faced a similar problem, how did you resolve it?

i managed to get all the public test cases and my service times generated aligns with the number of serve events according to the test cases. 

because if you look at the screenshot, for some reason y still waits at 1 for me. My test case for lab3 shows that my wait list seems to be emptied whenever it is after a done event.  

![image](https://user-images.githubusercontent.com/104271512/221298326-dbc47151-6338-4549-9465-0ca67aeedee1.png)

![image](https://user-images.githubusercontent.com/104271512/221298453-35c5d99d-558a-48cf-be00-8b6c8892b3a4.png)

![image](https://user-images.githubusercontent.com/104271512/221298732-daa89be9-1c8f-4859-b521-83cf133e01af.png)

**Comment by granolaluvr69** [comment]
For my algorithm, I checked if the queue size of the server in serve was greater than 0, and removed them from the queue if that was the case.

**Comment by Leeeef552** [comment]
> For my algorithm, I checked if the queue size of the server in serve was greater than 0, and removed them from the queue if that was the case.

did you do this in serve event?

**Comment by Leeeef552** [comment]
To anyone that faced the same issue, my problem was my wait->intermediate event, my intermediate event took reference to the wrong server so my waiting list was a different one, so if you face a similar issue can try taking reference to the server in your array of servers(the parameter used in the method to run each event) you carried in from the previous event. Thanks

**Comment by Cecilia0327** [comment]
> To anyone that faced the same issue, my problem was my wait->intermediate event, my intermediate event took reference to the wrong server so my waiting list was a different one, so if you face a similar issue can try taking reference to the server in your array of servers(the parameter used in the method to run each event) you carried in from the previous event. Thanks

i face exactly the same issue. Could u plz give a more detailed explanation of how u locate the bug in ur wait -> intermediate? Thanksss!

**Comment by Leeeef552** [comment]
My events takes in a server as an attribute, this is so that I can identify the ID of the server in my toString method. 

But you shouldn't use this event's server status as the most updated status, instead, you should use your list of servers that you pass in your event method to get the most updated status. (Status includes the waitlist at each server) since this is what's truly updated after each loop in your simulation. 

Hope I'm clear enough

**Comment by Cecilia0327** [comment]
> My events takes in a server as an attribute, this is so that I can identify the ID of the server in my toString method.
> 
> But you shouldn't use this event's server status as the most updated status, instead, you should use your list of servers that you pass in your event method to get the most updated status. (Status includes the waitlist at each server) since this is what's truly updated after each loop in your simulation.
> 
> Hope I'm clear enough
ohh i see. i'll check my events and thanks again
