### ISSUE TITLE
[Exercise 2] How to instantiate the constructor for a subclass that need less parameter than its parent class?

### ISSUE THREAD

**Issue by Ooimax123** [nus-cs2030/2223-s2#265]
Hi all, i am doing self exercise 2 level4, which requires me to create SmallCruise and BigCruise classes. My plan was to creating subclasses from Cruise class but since both the subclasses requires only 2 params instead of 4, I am getting compilation error. Does anyone face the issue before?

**Comment by trickypepe** [comment]
Hi, I think there are 2 ways you can try to implement this:

The more proper way would be to include the fixed parameter in your super() call. So like super(id, arrivalTime, 1, 30), abstracting out the magic numbers.

Or you can also input dummy values override the getters() in your parent cruise class so when SmallCruise.getNumOfLoadersRequried() it always returns 1. 

Hope this helps!

**Comment by Ernestnzx** [comment]
Personally I did the first method that trickypepe mentioned! I calculated the necessary variables in place of the `super()` methods for both `SmallCruise` and `LargeCruise`. Just remember to `private static final` your magic numbers and you should be good to go!
