### ISSUE TITLE
Need help in adding all the Arrive Events to the PQ at the start 

### ISSUE THREAD

**Issue by calista03** [nus-cs2030/2223-s2#267]
# Summary

Hi there! Before calling .poll().first() and .poll().second() on my PQ of Events, I first initialise all the Arrive events and add them to the PQ (based on the arrivalTimes given). I include the serverlist as an attribute of the Arrive Events, so that for each Arrive Event I can look through the serverlist and check the availability of the servers - if any one server is free, then I can return a new Serve event. However, when initialising and adding all the Arrive events at the start, (before executing any of the events), I am unable to put in the updated serverlist for each subsequent Arrive Event that I create. Is there any other way that I can go about doing this? Any help will be greatly appreciated! 

## Description:

For example, when I first add all the Arrive Events in the PQ, I am putting in the SAME serverlist (the original serverlist, before any of the events have been executed) into each of the Arrive Events - this means that after the first Arrive event followed by Serve event has been executed (by right Server 1 should be unavailable to serve for a while after that), the second Arrive event does not contain the updated serverlist, and therefore will also call Server 1 to serve the second customer in the second Arrive Event. The screenshot below shows my output because of this. 

## Code Snippets

Attach code snippets (if any)

## Screenshots

Screenshots (if any)
![Screenshot 2023-02-25 at 11 34 28 AM](https://user-images.githubusercontent.com/124029739/221334133-c705b228-4d20-4f47-9b2c-3412ab69c05f.png)

**Comment by sjcze** [comment]
You could create a function that sets the serverlist within the Arrive class. Then call it when you pop the Arrive event from the PQ to update the serverlist attribute.

**Comment by liang-zhengxin** [comment]
I don't think you will be able to update the server list of previously created ArrivalEvents without violating the ```final``` attribute.

You may consider passing it into a function that does the logic of your ArrivalEvent and returning it to update in the ```simulate()``` function for the next event.

**Comment by granolaluvr69** [comment]
Hi Calista,
For every iteration of your loop, 
- ensure that the method you use to obtain the next event takes in serverlist as an argument 
- ensure that all your events have a getserver method which takes in serverlist as an argument to give you the most updated server at that point of time
- take the returned server, update serverlist with it, and assign it back to serverlist
- for the next iteration, your execute will now make use of the most updated serverlist to decide the next event.
Hope this helps!

**Comment by calista03** [comment]
> Hi Calista, For every iteration of your loop,
> 
> * ensure that the method you use to obtain the next event takes in serverlist as an argument
> * ensure that all your events have a getserver method which takes in serverlist as an argument to give you the most updated server at that point of time
> * take the returned server, update serverlist with it, and assign it back to serverlist
> * for the next iteration, your execute will now make use of the most updated serverlist to decide the next event.
>   Hope this helps!

Hi there! Thanks for the advice! I am currently doing that, however I am not sure how I can create Arrive events with updated serverlist, as for me I create all the Arrive events at one shot at the start, then add them all to the PQ before I start iterating through the PQ and executing my events. Is my way of adding Arrive events all at once to the PQ advisable? Or is there another way that you used?

**Comment by jaejayrome** [comment]
Greetings Calista Tan Shu Yan, the flaw in your design of your program lies with the fact that the server list is property of a single arrival event. That shouldn't be the case as it would give rise to your problem whereby you aren't able to access the updated server list for the following event. Either 1. Return a Pair<PQ<Event>, ImlList<Server> that would return both the updated server list and the updated queue AFTER adding the next event within the arrive class, namely (wait, serve or leave). Or 2. Return a PQ<Event> in your while loop but before the next iteration, update the server list that's native to within your simulate() method. However, choosing the latter you would have to consider that the serve event or wait event gets polled out before the second customer arrives. Else, in the case if the second arrival gets processed, the server list wouldn't be the most updated customer in the server or it's corresponding queue. Hope this helps!!

**Comment by granolaluvr69** [comment]
> > Hi Calista, For every iteration of your loop,
> > 
> > * ensure that the method you use to obtain the next event takes in serverlist as an argument
> > * ensure that all your events have a getserver method which takes in serverlist as an argument to give you the most updated server at that point of time
> > * take the returned server, update serverlist with it, and assign it back to serverlist
> > * for the next iteration, your execute will now make use of the most updated serverlist to decide the next event.
> >   Hope this helps!
> 
> Hi there! Thanks for the advice! I am currently doing that, however I am not sure how I can create Arrive events with updated serverlist, as for me I create all the Arrive events at one shot at the start, then add them all to the PQ before I start iterating through the PQ and executing my events. Is my way of adding Arrive events all at once to the PQ advisable? Or is there another way that you used?

Your arrive events don't need to have serverlist as an attribute in them, what you should aim to do is to pass in serverlist into the methods which need them instead, as serverlist is always changing for every event.

**Comment by eunicel23** [comment]
hi calista, you can try adding the updated serverlist into your method in arrive that gets the next event instead of adding it into the arrive event itself! the method that gets the next event will return a pair containing the next event and the updated serverlist

**Comment by calista03** [comment]
> > > Hi Calista, For every iteration of your loop,
> > > 
> > > * ensure that the method you use to obtain the next event takes in serverlist as an argument
> > > * ensure that all your events have a getserver method which takes in serverlist as an argument to give you the most updated server at that point of time
> > > * take the returned server, update serverlist with it, and assign it back to serverlist
> > > * for the next iteration, your execute will now make use of the most updated serverlist to decide the next event.
> > >   Hope this helps!
> > 
> > 
> > Hi there! Thanks for the advice! I am currently doing that, however I am not sure how I can create Arrive events with updated serverlist, as for me I create all the Arrive events at one shot at the start, then add them all to the PQ before I start iterating through the PQ and executing my events. Is my way of adding Arrive events all at once to the PQ advisable? Or is there another way that you used?
> 
> Your arrive events don't need to have serverlist as an attribute in them, what you should aim to do is to pass in serverlist into the methods which need them instead, as serverlist is always changing for every event.

Hi Kenneth! Oh I understand what you mean now! Thanks for the help :)

**Comment by calista03** [comment]
> Greetings Calista Tan Shu Yan, the flaw in your design of your program lies with the fact that the server list is property of a single arrival event. That shouldn't be the case as it would give rise to your problem whereby you aren't able to access the updated server list for the following event. Either 1. Return a Pair<PQ, ImlList> that would return both the updated server list and the updated queue AFTER adding the next event within the arrive class, namely (wait, serve or leave). Or 2. Return a PQ in your while loop but before the next iteration, update the server list that's native to within your simulate() method. However, choosing the latter you would have to consider that the serve event or wait event gets polled out before the second customer arrives. Else, in the case if the second arrival gets processed, the server list wouldn't be the most updated customer in the server or it's corresponding queue. Hope this helps!!

Hi Jerome Goh, thanks so much for the advice!! Really appreciate it :)

**Comment by calista03** [comment]
> hi calista, you can try adding the updated serverlist into your method in arrive that gets the next event instead of adding it into the arrive event itself! the method that gets the next event will return a pair containing the next event and the updated serverlist

Hi Eunice! Thank you so much for the advice! I am planning to do that just that I will have two different methods that both take in the serverlist, one returning the next Event and another returning the updated serverlist!
