### ISSUE TITLE
EX2 Test 5

### ISSUE THREAD

**Issue by kmkmkmkmkmkmmm** [nus-cs2030/2223-s2#270]
Hi, is the only way to check expired services in the active list through indexing in a separate integer list? I am stuck at the last test and i am unsure why
<img width="633" alt="Screenshot 2023-02-25 at 15 02 34" src="https://user-images.githubusercontent.com/122666164/221343965-926ef84d-43f8-432c-ac05-8c63019d2f95.png">

**Comment by trwstin** [comment]
you are checking for expired services in the active list using a separate integer list? can you explain how that works?

you can try indexing through the active list, then compare serviceTimes of the respective services and the incoming cruise

**Comment by wmingchuan** [comment]
Have an active list where all the loaders are free. Have another expired list where all the workers are assigned to work.

Before each new cruise arrives, go through the expired list to find those loaders that have done loading. Remove the first element from the expired list each time, check if it is done already. If it is done, add it to the active list. If it is not done, add it to a temp list. When you finish going through the expired list, there will be no element left. Now assign the temp list to the expired list.

Then you go through the active list and assign loaders.
