### ISSUE TITLE
ex 3 test case 6 error

### ISSUE THREAD

**Issue by NwaterM** [nus-cs2030/2223-s2#272]
Hi everyone! I am unsure how i can solve this error. I do have a mass method in SolidImpl class and that method creates a Shape3D object, uses the shape3d object to call the mass method in shape3d child classes. thank you in advance!
<img width="1241" alt="Screenshot 2023-02-25 at 3 43 06 PM" src="https://user-images.githubusercontent.com/122254436/221345542-3e6c61ea-68e5-4908-892b-0803b153ed01.png">

**Comment by sethteo** [comment]
You shoudl create a SolidImpl object within the SolidSphere/SolidCuboid which you can then use to call the SolidImpl methods

**Comment by Cepheux** [comment]
SolidImpl and SolidCuboid should extend to the right classes. Try creating a method mass() inside SolidImpl and then SolidCuboid should consist of a method to return the SolidImpl object

**Comment by glenn2030** [comment]
The error is basically you are not using the "mass method In solidImpl", so u need to create a solidimpl object in your mass() method for both solidsphere and solidcuboid and run the mass method with created obj!

**Comment by kaiyanggg** [comment]
Hi, you should replace the mass() method in SolidCuboid. What you can do is to create a SolidImpl object, and call the mass() method with this new SolidImpl, to compute the mass. This will allow for delegation as SolidImpl and SolidCuboid are not directly related.

**Comment by leonardwx** [comment]
U will need to create mass method inside Solidimpl. Then inside your SolidCuboid u can call the Solidimp with it's mass
