### ISSUE TITLE
EX 2 lvl 3 

### ISSUE THREAD

**Issue by ghost1nthemachine** [nus-cs2030/2223-s2#275]
![Screenshot 2023-02-25 at 6 36 45 PM](https://user-images.githubusercontent.com/125187978/221352444-f15938bc-8a4b-41e3-a535-4fb678f9bea1.png)

Having issues with Loader 2 being used 2 times when serving the third Cruise. This is the test case where the Loaders are being re-used from the Expired Queue. 

dont understand why my algo works for the second cruise but not the third. Anyone has any idea how to debug this :(

also we do need to "sort" the expired queue?

**Comment by ayevxn** [comment]
There is no need to sort the expired queue if you use 'first in first out' principle.

With regard to your issue, I am not too sure but it looks like it might be an issue with the iteration. You can try to system.out.println() in your iterative process to see if you're moving the loaders properly.

**Comment by sp4ce-cowboy** [comment]
What `int` value are you using for the Loader ID when you create a new Loader? i.e. Loader(`int`) I had this problem but I used counters outside (and inside) the cruises loop to keep track of the Loader ID.

**Comment by aowz** [comment]
It depends on your implementation but it might be worth checking out how you determine if your Loader is occupied. It seems like Loader 2 is being identified as having completed its task when it is not. This might be the reason why it is being added back to your list of available loaders to be reassigned.

**Comment by ghost1nthemachine** [comment]
> There is no need to sort the expired queue if you use 'first in first out' principle.
> 
> 
> 
> With regard to your issue, I am not too sure but it looks like it might be an issue with the iteration. You can try to system.out.println() in your iterative process to see if you're moving the loaders properly.

Thanks for the reply. figured it out.. i wasnt properly removing the loaders from the queue during the iteration.
