### ISSUE TITLE
Lab 4 error

### ISSUE THREAD

**Issue by AmanDesai34** [nus-cs2030/2223-s2#276]
# Summary

Description of the question / problem here.

## Description:

Any idea how i can solve this?

## Code Snippets

Attach code snippets (if any)

## Screenshots
<img width="895" alt="Screenshot 2023-02-25 at 7 23 21 PM" src="https://user-images.githubusercontent.com/124550223/221354251-b628f5e3-90e8-4067-91ce-0e451957d68a.png">

Screenshots (if any)

**Comment by sp4ce-cowboy** [comment]
Try resubmitting the code, when I submitted sometimes codecrunch would glitch and not load my outputs so it ends up being marked as no output.

**Comment by AmanDesai34** [comment]
Okay i realised had a logic error in my comparator class thanks tough!!!
