### ISSUE TITLE
Unknown error lab 4

### ISSUE THREAD

**Issue by AmanDesai34** [nus-cs2030/2223-s2#278]
# Summary

Hey guys, does anyone know how ican solve this error. Never come across this before

## Code Snippets

Attach code snippets (if any)

## Screenshots
<img width="1084" alt="Screenshot 2023-02-25 at 8 16 53 PM" src="https://user-images.githubusercontent.com/124550223/221356389-a3e60592-6b26-4b47-b060-0d7075c667ab.png">

**Comment by weitatftw** [comment]
you need to define a function named doesItProvideShareARide() in PrivateCarX class as it is a method that was specified within the Driver interface. You must define this method in classes that inherit from Driver

**Comment by AmanDesai34** [comment]
PrivateClassX isnt a class created by me, i believe its been created code crunch for the test case

**Comment by AmanDesai34** [comment]
And I have checked, the methods has been correctly implemented. If anyone has come across this,  please do help thanksss!

**Comment by Lofthesaver** [comment]
Hi, check if you are hardcoding the output of any services in your client.

**Comment by viethaaaa** [comment]
hi u can try ensuring your Driver (parent class of PrivateCar / PrivateCarX etc.) is an abstract class and has the abstract method doesItProvideShareARide(); it could be clearer if you upload your code snippets of this method too so ppl can see it it is correctly implemented

**Comment by sp4ce-cowboy** [comment]
Hi, when I had a similar issue, I noticed the problem was that the implemented method needs to have exactly the same method signature (same name, parameters, order of parameters and return type), and on top of that it needs to have the same return type. Maybe you can try to check your methods again to see if they have the same signature.

**Comment by lynettelcl** [comment]
It might have something to do with the naming? Naming of the variables and parameters etc, though im not sure if thats the problem. If all the naming is accurate then it might have something to do with the class type (interface/abstract)

**Comment by AmanDesai34** [comment]
Thank you all but it was due a bit of hardcoding which caused it>
