### ISSUE TITLE
wrong order of events

### ISSUE THREAD

**Issue by hcyrr** [nus-cs2030/2223-s2#279]
## Description:
facing this issue whereby if the server is done serving a customer, and this server has a customer waiting, the serve event for the customer waiting is polled first instead of the done event. i think this happened bc this two events are in the pq at the same time. how can i resolve this? 

eg
supposed output
1.500 1 done serving by 1
1.500 2 serves by 1
2.500 2 done serving by 1

my output
1.500 2 serves by 1
1.500 1 done serving by 1
2.500 2 done serving by 1

**Comment by glenn2030** [comment]
You need to use your comparator! In your comp, it should compare the timing and if the timing is the same, you should compare the customer ID, e.g in your case, the customer ID for 1 should proc first since it < than the customer ID for 2.

**Comment by hcyrr** [comment]
managed to resolve this using your tip! thank you glenn :)
