### ISSUE TITLE
CodeCrunch #Exercise 1 - Warning (unchecked call to add(E))

### ISSUE THREAD

**Issue by JYeoZS** [nus-cs2030/2223-s2#28]
Hi,

My code output is okay for the exercise, just having a warning about unchecked call. Photo below.

Anyone else facing this problem and how did you resolve it?

Thanks.

![Screenshot 2023-01-27 at 11 13 41 PM](https://user-images.githubusercontent.com/122290983/215120892-878d44e0-433c-4cda-a2f8-21017d2a8de7.png)

**Comment by shionhigashi** [comment]
I changed the code to use generics and there was no more warning, hope this helps

ImList<Point> points = new ImList<Point>().add(new Point(0.0,0.0)).add(new Point(1.0,0.0))

**Comment by Xequil1** [comment]
In general the constructor should follow the way the type is assigned.

So:
ImList <Point> points = new ImList<Point>();

Also I think this works:
ImList <Point> points = new ImList<>();

**Comment by Xequil1** [comment]
So in general, the constructor should be written like how the type is assigned.

So one can write it like this:
`ImList<Point> points = new ImList<Point>();`

Also I think this works too:
`ImList<Point> points = new ImList<>();`

**Comment by JYeoZS** [comment]
Hi, tried your methods, yes the warnings stopped.

Looks like the CodeCrunch public test case is missing the ```<Point>``` section.

Thanks for the help.

Cheers.
