### ISSUE TITLE
Getting statistics 

### ISSUE THREAD

**Issue by tali-a** [nus-cs2030/2223-s2#281]
Hi, I defined a separate class to process things like waiting time and number of served/left customers. I pass an instance of the class into my events as they are executing, but  the statistics aren't updating correctly though I've reassigned them back to updated values. is the only way to get them to update properly to place them as attributes when i create  a new event? overall.... I feel like this is an overly complicated/wrong approach? Is there a simpler way to get  average waiting times? thank you so much..

**Comment by granolaluvr69** [comment]
I also created a statistics class, but updated the statistics in simulate() itself using the same statistic object, you could try it too.

**Comment by calista03** [comment]
Hi Talia! What I did was to create methods called ServedCounter and LeftCounter in each Event subclass that would return either 0 or 1 depending on what Event subclass it specifically is, and in my Simulator's simulate() method I created two variables (servedcounter and leftcounter), so everytime I execute an event, I will just do : servedcounter += event.ServedCounter() and leftcounter += event.LeftCounter(). Hope my explanation is not too confusing haha.. hope this helps!

**Comment by haqanh** [comment]
One thing you can consider is having a method which return +1 in your Serve/Leave, but 0 in your other event. Then, you can call this in your Simulator every time you queue your Event. And then return these counter at the end with your final String.

Hope this helps! :)

**Comment by sethteo** [comment]
I have a method in all of my Events called 
Statistics update(Statistics stat) which then calls the relevant Statistic methods such as Serve() which returns a new Statistics object with the same average time, serve number ++, same leave number in the case it is in a ServeEvent

On events that do not change the Statistics object (such as Arrival) my update method just returns the input stat object

**Comment by eunicel23** [comment]
for me i had a method in each event that returns the string of the event name, then counted for each serve and leave event. for waiting time i had another method in serve to calculate waiting time

**Comment by tali-a** [comment]
Thanks everyone! I implemented Seth's method :)

> I have a method in all of my Events called Statistics update(Statistics stat) which then calls the relevant Statistic methods such as Serve() which returns a new Statistics object with the same average time, serve number ++, same leave number in the case it is in a ServeEvent
> 
> On events that do not change the Statistics object (such as Arrival) my update method just returns the input stat object

**Comment by tali-a** [comment]
Hi, did anyone face issues when adding to their wait time? I'm currently adding to wait time in  the wait class, and issues arise when queue length for each server is greater than one. i think the source of the error is that the updated server is not being retrieved. However, the  update statistics method doesn't have access to the updated server list. Any tips would be appreciated :) Thanks in advance!

**Comment by 0liverkong** [comment]
hi tali, are you using the approach that generates invisible waitEvents? feels like the issues about passing information between different objects will become way easier to solve if you try that approach. it becomes clearer with that approach that adding the wait time to your statistics data structure on the processing of the serve event is simpler.

**Comment by tali-a** [comment]
Thanks! I didn't use that approach, which i regret now... had many issues.  I ended  up passing in the updated list as an additional parameter

> hi tali, are you using the approach that generates invisible waitEvents? feels like the issues about passing information between different objects will become way easier to solve if you try that approach. it becomes clearer with that approach that adding the wait time to your statistics data structure on the processing of the serve event is simpler.
