### ISSUE TITLE
Error in lab 4

### ISSUE THREAD

**Issue by alvintjw** [nus-cs2030/2223-s2#283]
# Summary

Need help for Error in Lab4

## Description:

Did Anyone encountered this error before? Does it mean I have invoked a method from java.uti..objects package or can it mean something else because im looking through the package online as well as all my classes and I did not invoke any method from the package. I didn't even import it :/ 
## Code Snippets

Attach code snippets (if any)

## Screenshots

![telegram-cloud-photo-size-5-6327891625367417798-y](https://user-images.githubusercontent.com/65883895/221372267-88d5b686-0efd-4805-bf05-33629da78093.jpg)

**Comment by Lofthesaver** [comment]
Hi, there is probably a constant variable that isn't declared static in your code.
