### ISSUE TITLE
Out of bounds when updating Server time

### ISSUE THREAD

**Issue by ghost1nthemachine** [nus-cs2030/2223-s2#284]
# Summary
I have a method that updates server nextavailtime. it takes in my imlist of servers and returns an updated list of servers. i only have this method in my Done, serve and arrival class.

somehow during the serve event, Theres an out of bounds error when i try to retrieve a server from my servers imlist. somehow my imlist server became empty ? and i cant retrieve any servers from the list. im on the brink of giving up tbh

any ideas how to debug this? I return a pair<Event,Imlist> after i execute an event, which includes imlist of servers

Attach code snippets (if any)

## Screenshots

Screenshots (if any)
![image](https://user-images.githubusercontent.com/125187978/221373229-970ddd98-f45a-4383-81a1-34fcbe4e9153.png)

**Comment by vanessakohh** [comment]
hi! i got this issue quite frequently & its because I use my ServerID when referencing the server. (eg server 1, server 2, 3... server n) but when you get it from the serverList, you want the index of the server, which should be (ServerID - 1) since the index starts from 0. try that.. i hope it works!

**Comment by ghost1nthemachine** [comment]
> hi! i got this issue quite frequently & its because I used my ServerID when referencing the server. (eg server 1, server 2, 3... server n) but when you get it from the serverList, you want the index of the server, which should be (ServerID - 1) since the index starts from 0. try that.. i hope it works!

hi, thanks for the reply. unfortunately i did call (servernum -1) but the error prevails

**Comment by JonathanCheeNUS** [comment]
Hello, for myself I used the .set function in ImList to update the server according to their (servernumber - 1) as index. It could be that you are trying to update the list when it is still empty in the arrival resulting in this error. It helped me a lot to print out the lists in the simulator to visualise what actually went wrong in my project.

**Comment by aowz** [comment]
hi, i personally got this issue a lot. It's because I got the server ID directly from the server. Since there is no server 0 and there is an index 0 in ImList, I had to make sure that I took my serverID - 1 in order to get the index position of that server in the serverList.

**Comment by NeoHW** [comment]
If your ImList server becomes empty, it could be due to some part of the code accidentally removing and updating your serverList ,, it would be worth looking into that

**Comment by wesleychoy** [comment]
I agree with the others, I think this is either due to you modifying the server list or the index is wrong
