### ISSUE TITLE
Help for Sorting Bookings

### ISSUE THREAD

**Issue by alvintjw** [nus-cs2030/2223-s2#287]
# Summary

Error in test case 3 where my bookings seem to be sorted base on waitTime rather than fare first but can't seem to figure out why. Any help would be appreciated.

## Code Snippets
<img width="963" alt="Screenshot 2023-02-26 at 3 25 17 AM" src="https://user-images.githubusercontent.com/65883895/221375843-b5e11553-f9ca-42a2-95ba-93cfa9207344.png">
<img width="571" alt="Screenshot 2023-02-26 at 3 25 36 AM" src="https://user-images.githubusercontent.com/65883895/221375867-9c89608d-3f03-4c4b-bf43-78b809273292.png">

## Screenshots
<img width="1022" alt="Screenshot 2023-02-26 at 2 56 30 AM" src="https://user-images.githubusercontent.com/65883895/221375837-05bf15d6-01e1-434a-9de3-28008f233f9a.png">

Screenshots (if any)

**Comment by aa01xx** [comment]
Actually in your comparator, you can make use of compareTo defined in booking. If your compareTo is working properly in booking then your comparator will work fine. With this, you do not need to recompare fares and waiting time in your comparator.

**Comment by alvintjw** [comment]
@aa01xx oh thanks man! implemented your tip and it worked!

**Comment by aowz** [comment]
Hi, if you take a look at code crunch they would have specified for you to use the compareTo method by implementing comparable in your booking class. 
![image](https://user-images.githubusercontent.com/125140598/221378321-f849a6fa-f97b-4f6e-a17f-0fcf3e9781ee.png)

**Comment by lynettelcl** [comment]
You can make use of the compareTo method that you would have already written in the booking class, should work that way :)
