### ISSUE TITLE
lab 4 level 3 compareTo error

### ISSUE THREAD

**Issue by secretApple** [nus-cs2030/2223-s2#290]
hi, im not sure how to implement the compareTo function, especially because it is comparing this booking to another booking but the parameters of both (driver and request) are the same so what will differentiate them? i tried having a method for calculating the fare of the first type of service and another to calculate the second type of service and then comparing them but i get the result shown below. how should i change my compareTo method?

Screenshots (if any)
![image](https://user-images.githubusercontent.com/126102015/221392172-705aff61-47e5-48fb-b129-5bf9ca92b30b.png)

**Comment by sp4ce-cowboy** [comment]
I think your compareTo method might not be processing the condition whereby everything is equal and thereby returning 0. In my compareTo method, I used nested-if-else statements where firstly the fares are checked, and if the fares are the same, the waiting times are checked, and if those were also the same, then return 0. You can to modify your compareTo method such that it implements all the return values properly, including 0.

**Comment by ugchongg** [comment]
I did the above too, it was similar to the implementation of the event comparator in lab2. You might want to consider only comparing the fare of the preferred service of each driver (the cheaper one)

**Comment by bentoh95** [comment]
in your compareTo method, you should compare the fares, and return -1 or 1 based on their difference, and if the difference in fare is 0, you can compare their wait time which will return either a negative value or positive value,
