### ISSUE TITLE
Cyclic Dependency detected in Lab 3

### ISSUE THREAD

**Issue by ugchongg** [nus-cs2030/2223-s2#291]
# Summary

Hi I am getting this compilation error on code crunch but I am not quite sure how to work around it, does this mean my ArrivalEvent is dependent on ServeEvent, DoneEvent on ServeEvent and so on.... any help would be appreciated thanks!!
![image](https://user-images.githubusercontent.com/121675791/221393221-41f863a1-3938-4f4d-97f1-7597e9ebf4c6.png)

**Comment by alvintjw** [comment]
Had this issue as well. Pretty sure your ServeEvent is generating DoneEvent which then generates ServeEvent again so it's a cycle. You can get the correct output but you wont bypass codecrunch. You have to think of another way for your events to flow such that no two events call each other

**Comment by alvintjw** [comment]
![image](https://user-images.githubusercontent.com/65883895/221394325-4bf76e03-09b8-4c5b-8dbb-bea2448308d3.png)

**Comment by wmingchuan** [comment]
Your Done event returns a Serve event, meaning you are checking the queue for next Serve event after the Done event. This will result in a cycle. Make sure Done event does not return Serve. Use another way to check for the queue.

**Comment by jacoblimjy** [comment]
As per mentioned, your serve returns done with then return serve again, you need to find a different implementation. Consider creating another class to help resolve this issue.

**Comment by ugchongg** [comment]
thank you all! managed to fix it!
