### ISSUE TITLE
Time Limit Exceeded

### ISSUE THREAD

**Issue by ahndrayo00** [nus-cs2030/2223-s2#292]
# Summary

Description of the question / problem here.
My code seems to work fine in passing the test cases, but it is too slow. Anyone can help me understand how to optimise? :')
## Description:

Clarifications or details with respect to the issue you are facing

## Code Snippets

Attach code snippets (if any)

## Screenshots

Screenshots (if any)
![image](https://user-images.githubusercontent.com/123559896/221396550-113b7d56-9333-480a-9996-dd125c95b3b1.png)

**Comment by alvintjw** [comment]
Is your code checking for condition more often that it should? For eg. checking for a condition that will always remain true/false inside a while loop or if statement. Or perhaps checking for excessive amount of conditions each time?

**Comment by JYeoZS** [comment]
Faced this same problem also. There could be something wrong with your queue. Likely a bug in code since you have gone so far to test case 10. See #131

Of course if above fails you can see if there are too many nested for loops, etc. but suggest highly unlikely.


Almost there. All the best to you!

Cheers.

**Comment by wmingchuan** [comment]
check for infinite loop, an event might be returning itself with the same time, so it's stuck in that loop

**Comment by ahndrayo00** [comment]
Update: was pretty sure it was an infinite loop somewhere. My previous design was that within Serve event, I had logic in there to check if the customer was first in queue, and depending on this, generate a Done event or another Serve event.

But I was pretty sure that was causing some form of loop, so I disaggregated that logic into another event class called Waiting, where customers will go from Arrive -> Wait -> Waiting (only if there are customers ahead of them in the queue) -> Serve -> Done. 

Hope this helps for anyone facing the same issue as me!
