### ISSUE TITLE
Seeking for some hints for the booking comparator for Lab 04

### ISSUE THREAD

**Issue by nig3lcmc** [nus-cs2030/2223-s2#295]
Looking for some guidance for test case 3 when it comes to designing the Booking comparator. Within Booking itself, I should include a getCheapestFare method where it determines the cheapest fare out of the services provided by the driver.
As for the compareTo method, its just comparing the the cheapest fares between two bookings, in the event of a tie, compare waitingtime.

**Comment by Fastumkj** [comment]
I did a return 1, -1, 0 instead. Maybe you would like to try this?

**Comment by trwstin** [comment]
your comparator should be able to just call the compareTo method as a means of comparison between the 2 bookings

**Comment by bawowo** [comment]
yup, you are right about the compareTo method. So the 'fare' for each booking you are comparing (e.g. booking b1, booking b2) should be the cheapest fare out of the services provided by the driver already. for myself, to do this I included the comparison inside the constructor of Booking itself. so the the services and their computed fare are iterated in the constructor to find the lowest fare, before they are put into compareTo() method. Maybe can try this haha but im sure there other methods as well!

**Comment by lynettelcl** [comment]
same as the above comment, i returned 1 and -1. for the BookingComp class, i made reference to the one taught in the lecture slides (same as the one i had for lab 2 comp class)

**Comment by aowz** [comment]
I was confused with the logic at first but I simply used -1 when the fare was cheaper or when the time was smaller, 0 when they are tied and 1 when the fare is more expensive or time is greater.

**Comment by nig3lcmc** [comment]
Thanks everyone!
