### ISSUE TITLE
Facing " attempted to call method serveCruises(ImList<Cruise>) which cannot be invoked until class RecycledLoader is declared" error

### ISSUE THREAD

**Issue by Klowhe** [nus-cs2030/2223-s2#297]
Anyone has any idea how to resolve this, I tried putting RecycledLoader in the same file as level5.jsh before the serveCruises method but still had this error.

**Comment by kmkmkmkmkmkmmm** [comment]
hi, have you tried using /open RecycledLoader.java in ur jshell before opening and running level5.jsh?

**Comment by sp4ce-cowboy** [comment]
I think you need to open the files in jshell in bottom up dependency order, meaning the classes that don't depend on anything must be opened first, followed by the classes that depend on them. If RecycledLoader is not "found" you can try to /open Loader class first, and then the Recycled class. Sometimes jshell can glitch, so I usually /exit jshell to drop everything from memory and restart by opening each class in order, and then opening the .jsh file at the end. 

Also, occasionally, if the method in the .jsh file is not declared properly (i.e. errors in code that prevent it from 'accepted' by jshell) it will not get added to jshell if the .jsh file with the same method already exists in jshell (which you can check with `/list`. Meaning, you would have to type `/drop <method name>` first and then import the .jsh file again, which would now show an error message explicitly. Alternatively, you could just `/exit` jshell as above, which would also drop all the methods anyway.

**Comment by Klowhe** [comment]
I did manage to open all the files in jshell without any errors though

**Comment by granolaluvr69** [comment]
Firstly, you should reset your jshell by issuing the following command:
/reset

then maybe you could try opening your files in this order:
/open ImList.java
/open Cruise.java
/open BigCruise.java
/open SmallCruise.java
/open Loader.java
/open RecycledLoader.java
/open Service.java
/open level5.jsh

**Comment by Klowhe** [comment]
Alright thankss
