### ISSUE TITLE
Wrong Output for Private Test Case

### ISSUE THREAD

**Issue by rshalinisai** [nus-cs2030/2223-s2#300]
# Summary

Description of the question / problem here.

## Description: Is there smtg wrong w the way I did my ShareARide class as I am not sure if I rounded down?

Attach code snippets (if any)

## Screenshots

![image](https://user-images.githubusercontent.com/122519417/221414245-33b01f50-689a-46e7-af29-bae2406b1647.png)

**Comment by tristantanjh** [comment]
this looks like it could be a minor calculation error, for the ShareARide service. maybe there might be something wrong with the division, as we're dealing with floating point numbers.

**Comment by rshalinisai** [comment]
oops yes i realised i accidentally instantiated the value of surcharge as 600 instead of 500 thanku!
