### ISSUE TITLE
Ungraded practice 2 question

### ISSUE THREAD

**Issue by Xequil1** [nus-cs2030/2223-s2#302]
I am having difficulty with level 3 onwards. In particular, I am confused how the case class is able to display different class types by having different constructors ie: 

```
Case c = new Case(new Person("A123", "PP", 8), new PCR("alpha"))
Protocol p = c.getCurrentProtocol()
```
c is an instanceof P1

and then we have level 4:

```
Case c = new Case(new Person("B234", "M", 7), new PCR("delta"))
Protocol p = c.getCurrentProtocol()
```
c is an instance of P2

I don't recall being able to change class types just by having a different input in the constructor.

**Comment by 0liverkong** [comment]
i dont think its c thats the instance of p1 or p2, but the attribute of c

**Comment by Xequil1** [comment]
Doesn't instanceof compare the classes of the 2 objects?

So, do you mean that your Case class has an attribute of the different protocols?

**Comment by 0liverkong** [comment]
I would think so although ive yet to start on it :3

**Comment by Xequil1** [comment]
Nvm I woke up and saw my mistake lol.
