### ISSUE TITLE
Failing 2nd test case of level 5

### ISSUE THREAD

**Issue by rshalinisai** [nus-cs2030/2223-s2#303]
# Summary

Description of the question / problem here.

The order of my outputs for line 2 and 3 is flipped (like for the same price im printing the longer waiting time first but this prob only occurs for the 2nd test case and not the first??)

Attach code snippets (if any)

## Screenshots

![image](https://user-images.githubusercontent.com/122519417/221419623-bc5cfe1a-a8e7-43b5-9844-51808f81afbb.png)

**Comment by leonardwx** [comment]
perhaps check your compareTo/comparator method, inside the method it should return a shorter waiting if they similar fares.

**Comment by secretApple** [comment]
something similar happened to my code, i had to change the way i compared bookings in my booking comparator and then this problem got fixed

**Comment by rshalinisai** [comment]
> something similar happened to my code, i had to change the way i compared bookings in my booking comparator and then this problem got fixed

how did u ammend ah rn my Booking comparator is:

 @Override
 34     public int compareTo(Booking other) {
 35         if (this.fare < other.fare) { //if this is cheaper than other
 36             return -1;
 37         } else if (this.fare > other.fare) {
 38             return 1;
 39         } else {
 40             if (this.driver.getPassengerWaitingTime() < other.driver.getPassengerWaitingTime()) {
 41                 return -1;
 42             } else if (this.driver.getPassengerWaitingTime() >
 43                     other.driver.getPassengerWaitingTime()) {
 44                 return 1;
 45             } else {
 46                 return 0;
 47             }
 48         }

**Comment by secretApple** [comment]
for me i created a Booking Comparator class and implemented the comparison method in it instead of using a method from the Booking class, but i think there are other ways of doing it too

**Comment by rshalinisai** [comment]
> for me i created a Booking Comparator class and implemented the comparison method in it instead of using a method from the Booking class, but i think there are other ways of doing it too

hmm yeaa I also hv a BookingComp class and my level5.jsh sorts based on this BookingComp class not based on the compareTo method in my Booking class

**Comment by youthfrost** [comment]
your compareTo is a comparable but since Imlist takes in comparator, u probably need a comparator class that uses compareTo method defined in your Booking

**Comment by territxl** [comment]
yup, I had a separator booking comparator for the level 5 test case and also a compareTo in the booking class. I think these 2 aren't the same since they are used in different context.

**Comment by mavisczx** [comment]
And also remember you cannot sort an ImList directly, you need to use sort or List.of() if the list is an immutable list

**Comment by Aron113** [comment]
yeah compareTo can't really be used here. Try checking your Comparator

**Comment by coderlimjingcheng** [comment]
Maybe you can show us your implementation of the BookingComp class?

**Comment by Xuehann** [comment]
maybe can write this.fare < other.fare first, then if this.fare == other.fare,  check if this.time<other.time, return -1 as well. then for else, return 0.

**Comment by EvanCh08** [comment]
It would be better if you could provide us with your BookingComp class
