### ISSUE TITLE
Failing lab 3 test case 7 - service times jumbled up

### ISSUE THREAD

**Issue by Sangobionn** [nus-cs2030/2223-s2#304]
# Summary

I have read a few posts that this may be due to caling getServiceTime() multiple times, and I have tried to fix it. I dont know if that is the problem or something else. I have only included the method in my serveEvent class constructor, but the value is needed for 2 methods - run and updateServerList. Am I calling getService Time too much or something else? Thanks man

<img width="432" alt="Screenshot 2023-02-26 at 11 36 03 PM" src="https://user-images.githubusercontent.com/126322178/221420431-70bea1b7-6b05-45e0-980f-02fe348c288d.png">

<img width="767" alt="Screenshot 2023-02-26 at 11 35 46 PM" src="https://user-images.githubusercontent.com/126322178/221420449-4dccd121-384a-41b3-a459-bed806d9ff32.png">

**Comment by wmingchuan** [comment]
Are you calling serviceTime() the moment the customer arrive? If you do that then the serviceTime()will be wrong. You can only call it when it is being served.

**Comment by youthfrost** [comment]
yup u need to check your timeStamp for your done serving event. Instead relying on customers arrival time, u could use service available time instead.

**Comment by territxl** [comment]
I think you should check based on when the serve event is actually served so that you can obtain the correct service time. Do check on how you update between your classes :)

**Comment by mavisczx** [comment]
the order of serve events need not be the order of arrival of customers, do check when do you return serve from wait event

**Comment by Aron113** [comment]
try creating a checker event for queued customers. Only when they pass the checker event, then invoke service time in the Serve event.

**Comment by ugchongg** [comment]
I used a checker event too, this checker event uses the next available time of the server before serving the customer in queue (i.e. the time it's done serving the previous customer)  as the service time in Serve event

**Comment by koiljat** [comment]
The serverStatus in your ServerEvent may not be the most updated, especially if there is a queue. You may want to refresh the serverStatus when calling the `run` method to get the most recent availableTime of your server.

**Comment by EvanCh08** [comment]
I initially encountered this problem. I called the getServiceTime() when the customer arrive. This is totally wrong, since your Supplier will get the number based on customer arrival, but it is supposed to be random. What I suggest you to do is to call it in serve instead. Hope this helps

**Comment by ryantangmj** [comment]
you have to call your getServiceTime in your serve class

**Comment by Sangobionn** [comment]
Thanks guys!
