### ISSUE TITLE
Ungraded 1 

### ISSUE THREAD

**Issue by Delocy** [nus-cs2030/2223-s2#306]
<img width="803" alt="Screenshot 2023-02-28 at 2 03 42 AM" src="https://user-images.githubusercontent.com/94375191/221646348-1c2bfb84-ddd5-4015-b570-86f83d5dd88f.png">
Anyone know how to fix this problem?

**Comment by ayevxn** [comment]
If I'm not wrong, this means that your broadcast() method initializes an instance of a specific class with toString() method returning your desired string output. Instead, you want broadcast() to call system.out.println() with your desired string output.
