### ISSUE TITLE
Ungraded Exercise 2

### ISSUE THREAD

**Issue by Brendan8899** [nus-cs2030/2223-s2#308]
Hi Guys, I realised that Protocol is an interfaces that forces its children to have a Next Method that returns a Protocol Object.

I was just thinking, how do I implement the business logic for this method in the child classes if the child classes cant return an Object that is its superclass?

**Comment by trwstin** [comment]
Since P1, P2, etc. are children of Protocol, your respective Next methods for each protocol can return one of these child classes instead, depending on the case requirements.

**Comment by nicholasteow** [comment]
The Next method in all the children classes will return you another children class(or even itself) based on the stated conditions

Since they are all children classes to protocols, you are essentially fulfilling the interface method

**Comment by Brendan8899** [comment]
Hmm but I will need to return multiple types of Classes like Discharge, Protocol 2, Protocol1 etc.. What should I do?

**Comment by nicholasteow** [comment]
i think it is ok to have one class for each of those protocols so p1, p2, p3 and more...

**Comment by trwstin** [comment]
> Hmm but I will need to return multiple types of Classes like Discharge, Protocol 2, Protocol1 etc.. What should I do?

I'm not sure what you mean by having to return multiple types of classes.

Iirc there isnt a scenario where you will need to return more than one type of protocol/event.

So you could just use if/else conditions to decide which event to return for each case.

**Comment by nicholasteow** [comment]
^^ yep yep just like what trustin is saying

**Comment by Brendan8899** [comment]
Yeah I am using if else condition to return different types of event. The issue is all these different return types for the different conditions must be under an "umbrella" type.  i.e to say if I defy my function to return a Protocol1 type, I can use if else condition to return a protocol2 return type

**Comment by trwstin** [comment]
> Yeah I am using if else condition to return different types of event. The issue is all these different return types for the different conditions must be under an "umbrella" type.  i.e to say if I defy my function to return a Protocol1 type, I cant use if else condition to return a protocol2 return type

Ok im starting to see what you mean with your original question l. 

However, I used ```public Protocol next(...)``` without any issue... Did you run into an error when doing so?
