### ISSUE TITLE
Ungraded Ex 1

### ISSUE THREAD

**Issue by TheTired223** [nus-cs2030/2223-s2#310]
Does anyone have a clue on what cyclic dependencies exist in this case? 
![image](https://user-images.githubusercontent.com/100417316/222417036-a18c8d68-d71e-4410-8df1-963a24c37432.png)
There's also the PagerStub.class that I haven't created but shows in this case which I'm confused about.

**Comment by Ernestnzx** [comment]
`Rec.class` -> `Term.class` -> `Send.class`-> `Rec.class`

My best guess is that `PagerStub.class`is not part of this dependencies here! Hope this helps

**Comment by justineeyx** [comment]
I think there is a cyclic dependency between term and send class as send references rec which references term and term references send. I believe pagerstub is a new class created by codecrunch that implements term, its just another instance of terminal

**Comment by Huanqing-Mao** [comment]
I guess you can draw the objects out on paper and draw arrows to show their relationships, if it forms a closed cycle then there is cyclic dependency.

**Comment by kyledilao777** [comment]
yeah I think here, as seen in the walkthrough video, you need to create different server states, similar to what we need to do for PA

**Comment by jacoblimjy** [comment]
Your host might have taken in Term somewhere and vice versa.

**Comment by AmanDesai34** [comment]
Yea, the walkthrough video explains it well how we can resolve this. You will have to create more classes to implement
