### ISSUE TITLE
List of Tasks in Chronological order

### ISSUE THREAD

**Issue by zxciisdbniel** [nus-cs2030/2223-s2#312]
# Summary
Noted that after edition of recurring task we need to reorder the list of tasks.
My question is if we need to print the Planner in chronological order if lets say the Tasks were not added in sequence (e.g. a task on day 10 is added before a task on day 1).
If I'm not wrong the test cases on the pdf has not covered this since all tasks have been added in chronological order (at least the day) so far.

## Description 
Describe the problem and any details if neceesary

## Idea s
Describe the approach used (if applicable)

## Screenshots (if any): 
Insert Images here if necessary

**Comment by Xequil1** [comment]
> is if we need to print the Planner in chronological order
For level 4 no.
But you need to print the tasks in sequence for DayView class for level 5.

**Comment by granolaluvr69** [comment]
need to sort for recurring task, no need to sort for planner, need to sort for dayview.

**Comment by trickypepe** [comment]
I believe there's no need to sort for planner ( I didn't). But anyway if you notice your planner is outputting in the wrong order its quite easy to add a sort line so you don't have to worry about that.

**Comment by andersooi** [comment]
I didn't sort my Planner but I did sort in the view method so that it is printed out in chronological order.

**Comment by guanquann** [comment]
The sorting method (Comparator) for both recurring task and dayview should be the same.

**Comment by geoffong11** [comment]
It depends on your implementation (I have 2 comparators btw)
