### ISSUE TITLE
Constructor overloading with the extra attribute being an ImList

### ISSUE THREAD

**Issue by eesean** [nus-cs2030/2223-s2#313]
Hi all,

Although overloading is not always recommended, I would like to ask how constructor overloading can be done with the extra attribute being an ImList of say element E. If I have 4 attributes but I want to do the following in jshell:

Class(A, B, C) instead of Class(A, B, C, D) and D is an ImList attribute of element E,

Is there a way to overload my constructor such that my class does not start off with an empty ImList? If I have a method within the class that helps create this list (say method F), could I do the following?

Class(A, B, C) {
    this(A, B, C, this.F( ))
}

**Comment by Xequil1** [comment]
Unsure if you can call a method before the object is constructed, but perhaps this is something you could do:

You can have a different constructor that takes in the ImList and assign that ImList to the attribute. While the usual or default constructor will just create a new ImList.
```
int a;
    ImList<x> b;
    
    Class(int a) {
        this.a = a;
        this.b = new ImList<x>();
    }
    
    Class(int a, ImList<x> b) {
        this.a = a;
        this.b = b
    }
    
}
```

**Comment by granolaluvr69** [comment]
Yeah, you can, just call this.d = new ImList<...>().add(Elem) in the constructor without D.

**Comment by Jovan131** [comment]
Yes, you can make F a static method and include it before the constructor. You can write it in this format:

class A {
    //Variables
    private final int variable1; 

    //Static methods
    static f() {}

    //Constructors
    A() {
        this.f()
    }

    //Methods (non-static)
}
