### ISSUE TITLE
PA1 Level 5

### ISSUE THREAD

**Issue by clarwen** [nus-cs2030/2223-s2#315]
Hi!

I faced an issue with level 5 of PA1. May I know what are the requirements to be added into the DayView? If the task is recurring, do I only add the start date of the recurring task? (the first line of statement when recurring task it created) Or do I add the task number that coincides to the date? 

<img width="788" alt="Screenshot 2023-03-05 at 4 14 37 PM" src="https://user-images.githubusercontent.com/119107037/222949882-a8dfb142-349d-40dd-9df8-d77da0e91042.png">

I was wondering if I am adding the wrong tasks as I seem to fail a test case, although my edit method in recurring task is working perfectly fine. 

<img width="576" alt="Screenshot 2023-03-05 at 4 14 21 PM" src="https://user-images.githubusercontent.com/119107037/222949815-30f78886-91ef-4f96-8799-fc2ccc66e1eb.png">

**Comment by Xequil1** [comment]
> May I know what are the requirements to be added into the DayView? If the task is recurring, do I only add the start date of the recurring task? (the first line of statement when recurring task it created) Or do I add the task number that coincides to the date?

Add the task that coincides with the day.

**Comment by granolaluvr69** [comment]
Add in the tasks which fulfil either one of these criteria:
1. Are not cancelled and occur on the same day as DayView (if it's not a RecurringTask)
2. Are in the ImList attribute of the RecurringTask, are not cancelled, and occur on the same day as DayView (if it's a RecurringTask)

**Comment by Jovan131** [comment]
RecurringTask consists of a number of Tasks, each with different days. Add in the Task that corresponds to the given Day. Remember to exclude any cancelled Tasks and display the Tasks in chronological order.

**Comment by tallkoh** [comment]
you might be adding the main task of RecurringTask (the task header), rather than the exact task that is part of the ImList of the RecurringTask object

**Comment by trwstin** [comment]
yea it looks like you are adding the base recurringtask, instead of the tasks under the recurringtask. 

find a way to extract these tasks and use it in your DayView's view() method

**Comment by leonardwx** [comment]
I faced the same issue at the last test case, just make sure your cancelled Tasks and tasks inside your RecurringTask are omitted

**Comment by dylanlo8** [comment]
what you could do is to extract the list of tasks from RecurringTask and check one by one to see if they have the same day as what you want to filter -> and then add to the list you want to print out

**Comment by ryantangmj** [comment]
You need to tasks that are not cancelled and fall on the same day into dayview. The tasks in recurringtask that fit the same criteria should be added too

**Comment by Aron113** [comment]
Similar to the previous issue, you might need to check through the tasks of recurring task and add those to an ImList

**Comment by leonlu178** [comment]
all the tasks that have the same start day will be included

**Comment by clarwen** [comment]
thanks everyone
