### ISSUE TITLE
What is lv5 talking about?

### ISSUE THREAD

**Issue by jianjiezzz** [nus-cs2030/2223-s2#317]
# Summary
1. I will have a View Interface with a view method --> which I suppose it means that my planner have to implement View and orverride the function.
2. But my planner.view suppose to take in a DayView class based on the qns?? --> p.view(new DayView(3))
I am so confused, can anyone enlighten me?

## Screenshots (if any): 
![image](https://user-images.githubusercontent.com/119864021/222958862-4cd2f826-0059-4435-be50-f63dd850e3ed.png)

Insert Images here if necessary

**Comment by wongjingwen** [comment]
Hi, what i have interpreted was that DayView would implement the View Interface and Planner's view method would use declaration and call the view method defined in DayView.

**Comment by granolaluvr69** [comment]
Delegate the view method in the planner to the DayView class, as DayView implements the View interface.

**Comment by trwstin** [comment]
it's two different .view() methods, the one in the interface provided is not the one directly called in p.view(new DayView(3)).
