### ISSUE TITLE
Must every field in Shop and Server be delcared private final?

### ISSUE THREAD

**Issue by ianwonghanli** [nus-cs2030/2223-s2#32]
# Summary

I have tried to code on my computer and it works on my computer. However, when I try to submit it to codecrunch, i get the error saying that i should make all fields private final? Must I make all fields private final

**Comment by zhanyang01** [comment]
yes as i think we would not be able to submit without making it private final and also to ensure that our programme is effect free and it also helps in maintaining the abstraction barrier.

**Comment by wmingchuan** [comment]
I think can use either protected final or private final depending on the class. If your Shop class needs access things from the other two classes, then need to use protected final since they are different files in the same package.

**Comment by JYeoZS** [comment]
Hihi, for the purposes of this course (at our stage at least), recall protected is used between parent-child relationship. In future this may change.

So for lab 1, yes all fields have to be private final for effect-free programming. We're looking at a has-a and not an is-a(inheritance) relationship.

**Comment by danqiye1** [comment]
Yep, in this class everything is to be `private final` unless the instructions explicitly says otherwise.

**Comment by geraldckj** [comment]
Yep, seems to be that way

**Comment by Huanqing-Mao** [comment]
Yes, I think we should create new objects instead of changing the properties

**Comment by vatsalya1103** [comment]
you might need to use getters for it but yeah you have to declare all attributes private final.

**Comment by SimonSeeYongsheng** [comment]
> # Summary
> I have tried to code on my computer and it works on my computer. However, when I try to submit it to codecrunch, i get the error saying that i should make all fields private final? Must I make all fields private final

Yes you have to make all attributes private final

**Comment by danqiye1** [comment]
I will go ahead and close this issue. Reopen if needed.
