### ISSUE TITLE
cancel() method

### ISSUE THREAD

**Issue by hhuilingg** [nus-cs2030/2223-s2#320]
hi! i would like to check if there's a way to handle the cancel() method in Task without creating another class?

**Comment by e0959170** [comment]
unfortunately, i don't think so since the error requires there to not be a cancel() method for the cancelled tasks and your task method would most probably have one

**Comment by fy17ohhh** [comment]
in the sample output it shows that return type of cancel() has diff methods from Task Class, do need to create another class

**Comment by dylanlo8** [comment]
for me, the cancel method creates a separate class that does not depend/inherit on task but it should not have the functions like edit and cancel in the separate class.

**Comment by hhuilingg** [comment]
alright thankyou all!
