### ISSUE TITLE
Quotation marks around output

### ISSUE THREAD

**Issue by cher212** [nus-cs2030/2223-s2#321]
<img width="377" alt="image" src="https://user-images.githubusercontent.com/125173830/223018827-fbcd0991-5c6c-45b3-b805-5abd85e907f6.png">
<img width="245" alt="image" src="https://user-images.githubusercontent.com/125173830/223018857-0acfbca1-fe03-4edd-b59d-04136e0988c2.png">
Will the quotation marks around my output cause an issue if I submit it on CodeCrunch?

**Comment by pehzerong** [comment]
Hey there, I'm facing the current issue as you right now and I'm not too sure if it'll pass CodeCrunch. I suspect I'm having this issue because  my cancel() method currently returns a String in which i use it to join "[cancelled]". I'm thinking of changing my method to perhaps return another class. Hope this helps!

**Comment by nicholasteow** [comment]
hi u shouldnt be returning a string but rather the task itself to be able to not have quotation marks in the output. Pretty sure the above output will fail codecrunch :(

**Comment by xZealthiusx** [comment]
Agree with what @nicholasteow has shared. If your implementation is correct, the output should not be a String but the Task itself. Just got to check that the toString() is correct for your task!

**Comment by leonardwx** [comment]
yes the quotation mark will be a issue. it shouldn't return a string but return a task that is cancelled

**Comment by tristantanjh** [comment]
yes, you should be returning a cancelledtask which has its own toString method that you can add the [cancelled] to

**Comment by shuyaoao** [comment]
yes and your cancelled task should have some relationship with your Task class through a superclass, this will aid u in the higher levels

**Comment by Delocy** [comment]
Yes u should return another class and not a string as your output

**Comment by e0968868** [comment]
The return type should not be String, but another class (depends on your output) and hence its corresponding toString() method

**Comment by Nicknzk** [comment]
in this case, maybe u want to think about creating a separate class with its toString() being the one that includes cancel?
