### ISSUE TITLE
PA1 level3 hidden test case

### ISSUE THREAD

**Issue by ngshiyingg** [nus-cs2030/2223-s2#322]
# Summary
Hi, I am unsure of why I failed the hidden test case for level 3. I tried to play around on jshell but couldn't find the error :( 

any help would be much appreciated, thanks!:>

## Idea 
i did the level 3 methods in RecurringTask class. (pass the given test cases too) 

## Screenshots (if any): 
<img width="802" alt="Screenshot 2023-03-06 at 2 29 10 PM" src="https://user-images.githubusercontent.com/122260950/223049040-90629bb0-7a5e-42ed-b991-7980f35b280e.png">

so i tried to shift the sequence of cancel and edit:
<img width="664" alt="Screenshot 2023-03-06 at 3 59 33 PM" src="https://user-images.githubusercontent.com/122260950/223051505-221b54db-0a63-4d51-b4a2-c7b84b9cbafe.png">

**Comment by weitatftw** [comment]
did you define your comparator correctly?? because you also have to take into account the case when you have 2 tasks that have the same day, how are you going to sort them?

**Comment by leroyteojy** [comment]
You might want to check if the list of tasks is sorted properly. The tasks shouldn't be sorted only when you're going to print the output but rather it should already be sorted when your RecurringTask is created.

**Comment by ngshiyingg** [comment]
@leroyteojy omg yes that solved the issue, thankyou:D

**Comment by nicholasteow** [comment]
> You might want to check if the list of tasks is sorted properly. The tasks shouldn't be sorted only when you're going to print the output but rather it should already be sorted when your RecurringTask is created.

u are such an inspirational figure
