### ISSUE TITLE
lv 5: How to extract specific child class in a parent list?

### ISSUE THREAD

**Issue by jianjiezzz** [nus-cs2030/2223-s2#323]
I have a TaskParent List that contains either Task or Cancel Task. I want to only get the working Task in the List and append it to a ImList<Task>. Is there anyway to do this?

**Comment by leonardwx** [comment]
U can try adding another new list inside your add method that only takes in the only working task and tasks inside the RecurringTask

**Comment by dylanlo8** [comment]
What you could do is to use the imList addAll method.
1) Create an abstract extract method in your TaskParent and implement extract in your Task or Cancel Task.
2) For Task -> you can return an ImList of type Taskparent which includes the task within the list. 
3) For Cancel Task -> you can just return an empty list but still needs to be of type TaskParent.
4) Depending on which question you are addressing, you can have an overall ImList which adds the outputs from 2) and 3) -> Cancel task will not make any modifications to the overall ImList! hope this helps!

**Comment by jianjiezzz** [comment]
OMG, thanks for the info guys, really HELPED ME SO MUCH. FINALLY DONE WITH this PA
