### ISSUE TITLE
confused by testcase 5_1

### ISSUE THREAD

**Issue by rayray39** [nus-cs2030/2223-s2#324]
# Summary
enable to pass testcase 5_1 despite same output but on different lines

## Description 
hi, i had fixed everything (display the required tasks in the recurring task list, and have the edited tasks saved properly to the recurring task list and planner too), however I am still facing this issue. any help is appreciated, Thanks!!

## Screenshots (if any): 
![jshell pa1 testcase 5_1](https://user-images.githubusercontent.com/108506541/223172468-f8f9c06e-3306-4478-956e-33bd320780b1.png)

**Comment by weitatftw** [comment]
did you sort the list of tasks before printing them?? it seems like the tasks are not printed in the correct order

**Comment by leezhanpeng** [comment]
If you have implemented the sorting of the tasks properly, make sure you equate your sorted task back to itself since ImList is immutable.

**Comment by jeffkhong11** [comment]
You may want to check if your comparator is done correctly

**Comment by leonardwx** [comment]
check whether the tasks were sorted by the start time during the same day?

**Comment by sparklingwater13** [comment]
for the tasks on the same day the earlier start time should go first

**Comment by wongjingwen** [comment]
do we need to factor in the endTime?

**Comment by leonardwx** [comment]
we don't need to include the end time as we only need the start time and sort them in order of the timing that comes first

**Comment by gene2345** [comment]
you should check ur comparator and sort by start time

**Comment by aldensiol** [comment]
it seems to me that your comparator has been implemented incorrectly

**Comment by dylanlo8** [comment]
To add on to the comparator issue, just make sure to check the logic regarding how you want to compare between two Tasks! there could be a logic flaw there!

**Comment by BrendaTan29** [comment]
Hi, what i did was to sort add all the tasks that need to be printed into an immutable list first then sorted it.

**Comment by OwenChanJF** [comment]
Think about how you want your events to be listed, they should be listed. Listed by the recency of date, followed by which event comes first during the day. This should be implemented in the place where your comparison takes place

**Comment by NeoHW** [comment]
you could check your comparator or your ImList so that your events would be sorted

**Comment by e0968868** [comment]
Did you sort with the comparator before printing out the tasks in the imlist?

**Comment by nigel-tannn** [comment]
Hi, you may want to check if you have managed the logic in your Comparator, after checking based on the day, you have to compare based on the time as well.

**Comment by easypzlemonsqueezy** [comment]
hi! i reckon you did not use the task comparator to sort the task in order, it shouldn't be a big issue

**Comment by wmingchuan** [comment]
make sure it's sorted

**Comment by Nicknzk** [comment]
at the end before u put the ImList<...> into the view(ImList<..>), make sure u re-sort again

**Comment by littlemidget3** [comment]
Hi you may want to check your comparator and ensure start time is factored in

**Comment by haqanh** [comment]
It appears that you have not sorted your list of task before returning them. You should define a comparator that compares the date and time of your task! Hope this helps :)

**Comment by tristantanjh** [comment]
hi i had the same problem, my problem was not that the sorting algo wasnt working. so in my case what i was doing when checking for the specific tasks in DayView was that i was creating and returning a new task based on the initial task given to the RecurringTask, but in this case if the first task in the recurringtask was being edited the task that i returned back to dayview would be the new task created based on the initial task's start and end times. not sure if your implementation is the same but if it is then you can return the specific edited task and it should be fine
