### ISSUE TITLE
Level 3 Test Case 6 Unable to pass test case

### ISSUE THREAD

**Issue by pehzerong** [nus-cs2030/2223-s2#326]
Been getting this issue but have no idea how to resolve it. Would appreciate any help!
<img width="649" alt="Screenshot 2023-03-07 at 11 53 53 AM" src="https://user-images.githubusercontent.com/108965051/223316792-4e3c7a39-126b-439f-b109-9328da2dfcaf.png">

**Comment by trwstin** [comment]
Seems like the issue is related to this example test case from the question:
![image](https://user-images.githubusercontent.com/68576751/223318493-37664d03-0c8c-490e-a8b1-6ef773ac0b3c.png)

"A specific occurrence of a recurring task that has been cancelled can be re-edited."

How does your edit method work currently?

**Comment by littlemidget3** [comment]
Building on what trwstin mentioned, you must implement an edit method that is able to 'edit' your cancelled task. Depending on how you built your Cancelled Task, you will approach your edit method differently. If your CancelledTask does not have edit method, you must find away around it. Perhaps, along the lines of replacing the CancelledTask with a new Task. Be careful not to use explicit type-casting when doing this

**Comment by leonardwx** [comment]
i think there is something wrong with your edit method, you should check your edit (index,start,end) method is only changing the particular index of the recurring tasks, then set(index, Task) back to your ImList

**Comment by vancwe03** [comment]
it could be because you didnt sort ur list of tasks in the edit method, try editing a task such that the list needs to be reordered then check that when u cancel a particular task, the correct task is being cancelled.

**Comment by kaiyanggg** [comment]
Hi, it seems as though your edit(int index) method is not editing a cancelled task. You can make sure that the edit method that takes in the integer index can "edit" a cancelled task, one thing you can try (what I did) is to replace the CancelledTask with a new Task via the set() method. The sorting of the new task list via the comparator can only be done after the above.

**Comment by chewbum** [comment]
your edit method returns a wrong type of Task

**Comment by weitatftw** [comment]
did you sort the list of tasks in the RecurringTask correctly?? you need to account for the possibility of two tasks possess the same day too

**Comment by AmanDesai34** [comment]
I think its to do with your edit method

**Comment by vivyanliew** [comment]
im facing this issue right now... How did u solve it
