### ISSUE TITLE
lvl 4 Adding task to planner

### ISSUE THREAD

**Issue by ghost1nthemachine** [nus-cs2030/2223-s2#327]
# Summary
whenever i add a task, instead of printing out the new task it adds the old task. not sure if i missed out a step

in my add method, i return a new planner using the overloaded constructor with a new updated imlist.

tasks = tasks.add(task); // i created a new imlist and made sure to add the new task
## Screenshots (if any): 
![image](https://user-images.githubusercontent.com/125187978/223360124-b9abf2fe-71f5-449e-812a-ed225812e387.jpeg)

**Comment by leonardwx** [comment]
did you update your ImList properly when you add a new task?  it should be taking a new task and not the previous task

**Comment by ghost1nthemachine** [comment]
ok it was my toString method that was wrong oop
