### ISSUE TITLE
Level 5 - how to print individual task from recurring task? 

### ISSUE THREAD

**Issue by emilythx** [nus-cs2030/2223-s2#328]
# Summary
Hi everyone! I am facing some issues with printing out the individual tasks from the recurring task. May I ask if anyone faced the same issue, and if so, how did you work around it? For some context, my ImList takes in all kind of tasks(Task/CancelledTask) and I have a Recurringtask that extends from task. Thanks!

**Comment by e0959170** [comment]
maybe in ur planner add() instead of adding the entire recurring task, you could add in the individual tasks into the imList instead :D

**Comment by jorwong** [comment]
You might wanna explore the idea of overloading the toString() method in the recurring task to print out only the Task that you need

**Comment by justineeyx** [comment]
u can have a return tasklist method in your recurring task class and make use of the addAll method in your dayview class to addAll of the elements in the list u returned into a separate imlist.

**Comment by leonardwx** [comment]
you can have overloaded constructor for RecurringTask that takes in a ImList, and the ImList will take in all the tasks inside RecurringTask. From there you can just print out the RecurringTask in the toString method :)

**Comment by haqanh** [comment]
maybe you can consider having a method that return the list of task from recurring task, which you can then add to the ImList that you are printing. Hope this helps!

**Comment by AmanDesai34** [comment]
Maybe you could consider using overloading methods
