### ISSUE TITLE
Pa1 test case 3

### ISSUE THREAD

**Issue by ghost1nthemachine** [nus-cs2030/2223-s2#329]
not sure if its codecrunch but ive tried this testcase in jshell and it seems ok. anyone knows why its printing out wrongly?

![image](https://user-images.githubusercontent.com/125187978/223492622-43babec3-aa6f-4e64-8f38-edfaa8d8f1d6.jpeg)

![image](https://user-images.githubusercontent.com/125187978/223492750-97bc471c-638f-4c1a-85a7-4d6edabbd10d.jpeg)

**Comment by OwenChanJF** [comment]
This has to do with your edit. Probably in your ReccuringTask.Edit(14,15) - for batch edit, you accessed your list of events, used the day for the specific events and changed the time. However, you're supposed to return a batch edit of time, with the the use of "SkipInDays" from the original "RecurringTask" (i.e, The starting day being 1 with 7 days skipped in-between). Hopefully this helps!

**Comment by nigel-tannn** [comment]
It's possible that the private test case may have done a batch edit.  Would be good to check the batch edit method in your RecurringTask class to see if it returns a new RecurringTask object

**Comment by ghost1nthemachine** [comment]
> This has to do with your edit. Probably in your RecurringTask.edit(14,15) - for batch edit, you accessed your list of events, used the day for the specific events and changed the time. However, you're supposed to return a batch edit of time, with the the use of "SkipInDays" from the original "RecurringTask" (i.e, The starting day being 1 with 7 days skipped in-between). Hopefully this helps!

this was exactly the issue. thanks! :)
