### ISSUE TITLE
test run issues 

### ISSUE THREAD

**Issue by WILLSONXWX** [nus-cs2030/2223-s2#33]
# Summary
Not able to run the test cases given 
## Description:

I have already save all classes to the same directory and compiled them all but when I try to input the test values, it has reported errors to me. 

## Code Snippets

Attach code snippets (if any)

## Screenshots

<img width="987" alt="Screenshot 2023-01-28 at 8 28 08 PM" src="https://user-images.githubusercontent.com/123813085/215266357-93eae4ee-70ee-42bf-a53d-56f4836363e7.png">

**Comment by NeoHW** [comment]
It seems like your main class could not be found by the JVM. You could try checking if your classpath is set correctly, or if your Main/Shop class is private instead of public. You could also try checking if there are any typos in your class name or package name.

**Comment by WILLSONXWX** [comment]
I used java Main <1.in instead of java Main.java<1.in and it is just magically solved
