### ISSUE TITLE
Failing Test Case 5_1

### ISSUE THREAD

**Issue by Jeko1239** [nus-cs2030/2223-s2#330]
![image_2023-03-07_22-02-50](https://user-images.githubusercontent.com/124948961/223510490-c092065b-8148-48c6-8fec-2e8b4f1b3c7d.png)

I cannot get the last line in my output to print even though a previous test case already checks that we have to iterate through the list of tasks within a Recurring Task. Any help is great thanks :D

**Comment by easypzlemonsqueezy** [comment]
hi! i'm not too sure how you've implemented your recurringtask and i did not encounter this error myself, but i am guessing that you may not be filtering the imlist of tasks correctly. you might wanna check your implementation of planner and specifically the view method again, hope this helps!

**Comment by Jeko1239** [comment]
the problem was cause of the method i was filtering through the tasks, managed to solve it thanks :D
