### ISSUE TITLE
TaskComparator Implementation

### ISSUE THREAD

**Issue by alvintjw** [nus-cs2030/2223-s2#333]
# Summary
Unsure if anyone used this method but I have a Interface Tasktype that only has the getTaskonDay Method. 
My canceltask, task and Recurring tend all implements this Tasktypes so I can store all of them in a ImList of Tasktype. When i implemented my TaskComparator, Im comparing it with the Task class. It worked fine in my recurringtask class as I constructed a ImList<Task> of all the recurringTask, sort, then add them back to a ImList<Tasktype>. However, facing problems in 2 area. My recurringTask.cancel(1).edit(1,2,3,4) will not output the correct answer because my temptasklist is replicating the tasklist without the cancelled task. In addition, in my DayView class, I would not able to replicate this method so I would not be able to sort the task list. Was wondering if the TaskComparator implementation have to be comparing Tasktype and not Task.
## Description 
Describe the problem and any details if neceesary

## Idea s
Describe the approach used (if applicable)

## Screenshots (if any): 
Insert Images here if necessary
<img width="935" alt="Screenshot 2023-03-08 at 2 23 17 PM" src="https://user-images.githubusercontent.com/65883895/223635300-6ab1eba2-d593-430d-a365-8eb974c9c165.png">

**Comment by jarenl0ke** [comment]
@alvintjw Perhaps could try to store the tasklist within the RecurringTask as a property itself, so there would be no need to constantly create the ImList whenever calling the edit() method but rather, the edit() method would tap on the tasklist property and edit that accordingly?

For the comparator implementation, seems like it should need to be able to compare TaskType since within the DayView class it has to be able to accept TaskType (since it can accept Task and RecurringTask).

**Comment by tristantanjh** [comment]
your comparator should be accepting tasktype instead of purely task, if not you would not be able to sort recurringtasks which has cancelledtasks, as well as not being able to sort both recurringtasks and regular tasks for the dayview class

**Comment by sethteo** [comment]
For your TaskComparator it should accept your Tasktype as your updatedList is of type Tasktype so it will be able to sort through all kinds of Tasks since the ImList<Tasktype> of your RecurringTask can have all sorts of tasks

**Comment by easypzlemonsqueezy** [comment]
hi! yup that's correct, your Comparator should be taking in TaskType instead of Task, since you want to sort your RecurringTask and CancelTask as well, hope this helps!

**Comment by littlemidget3** [comment]
your comparator needs to be able to accept the recurringTask and CancelTask as well as they need to be sorted. Depending on your implementation of a parent abstract class/interface, created your ImList of the corresponding type.
