### ISSUE TITLE
Jshell not responding

### ISSUE THREAD

**Issue by sohjoana** [nus-cs2030/2223-s2#334]
<img width="703" alt="Screenshot 2023-03-08 at 2 19 26 PM" src="https://user-images.githubusercontent.com/122262872/223634706-2ada7d3a-f5e4-423f-ace1-1925e8319a26.png">

 
<img width="593" alt="Screenshot 2023-03-08 at 2 28 28 PM" src="https://user-images.githubusercontent.com/122262872/223636097-3a4ce446-9cbc-4df4-b5a8-febf8f6c7a37.png">

How do I troubleshoot this? I only have one terminal window open
I've tried inputting the ps -aux command however I don't see any instance of jshell running.

**Comment by trwstin** [comment]
Have you tried turning your computer off and on

**Comment by littlemidget3** [comment]
i had this issue as well. I stopped running docker and restarted my computer. Was fine after
