### ISSUE TITLE
difference between abstract class and interface?

### ISSUE THREAD

**Issue by taugwa** [nus-cs2030/2223-s2#336]
i was under the impression that methods cannot be implemented in interface... but based on today's lecture i guess not? i attached a ss of today's lecture where a method was implemented. so can i ask what is the key difference between an interface and an abstract class? thank you!
<img width="356" alt="Screenshot 2023-03-08 at 5 48 42 PM" src="https://user-images.githubusercontent.com/122268711/223679702-8c34ff12-d804-4058-8bbe-fcab61eb9281.png">

**Comment by tallkoh** [comment]
i believe a method can be implemented here because it's a static method! this method will not be overridden in the implemented classes.

**Comment by e0968868** [comment]
^ yes, this example from the lecture works because static methods can be implemented in interfaces
some of the differences between the 2 is that you can have attributes in abstract class but not interface, and also abstract class doesnt allow for multiple inheritance, but you can implement from multiple interfaces

**Comment by haqanh** [comment]
static methods can be implemented in Interfaces as it can be called from the interface itself instead of an instance of the interface

**Comment by jon3r4de** [comment]
I think the main difference is just that abstract classes can have attributes.

**Comment by UmpoDumpo** [comment]
The interface body can contain abstract methods, default methods, and static methods. The main difference between an interface and an abstract class is that an interface cannot have state, whereas the abstract class can have state with instance variables/attributes.

**Comment by UmpoDumpo** [comment]
> 

yes and no!
you can check this link out [https://www.baeldung.com/java-static-default-methods]

**Comment by minhphongle** [comment]
Abstract classes are classes that can be extended and can contain both concrete and abstract methods, while interfaces are contracts that define a set of methods that implementing classes must provide, but cannot contain any implementation details -> so interface can defo implement methods. Hope it helps.

**Comment by taugwa** [comment]
ok thanks everyone for helping to clarify my doubts!
