### ISSUE TITLE
List of tasks not updated

### ISSUE THREAD

**Issue by eesean** [nus-cs2030/2223-s2#338]
Hi all,

My implementation for recurring task involves a parent class with most of the attributes and getters in the class, and the child classes are recurring task and its cancelled counterpart.

I tried including the ImList of tasks attribute to my recurring task class as per the PA walkthrough, however the list of tasks wont update after cancel(index) and the edit with index methods. Would like to ask whether the issue would be due to the way I included the additional attribute (even though I followed the walkthrough for that part), and would it be better to put this attribute in the parent class instead?

Will also like to hear any suggestions on how to include the additional attribute into the constructor for recurring task class if anyone has a similar implementation!

**Comment by emilythx** [comment]
Hi! I'm not sure if this may help but how I updated my list was by making the necessary changes within the cancel(index) and edit method. After which, i will return this updated list (example: return new RecurringTask(task,frequency,occurence,updatedlist) :)

**Comment by EvanCh08** [comment]
Hi, as for my implementation, I have 2 constructors one that takes in a list of tasks and on who does not. So what I did was returning another recurring task in those two methods. Hope this helps.

**Comment by eesean** [comment]
Thanks for the inputs! Managed to fix the issue :)
