### ISSUE TITLE
Cannot find symbol: class ViewStub

### ISSUE THREAD

**Issue by weitatftw** [nus-cs2030/2223-s2#339]
# Summary
I'm now facing this issue where I can't pass the final test case and it says that the class ViewStub hasn't been defined yet. But the question didn't mention anything about creating a ViewStub class which really confused me. Does anyone have any idea what may be causing this issue? 

## Screenshots (if any): 
<img width="900" alt="Screenshot 2023-03-08 at 7 54 07 PM" src="https://user-images.githubusercontent.com/79369027/223707203-957688cc-fe1e-4ba0-ac6d-1395d4f79456.png">

**Comment by ghost1nthemachine** [comment]
Faced this issue too, just a minor change to your planner's view method. it should take in View not DayView.

view(DayView view) --> view(View view)

**Comment by allnotavailable** [comment]
hi I have changed day view to view but the problem still remain. Any idea?

**Comment by weitatftw** [comment]
> hi I have changed day view to view but the problem still remain. Any idea?

same here

**Comment by weitatftw** [comment]
> Faced this issue too, just a minor change to your planner's view method. it should take in View not DayView.
> 
> view(DayView view) --> view(View view)

i've tried this but to no avail :( this error is still showing
