### ISSUE TITLE
Lab 01: Unable to pass TC 10

### ISSUE THREAD

**Issue by fy17ohhh** [nus-cs2030/2223-s2#34]
## Description:

Hi, I tried a few times but still couldn't pass TC10; passed all previous TC

## Screenshots

<img width="580" alt="image" src="https://user-images.githubusercontent.com/103088135/215278186-f037a416-f4c2-44b9-96a2-be63e93087b5.png">

**Comment by JYeoZS** [comment]
Need more context. 

Prolly something wrong with logic of loops?

At this stage is server 2 occupied? If it is and code returning server 2 at line 20, there's flaw with logic flow of code.

How is your code keeping track of time? Guessing problem lies there.

Cheers.

**Comment by fy17ohhh** [comment]
> Need more context on customers arrival and leaving times, number of servers and servers currently occupied.
> 
> Prolly something wrong with logic of loops?
> 
> At this stage is server 2 occupied? If it is and code returning server 2 at line 20, there's flaw with logic flow of code.
> 
> How is your code keeping track of time? Guessing problem lies there.
> 
> Cheers.

thx! checked logic flow again and successfully solved the issue!
