### ISSUE TITLE
must view take in an ImList<...> type input?

### ISSUE THREAD

**Issue by Leeeef552** [nus-cs2030/2223-s2#341]
Codecrunch test case says that we need to implement the interface View with the void method view(). are we allowed to implement view without taking in an ImList<..> type input? Because the other test case shows that it takes in DayView instead? Its quite confusing

**Comment by hhuilingg** [comment]
since it is given in the question, we need to implement the interface View with the void method view(). 

as for the test case (p.view()) gives you a hint that Planner also has a view method but taking in DayView so Planner does not implements the interface.

**Comment by nicholasteow** [comment]
Planner has a view method that takes a View interface(which means the method can also take a DayView since DayView implements View)

**Comment by Leeeef552** [comment]
Ok thannks a lot
