### ISSUE TITLE
Test Case 5_1 PA1 

### ISSUE THREAD

**Issue by Leeeef552** [nus-cs2030/2223-s2#342]
Anyone else got this error? 

I tried to test on my jshell and the error didnt appear.
![image](https://user-images.githubusercontent.com/104271512/223792173-863a802f-6445-44f9-8612-e413feed0201.png)
![image](https://user-images.githubusercontent.com/104271512/223792418-37ce6b2e-dd6e-4ad2-ac45-edfcee697529.png)

**Comment by easypzlemonsqueezy** [comment]
hi! can you expand the error so i can see the context of test case 5.1?

**Comment by Leeeef552** [comment]
Its fully expanded

**Comment by sethteo** [comment]
hello ! what is the implementation for your recurring task index cancel method

**Comment by Leeeef552** [comment]
my recurring task takes in a list of tasks as attribute. To edit I will create a new task, set my the task by editting my list attribute then create a new recurringtask with the new list.

**Comment by sethteo** [comment]
> my recurring task takes in a list of tasks as attribute. To edit I will create a new task, set my the task by editting my list attribute then create a new recurringtask with the new list.

For the cancel(int index) method you did the same as well right (e.g create a new cancel task then your imlist.set(newly created task)

Because for this error I think its only if you explicitly check if its a cancelledtask (e.g checking if it contains the words "[cancelled]"

**Comment by Leeeef552** [comment]
oh shit youre right seth! Thanks! 

> > my recurring task takes in a list of tasks as attribute. To edit I will create a new task, set my the task by editting my list attribute then create a new recurringtask with the new list.
> 
> For the cancel(int index) method you did the same as well right (e.g create a new cancel task then your imlist.set(newly created task)
> 
> Because for this error I think its only if you explicitly check if its a cancelledtask (e.g checking if it contains the words "[cancelled]"

Oh shit youre right seth! Thanks! Its resolved
