### ISSUE TITLE
Test Case 5_1 recurring task false

### ISSUE THREAD

**Issue by ghost1nthemachine** [nus-cs2030/2223-s2#343]
what is this test case?

<img width="1512" alt="Screenshot 2023-03-09 at 9 45 49 AM" src="https://user-images.githubusercontent.com/125187978/223894598-7dc613c1-519f-43ca-84cd-76af25a84c55.png">

**Comment by weitatftw** [comment]
did you use the .includes("[cancelled]") method in your Planner class?? The true / false thing might just be a test case that the prof implemented to check for the use of the method mentioned above. If you used the .includes() method you would need to remove it and re-write parts of your code to resolve this issue

**Comment by UmpoDumpo** [comment]
Were there any comments given? I believe this could be due to the regrading. Do check if you use any methods that were not used in previous labs like .contains()!

**Comment by kayeugenia** [comment]
i think he mentioned that you are not allowed to use string checker! (method that allows u to see if it is cancelled/not based on the toString output)

**Comment by SimonSeeYongsheng** [comment]
How did you go about checking if the task is cancelled or not cancelled?

**Comment by easypzlemonsqueezy** [comment]
hi! i suspect it might have to do with you recoding the instanceof using the tostring method, you might have to find another way to code this

**Comment by leonlu178** [comment]
i was able to solve it using boolean attributes so it could be something else that u have neglected in the adding of tasks

**Comment by ghost1nthemachine** [comment]
resolved it, thanks a lot for the help!! :) it was due to my use of string contains()

i use the addAll method from imlist to overcome this
