### ISSUE TITLE
PA1 test case 3 fail

### ISSUE THREAD

**Issue by tryngmyhardest** [nus-cs2030/2223-s2#345]
had to resubmit my code after the re-grade but now im getting another error

anyone knows what causes this?

i understand this is regarding my batch edit method but i didnt make any changes to it and it worked before. 

my logic was to make a new imlist and return a new recurringtask.

thanks!
<img width="932" alt="Screenshot 2023-03-09 at 8 33 48 PM" src="https://user-images.githubusercontent.com/127404598/224026063-2bd7d591-cee5-4620-91b4-fc803791a3ef.png">
<img width="539" alt="Screenshot 2023-03-09 at 9 12 26 PM" src="https://user-images.githubusercontent.com/127404598/224033765-11644408-3b22-47af-a615-2038ed32d9ae.png">

**Comment by TheTired223** [comment]
Hi, have you tried checking if the Cancel class (name based on your cancel implementation) has the right input for day? If I'm not wrong based on the index you can add day and frequency*index. Maybe the Cancel class doesn't carry over this input when editing the imlist.

**Comment by tryngmyhardest** [comment]
> Hi, have you tried checking if the Cancel class (name based on your cancel implementation) has the right input for day? If I'm not wrong based on the index you can add day and frequency*index. Maybe the Cancel class doesn't carry over this input when editing the imlist.

Thanks a lot for the reply! Yep it was my cancel method that putting in the wrong day thanks man
