### ISSUE TITLE
Problems regarding view method test cases

### ISSUE THREAD

**Issue by yueyaozzz** [nus-cs2030/2223-s2#347]
# Summary
My view method in class DayView seems not be able to drop out the cancelled tasks successfully.

## Idea s
Since both test cases fail for a CancelledTask object, I assume the problem is within the getLstOnDay() method in CancelledTask class. However my getLstOnDay() method in CancelledTask just return an empty ImList so I don't know why this does not work.

## Screenshots (if any): 
<img width="1298" alt="Screenshot 2023-03-09 at 11 33 02 PM" src="https://user-images.githubusercontent.com/122427063/224079645-9dc5cf77-7670-42c5-807b-45b6a061a40e.png">

**Comment by easypzlemonsqueezy** [comment]
you may want to check the implementation of your getlstonday() for your recurringtask, they seem to both originate from recurringtask, hope this helps!

**Comment by Eleanoritsme** [comment]
Maybe you need to check the getLstOnDay() method you used for RecurringTask and Task, maybe you only checked the day on RecurringTask and didn't check cancelledTask
