### ISSUE TITLE
Can not find symbol "ViewStub" 

### ISSUE THREAD

**Issue by xgkiri** [nus-cs2030/2223-s2#349]
![case5_1](https://user-images.githubusercontent.com/107925929/224228466-f276ad5b-5408-4b46-a0d3-7923c24d1473.png)
It reports that there is no class "ViewStub" in the last test case.
Does anyone meet the same problem?

**Comment by e0968868** [comment]
Your planner's view method needs to take in a generic View rather than a Dayview

**Comment by coderlimjingcheng** [comment]
I think it has to do with your view method in Planner class. The .add method should take in a View interface rather than DayView class. Basically, the method should be .add(View DayView) not .add(DayView DayView). That was my solution to this problem. Hope it helps!

**Comment by minhphongle** [comment]
I also had a similar issue, what I did was changing the class Dayview in the .add() to the interface View. Hope that helps.

**Comment by weitatftw** [comment]
i believe that this is the same issue as #339, you can check it out for a possible solution

**Comment by xgkiri** [comment]
Thanks to all.
Now I have already solved this issue.
What I did is using exactly the same interface "View" as the guide. And Change my method "view" in class Planner from `void view(DayView DayView)` to `void view(View DayView)`. 
I guess the CodeCrunch will create a "ViewStub" class which implements the interface "View". When you call the "view" method of the interface, it just prints out the "empty view". 
If your interface is not the same as the guide, the class "ViewStub" can not be created since it will fail to override. That is why there is a "can not find symbol" report. And if you do not use the "view" method in Planner, you can not invoke the override method "view" in "ViewStub". Then your output will miss "empty view".
So it can test whether you use the same interface as the guide and you use its "view" method in Planner.
