### ISSUE TITLE
Cyclic Dependency with IS-A and Has-A Task for RecurringTask

### ISSUE THREAD

**Issue by UmpoDumpo** [nus-cs2030/2223-s2#351]
The PA solution's RecurringTask class IS-A task and also HAS-A task. Doesn't this result in cyclic dependency?

Insert Images here if necessary
<img width="325" alt="image" src="https://user-images.githubusercontent.com/115340765/224306220-7bb88371-116f-4aee-b258-e488b1250717.png">

**Comment by zhanyang01** [comment]
i think it is because although recurring task depends on task but task on the other hand does not depend of recurring task, hence it is not a cyclic dependency

**Comment by choongzhanhong** [comment]
Yep it is not cyclic because Task doesn't depend on RecurringTask. There is no point in the code of Task that RecurringTask is mentioned. i.e. you can compile Task.java without needing RecurringTask.java but not vice versa.

**Comment by leezhanpeng** [comment]
Like others pointed out, RecurringTask depends on Task but Task does not need RecurringTask. A cyclic dependency is when two classes rely on each other for your program to run. For two classes only, if any class can run independently of the other, then no cyclic dependency is present.

**Comment by haqanh** [comment]
I was also puzzled at first but since Task does not depend on RecurringTask, it would not lead to cyclic dependency i.e. you can compile Task without having to compile RecurringTask prior and do test cases with just Task

**Comment by UmpoDumpo** [comment]
got it cheers all
