### ISSUE TITLE
Event returning itself

### ISSUE THREAD

**Issue by tryngmyhardest** [nus-cs2030/2223-s2#353]
how can I make an event return itself without making it an infinite loop? for example my pendingserve, leave and done events dont return another event so I return “ this” however its not being removed from the queue :(

my impl is to return a new Pair of nextevent and imlist of updated servers after each event. thanks!

**Comment by jianjiezzz** [comment]
Personally, I added a If statement in my simulator, if UpdatedEventPair.first( ) != currentEvent then I add the Event into the PQ. Therefore, if it returns the same object, it would not be add back to the PQ.

**Comment by leonardwx** [comment]
u can try to create a boolean indicator to specify whether the event is last or not last. Eg. Done.hasEvent = false

**Comment by tryngmyhardest** [comment]
@jianjiezzz @leonardwx nice thanks !! :)
