### ISSUE TITLE
What should be the logic for comparator?

### ISSUE THREAD

**Issue by jianjiezzz** [nus-cs2030/2223-s2#354]
Previously I assigned a Event priority index for each Event, So I compare by Time --> Event Priority Index --> Customer Index
But the new system flagged me for using private static final event index = 1/2/3/4/5
How should I change my Intcomp? Is it just compare time --> customer index only?
Or is there a way to compare event priority index without declaring private static final?

**Comment by jhsoh** [comment]
Prioritise according to arrival time of customers. If arrival time is the same, then prioritise based on ascending customer id
