### ISSUE TITLE
Lab 5 test case 9_04

### ISSUE THREAD

**Issue by Leeeef552** [nus-cs2030/2223-s2#356]
Hi did anyone face this issue for lab5?

My implementation is that Done event willl generate rest time, if more than 0, it will call serverRest event, which is just an event to pass the updated server next available time to the next event and to update the server list. 

![image](https://user-images.githubusercontent.com/104271512/224466668-b1bfdd90-a828-410d-ae24-a4502734d585.png)

**Comment by dylanlo8** [comment]
Hi your output seems to show something very wrong with your Done event event time since the Done eventtime is 0.388 only. Maybe try to check the whether the correct event time is being inputted into the creation of the Done event first?

**Comment by Leeeef552** [comment]
ok but the thing is the output is correct for the other test cases. And i was also able tp get the public test cases on code crunch
