### ISSUE TITLE
problem with given test case 

### ISSUE THREAD

**Issue by taugwa** [nus-cs2030/2223-s2#358]
hi, did anyone run into the same issue with the 3rd given test case in lab5, and if so, how did yall solve it? for lab 5.1, i retained much of my code from the previous lab but i added a new RestEvent and updated the serverEndTimes during rest but somehow my queue is now messed up. i attached a pic of the output i got and the correct output below.

thank you!

<img width="178" alt="Screenshot 2023-03-11 at 2 32 02 PM" src="https://user-images.githubusercontent.com/122268711/224469287-4b63a71f-7447-4a3a-9689-094f8de59f89.png">
<img width="277" alt="Screenshot 2023-03-11 at 2 32 26 PM" src="https://user-images.githubusercontent.com/122268711/224469282-b78c654d-ad6e-4893-b7ee-d5bd35be3f72.png">

**Comment by alvintjw** [comment]
I had this problem where in lab3 I "dequeue" the customer at the done event. once I changed it to "dequeue" at the serve event and update accordingly the updated server queue size, the issue was resolved.

**Comment by taugwa** [comment]
this worked! thank you :))
