### ISSUE TITLE
Planner Case

### ISSUE THREAD

**Issue by TheTired223** [nus-cs2030/2223-s2#360]
Hi does anyone have any idea what this case is referring to?
![image](https://user-images.githubusercontent.com/100417316/224476233-1fc001e7-716f-41a8-b443-e14bd70efc2d.png)

**Comment by fy17ohhh** [comment]
seems like your p.view function only accepts DayView Class, but not other classes that implements View Interface

**Comment by e0959170** [comment]
there are a number of reasons this error could be happening. for me i  made my view methods View() instead of view(). for my other friends their issue was that in planner they took in DayView instead of View, like what the above commenter has mentioned

**Comment by littlemidget3** [comment]
check if youre only taking in a DayView, instead of a View

**Comment by Aron113** [comment]
take in the View interface in the function
