### ISSUE TITLE
Lab 5 test case 9_9

### ISSUE THREAD

**Issue by syafiq9326** [nus-cs2030/2223-s2#364]
# Summary
Unsure of the self-checkout queue.

## Description:

Is the q size for self-checkout not supposed to be the same for all machines? I don't understand what went wrong here since it's a private test case, would appreciate any insights. Thanks in advance!

## Screenshots

![image](https://user-images.githubusercontent.com/50677984/224484771-1eb116a8-5843-4b1a-8239-07c68f07e26f.png)

**Comment by VanyaPriscillia** [comment]
There is only 1 queue for all self checkouts. The toString of Wait Event in the self checkout server always returns the same (for example, it must return “waits at self-check 1” everytime you call the Wait Event).

**Comment by syafiq9326** [comment]
Ah okay, got it thanks Vanya!

**Comment by JYeoZS** [comment]
Hi, regarding this issue, curious also. Say qmax is 2. There are 3 self-checkout counters.

Can the self checkout queue have 2 or 6 maximum?

Thanks.

**Comment by VanyaPriscillia** [comment]
The maximum is 2, not 6.
