### ISSUE TITLE
Lab 05 Test Case 9_3

### ISSUE THREAD

**Issue by taugwa** [nus-cs2030/2223-s2#365]
hi, if anyone had the same issue can i ask how did yall solve it? i can't seem to figure out why this is wrong. thanks in advance :)
<img width="604" alt="Screenshot 2023-03-11 at 9 36 34 PM" src="https://user-images.githubusercontent.com/122268711/224487808-d0f4b666-d425-47cc-9e6d-f4fe7dbd2270.png">

**Comment by VanyaPriscillia** [comment]
I think you should consider when to generate the rest time.

**Comment by emilythx** [comment]
Hi, I encountered a similar issue as I was getting my rest time at serve event (to update the serverlist). I changed it to generating my rest time at the done event and it worked! Hope this helps :)

**Comment by JYeoZS** [comment]
Hi, got similar problem, changed rest time to invoke in doneEvent. Still got the same problem.

Suspect something to do with how WaitEvent keep track of server time, how did you go about solving that problem? 

Much thanks.

**Comment by jeffkhong11** [comment]
Firstly, can insert println statements in the Done event to check if the executeEvent() is invoked. If it isn't may want to check the implementation of the simulate() method.
Otherwise, it could be in the if statement in the WaitEvent's execute(), where I need to check that the updated server's timing is the same as my event time before i go to Serve.
That was the problem that I faced ^

**Comment by aa01xx** [comment]
It seems like your server's available time is not updated with the rest time generated, perhaps you can try checking that your servers are being updated with the new available time? Or perharps it could be that the start time of Serve event is not being updated properly.

**Comment by JYeoZS** [comment]
Hi, problem only occurs when there are more than 1 customer in queue though. 

I have my restEvent after DoneEvent, and my getRest() method is invokes in DoneEvent, am I on the right track? 

It looks like the problem may be that my 2nd customer in queue is basing his timing off the DoneEvent time of the customer ahead....

**Comment by emilythx** [comment]
hmmm maybe you would like to check on how you are updating your server's time during done event? When you generate the getRest() on your done event, you may consider updating your server's time to currentEventTime + getRest() --> this was the change that I made. Server's time will get updated so that the next available time will be based on this. Yes, I do have a restEvent as well :)

**Comment by BrendaTan29** [comment]
hello! i experienced the same problem as you but I managed to fix it by changing my inequality sign in my if else statement in my buffer event. you can consider checking that your server's next available time is <= the event's time. hope this helps!

**Comment by taugwa** [comment]
hi, thank you everyone for your responses, they were very helpful! ultimately the issue for me was that my buffer event between wait and serve generated a serve event that did not consider the rest timing of the server in certain situations, e.g. 
0.100 1 arrives
0.100 1 serves by 1
0.200 2 arrives
0.200 2 waits at 1
1.100 1 done serving by 1
1.100 2 serves by 1 (but this might not be true as server may have rest time)

(example courtesy of @j0205m's comment in this thread: https://github.com/nus-cs2030/2223-s2/issues/355)

**Comment by vanessakohh** [comment]
> hi, thank you everyone for your responses, they were very helpful! ultimately the issue for me was that my buffer event between wait and serve generated a serve event that did not consider the rest timing of the server in certain situations, e.g. 0.100 1 arrives 0.100 1 serves by 1 0.200 2 arrives 0.200 2 waits at 1 1.100 1 done serving by 1 1.100 2 serves by 1 (but this might not be true as server may have rest time)
> 
> (example courtesy of @j0205m's comment in this thread: #355)

Hii, do you think you could point me in the right direction? I also have the issue where my buffer event creates a serve event without considering the serverrest times... How did you manage to solve this?
