### ISSUE TITLE
Server serves multiple people in the same time slot

### ISSUE THREAD

**Issue by weitatftw** [nus-cs2030/2223-s2#366]
# Summary

I'm currently stuck at test case 9_03 where my server begins to serve multiple people at the same time once its free even though I have a flag variable in the server that signals whether the server is currently serving people or not. Does anyone have any idea what might have went wrong??

## Screenshots
<img width="428" alt="Screenshot 2023-03-12 at 12 01 32 AM" src="https://user-images.githubusercontent.com/79369027/224494798-c8add772-4614-442b-9898-e525658186dc.png">

**Comment by littlemidget3** [comment]
perhaps you have to check your wait/ wait intermediate events. They may only be checking if the servers are available, and not whether they're the next customer in line.

**Comment by weitatftw** [comment]
> perhaps you have to check your wait/ wait intermediate events. They may only be checking if the servers are available, and not whether they're the next customer in line.

Thanks for the help! I managed to solve this issue but then I'm now facing another issue - apparently some of my customers don't queue at the right server and I'm really confused because all of the previous customers queued at the right server but why not all of them??

**Comment by weitatftw** [comment]
I've solved the issue, thanks for the help!
