### ISSUE TITLE
Lab 5 Private Test Case 9_11

### ISSUE THREAD

**Issue by syafiq9326** [nus-cs2030/2223-s2#368]
# Summary
Private Test Case 9_11, customer served by wrong machines.

## Description:
I am having issues clearing the above private test case. My server manager class is able to add or minus the size of the queue and also has a function to check which machine is free to serve next (Since any machine can serve those in the self-checkout q once free). I assume that I am not controlling the time in the buffering wait event for my machines correctly?

I tried doing some smaller cases since I can't figure out the private ones.

Would appreciate any help, thanks!

## Code Snippets
A smaller case where I have 0 human servers, 2 machines and a q size of 2. As seen below, I am able to get the earliest machine to serve a customer in the self-checkout q but the time is not correct. Self-check 2 should be done at 1.500 and should serve customer 4 at 1.500 but it is serving it at 2.00. I assume then that this is where it all went wrong.

![image](https://user-images.githubusercontent.com/50677984/224511384-4f37db94-4be4-43b6-894e-01566e300c10.png)

## Screenshots

Test Case 9_11 private testcase
![image](https://user-images.githubusercontent.com/50677984/224511350-cce49305-7907-4a6b-83de-06404850dfc2.png)

**Comment by 0liverkong** [comment]
youre waitmore/invisible wait events seem to be incorrectly generated.
if the customer is in the queue to self checkout, they should generate the next waitmore/invisible wait event based on the next upcoming free time of any self checkout counter, not just the first one (which is self check 1 in this case)

your serve event for customer 4 seems to only look at self checkout 1, so this error happened. i think.

**Comment by syafiq9326** [comment]
Yup spot on, managed to solve it, thanks a lot man!

**Comment by Jeko1239** [comment]
may i ask what u fixed to solve ur problem, my timing seems to be exactly the same as yours

**Comment by Jeko1239** [comment]
may i ask how did u manage to fix ur problem, I have the exact same timings as yours
