### ISSUE TITLE
Accounting for rest time

### ISSUE THREAD

**Issue by eesean** [nus-cs2030/2223-s2#370]
Hi all,

My implementation involves a queue of customers for each human server (priority queue) and a timestamp is associated with each customer.

That being said, I would like to have advice on whether there is a need to factor for rest time, meaning when a human server rests, 1) is it needed to update the timestamp for every customer in the queue, or 2) Only update for the customer at the head of the queue, or 3) there's no difference between the first and second approach? (Each priority queue has a comparator that is based on the customer number)

Below is my output for test case 3. The server is supposed to rest after serving customer number 5, customer 6 was at the head of the queue and I have updated the timestamp of customer 6 to be the next service time for the server, however it appears as if the server serves the next customer immediately. There could be an error with my implementation but nonetheless I would like to seek opinion on whether there would be any difference between the two approaches stated above (as well as any other suggestions to factor in the rest time).

<img width="165" alt="rest" src="https://user-images.githubusercontent.com/110977266/224528297-c7459706-aaf9-4d70-a404-850d4ca80c62.png">

**Comment by timothysashimi** [comment]
I guess it depends on your implementation. What i did was to have a wait event for every customer in the queue. So each customer will check whether he is first in the queue when the server is done serving someone. If hes at the first but the server needs to rest, then he will wait until the server is free. If the server does not need to rest, generate a service event. if hes not at the front of the queue, generate another wait event which will be the time the server finishes serving the next customer

**Comment by Aron113** [comment]
i think its dependent on how you check when to serve the next customer. If you are using a Checker event, probably just need to update the Server's free time

**Comment by littlemidget3** [comment]
what your wait event needs to do is to check on the server's free time after the get rest time has been factored in. Depending on implementations, most wait events are assigned the timing where server is done serving, but the timing does not account for the rest. Perhaps check if your wait event is checking against the get available time.

**Comment by eesean** [comment]
Thanks for the inputs! I have checked my implementation that the rest time is factored in, and did a bit of debugging such that if buffer time is greater than 0.0, I would print out a statement indicating that it is resting.

I end up getting the same output as the one above, not sure whether it is just my luck with the probability or smth :<
