### ISSUE TITLE
Ex 4 level 4

### ISSUE THREAD

**Issue by yuzujy** [nus-cs2030/2223-s2#373]
Hi can I ask what is the problem here? thanks! i have tried both extends and super...
<img width="457" alt="image" src="https://user-images.githubusercontent.com/122694072/224532513-005a246a-090d-4a20-91f3-bc56c5426241.png">
<img width="462" alt="image" src="https://user-images.githubusercontent.com/122694072/224532534-a032c86f-bbe9-4e29-bf9b-91b465ed49cf.png">

**Comment by 0liverkong** [comment]
your Supplier generic is invariant so it needs to have either an ? extends or ? super

**Comment by granolaluvr69** [comment]
The return type is Maybe<? extends T> so you can try making the supplier supply something of type <? extends Maybe<? extends T>>.
