### ISSUE TITLE
Ex 4 level 5

### ISSUE THREAD

**Issue by wongjingwen** [nus-cs2030/2223-s2#374]
![Screenshot 2023-03-12 174001](https://user-images.githubusercontent.com/120257984/224536681-979c9b92-db2a-40cb-9699-1eb3e2565da6.jpg)

Does anyone know what is wrong with the output? Im not sure how to go about handling it.

**Comment by nigel-tannn** [comment]
Hi, can I check how you managed to check if the Maybe context is not nested without using instanceof?

**Comment by wongjingwen** [comment]
i used the instanceof within my equals method.

**Comment by nigel-tannn** [comment]
Did you use your equals method within your flatMap?

**Comment by wongjingwen** [comment]
nope

**Comment by 0liverkong** [comment]
or should return Maybe<T> and not Maybe<? extends T>. so change your or() to unwrap the maybe and wrap it up again.

**Comment by rayray39** [comment]
hi i just wanna ask if the method definition for flatMap is siimilar to map? (if its a Maybe.empty then return a new Maybe.<R>empty, else return Maybe.<R>of(flatMapper.apply(this.value)) )?

**Comment by wongjingwen** [comment]
Hi, i have tried thi s: "Maybe.of(flatMapper.apply(this.value)) )" but it does not works . It state <R> of(R) of type Maybe is not applicable for the arguments( ? extends Maybe<? extendsR>)

**Comment by omarsfs** [comment]
hi what was the issue in the end and how did you resolve it? does it have to do with your previous methods?
