### ISSUE TITLE
Test Case 9_04

### ISSUE THREAD

**Issue by lershuan** [nus-cs2030/2223-s2#375]
Any idea what test case 9_04 is testing for? I managed to get my output for 3.in correct, but not sure why this test case is failing on CodeCrunch.

![Screenshot 2023-03-12 at 5 53 33 PM](https://user-images.githubusercontent.com/122249627/224537237-f0027a26-d35e-4421-992d-a4137a808850.png)

**Comment by littlemidget3** [comment]
it seems like your server isn't taking a break, and is immediately serving the next customer. I haven't seen the issue where someone passes 3.in but failed test case 4 yet,  but perhaps you could check if you wait/wait intermediate is checking against the server's free time before a serve event is returned. Are your rest events coming in immediately after done? else the wait event may be prioritised, depending on implementations

**Comment by yugan01** [comment]
I am also facing this same issue. My wait class is checking against the server's free time before a serve event is returned but I'm still not sure as to why this issue still arises
