### ISSUE TITLE
Test Case 9_11

### ISSUE THREAD

**Issue by whsiah** [nus-cs2030/2223-s2#376]
Does anyone know what kind of scenario could be causing an error for this test case?
I can't seem to tell which of my class(es) might be bugged from the output snippet provided.

![photo_2023-03-12_20-23-06](https://user-images.githubusercontent.com/122257619/224544436-e04110e7-bc97-4407-87b7-3758f8b7ef4c.jpg)

**Comment by 0liverkong** [comment]
same issue as #368 . Might also have an additional issue of incorrectly updating the selfcheckout queue so 17 leaves when it is supposed to stay. All the best :3

**Comment by whsiah** [comment]
@0liverkong 
Thanks for pointing out both issues correctly, passed this test case after fixing them. You're a godsend!

**Comment by Jeko1239** [comment]
may i ask how did u manage to fix ur problem, I have the exact same timings as yours

**Comment by whsiah** [comment]
> may i ask how did u manage to fix ur problem, I have the exact same timings as yours

as mentioned by @0liverkong, you need to check that customers waiting in queue for a self checkout counter are updated to wait for the earliest available self checkout counter instead of the self checkout counter they were originally assigned to upon arriving to the shop
