### ISSUE TITLE
Testing with input files in vim

### ISSUE THREAD

**Issue by kelleyhan25** [nus-cs2030/2223-s2#38]
Hello! 

How are we supposed to use/write the 1.in, 2.in files to test our Main.java class? I'm not sure how to use vim to test the Main, Shop, Server and Customer classes together. Any help would be appreciated!

**Comment by lihongguang00** [comment]
Hi Kelley, 

Let's assume you're looking to test your code against the 1.in test cases.

1. Copy the test cases into a file named "1.in". You can do this by typing `vim 1.in` in your cmd, input your test cases then saving it with `:wq` command in vim.
2. Ensure the "1.in" file is in the same directory as the java files you are looking to test.
3. Back in your cmd, make sure to compile all your java files by using `javac <file_name>.java`. Alternatively, shortcut to compile all files in the directory is using the command `javac *.java`.
4. After compilation, just type `java Main.java < 1.in` and it should output the result from your test cases.

**Do note that if you make any changes to your classes, you will need to recompile them again before doing step 4.

Hope this helps, cheers!

**Comment by wmingchuan** [comment]
java Main.java < 1.in gives me an error, but it works when I just do java Main < 1.in
You can also java Main < 1.in > 1.o and it will save the output in the file 1.o. Can do this if the output is very long and you want to save and view it later.

**Comment by SimonSeeYongsheng** [comment]
The easiest way I found was to copy and paste the test cases to a notepad and save as type "All Files (*.*)" and ensure you name it with a *.in file extension. That way you can mass copy all the test cases.

**Comment by kelleyhan25** [comment]
Thank you!!
