### ISSUE TITLE
Need help with test case 9_12

### ISSUE THREAD

**Issue by cswssn** [nus-cs2030/2223-s2#383]
Seems like a very isolated bug in which 994 and 995 were suddenly served together. Anyone knows what could be causing this?
![image](https://user-images.githubusercontent.com/127683578/224560410-7dc07444-eaa4-4a9e-bd20-768959949f30.png)

**Comment by JonathanCheeNUS** [comment]
I would suggest doing a separate test case to check if your servers' status are being updated properly when they are serving. If you are polling one event at a time from your PQ this really should not happen so I am quite confused as well

**Comment by cswssn** [comment]
> If you are polling one event at a time from your PQ this really should not happen so I am quite confused as well

I am indeed polling one event at a time and it is strange that the issue did not occur for previous test cases.
> I would suggest doing a separate test case to check if your servers' status are being updated properly when they are serving. 

I thought that the issue might be due to 2 customers arriving and waiting for the same server at the same time, but my custom test case did not have any issues. Any idea what I should be simulating to test whether the servers' statuses are updated correctly?

**Comment by haqanh** [comment]
> > If you are polling one event at a time from your PQ this really should not happen so I am quite confused as well
> 
> I am indeed polling one event at a time and it is strange that the issue did not occur for previous test cases.
> 
> > I would suggest doing a separate test case to check if your servers' status are being updated properly when they are serving.
> 
> I thought that the issue might be due to 2 customers arriving and waiting for the same server at the same time, but my custom test case did not have any issues. Any idea what I should be simulating to test whether the servers' statuses are updated correctly?

Perhaps you can print the server state each time you poll an event? or put a println statement in your class/method that update your server, that way you can see when it is called and whether or not its called correctly.

**Comment by cswssn** [comment]
Found the bug, issue has been resolved.
