### ISSUE TITLE
Incorrect average waiting time

### ISSUE THREAD

**Issue by kayeugenia** [nus-cs2030/2223-s2#385]
hi! I am not sure if anyone faced the same issue before. My code currently works well for the test cases, but the only wrong output is the average waiting time. 
<img width="237" alt="Screenshot 2023-03-13 at 5 52 33 PM" src="https://user-images.githubusercontent.com/122983473/224667133-041ae13e-2eb9-44d5-90e4-12e2a684d608.png">
to be honest, i am not sure how codecrunch shows the average waiting time as 0.519 because when i calculated manually, i got the same answer as my code output (0.434).

FYI, I did not make a new rest class and only get the server's rest time in Done event.

Thank you!

**Comment by granolaluvr69** [comment]
I did the calculation and it looks pretty okay though... I got 0.5186. 
I took the time of the serve event minus the arrival time of the customers and averaged it out by dividing by the number of customers served, if it helps.
(0 + 0 + 0 + (3.053 - 2.776) + (4.053 - 3.877) + (5.902 - 3.910)  + 0 + 0 + (10.006 - 9.105) + (11.006 - 9.160)) / 10 = 0.5186

**Comment by kayeugenia** [comment]
thank you! turn out my problem was that the server is not updated correctly
