### ISSUE TITLE
Why does my self checkout counter serve the wrong person?

### ISSUE THREAD

**Issue by weitatftw** [nus-cs2030/2223-s2#389]
# Summary

I've tried placing debugging statements to see if I updated the state of my self checkout counters correctly during serving and finishing and it was correct. I've also tried printing out the self checkout counter number too and it was in the correct order. I've checked the toString methods of all Events and they are all looking ok. Anyone have any idea why does my self checkout manager serve the customer even when I have specific boolean flags that indicate that that specific self checkout counter is being used and the other self checkout counters are free?? I've been stuck here for quite long.

## Screenshots
<img width="262" alt="Screenshot 2023-03-13 at 8 55 13 PM" src="https://user-images.githubusercontent.com/79369027/224709297-b735d447-3a86-4d49-ad0f-4ebf19d4569f.png">

**Comment by fy17ohhh** [comment]
Not sure about your specific implementation, but have you updated the sever list with flagging in Simulator.java?

**Comment by weitatftw** [comment]
thanks for the help! i've managed to solve the issue
