### ISSUE TITLE
How to insert element into ImList?

### ISSUE THREAD

**Issue by jianjiezzz** [nus-cs2030/2223-s2#39]
I want to insert object at specific index, but ImList.add(index,object) doesnt work. Anyone knows whats the syntax for insert?

**Comment by lihongguang00** [comment]
Hi jianjie,

You can consider this function. Hope this helps!

![image](https://user-images.githubusercontent.com/84987837/215409646-08b553e6-b947-4726-b05b-1a8723594952.png)

**Comment by granolaluvr69** [comment]
I did this for my Shop class, worked for me.
``` java
ImList<E> list = new ImList<>();
list = new ImList<>().set(index, <new_element>);
```
Try it out, hopefully it works for you too!

**Comment by territxl** [comment]
I think you can also check out the Imlist.java file to see the various methods it has and see which one you would like to use.

Hope this helps!

**Comment by e0959170** [comment]
adding to the discussion, i don't think the ImList.add() method takes in index as a parameter so in the future you might want to check through the ImList file first because they do state the methods and the relevant parameters that you can use for any ImList object, along with a description :D
