### ISSUE TITLE
Lab 05 test case 9 : updating the Self Counter queue

### ISSUE THREAD

**Issue by ghost1nthemachine** [nus-cs2030/2223-s2#390]
<img width="653" alt="Screenshot 2023-03-14 at 1 00 19 AM" src="https://user-images.githubusercontent.com/125187978/224773066-7045a197-547b-4291-ae33-9f13b70d987c.png">

I believe the issue here is that my self counter queue is not being updated with customers, however i did attempt to add them in my arrival event before gg to the wait event.

but im starting to think that im removing the customers "too fast" ( in the wrong event )as i do it in my transition event right before the serve event.

i only use 1 imlist for all my selfcheckout counters which is the first self checkout's queue

Any advice how i can debug this? thanks alot

(sorry for the wrong label)

**Comment by maze508** [comment]
Start printing at places where you think that could go wrong and you should be able to debug from there.

**Comment by 0liverkong** [comment]
do the removing of the customer from the queue in the serve instead it may be easier

**Comment by ghost1nthemachine** [comment]
resolved: I had to override my checkQueue method in my selfcheckcounter class bc  it would not check the length of the queue in the parent server class
