### ISSUE TITLE
Lab 5 Fail test case 9_04: Unsure why the correct sequence is different from mine

### ISSUE THREAD

**Issue by yugan01** [nus-cs2030/2223-s2#391]
# Summary

Hi, the expected output as per shown below follows 11) 0.313 1 done serving by 1 and then proceeds to 12) 0.627 3 serves by 1, from my understanding, after the server has served the customer and taken the rest time, the server should serve the next customer, I believe my implementation of my rest class and the adding of the resting time to next available time is correct as I've passed test case 3.  I am still unsure why there is a 0.314 time gap between line 11 and line 12. 
Thanks in advance!

## Description:

Clarifications or details with respect to the issue you are facing

## Code Snippets

![image](https://user-images.githubusercontent.com/122327042/224870011-a104bacf-027a-4c8e-9626-81703db4853b.png)

## Screenshots

Screenshots (if any)

**Comment by fy17ohhh** [comment]
Have you passed all the 3 test cases in lab 5 file? Still seems that your server 1 didn’t have a rest after serving customer 1

**Comment by jiarui22** [comment]
maybe you can check if your condition from wait event to serve event is complete, the updated server's available time should be less than or equal to the wait event time, otherwise serve event will not be generated.

**Comment by keshialimm** [comment]
Hi, I'm facing the same issue as you.. test case 3 can account for the rest times, but cannot do so in test case 4. Have you solved the issue?

**Comment by granolaluvr69** [comment]
You can try putting a tostring for the invisible events to debug your program. The problem seems to be the generation of serve events from an intermediate event.

**Comment by yugan01** [comment]
Thanks to all, I realised I did not update my servers and update the serverList as it transited from my Done to Rest event.
