### ISSUE TITLE
too many service times generated

### ISSUE THREAD

**Issue by wyqng1234** [nus-cs2030/2223-s2#392]
# Summary

im getting this error on codecrunch although i made sure to only call getServiceTime once per customer. getServiceTime is also located in the constructor of my serve event. otherwise, i get the correct output when i run it on my own terminal. I've also checked that getServiceTime is being called in the correct order by adding System.out.print(Integer.toString(this.index) + "used" + "\n"); in my getServiceTime method in customer class. can someone point me in the right direction?

**Comment by glenn2030** [comment]
You cant print getServiceTime every time you call it so you can see how many times it is actually called per customer. If it is only once per customer, it is probably just the output that is different. Try to craft your own test case with and see if the output is correct! I used

**Comment by kenzverylayz** [comment]
Do note that you should only be calling getServiceTime in the serve event as well. Failing to do so will result in a incorrect service time being allocated to the customer even if you only call it once per customer

**Comment by ghost1nthemachine** [comment]
I faced this error too and it depends on which test case in code crunch. if it the 9th or last test case, the error is not with the getservicetimes but perhaps you are not updating the state of the servers correctly(in the right events). another suggestion wld be to check if you account that the servers queue can be 0 in your checkqueue method(when decide to add customers to the queue).

**Comment by hcyrr** [comment]
i faced this error too, like you i originally called getServiceTime in the constructor of my serve event, i fixed it by setting my servicetime attribute of my serve event to a default value in the constructor, and then only calling getServiceTime in the method that updates the pq and servers. hope this helps you
