### ISSUE TITLE
5.2 Test Case 9_11 time limit exceeded error 

### ISSUE THREAD

**Issue by emilythx** [nus-cs2030/2223-s2#396]
# Summary

Hi! I am currently facing some errors with test case 9_11, and I am not too sure where my error is. For some context, I have an abstract server consisting of both human and self-check servers. I have tried to create my own case 9_11 test case (with a random probability) and managed to get an output. Any help is greatly appreciated~ thanks!! :") 

## Description:

Clarifications or details with respect to the issue you are facing

## Screenshots

<img width="365" alt="Screenshot 2023-03-14 at 5 48 25 PM" src="https://user-images.githubusercontent.com/122248580/224964095-3cdfa2d1-e76c-437c-8ee3-ba72a51040a2.png">

**Comment by littlemidget3** [comment]
you may be facing an infinite loop. Since your arrive class doesnt print, perhaps you can begin by examining that class. You can put in a println statement to check if the bug is there. Check the inequalities as well.

**Comment by jacoblimjy** [comment]
might want to check for for loop(s) nested in another for loop

**Comment by 0liverkong** [comment]
does 9_11 have multiple self checks? if your own test case has only one self check then a likely problem is that your code does not remove the customer from the queue properly

**Comment by nigel-tannn** [comment]
Faced a similar issue, do check if your serverList is being updated to a "busy" state in your Serve class once you have assigned the customer to a self-check counter, this way the self-check counter should no longer be able to accept another customer until the customer is done being served.

**Comment by ryantangmj** [comment]
To solve this issue, you have to update the customer to the fastest available server in your wait class and your intermediate wait class (if you have)

**Comment by Aron113** [comment]
you probably need to check your Arrive event if it detects a server that has a full queue but is no longer busy

**Comment by Danpng01** [comment]
Hi I also faced this error, you should use print statements in your classes (specifically waiting and keep waiting) to see if the customer and server facing the infinite loop have the conditions that are not being caught by your serve class. In my case I kept returning the same timing without update the nextservetime.

**Comment by emilythx** [comment]
Hi thanks for the suggestions everyone! Apologies for the late responds. I managed to fix the issue as my for loop was iterating wrongly.

**Comment by emilythx** [comment]
Hi @subhadhra-m ! iirc, my continueWait event for selfcheckout servers are incorrect. As for my implementation, I only update the k+1 server, and I'll iterate through the selfcheckout servers to get the shortest avail time & selfcheckout serverID. Somehow i wasnt getting the k+1 serverTime that does the comparison, but i managed to solve it by:
<img width="569" alt="Screenshot 2023-04-04 at 1 35 23 AM" src="https://user-images.githubusercontent.com/122248580/229584900-489ab824-a086-4ad7-b9ac-21120e24f7a1.png">
before i start my iteration. Hope this helps!

**Comment by subhadhra-m** [comment]
Thank you for your input @emilythx :) I managed to solve my issue. I was having an infinite loop as I was checking whether the selfcheckout server was free in my implementation for getting the fastest available selfcheckout.
