### ISSUE TITLE
Ex4+ Level6 

### ISSUE THREAD

**Issue by fy17ohhh** [nus-cs2030/2223-s2#397]
<img width="657" alt="image" src="https://user-images.githubusercontent.com/103088135/224990208-6a0e782f-2731-456a-b958-8d718a85b36e.png">
Hi, does anyone know what could be the possible reasons of the error? For my equals method in Maybe Class I use .equals() to check for two values if both of them are not empty

**Comment by granolaluvr69** [comment]
If you directly compare the maybes without checking their inner contents, you will return true. Try comparing the inner values instead. The .or() method might help.

**Comment by fy17ohhh** [comment]
> If you directly compare the maybes without checking their inner contents, you will return true. Try comparing the inner values instead. The .or() method might help.

I used or() to check and the above test case returns false, dunno why ma.equals(mb) is true

**Comment by 0liverkong** [comment]
cant even get my code to  compile for level 6 👉👈 how do yall do it

**Comment by granolaluvr69** [comment]
> > If you directly compare the maybes without checking their inner contents, you will return true. Try comparing the inner values instead. The .or() method might help.
> 
> 
> 
> I used or() to check and the above test case returns false, dunno why ma.equals(mb) is true

You should run it through filter to check if the value contained is equals to null and then use or().

**Comment by granolaluvr69** [comment]
> cant even get my code to  compile for level 6 👉👈 how do yall do it

You can try following the slides in the lecture, and you can use the methods that you defined in the regular maybe exercise, provided you don't use private methods to obtain values in other (non this) maybe contexts.

**Comment by 0liverkong** [comment]
> > cant even get my code to  compile for level 6 👉👈 how do yall do it
> 
> You can try following the slides in the lecture, and you can use the methods that you defined in the regular maybe exercise, provided you don't use private methods to obtain values in other (non this) maybe contexts.

does this mean i have to change the access modifiers of private functions like get()

**Comment by granolaluvr69** [comment]
No, get(), isEmpty() and isPresent() have to remain private. You have to use other methods to get values and compare them.

**Comment by fy17ohhh** [comment]
> > > If you directly compare the maybes without checking their inner contents, you will return true. Try comparing the inner values instead. The .or() method might help.
> > 
> > 
> > I used or() to check and the above test case returns false, dunno why ma.equals(mb) is true
> 
> You should run it through filter to check if the value contained is equals to null and then use or().

I used or to check for null directly, may I ask how you construct a Predicate in the filter? If I was to use filter to check for null, it keeps showing that filter(Predicate<? super capture#12-of ?>) in the type Maybe<capture#12-of ?> is not applicable for the arguments in my Predicate

**Comment by granolaluvr69** [comment]
filter(x -> x == null).orElse(false)

**Comment by fy17ohhh** [comment]
> actually i think i might not have to use filter to check it after all, other.map(x -> true).orElse(false) should work fine.

thx for the reply! finally managed to implement the method using orElse() only
