### ISSUE TITLE
Adding Checkstyle within Vim

### ISSUE THREAD

**Issue by jamiewong1210** [nus-cs2030/2223-s2#4]
I'm not sure what to add in the description stating [path to folder]. In my case, would it be /workspace/cs2030_checks.xml? How does Vim check our code using this checkstyle template since when i compiled my program there was no error the program having poor syntax.

![Checkstyle](https://user-images.githubusercontent.com/120257984/211450413-8c5e30fd-1d21-4ae2-b67b-4c32817fc8e3.jpg)

**Comment by danqiye1** [comment]
Hi Jamie, your path to folder will be the folder where your cs2030_checks.xml resides. You can find that out by navigating to the folder containing cs2030_checks.xml and typing the command `pwd`. If you are using docker, then it should be `/workspace/cs2030_checks.xml`.

Once you have run `source ~/.bashrc`, you should be able to call the `checkstyle` command from your terminal and it will check the java files in your current folder. What step 2 is doing is just renaming the whole chunk of command and arguments as a command called `checkstyle`.

**Comment by Follow-Mee** [comment]
vim ~/.bashrc
<img width="928" alt="image" src="https://user-images.githubusercontent.com/96849432/214778751-ab6dc58c-fd96-41a8-91a5-383e6bc8b578.png">
<img width="411" alt="image" src="https://user-images.githubusercontent.com/96849432/214778923-2d225db0-1872-4465-9c4a-22973b18e317.png">
Can I some directions what I am supposed to do from here?
