### ISSUE TITLE
lab 5.1 test case 3

### ISSUE THREAD

**Issue by yuzujy** [nus-cs2030/2223-s2#400]
Hi somehow my serving time is wrong? However, I dont get it because its the same code as in lab 3 for the getservicetime which passed all the test cases then?
<img width="238" alt="image" src="https://user-images.githubusercontent.com/122694072/225250264-afd4244a-5319-4b3e-a4b9-987d01937ae6.png">

**Comment by yugan01** [comment]
Hi! Perhaps you can check if service time is only gotten in the nextEvent method of your serve class and not anywhere else
