### ISSUE TITLE
Error with Maybe.java isEmpty() Exercise 4

### ISSUE THREAD

**Issue by JYeoZS** [nus-cs2030/2223-s2#401]
Hi,

Mind if clarify if there is a bug in the codecrunch version of Exercise 4 isEmpty() method?

The method currently returns this.value != null....

![Screenshot 2023-03-15 at 8 04 44 PM](https://user-images.githubusercontent.com/122290983/225304404-5bd24c66-d486-4e1c-9c92-ee4dcd78a33d.png)

Thanks. 👍

**Comment by trwstin** [comment]
haha i changed it to == as well

**Comment by Lofthesaver** [comment]
Hi, that should be a bug, you can just change it to ==

**Comment by Yew-Wei** [comment]
Yup managed to pass the testcases after changing the isEmpty method to == :)

**Comment by JYeoZS** [comment]
lol, yeah sounds about right with ==....
