### ISSUE TITLE
Lab 05 test 9_03

### ISSUE THREAD

**Issue by iwillnotcry** [nus-cs2030/2223-s2#402]
Hii I keep getting this issue for test case 9_03 and I don't understand what went wrong with my code. What I did was update the server's next available timing in my Done event, which worked ok in the public test cases but I can't really pinpoint what's not working here. Anyone has an idea? Much appreciated tqtq

<img width="468" alt="Screenshot 2023-03-15 at 8 36 22 PM" src="https://user-images.githubusercontent.com/124991772/225310598-52f4199b-eb1c-4187-86c6-bc5636f8cff1.png">

**Comment by 0liverkong** [comment]
when deciding the queue to join does it look at the first non empty queue? or are there checks made to see which server is free?

**Comment by iwillnotcry** [comment]
> when deciding the queue to join does it look at the first non empty queue? or are there checks made to see which server is free?

In my arrive event it checks to see if the servers are free first, then loops through their queues in order and joins the first one with a slot. Kind of like lab 3?

**Comment by 0liverkong** [comment]
high chance the error source is there - if you can split your code into even simpler usable functions the bug might start to show itself. check if resting times are correctly updated and that the customer sees the latest info of the server list as well

**Comment by Ramanenbh** [comment]
@iwillnotcry i also got the exact same issue as you

**Comment by iwillnotcry** [comment]
> @iwillnotcry i also got the exact same issue as you

Did you figure out why?

**Comment by Ramanenbh** [comment]
it is likely due to somewhere the shop or servers not being updated correctly, i tried to make some edits then encountered a time limit exceeded. Now I am redoing my entire implementation :(

**Comment by ghost1nthemachine** [comment]
hi have u implemented your self check counters in this code? like the implementation for 5.2? 

i actually faced this issue only after i added the 5.2 implementation for self counters. iirc for 5.2 I had changed the way i added customers to the queue in my arrive event and it caused this error. perhaps you could triple check that part of your code. to fix it, I changed how i added custs by delegating the "work" to different methods. for example. i use one method to update the serverlist, and another method to retrieve a new server.

**Comment by Ramanenbh** [comment]
@iwillnotcry how did u manage to fix it?

**Comment by iwillnotcry** [comment]
> @iwillnotcry how did u manage to fix it?

Oh I figured out I actually put in the wrong list of updated servers in my Done event due to a typo LOL but my friend really helped by giving me this test case to run which you can try: 

<img width="133" alt="Screenshot 2023-03-17 at 10 06 29 AM" src="https://user-images.githubusercontent.com/124991772/225793659-d42d7697-8630-4b65-a616-54cada97b822.png">

^This test case has 0 restTime, but the problem I had here was that customer 8 will still wait at server 1 even though server 1's queues were already at maximum. You'll probably get a similar error but u can use print statements to debug. Also u shld definitely compare ur lab 5 code to ur lab 3 code and like trace the changes you've made if you've passed lab 3 cos I realised my lab 3 code could work with the above test case. Atb!!
