### ISSUE TITLE
Test case 9_03

### ISSUE THREAD

**Issue by eesean** [nus-cs2030/2223-s2#404]
Hi all,

Not sure whether anyone has a similar issue for this test case, it's as if the arrive (or wait even) event for customer 10 is not meant to be captured for the actual output (left).

<img width="299" alt="Screenshot 2023-03-15 215707" src="https://user-images.githubusercontent.com/110977266/225330941-07ed33a9-0804-4c66-ae17-0b13368de889.png">

That aside, I tested my implementation against 3.in, factored in the rest time but it is as if customer 6 is served immediately even though the server 1 is supposed to rest (or the buffer time generated was 0.0, just my luck with the probability). Would like some advice as to how I could factor in the rest time, or what kind of edge cases should I consider?

<img width="165" alt="rest" src="https://user-images.githubusercontent.com/110977266/225331471-f34ad403-5a3f-43f3-8e97-b8129ab51f6b.png">

**Comment by trwstin** [comment]
which part of the process are you calling getresttime

**Comment by eesean** [comment]
For my case I call getresttime if the head event in the queue of events is a Done event, during which I update the corresponding server's next service time to factor in the rest time.

**Comment by hhuilingg** [comment]
i faced similar issue previously as i did not take into account that my customer queue will need to be updated including the server rest time. so what i did was to check that the customer will only be served when the clock time is less than or equal to the server next available time. (this is based on my implementation, i'm not if this will works for u) hope it helps!

**Comment by trwstin** [comment]
> For my case I call getresttime if the head event in the queue of events is a Done event, during which I update the corresponding server's next service time to factor in the rest time.

In Done, did you remember to update ur serverlist with the restTime added to the server's current finishTime?

**Comment by trwstin** [comment]
> For my case I call getresttime if the head event in the queue of events is a Done event, during which I update the corresponding server's next service time to factor in the rest time.

sounds about right... have you tried adding some System.out.println's to check if they are actually being updated with the restTime factored in?

e.g. in your simulator class you can print out Server 1's next service Time, then take note of the timings around the 4.053-5.053 area

**Comment by glenn2030** [comment]
Between wait and Serve, you need a way to make sure that when it serves, it gets the most updated server done time including the waiting time! The error is probably cause it serves before the previous customer is done, hence the timing you get is wrong.

**Comment by 12thfret** [comment]
Hi, i too encountered this problem. My issue was not considering the customer queue length. In my previous implementation, if qMax was 2, i would check for availability in the queue by using queue.size() <= qMax. There is an equality sign since if the first customer in the queue is being served, the queue can still accommodate 2 other people. Now however, given the case that the first customer in the queue might not necessarily be served (if the server is resting), i had to change my conditional statements when checking for availability. Not sure if i completely sidetracked but hope this helps abit.

**Comment by easypzlemonsqueezy** [comment]
hi! can i ask how you managed to resolve customers 10 and 11 getting served at the same time? i'm having the same issue

**Comment by eesean** [comment]
Hi! So during my wait event when I am about to serve the customer at the head of the queue, I check for two things:

1. The corresponding server is not serving anyone
2. The server is not resting

Only based on these 2 criterias do I execute the method for next event (and remove the front customer from the waiting queue); If both criterion are not met, I add the event back into the queue.

In both scenarios I take into account the waiting time because I update the time stamp for the polled event based on the corresponding server's next available service time. Hope this helps!
