### ISSUE TITLE
Lab 5 Multiple Output detected on CodeCrunch

### ISSUE THREAD

**Issue by trippingovrair** [nus-cs2030/2223-s2#406]
hi, i am not sure why i keep running into this Multiple Output detected problem on CodeCrunch as i did not have any print statements. thanks

<img width="1489" alt="Screenshot 2023-03-16 at 12 28 58 AM" src="https://user-images.githubusercontent.com/124991845/225377534-67cc4302-7ab9-41ed-97f7-263a28790d39.png">

**Comment by briannoelkesuma** [comment]
first, check clearly if you have any print statements in any method/class and check every single one of them.
second, if there really isn't, you can check if u are returning two different strings instead of concatenating one single string variable.
hope this helps!

**Comment by glenn2030** [comment]
Im pretty sure u tried to debug by printing out some stuff, do check if you removed them!

**Comment by nigel-tannn** [comment]
This usually means that you've accidentally printed out something that you shouldn't be printing, you could look through your code to see if there any extra stuff.

**Comment by ryantangmj** [comment]
You probably have a print/println somewhere!

**Comment by tallkoh** [comment]
just search on vscode if u have any other print statement

**Comment by gene2345** [comment]
probably have a system.out.println statement somewhere

**Comment by Fastumkj** [comment]
faced similar error, usually it's the println/print statements.

**Comment by markychamp** [comment]
faced the same error too! had a println statement hidden somewhere
