### ISSUE TITLE
Lab 5 Test Case 9_11

### ISSUE THREAD

**Issue by briannoelkesuma** [nus-cs2030/2223-s2#407]
# Summary

Not sure why I am getting **time limited exceeded error**. I don't have nested for loops in my code. Has anyone faced this issue? 

## Screenshots
<img width="406" alt="Screenshot 2023-03-16 at 12 56 49 AM" src="https://user-images.githubusercontent.com/110296183/225383801-7f019920-7366-450e-9b2c-8bf2df2e7457.png">

**Comment by 0liverkong** [comment]
your function that removes a customer from its queue might not work. use print statements to deebug

**Comment by Lofthesaver** [comment]
Hi, it may be that your priority queue is infinitely long (i.e., it is never empty), you can print your PQ to debug and check that all your events end somewhere (i.e., your Leave and Done Events are not added back into the PQ)

**Comment by Aron113** [comment]
check that you are passing on the most free self-checkout server and its free time

**Comment by Yihao2001** [comment]
how u check for whether a customer in queue can be served might not be working

**Comment by briannoelkesuma** [comment]
thanks

**Comment by briannoelkesuma** [comment]
thanks all! for those facing the issue, i solved this problem by changing the condition in my wait event to just checking if the Cust Arr Time > Server End Time. hope it helps!
