### ISSUE TITLE
Lab 5 Test Case 9_14

### ISSUE THREAD

**Issue by EpicSpirito** [nus-cs2030/2223-s2#409]
## Description:

Hi guys, anyone knows why I fail this test case?

## Screenshots

![Screenshot 2023-03-16 015526](https://user-images.githubusercontent.com/92631089/225400497-112f520b-b434-4ff2-ab2e-984f338bf72b.png)

**Comment by trwstin** [comment]
Seems like something is wrong with how you call getRestTime?

In the specific case above, it is being invoked one step early - resulting in Server 1 getting Server 2's rest time (rest for 0.720s)

So instead of:
Server 1 rest 1.604s (6.305->7.909)
Server 2 rest 0.720s (7.583->8.303)

You have:
Server 1 rest 0.720s (6.306->7.026)
Server 2 rest 0s (7.583->7.583)

**Comment by Yihao2001** [comment]
might want to check if accidentally took in rest time as a double instead of as a supplier which could have caused your rest time to be a constant rather than something that changes

**Comment by EpicSpirito** [comment]
> Seems like something is wrong with how you call getRestTime?
> 
> In the specific case above, it is being invoked one step early - resulting in Server 1 getting Server 2's rest time (rest for 0.720s)
> 
> So instead of: Server 1 rest 1.604s (6.305->7.909) Server 2 rest 0.720s (7.583->8.303)
> 
> You have: Server 1 rest 0.720s (6.306->7.026) Server 2 rest 0s (7.583->7.583)

Strange that getRestTime works for the previous part, but fails for the last few lines

**Comment by EpicSpirito** [comment]
> might want to check if accidentally took in rest time as a double instead of as a supplier which could have caused your rest time to be a constant rather than something that changes

I set rest time as a supplier in Server Class, then I created a method in Serve Event that computes the eventDoneTime. That method is only called once in ServeEvent, which is saved as a double and pass to ServeDone Event as EventDoneTime and used to update that Server's available time.
