### ISSUE TITLE
Exercise 4 - Level 4

### ISSUE THREAD

**Issue by subhadhra-m** [nus-cs2030/2223-s2#410]
<img width="494" alt="Screenshot 2023-03-16 at 12 26 38 PM" src="https://user-images.githubusercontent.com/125443673/225514511-40c2f65f-984e-49a2-8ac6-05157c8532d4.png">

How may I typecast maybeOther to a Maybe<T> object when writing the or method 
Using value -> T(value) gives me unchecked or unsafe operations error

**Comment by JYeoZS** [comment]
Hi, maybe should replace code with pseudo code.

Anyways, I did it without a map function.

Consider there are 2 "? extends" you need, one for the Maybe and one for the value inside Maybe.

Tripped me off also, haizzz....

Cheers.

**Comment by 0liverkong** [comment]
it shouldnt be maybe<?> for one, since your supplier is one that provides an object of type T.

**Comment by granolaluvr69** [comment]
Your supplier should be of type Supplier<? extends Maybe<? extends T>>.

**Comment by subhadhra-m** [comment]
Thanks guys, managed to solve it!
