### ISSUE TITLE
Lab 5.2 self checkout queue

### ISSUE THREAD

**Issue by j0205m** [nus-cs2030/2223-s2#412]
hi, i understand that all self checkouts are managed by one queue but i'm struggling to visualise a possible implementation of this without having a queue for each individual self checkout counters. i was thinking along the line of looping through the list of counters and updating with the same queue but this method seems inefficient. any hints on how i can go about doing this? any help is appreciated!

**Comment by weitatftw** [comment]
you could create a self checkout counter manager class that stores a list of all of the self checkout counters and the manager has a single queue attribute that is shared among all counters. so when you serve a customer you can simply dequeue the first person in the common queue of the manager.

**Comment by 0liverkong** [comment]
for me i did an ugly solution. if the index cant be found in the list of queues then it is a self checkout, return the last queue.

**Comment by granolaluvr69** [comment]
You can just take the queue of the first selfcheckout into account (i.e. iterate to server number k + 1 in when doing queue assignment.)

**Comment by timothysashimi** [comment]
you can treat all the self checkouts as one giant server that has the queue of customers and check the queue. can have methods that check and get the earliest available server

**Comment by Aron113** [comment]
you could update all the queues for self checkout servers (essentially treating them as one queue)

**Comment by glenn2030** [comment]
You are suppouse to have a queue for every one of your selfcheck out, but whenever u update 1, u update all. This can be done through a method and u juz call that method whenever you touch your selfcheckout queue.

**Comment by xyxyiuxy** [comment]
what I did is I put the counters at the end of my server list then loop through this list. Then when I need to update the queue for a specific queue, I would loop through the serverlist (the part only contains self checks) to update the queue one by one for each counter since they share the same queue.

**Comment by j0205m** [comment]
thank u everyone!
