### ISSUE TITLE
Exercise 4 equals() method instanceof

### ISSUE THREAD

**Issue by JYeoZS** [nus-cs2030/2223-s2#415]
Hi, did anyone face this problem of using instance of in equals() method but rejected by codecrunch, as canvas notes make use of instance of also.

Did you go about modifying code to remove instanceof? Much thanks. 👍 

![IMG_20230317_000103](https://user-images.githubusercontent.com/122290983/225679892-fb9887db-027c-4a81-923a-e3bec05dec15.jpg)

**Comment by 0liverkong** [comment]
do you have the \@Override decorator?  maybe also check if the function is public boolean equals(Object). instance of should not be used in any other method at all.

**Comment by JYeoZS** [comment]
Ah yes spot on. Missed out an @Override decorator.... haiz...

Much thanks, cheers. ;)
