### ISSUE TITLE
Input Discrepencies

### ISSUE THREAD

**Issue by niclee1219** [nus-cs2030/2223-s2#418]
# Summary

Passed initial 4 test cases, not sure where I should look at for this error

## Description:

Seems like its due to my serve time, but I'm not sure why its only affecting the last few outputs

## Screenshots
<img width="461" alt="Screenshot 2023-03-17 at 12 46 33 PM" src="https://user-images.githubusercontent.com/20497341/225814967-f06e5988-0917-4e4a-9d4c-b61f7a453e4e.png">

**Comment by easypzlemonsqueezy** [comment]
hi!  your serverlist is not getting updated with the correct timings, you might wanna check how you implemented that, hope this helps

**Comment by ayevxn** [comment]
Likely there is an issue with the updating because Server 2 should be done serving 8 at 11.636 but your output shows that it is done at 9.095.

**Comment by codecode24** [comment]
I think your customer's service time might be getting added to the wrong place, because according to your output,  2 serves 10 at 9.095, which is before 2 starts waiting at 9.160

**Comment by littlemidget3** [comment]
yup ensure that you are calling the service time in the right event.
also check that in each event, you are updating the server in your server list so that the next available time is reflected correctly

**Comment by niclee1219** [comment]
hi all @littlemidget3 @codecode24 @ayevxn thanks for all the input! 

all the suggestions are valid, but I solved it using an interim wait class.

@those still stuck with lab 3, here is a possible solution that might help:

-  Implement a interim wait class to be updated to the server's next unavailable until time


# Code Output Example with 1.in



![2023-03-19 14 18 18](https://user-images.githubusercontent.com/20497341/226157320-2e5e321d-629d-4bf8-baf4-a87b2e447c6a.jpg)


## Explanation

for interim wait, itll be called directly when waits getnext event is called 

so 0.6 interim will be called

after that since its next in pq, itll be pollled. since server 1 still busy, ill generate a new interimwait at the next time server is avail, (1.5 interim wait)

then 1.5 interim wait will be polled aft 1 is done serving 1. since at 1.5 when i call interim’s get next event, server is done serving so i can call serve for 2. 

if server 1 is still serving, then itll call the next avail timing


Hope this helps all!
