### ISSUE TITLE
Lab 5.2 testcase 9_11 Codecrunch and local inconsistent output

### ISSUE THREAD

**Issue by s-peiran** [nus-cs2030/2223-s2#420]
Hi can anyone advise what could be the error and how I might proceed to troubleshoot it? Got no clue going forward if my own test case does not give the same problem as codecrunch.

Code Crunch:
<img width="445" alt="image" src="https://user-images.githubusercontent.com/96849432/225866024-c5257fa8-fee0-41c0-9221-284bc0148c2c.png">
<img width="438" alt="image" src="https://user-images.githubusercontent.com/96849432/225866156-b5888749-9ff8-466c-9208-39537dad5004.png">

Local  Machine:
<img width="434" alt="image" src="https://user-images.githubusercontent.com/96849432/225865873-13c7890e-bd5b-4820-aea9-1074718abf80.png">
<img width="318" alt="image" src="https://user-images.githubusercontent.com/96849432/225866271-fb91608b-79cd-4e55-a69e-91a402ed52d5.png">

TestCase:
<img width="112" alt="image" src="https://user-images.githubusercontent.com/96849432/225866870-86621256-bc78-45e1-bb07-c4f57177bc2b.png">

Thanks!

**Comment by 0liverkong** [comment]
are the probabilities the same? it might not be 2 2 3 0.5 leh

i recommend drawing out the simulation using papers and symbols. follow your code output and see where is the first point of failure.

**Comment by trwstin** [comment]
Are you properly updating the next available time for self-checkouts? Your self-checkout 4 was able to serve customer 5 while in the midst of serving customer 4

**Comment by s-peiran** [comment]
Thanks all for your input. Turns out the issue is at my server's create new server method on determining whether the "next available time" should be updated or not, was erroneous. i.e. wait event or server even is generated.
