### ISSUE TITLE
Use of restricted api detected

### ISSUE THREAD

**Issue by granolaluvr69** [nus-cs2030/2223-s2#426]
# Summary
My submission got rejected by codecrunch even though I didn't import java.util.Set in any of my classes other than the provided ImmutableSet class...
Removing ImmutableSet.java from my submission still doesn't work.

## Screenshots
<img width="359" alt="Screenshot 2023-03-17 at 11 46 03 PM" src="https://user-images.githubusercontent.com/120318851/225954978-0f044c01-6e9a-4d37-a77a-f6a6a4b16859.png">

**Comment by granolaluvr69** [comment]
<img width="406" alt="Screenshot 2023-03-18 at 12 55 58 AM" src="https://user-images.githubusercontent.com/120318851/225969473-d74ea744-1627-4162-abbd-c18f9fc361b0.png">
Ok I managed to resolve it by deleting the highlighted part, apparently its a method that the Set api has.

**Comment by leezhanpeng** [comment]
Thank you so much! Got stuck on this for so long because of that too.
