### ISSUE TITLE
Lab 6 Level 3 Clarifications - Map or Immutable Map

### ISSUE THREAD

**Issue by JYeoZS** [nus-cs2030/2223-s2#428]
Hi, am just curious if KeyableMap is supposed to take in a ImmutableMap or Map<String,V> as mentioned in question, as Student and Module all both use ImmutableMaps? Just curious if reading question wrongly.

How does it affect if we use Map though... 

If anyone has gone beyond level 3 please advice. Much thanks. :)

<img width="1120" alt="Screenshot 2023-03-18 at 11 15 52 AM" src="https://user-images.githubusercontent.com/122290983/226081738-2061e11f-5374-41a5-a208-32ae21e1dda6.png">

**Comment by granolaluvr69** [comment]
KeyableMap takes in a key (mod code / student name / roster name) and an ImmutableMap from the key to the thing contained in the map (assessments / mods / students respectively). You're supposed to delegate the implementation of these three classes to the KeyableMap class. Good luck!

**Comment by JYeoZS** [comment]
Hi, please correct if wrong.

So level 3 is saying KeyableMap should have in its constructor:
1. String Key
2. Map<String, V> map

Where V refers to the ImmutableMap in Student, Module and Grade in Assessment?

**Comment by granolaluvr69** [comment]
Personally, I went with the second because ImmutableMap also wraps around a Map, so I saw no point in wrapping map directly using keyablemap.

**Comment by taugwa** [comment]
i used the 2nd approach too 👍🏻 should work

**Comment by JYeoZS** [comment]
Ok yeah reread the question a little vague. Constructor should have immutableMap.

The map is referring to usage in methods, not constructor. Would be nice if the question is clearer though...
