### ISSUE TITLE
Lab 06: Restricted API

### ISSUE THREAD

**Issue by lsy8117** [nus-cs2030/2223-s2#432]
# Summary

Use of Restricted API detected

## Description:

I thought in the question description they ask us to use entrySet() to iterate through the ImmutableMap, but CodeCrunch said cannot use Set (thus cannot use entrySet())
I also tried using ImmutableMap<V>.values() but then they said cannot use Collection. 
So how am I supposed to print out all items in my ImmutableMap?

## Screenshots
![Screenshot 2023-03-18 at 3 18 55 PM](https://user-images.githubusercontent.com/123756364/226091302-91bd5e14-4fd8-407e-954b-321774cc71c3.png)
![Screenshot 2023-03-18 at 3 19 13 PM](https://user-images.githubusercontent.com/123756364/226091313-81729d6d-ff95-466a-bd70-c63679fa6672.png)

**Comment by granolaluvr69** [comment]
Hi, you can refer to this [link](https://github.com/nus-cs2030/2223-s2/issues/426) for more details about how I managed to resolve this issue, hope it helps!

**Comment by lsy8117** [comment]
> Hi, you can refer to this [link](https://github.com/nus-cs2030/2223-s2/issues/426) for more details about how I managed to resolve this issue, hope it helps!

oh yea thanks!! I didn't see ur post hahaha this helps a lot:))
