### ISSUE TITLE
Infinite Loop when Queue/Wait event is being called for Self Checkout Counters

### ISSUE THREAD

**Issue by pehzerong** [nus-cs2030/2223-s2#435]
Can't seem to debug this problem. My approach is to check if the Queue event's time information is less than the Main Self Checkout Counter's List of self checkout counters  earliest end time. 

If it is less, serve with the self checkout counter.

 If not, return another Queue event with the earliest end time and the Main Self Checkout Counter.
 
Not sure if this approach is right an would appreciate any input. Thanks!

**Comment by prisciliapangg** [comment]
I assume you checked if your server is a self checkout counter in the queueevent, if so: check if the customer polled is the first customer in the self checkout counter's queue. if it isn't, queueevent should be returned. else, check all the selfcheckoutcounters. if any self checkout counters are free, return the serveevent. (while looping through this, I would also find the selfcheckoutcounter with the earliest timefree, and update the queueevent (if it is returned) with this earliest timefree). hope that helps!

**Comment by pehzerong** [comment]
Thanks for helping! Turns out, the issue was with my book keeping.
