### ISSUE TITLE
Lab 5.1 Time Limit Exceeded for Test Case 9_03

### ISSUE THREAD

**Issue by tinghwei** [nus-cs2030/2223-s2#437]
I am currently generating an infinite loop of intermediate wait events and I can't find where my code went wrong. I have referenced the most updated server and will only return another intermediate wait event when customer is not at the front of the queue or server is not free. 
Does anyone know how to solve this? 

![image](https://user-images.githubusercontent.com/122725424/226094203-c948adbc-7949-4d91-93ff-f9c7fb2a4e16.png)

**Comment by jorwong** [comment]
It is hard to pinpoint what went wrong without seeing your implementations. However, I faced the same issue and it was occurring in the intermediate wait event for mine as the first customer in the queue is not matching the customer in the event causing it to loop infinitely

**Comment by tinghwei** [comment]
omg tqsm, i managed to solve the error!! my mistake lies in my queue of customers as well
