### ISSUE TITLE
Exercise #4 5_1 Test Case 7 

### ISSUE THREAD

**Issue by briannoelkesuma** [nus-cs2030/2223-s2#439]
Does anyone know what the issue is here? Did my flatmap method cause me to fail this test case? 
<img width="492" alt="Screenshot 2023-03-18 at 5 04 27 PM" src="https://user-images.githubusercontent.com/110296183/226096038-f42c7c76-30ec-40cb-aaa0-a4a027fd389d.png">

**Comment by fy17ohhh** [comment]
what does your or() return? Maybe<T> or Maybe<? extends T>? should be the former

**Comment by briannoelkesuma** [comment]
> what does your or() return? Maybe or Maybe<? extends T> should be the former
how did you know it was the former though?

**Comment by granolaluvr69** [comment]
> > what does your or() return? Maybe or Maybe<? extends T> should be the former
> 
> how did you know it was the former though?

Other than the flatmap method, only the or method returns a maybe of type <? extends T>.

**Comment by jiarui22** [comment]
I solved the problem by using the method mentioned in #424
