### ISSUE TITLE
Possible design violation

### ISSUE THREAD

**Issue by kmkmkmkmkmkmmm** [nus-cs2030/2223-s2#440]
Hi! has anyone gotten such a message for their labs before? if so, what did you do to solve it? thanks!<img width="645" alt="Screenshot 2023-03-18 at 17 12 31" src="https://user-images.githubusercontent.com/122666164/226096601-0f3838a4-6544-43e8-962b-21a2b25a6877.png">

**Comment by trwstin** [comment]
check with my tutor

**Comment by chocococ** [comment]
i had that error previously and it was because i submitted the Main.java file, it was okay aft i resubmitted without the Main.java file

**Comment by tallkoh** [comment]
it might be because you have too many defined constants. keep it to max 2 constants
