### ISSUE TITLE
Checkstyle Error - Main.java

### ISSUE THREAD

**Issue by kayeugenia** [nus-cs2030/2223-s2#442]
# Summary
I encountered several errors that I have never seen before for my Main class. Tried googling but could not find any answer. If anyone has faced the same issue, could you please share how you manage to solve it.

## Screenshots
![photo_2023-03-18 18 18 56](https://user-images.githubusercontent.com/122983473/226099654-4beca473-602d-431d-830c-a9fdbb8e683a.jpeg)

**Comment by granolaluvr69** [comment]
I'm not sure how your main class looks right now, but I think following this format for your main class might help.
<img width="617" alt="Screenshot 2023-03-18 at 6 23 38 PM" src="https://user-images.githubusercontent.com/120318851/226099832-a7cba267-d776-44ac-91ba-6bfeaf0fb8c5.png">

**Comment by kayeugenia** [comment]
@granolaluvr69 hi! yes, I followed that, but my implementation has two while loops and a counter (so that i only do roster.add(student, module, assignment, grade) for the first 12 records). The output I received is also correct, so I am not sure what went wrong :(

but thank you very much!

**Comment by Dayn-Ang** [comment]
I believe the tab character error stems from having tab spaces in front of the lines stated (likely due to the tab spaces being present on the google slides). Just backspace the spaces in front and re-indent.

For the Javadoc comment error, I think you have to comment above the void main method as such

eg.
     /**
     * (write comment or documentation here)
     **/

**Comment by granolaluvr69** [comment]
eh sike just remove public from the public class Main line and it should work fine

**Comment by kayeugenia** [comment]
@granolaluvr69 @Dayn-Ang thanku!!
