### ISSUE TITLE
5.2 Self-Checkout Implementation

### ISSUE THREAD

**Issue by kayeugenia** [nus-cs2030/2223-s2#444]
## Description:
Hi! I am just curious to know how others implement their self-checkout. The reason is because I feel like I need to change a lot of stuff from lab 5.1 given that now there are 2 types of servers. And I need to extend my original Server and SelfCheckout to the "new Interface" ServerImpl. 
Not sure if there is any better way?

**Comment by trwstin** [comment]
I did it the way you mentioned, just that I called the interface Server and renamed Server to HumanServer, just so there would be less things to rename :')

**Comment by granolaluvr69** [comment]
You could just make SelfCheckout extend Server and set it's rest time to 0.0 and change the tostring accordingly. Checking if the server is a selfcheckout would just be a matter of comparing the number of servers to the server number.

**Comment by taugwa** [comment]
> I did it the way you mentioned, just that I called the interface Server and renamed Server to HumanServer, so there would be less things to rename :')

i did the same! then theres less to change

**Comment by user1914** [comment]
> 

how did your constructor for SelfCheckout look like for this?

**Comment by gene2345** [comment]
you can just use self checkout extends server and override some methods accordingly so that self checkout behaves differently from a normal server

**Comment by Danpng01** [comment]
Yup like how you mentioned it, I had a Humanserver (which was originally my server class) and a selfcheckout (which was a copy and paste of my original server, just with a different toString and getresttime).

**Comment by kayeugenia** [comment]
okay thanks yall!
