### ISSUE TITLE
Lab 5.1 Main.java interpretation

### ISSUE THREAD

**Issue by Fliprun** [nus-cs2030/2223-s2#447]
Hi, I'm having trouble interpreting the Main.java file for Lab 5.1. While implementing a Rest event, I noticed that the rest probability isn't used when initializing Simulator. Instead, it seems to be integrated into the rest time supplier. Does this mean that getting the time from the restTimes supplier would factor in the probability that the server will rest? Or in other words, calling restTimes.get() will return a rest time if the server passes the probability check and will return 0.0 if not? Thank you very much in advance!

**Comment by taugwa** [comment]
the getting should factor in the probability of the server resting

**Comment by leonardwx** [comment]
Supplier<Double> rest factors the probability of server resting, which generate a random rest time

**Comment by Fliprun** [comment]
Alright, thanks alot.

**Comment by jiangen16** [comment]
yup i think you can think of it that way. Factoring in the probability of whether the server will rest, then comparing with a randomly generated number by Random RNG_REST. If RNG_REST.nextDouble() < probRest (given by test case), it will generate a random rest time

**Comment by briannoelkesuma** [comment]
yes, u just need to pass in the restTimes which is a supplier double from simulator and invoke it in one place, to facilitate the on-demand supply of restTimes. (i.e. same as that for serviceTimes)

**Comment by Danpng01** [comment]
The implementation of rest time should be the same as service time! You can just copy one the relevant lines of code
