### ISSUE TITLE
When to call the restTime supplier?

### ISSUE THREAD

**Issue by piglisa** [nus-cs2030/2223-s2#449]
Hi I am debugging my code and like some other people, I have trouble passing test case 9_03. I have carefully read my code and concluded that the problem wasn't about updating the server's next available time. 

I suspect that I called the rest-time supplier at the wrong place. Currently, I call the restTime supplier in the constructor of my Done event, so whenever I have a Serve event, my nextEvent() method will create a Done event and call the value from there. I guess I have to call it later in the Done event instead.

Has anyone faced the same problem or can I know where you are putting the restTime supplier?

<img width="626" alt="Screenshot 2023-03-19 at 12 06 23 AM" src="https://user-images.githubusercontent.com/65667672/226118563-54f3de03-ee77-4f47-aa83-26b434d68743.png">

**Comment by prisciliapangg** [comment]
Hello, I called my getRestTime() in my DoneEvent and did not face the error (however, I placed it within the getNextEvent() method itself, instead of the constructor). I think the error here is that you did not update the server's freeTime to include restTime in your updatedServerList for the next event. Hope that helps!

**Comment by nigel-tannn** [comment]
I personally have an additional Event called Rest (which is called after Done).  This is where I call my getRestTime().  I think this really helps to segregate the responsibilities of each Event class.

**Comment by granolaluvr69** [comment]
You should apply the same logic you did when you implemented the supplier of service times back in lab 3. If you called serviceTime.get() in serve in lab 3, you should try to implement something similar in this lab. The same constraints apply, which is the on demand supply of rest times and also the limitation that you can only call the method once per customer that is served by a human server.

**Comment by piglisa** [comment]
Thanks everyone for the help. It was indeed the problem of where to put the supplier.get() for the restTImes. I changed the position of it to the nextEvent() of my Done class which creates a rest event. And it worked. Hope it will help others who are facing the same issue.
