### ISSUE TITLE
Ex 4 Test Case 5 (Public Test Case)

### ISSUE THREAD

**Issue by prisciliapangg** [nus-cs2030/2223-s2#450]
<img width="1019" alt="Screenshot 2023-03-19 at 12 57 52 AM" src="https://user-images.githubusercontent.com/123915785/226121549-3a8c3bf5-c2f9-4cb2-b39c-a3463d5162e1.png">
 
Hi! Did anyone face the same error? If so, may I get some tips on what I should do to solve this issue? Thank you!

**Comment by shakerfries** [comment]
i think you cannot assume that supplier.get() will give you a maybe<T> type. you can maybe try unwrapping ur supplier.get() value? 
i did smth like: 
Maybe<? extends T> temp = other.get() 
then i call the maybe.of method() aftwards

**Comment by prisciliapangg** [comment]
@tallkoh @shakerfries thanks for the help!! i got it!
