### ISSUE TITLE
Wrong wait time in lab5.1

### ISSUE THREAD

**Issue by edwinhrj** [nus-cs2030/2223-s2#451]
# Summary

hello, im facing problems trying to correctly track down the wait times of a customer waiting at a server.
 
what I'm currently doing is updating a waitTime variable that initially starts at 0. then, as each event is polled, I subtract the eventTime of the event (if its a WaitEvent) from waitTime, while I add the eventTime of the event (if it a ServeEvent or a DoneEvent) to waitTime. But its not working and i don't know why

is there any other method I can try to correctly track the customers' wait times? thanks guyss

## Description:

Clarifications or details with respect to the issue you are facing

## Screenshots

<img width="547" alt="Screenshot 2023-03-19 at 2 59 36 AM" src="https://user-images.githubusercontent.com/122248645/226130501-5c401a44-1d8a-4660-a8f6-7332707fefe8.png">

**Comment by alvintjw** [comment]
You can try adding an abstract method called getTotalWaitingTime that takes in totalWaitingTime and return itself. then as you are looping thru your PQ of events, call the event.getTotalWaitingTime and update to a variable. Essentially, you will be getting the waitingTime of all the events that occured. Then you just need to override this method at the serve event where instead of just returning itself. you return itself + the waitingtime of the customer.

**Comment by tinghwei** [comment]
I have an abstract method waitTime() in Event which will return 0. However, I override this method in Serve event where I instead return a value obtained from subtracting customer's arrival time from the time of Serve event. Then in my simulator, as I loop through the events I will call waitTime() and add it to a variable totalWaitTime. Outside the loop is when I will divide the totalWaitTime by the number of customers served. Hope this helps!

**Comment by jacoblimjy** [comment]
Try letting all events return a wait time of 0 except for serve

**Comment by taugwa** [comment]
> I have an abstract method waitTime() in Event which will return 0. However, I override this method in Serve event where I instead return a value obtained from subtracting customer's arrival time from the time of Serve event. Then in my simulator, as I loop through the events I will call waitTime() and add it to a variable totalWaitTime. Outside the loop is when I will divide the totalWaitTime by the number of customers served. Hope this helps!

this is what i did too!

**Comment by dlyxxx** [comment]
an alternative would be to keep track of your wait time in your server? i initialised the server with total wait time of 0, then each time a server serves a customer, the wait time is added. After all the PQ events is run, i will iterate through the servers and sum the wait times
