### ISSUE TITLE
Lab 6 Level 6

### ISSUE THREAD

**Issue by syafiq9326** [nus-cs2030/2223-s2#452]
# Summary

Additional steps for the Main class?

## Description:

Hi, does Main.java have to implement any new methods?

Currently, my Main is just calling roster.add(..) to create my roster. I then use roster.getGrade(...) to check if the inputs are in the test cases.

However, I realised that my test cases are replacing each other in the roster despite having the same module code although I have already accounted for that in level 5. I am also able to clear all the cases in code crunch except level 6, hence I am not sure where it went wrong (Did I not account for something else?).

Would appreciate any help, thanks!

## Code Snippets
![image](https://user-images.githubusercontent.com/50677984/226134065-a297a236-95e2-487f-bef5-c584b933ffaa.png)

## Screenshots

![image](https://user-images.githubusercontent.com/50677984/226134135-f2df63c0-a182-432f-b7cc-4316d1a7e411.png)

**Comment by JYeoZS** [comment]
Same problem, did you compare the ..toStrings() using == sign? Try using .equals() instead.

i.e.  if (___getKey().equals(___.getKey()) {...

**Comment by Huanqing-Mao** [comment]
I think you can try to check whether it previously exists in the roster and return a value using orElse in Optional class for level5

**Comment by syafiq9326** [comment]
Okay managed to solve it with @JYeoZS way, thanks! And yup @Huanqing-Mao , I was already using an orElse previously, thanks!
