### ISSUE TITLE
Ex04 TestCase: 5_1

### ISSUE THREAD

**Issue by alvintjw** [nus-cs2030/2223-s2#453]
<img width="1113" alt="Screenshot 2023-03-19 at 4 58 13 AM" src="https://user-images.githubusercontent.com/65883895/226139765-069419ad-8783-4448-a7c7-b193a9f401db.png">

Anyone encountered this error before and know how to fix it?

**Comment by rayray39** [comment]
hi i am facing this error too, may i know how did you managed to fix it? Thank you

**Comment by alvintjw** [comment]
@rayray39 Basically the Or method is wrong. The return type should be Maybe<T>  then in your method body, just do what you did for flatmap. You can look at issue 424 and 430 for extra clarification :))
