### ISSUE TITLE
Lab 6 Level 5 

### ISSUE THREAD

**Issue by sushimakerr** [nus-cs2030/2223-s2#456]
Hi, I understand that we are supposed to check from student to module to assessment if there is already an existing record in the Roster and only add to the record if it doesn't exist, but I'm not sure on how to go about checking through each student, module and assessment. does anyone have any ideas that they can share? thank you!

**Comment by wongjingwen** [comment]
You will need to check progressively(from student to  mod to assessment) if the record already exists in the roster. You could try using the orElse method in the Optional Class

**Comment by taugwa** [comment]
yep ^^ orElse helps to "unwrap" Optional<..> returned from .get(..), and if the Optional is empty it will then output wtv argument u put in orElse

**Comment by sushimakerr** [comment]
ahh okay got it, thanks! @taugwa @wongjingwen
