### ISSUE TITLE
Exercise 2: Failing Testcase 4?  Level 4 BigCruise Service Time

### ISSUE THREAD

**Issue by SimonSeeYongsheng** [nus-cs2030/2223-s2#46]
Hi guys, I would like to share a error that I made.

In the Codecrunch of Exercise 2 Level 4 it states:

BigcCruise: takes one minute to serve every 50 passengers

It should be "takes one minute to serve every 50 passengers (or part thereof)"

If you didn't include the "part thereof" in your code, you will be failing test case 4.

**Comment by e0959170** [comment]
by part thereof do you mean if  for example, there are 70 passengers we round up  70/50 to get 2 minutes?

**Comment by leezhanpeng** [comment]
> by part thereof do you mean if for example, there are 70 passengers we round up 70/50 to get 2 minutes?

Yep that's right.

**Comment by Ramanenbh** [comment]
I wish I saw this a week ago :(

**Comment by lershuan** [comment]
I have already account for the part thereof, but I'm not too sure why im still failing the test case

**Comment by syafiq9326** [comment]
Thanks, this was really helpful! I was wondering why I kept failing the private cases for big cruise..., appreciate it!

**Comment by tjdbryan** [comment]
You could do something like `Math.ceil((double) x / y)` to force int x into a double, so that the division returns a double instead of an integer (which becomes floor division) - and then you round it up using ceil.
