### ISSUE TITLE
Lab 6 Use of Restricted API Detected

### ISSUE THREAD

**Issue by sushimakerr** [nus-cs2030/2223-s2#461]
<img width="294" alt="Screenshot 2023-03-19 at 4 14 24 PM" src="https://user-images.githubusercontent.com/124802316/226162364-8aeb2be7-c582-4e46-82ef-a62724de8f7a.png">

I had the above problems when submitting on codecrunch, does anyone have an idea of why the java.util.Set restriction is being detected?

**Comment by jacoblimjy** [comment]
you are using entrySet() from ImmutableMap

**Comment by littlemidget3** [comment]
yup, when youre using your for loop in map.Entry e : map, omit the portion behind with entrySet()

**Comment by sushimakerr** [comment]
@jacoblimjy @littlemidget3 ahh i see thanks for your help! got it resolved!

**Comment by hengbl** [comment]
You are not allowed to use .values() from ImmutableMap as well :-(

**Comment by gene2345** [comment]
you are not allowed to use .values() and .entryset() in lab6
