### ISSUE TITLE
Lab 6 Level 5

### ISSUE THREAD

**Issue by rayray39** [nus-cs2030/2223-s2#462]
Hi, i am quite lost as to how to check if student/module/assessment already exists inside the roster. I have seen some other threads saying that using orElse() helps, but i still dont understand. Any help is appreciated, thanks!

**Comment by omarsfs** [comment]
You can use optionals to see if student/module/assessment exists by using the isEmpty() method to check  
For example: 
Optional<Student> student = roster.get(studentname)
if (student.isEmpty()) {
... create new Student
}

something along these lines!

**Comment by territxl** [comment]
you can think of it in a way to progressively check from student to module and to assessment. Like in Python dictionary, we check from outer to inner of a nested dictionary via the various keys. Hope this helps!

**Comment by trwstin** [comment]
you will have a bunch of strings as arguments in the method. these strings serve as the 'key' for your 'key-value' pair in the map.

so if you call get(<string>) and something comes out, the 'key-value' pair exists and you continue getting. You start from student and end with assessment.

if at any point nothing comes out of the get, the orElse is triggered to create a new 'key'.

**Comment by rayray39** [comment]
but how do i know what type to assign to the new key? cos it could be an assessment, module or student right? and orElse only returns the same type of key that is absent

**Comment by trwstin** [comment]
> @trwstin but how do i know what type to assign to the new key? cos it could be an assessment, module or student right? and orElse only returns the same type of key that is absent

You will know because it must follow this hierarchy Roster -> Student -> Module -> Assessment

So when you call get, you are moving one level down

**Comment by rayray39** [comment]
> > @trwstin but how do i know what type to assign to the new key? cos it could be an assessment, module or student right? and orElse only returns the same type of key that is absent
> 
> You will know because it must follow this hierarchy Roster -> Student -> Module -> Assessment
> 
> So when you call get, you are moving one level down

so does this mean that i need to call orElse multiple times?
something like this:
student = this.get(student).orElse(new Student);
module = this.get(student).get(module).orElse(new Module);

**Comment by Huanqing-Mao** [comment]
> > > @trwstin but how do i know what type to assign to the new key? cos it could be an assessment, module or student right? and orElse only returns the same type of key that is absent
> > 
> > 
> > You will know because it must follow this hierarchy Roster -> Student -> Module -> Assessment
> > So when you call get, you are moving one level down
> 
> so does this mean that i need to call orElse multiple times? something like this: student = this.get(student).orElse(new Student); module = this.get(student).get(module).orElse(new Module);

yes! You gotta call it multiple times :)

**Comment by trwstin** [comment]
> so does this mean that i need to call orElse multiple times? something like this: student = this.get(student).orElse(new Student); module = this.get(student).get(module).orElse(new Module);

yep yep, but take note that for your module you should be using the student u created in the previous line, instead of getting again

**Comment by rayray39** [comment]
thanks guys! managed to get the right output
