### ISSUE TITLE
java.lang.Classloader

### ISSUE THREAD

**Issue by calvnleong** [nus-cs2030/2223-s2#463]
# Summary
I got an error 'Error:
|  incompatible types: java.lang.String cannot be converted to java.lang.ClassLoader
|  new Module("CS2040")'

## Description:
I tried running the test case 'new Module("CS2040")' but all i got was an error:
'Error:
|  incompatible types: java.lang.String cannot be converted to java.lang.ClassLoader
|  new Module("CS2040")'
I ensured that in Module class, Module takes in a String

## Code Snippets

Attach code snippets (if any)

## Screenshots
<img width="611" alt="image" src="https://user-images.githubusercontent.com/124434962/226163998-047a29ea-c019-4b0a-9e09-a1a6cd6f418c.png">

**Comment by shionhigashi** [comment]
it might be because the name of your String variable is module, which is the same as the class name, i think changing it to "mod" will help!

**Comment by jiangen16** [comment]
hi im experiencing this problem too! i also didnt name my variable as "module"

**Comment by shionhigashi** [comment]
hm you might wanna check the order where you input the classes like ImmutableMap.java into jshell

**Comment by calvnleong** [comment]
Ah icic, i got it, thanks!
