### ISSUE TITLE
error in test case 3 lab 3

### ISSUE THREAD

**Issue by kelleyhan25** [nus-cs2030/2223-s2#467]
hello! does anyone know what this issue might mean? my first two test cases pass fine, but when i get to the third one and beyond when more than one server is introduced, i get this error. thanks in advance! 
<img width="753" alt="Screenshot 2023-03-19 at 10 49 37 PM" src="https://user-images.githubusercontent.com/122245700/226183963-5024fe58-7543-48a1-a1c5-24e9569ef425.png">

**Comment by trickypepe** [comment]
The error occurred when you called a get(0) in an ImList of length 0. It looks like it happened in your wait event when you tried to update it? Maybe its your ImList storing your queue?

**Comment by kelleyhan25** [comment]
> The error occurred when you called a get(0) in an ImList of length 0. It looks like it happened in your wait event when you tried to update it (line 21)? Maybe its your ImList storing your queue?

fixed it, thanks!!
