### ISSUE TITLE
package Map does not exist

### ISSUE THREAD

**Issue by edwinhrj** [nus-cs2030/2223-s2#468]
# Summary

## Description:

hi, I've been getting this error when trying to iterate through the Immutable Map class as per the example on codecrunch (turn the Map object into a Set using the Entry method), but I'm getting this error in my code. Does any one know whats going on? I've already compiled the Immutable Map class.

## Code Snippets

<img width="648" alt="image" src="https://user-images.githubusercontent.com/122248645/226186467-24e5efc1-8e43-4401-8f29-eacca66b51a7.png">

## Screenshots

<img width="713" alt="image" src="https://user-images.githubusercontent.com/122248645/226186516-9167ad04-388d-4fc9-b404-99ee63e029a3.png">

**Comment by whsiah** [comment]
Did you import java.util.Map?

**Comment by hhuilingg** [comment]
yeap, u would need to import java.util.Map. and also, saw that u are using .entrySet() i think code crunch don't allow that so maybe you can try use .iterator() instead

**Comment by briannoelkesuma** [comment]
yes. i believe u can only use java.util.Map for this case.

**Comment by e0968868** [comment]
you have to import java.util.Map

**Comment by Nicknzk** [comment]
the import.map is found in the immutableMap.java file

**Comment by vancwe03** [comment]
you need to import java.util.Map!

**Comment by erinchanshining** [comment]
you need to import java.util.Map

**Comment by DavidLawCheng** [comment]
yup need import java.util.Map

**Comment by littlemidget3** [comment]
yup need import java.util.Map

**Comment by nigel-tannn** [comment]
You need to import java.util.Map

**Comment by nicholasteow** [comment]
Hi pls remember to import the java.util.Map

**Comment by xZealthiusx** [comment]
Did you import java.util.Map?

**Comment by jeffkhong11** [comment]
Remember to remove .entrySet()

**Comment by leroyteojy** [comment]
Remember to import your java.util.Map outside of your ImmutableMap too!

**Comment by ryantangmj** [comment]
you can insert **import java.util.Map;** at the top of your script

**Comment by cswssn** [comment]
i think by now it is more than clear what the issue is but i shall join the class part farming
yup need import java.util.Map

**Comment by JustinGohkh** [comment]
import java.util.Map at the top!

**Comment by justineeyx** [comment]
import java.util.map !!

**Comment by nathankkh** [comment]
remove .entrySet() too
