### ISSUE TITLE
Fail testcase 9_03

### ISSUE THREAD

**Issue by edwinhrj** [nus-cs2030/2223-s2#469]
# Summary

Description of the question / problem here.

## Description:

hello, my customers served and left is correct, but any ideas why my output just abruptly stops at customer 19?

I'm assuming that every line above this is correct as it wasn't flagged out by codecrunch.

If that's the case any ideas why even though customers 11, 13, 16 and 20 were generating the correct events prior to this, would they abruptly terminate and end off at customer 20? thanks guys

## Code Snippets

Attach code snippets (if any)

## Screenshots

<img width="514" alt="image" src="https://user-images.githubusercontent.com/122248645/226188373-ea2d024b-8aeb-4bfd-a45d-25a540b6de6c.png">

**Comment by meljwang** [comment]
You should check your simulator class specifically the way your PQ works. Also comparing the outputs, your average waiting time seems to be quite different from the given output, you might want to look at how you count the average waiting time too. Hope this helps!

**Comment by nigel-tannn** [comment]
Hi, in this case it seems that your Wait class/Wait buffer class does not properly generate a serve, which means that the conditions for the customer in the queue to be served may not be accurate, hence the customers are not being served from the queue as they should be.

**Comment by littlemidget3** [comment]
could be an issue with the way your events are turning new events. I assuming you don't have any issues with your simulator, where you check that the PQ is not empty, so there may be a problem where your events are not returning new events. For example, wait does not return serve.

**Comment by kmkmkmkmkmkmmm** [comment]
hi, i think there might have been an issue with the condition u set for the queue to stop running in ur simulator, u might want to check your arrive/wait events in case ure not returning the right serve event, since ure missing customer 11's serve event

**Comment by leonardwx** [comment]
hi, i think u may want to check does your event return the next event, did you add your event properly into the pq after execution from simulator class? also check your while loop and other possibilities that can terminate your next event.
