### ISSUE TITLE
Lab 5.2 

### ISSUE THREAD

**Issue by shakerfries** [nus-cs2030/2223-s2#471]
# Summary

Hello! my customer is getting served by the wrong server... eg.my customer 5 supposed to be serve my selfcheckout instead of human server

before customer 5, all other customers are served correctly by their respective human servers and selfcheckout... i have no idea whats wrong... my timing and serverlist are all updated correctly and my rest works as well... pls help thankyou!

![Screenshot (985)](https://user-images.githubusercontent.com/124678556/226192093-51ad17c2-eb6f-4b44-aea7-91c114d726f3.png)

**Comment by sethteo** [comment]
hii! are you using just 1 ImList of servers? Might be a logic issue where the index you used to call the specific server is wrong

**Comment by shakerfries** [comment]
> hii! are you using just 1 ImList of servers? Might be a logic issue where the index you used to call the specific server is wrong

yep i am using 1 imlist of servers! 
however in this case my customer is supposed to be serve by my selfcheckout instead of human server and i made sure to check beforehand whether it is a human server or selfcheckout.. so i dont think its an index issue tho

**Comment by briannoelkesuma** [comment]
there might be an issue with how u update the endtime of the human server. 
check if that could be the issue? 
in ur case, customer 5 might be going to a human server instead of a self checkout server as a result of this because the human server is free while it shouldn't be, according to the test case u provided.

**Comment by meljwang** [comment]
You might want to look at your implementation for resting human servers.  It seems that your server 1 is not resting as it should (it could be that the wrong rest time is generated) which is why your server 1 accepted customer 5 whereas in the given test case, server 1 only accepted customer 7 at 9.006.

**Comment by littlemidget3** [comment]
could check the way you assign timings from your timings for wait. Are you iterating through your counters to find the next earliest time? and ensure youre adding and removing from the right queue

**Comment by Yew-Wei** [comment]
> > hii! are you using just 1 ImList of servers? Might be a logic issue where the index you used to call the specific server is wrong
> 
> yep i am using 1 imlist of servers! however in this case my customer is supposed to be served by my selfcheckout instead of human server and i made sure to check beforehand whether it is a human server or selfcheckout.. so i dont think its an index issue tho

Could it possibly be how your ImList is implemented? Cause type checking shouldnt be needed if you have an ImList<Server>  where anything that inherits from your server should have similar functionalities.

**Comment by calvnleong** [comment]
in your intermediate wait event, did you ensure that the intermediate wait event's start time is the earliest available time among all the self checkout counters?

**Comment by Danpng01** [comment]
One thing to check is if when you update the server queue in serve, if afterwards you get the most updated server again. This was the issue I faced, hope it helps!
