### ISSUE TITLE
Lab 6 Level 5

### ISSUE THREAD

**Issue by EpicSpirito** [nus-cs2030/2223-s2#472]
## Description:

Hi, is the add method in the Roster class supposed to mutate the current Roster instance instead of creating a new one?
No `roster =` after the second command

**Comment by jefflcy** [comment]
Hi,  Roster::add returns a new roster itself, it does not mutate the original roster. I believe the testcases are showing how new entries into a roster already with 1 Student would look like. Do note that if an Assessment of the same name already exists for that Student for that Module, it overwrites/replaces the old record as seen in Testcase line 6 for lvl 5 :)

**Comment by e0968868** [comment]
you have to create a new Roster with a new Student/new Module depending on what is contained in the current Roster

**Comment by hhuilingg** [comment]
do also remember to check if there's existing record. eg if the student is alr in the roster and taking another module, you should be adding module to that person. if the record of student,module,assessment title is the same, but the grade is different, you would need to update the grade

**Comment by EpicSpirito** [comment]
okay thanks, I see it now!
