### ISSUE TITLE
Lab 05 Fail Test Case 9_03

### ISSUE THREAD

**Issue by kaiyanggg** [nus-cs2030/2223-s2#474]
Hi, have been running into this issue and have not been able to figure out where I went wrong as I passed the public test cases. There has been one post with the same error previously, however the solution to solve it does not work for my particular case. Has anyone else ran into this/possibly know why this happens and can provide some help! Thanks :)

## Screenshots
![Screenshot 2023-03-20 at 10 47 42 AM](https://user-images.githubusercontent.com/91410174/226235400-9e4dbc97-188c-4c53-a9d3-f88a30f6b004.png)

**Comment by nigel-tannn** [comment]
In this case since the expected output is that 15 waits at 2 instead of 1, it means that the queue for 1 is full, so maybe you could check if your Serve event is accurately removing the customer that is being served from the queue.

**Comment by Danpng01** [comment]
Another possibility apart from queue management in serve is in next amicable serve time! If the condition to serve checks for the next serve time, it could be a scenario where the serve class incorrectly updates the time the customer can next be served

**Comment by kaiyanggg** [comment]
Thanks guys! Managed to solve, realised that the issue is because for my implementation, I placed the customer that is currently being served in the queue as well (worked for lab 3), which I believe messed up the queue.
