### ISSUE TITLE
Lab 6 level 3 unknown test case?

### ISSUE THREAD

**Issue by j0205m** [nus-cs2030/2223-s2#476]
# Summary

my output for level 3 is correct but i encountered this error and i'm not sure what this test case is... is anyone else facing the same issue?

## Screenshots
<img width="1470" alt="Screenshot 2023-03-20 at 12 20 49" src="https://user-images.githubusercontent.com/124303065/226246644-eb630e7e-ea0e-4ce1-a460-aca473319954.png">

**Comment by kmkmkmkmkmkmmm** [comment]
hi!! may i know what the problem for this was as im facing the same issue rn! @j0205m
