### ISSUE TITLE
test case 10 incorrect output (I swear I only getServiceTime() once)

### ISSUE THREAD

**Issue by sporobolous** [nus-cs2030/2223-s2#478]
# Summary

I am facing this issue, I worked backwards and assumed that there are 2 servers and the qmax is three

when run with the code I also realise that my customer 7 does not wait at 2 but at 1, hence the "too many service time generated" 

does anyone have suggestions thanks

<img width="900" alt="Screenshot 2023-03-20 at 2 38 17 PM" src="https://user-images.githubusercontent.com/110991431/226265020-8555d816-454b-443a-a4ea-9ed25821684e.png">

**Comment by secretApple** [comment]
you can check your queue whether it tracks the number of customers in it correctly and also indicates when it is full so that your customer will go to 2 (assuming 1 is full)

**Comment by meljwang** [comment]
I think you might want to check the way you coded the customer queue of each server and make sure that you remove/add customers correctly from the server queue in your queuing and serving events. Right now it seems that your server 1 is accepting more than 3 customers in the queue when the qmax should only be 3 (according to the test case).

**Comment by mkim123** [comment]
Seems like the queue length of server 1 is not getting updated properly when customers waits for server 1.  You might want to check the queuelength of server 1 for each iteration of customer served, by using the system.out.println function. This wrong updating of server might be because of the usage of this.server rather then the getter methods.

**Comment by 0liverkong** [comment]
where is your getservicetime called? calling it within the constructor of the serve event may be more secure since the events dont get interacted with a lot as compared to the customers.

**Comment by viethaaaa** [comment]
> where is your getservicetime called? calling it within the constructor of the serve event may be more secure since the events dont get interacted with a lot as compared to the customers.

hi can you clarify on this, I faced the same issue and tried calling it within the constructor of the serve event but it made me fail from test case 6 onwards already, instead of failing only test case 10? thanks!

**Comment by 0liverkong** [comment]
> > where is your getservicetime called? calling it within the constructor of the serve event may be more secure since the events dont get interacted with a lot as compared to the customers.
> 
> hi can you clarify on this, I faced the same issue and tried calling it within the constructor of the serve event but it made me fail from test case 6 onwards already, instead of failing only test case 10? thanks!

id intepret this as your issue coming from somewhere else... look at the first point of failure for test case 6 and see how to move on from there?

**Comment by calista03** [comment]
hi there! could it be because you are calling your execute() or nextEvent() method of the event class twice in your Simulator.java? that's what happened for me, hope this helps :)

**Comment by sporobolous** [comment]
thanks everyone! managed to follow everyone's suggest and found that at some point there will be a conflict with my server at done and wait events.
