### ISSUE TITLE
Creating immutable list of items by iteration

### ISSUE THREAD

**Issue by eesean** [nus-cs2030/2223-s2#48]
Hi all,

In CS2030 effect free programming is emphasised i.e. the original state should not be modified, but I would like to ask whether it is possible to create an immutable list of 3 items (e.g. A, B, C) by iteration, starting from an empty list? One possible method I have thought thus far would be by reassignment to a new list in each iterative step.

**Comment by lihongguang00** [comment]
Hi eesean,

If I did not misunderstand your question, your method of reassignment does not violate effect free programming principle.

e.g. To create your immutable list of 3 items, you can consider:
1. `ImList<item_type> my_list = new ImList<item_type>();`
2. `for (int i = 0; i < 3; i++) {`
3.     `my_list = my_list.add(<element>);`
4. `}`

After which, if you do `System.out.println(my_list)`, it should display [<element1>, <element2>, <element3>].

**Comment by eesean** [comment]
Oh I see, thanks for the insight!
