### ISSUE TITLE
Lab 5.1 Test Case 3

### ISSUE THREAD

**Issue by e0970430** [nus-cs2030/2223-s2#480]
Currently, I only have Arrive, Wait, Serve and Leave event classes but my code isn't passing the private test cases even though I only generated the servers' rest times once per serve event.

I think that I am supposed to implement an intermediate class between Wait and Serve events, but I am not really sure how it helps to update the shop and solve this error. Does your intermediate class just update the list of servers by adding the customer to the waiting queue of the servers or does it serve more purposes? 

Or, is there any other way that you have used to solve similar errors?

Thank you! :"

![image](https://user-images.githubusercontent.com/124949039/226278394-cfae14ee-f08f-4bd8-9f10-860b954611ad.png)

**Comment by JustinGohkh** [comment]
I don't think implementing the intermediate wait event will help in your case, as the main issue is with the rest timing, perhaps you just need to check if your wait and your queues take into account the rest time and the next readytime of the server?

**Comment by hcyrr** [comment]
i think instead of generating server's rest time in the Serve event, i think it should be done in the Done event
and i dont think u need to implement an intermediate event, u can make ur Wait event continue to return another Wait event if the server is not ready to serve this customer, just that this Wait event wont be printed

**Comment by edwinleck** [comment]
wondering if you implemented any changes to your code since? I am facing the same errors as well

**Comment by stxe09** [comment]
I have the exact same output rn so what helped me pass this test case was moving my calling of get Rest Time to Done event. 
if it's called at Serve, you might get different rest times sometimes, since the order of generating rest times for servers could be mixed up.

**Comment by kmkmkmkmkmkmmm** [comment]
hi, i faced the same problem as you, i think having a done event will help as u can put ur get rest time there! the problem is the buffer between done (rest) and the next serve or wait event, so i made a rest event just to make sure the server's new availtime is updated, tbh no point of a second wait event if ur first works, and i was too lazy to make a second wait so i stuck to this! then in my wait event i just checked if this.getTime() == server.getAvailTime() && queue.get(0).getN() == this.getCust().getN(), hope this helps!

**Comment by e0970430** [comment]
thank you for all your help and suggestions !! i managed to figure it out <3

for those who have the same problem, i solved it by 
1. adding a new condition in my serve class to check if this.time < server's next avail time, then if it is i regenerated a new serve event with the updated times
2. updating the toString() method of my serve class to not print out the wrong serve event toString()s
3. updating my implementation to only get the servers' rest time in the done event
4. updating my counter only in the done event (instead of updating in the serve event like i did previously)

**Comment by vanessakohh** [comment]
> thank you for all your help and suggestions !! i managed to figure it out <3
> 
> for those who have the same problem, i solved it by
> 
> 1. adding a new condition in my serve class to check if this.time < server's next avail time, then if it is i regenerated a new serve event with the updated times
> 2. updating the toString() method of my serve class to not print out the wrong serve event toString()s
> 3. updating my implementation to only get the servers' rest time in the done event
> 4. updating my counter only in the done event (instead of updating in the serve event like i did previously)

Hi, I was just wondering. Wouldn't regenerating another Serve event call getServiceTime() again & mess up the results?

**Comment by wesleychoy** [comment]
hi how did u make the toString method not print the wrong serve event?

**Comment by e0970430** [comment]
> > thank you for all your help and suggestions !! i managed to figure it out <3
> > for those who have the same problem, i solved it by
> > 
> > 1. adding a new condition in my serve class to check if this.time < server's next avail time, then if it is i regenerated a new serve event with the updated times
> > 2. updating the toString() method of my serve class to not print out the wrong serve event toString()s
> > 3. updating my implementation to only get the servers' rest time in the done event
> > 4. updating my counter only in the done event (instead of updating in the serve event like i did previously)
> 
> Hi, I was just wondering. Wouldn't regenerating another Serve event call getServiceTime() again & mess up the results?

@vanessakohh i only used getServiceTime() when the serve event is confirmed to have the right time so it didn't mess up the results for me

**Comment by e0970430** [comment]
> hi how did u make the toString method not print the wrong serve event?

@wesleychoy because my implementation is such that i returned a pair of events every time i executed an event, i formatted it such that the i would return pair(this, new serve event) when i updated the serve event, so if pair.first() is this, i would return an empty string
