### ISSUE TITLE
Lab 5.1: is a rest event needed

### ISSUE THREAD

**Issue by secretApple** [nus-cs2030/2223-s2#482]
for the first part of lab 5, is it actually necessary to create a Rest event (created after Done event)?
if yes, what would be the purpose of the rest event?

**Comment by Jeko1239** [comment]
yea u can implement it that way. Done Event can update events by returning pq.add(Rest Event), where the time for Rest Event is the time from Done event + restTimes.get(). similarly, u can update ur server in server list by the same amount of time. make sure u dont call restTimes.get() twice tho.

**Comment by edwinhrj** [comment]
I mean technically you can not include in a restEvent, as the logic for servers resting after their doneEvent can be encapsulated entirely in the HumanServer class (by including a busyUntilTime attribute) in the HumanServer class.

**Comment by shakerfries** [comment]
hello, you do not need to create a restEvent class . rest is a state, you can update the respective timing in your doneEvent class

**Comment by ghost1nthemachine** [comment]
personally I added a rest event just to prevent double printing of the Done event. theres other way around this tho and its not really needed

**Comment by ayevxn** [comment]
I didn't make a rest event, simply 'extended' the time that server is busy until by the rest time generated.

**Comment by hcyrr** [comment]
my rest event's purpose is to just update the server's next avail time, and set my server's isResting boolean to true. i think its up to ur implementation on whether u want to create a rest event, like mentioned above i think u can just do it in your done event, i made a rest event just so that its clearer for me
