### ISSUE TITLE
using entry in formatting toString() method

### ISSUE THREAD

**Issue by calvnleong** [nus-cs2030/2223-s2#484]
# Summary
Having to import java.util.Map.Module

## Description:
Just curious if anyone else got this incompatible types error when trying to create the toString() method in Module? 
I imported java.util.Map.Entry to solve this issue but it feels weird having to do so.
Is there another way in which we dont have to use Entry, or did most people use this method too?

## Code Snippets

Attach code snippets (if any)

## Screenshots

Screenshots (if any)
<img width="865" alt="image" src="https://user-images.githubusercontent.com/124434962/226298272-a27b3a06-75d6-4893-8384-75c2f6eb3d16.png">

**Comment by shakerfries** [comment]
you can try importing java.util.Map then call Map.Entry instead

**Comment by justineeyx** [comment]
hi calvin, i just used Map.Entry because the example given in code crunch did so as well
![image](https://user-images.githubusercontent.com/122433748/226301889-015f2283-8fac-4b8b-94db-f043e73bfaa1.png)

**Comment by e0968868** [comment]
Rather than importing java.util.Map.Entry, u should import  java.util.Map. and then iterate through Map.Entry

**Comment by SumDumPhuc** [comment]
Use Map.Entry after importing java.util.Map
