### ISSUE TITLE
Lab 6 - Restricted API

### ISSUE THREAD

**Issue by nathankkh** [nus-cs2030/2223-s2#485]
# Summary
Got rejected by CodeCrunch for using java.util.Collection.

## Description:
Haven't used entrySet(), and the only things I've imported are java.util.Optional and java.util.Map (Used to iterate through the map in  `for (Map.Entry<String, V> : map`, where map is an instance of `ImmutableMap`). Is there anything else I'm missing?

## Screenshots
![image](https://user-images.githubusercontent.com/115643118/226303257-480a0be2-934a-4992-a196-64e429030904.png)

**Comment by ryantangmj** [comment]
You probably used the values() method from the immutablemap class somewhere in your other classes

**Comment by nathankkh** [comment]
@ryantangmj that fixed it, thanks!
