### ISSUE TITLE
Incompatible type in Student class's put() in level 3 

### ISSUE THREAD

**Issue by jiangen16** [nus-cs2030/2223-s2#486]
# Summary

Hey guys, im experiencing some issues when compiling the code for Student class and KeyableMap

it states that there is an incompatible types: ImmutableMap<java.lang.String,Module> cannot be converted to ImmutableMap<java.lang.String,Assessment>. But i dont see where the ImmutableMap<String, Assessment> came in for Student.java

I've attached the error message and the code snippet for my Student class's put()

## Code Snippets

Attach code snippets (if any)

## Screenshots
![image](https://user-images.githubusercontent.com/123716826/226312848-b11f864e-a393-4281-b769-c295991a1407.png)

![image](https://user-images.githubusercontent.com/123716826/226312975-31ed77fd-c81f-4f72-86a1-bdd2f224973e.png)

**Comment by ansleytje** [comment]
I'm not sure if it exactly solves the problem but you should be returning a new Student instead of a new Module

**Comment by justineeyx** [comment]
u shld return new student(super.getKey(),newMap) since ur key value is being super w ref to keyableMap class

**Comment by gene2345** [comment]
your return type is declared as Student but you are returning Module, you should also try to use super() as much as possible

**Comment by JustinGohkh** [comment]
You should be returning a student instead of a module

**Comment by jiangen16** [comment]
resolved thanks yall!

**Comment by territxl** [comment]
Do check your return statement as you are returning a Module instead of the declared return type Student
