### ISSUE TITLE
Lab 05 9_03

### ISSUE THREAD

**Issue by mkim123** [nus-cs2030/2223-s2#488]
# Summary

My servers dont seem to rest

## Description:

For some reason, my server doesn't seem to rest, even after I've updated the rest time to the server's available time in the Done class. 
![code snippet](https://user-images.githubusercontent.com/124948994/226327502-965af5f1-ac00-4df3-ab23-44ed8180436b.png)

![github 2](https://user-images.githubusercontent.com/124948994/226326863-5f77289a-7ae3-47da-9abe-494d41b5c9dc.png)

## Code Snippets

Attach code snippets (if any)

## Screenshots

Screenshots (if any)

**Comment by koiljat** [comment]
you should be calling the get() method of the supplier at Done/Rest class. can you check if you have call it at the correct place?

**Comment by vancwe03** [comment]
check that you are using the most updated server in ur nextEvent method in your wait class

**Comment by mkim123** [comment]
> you should be calling the get() method of the supplier at Done/Rest class. can you check if you have call it at the correct place?
> 
> it should look something like this: `server.getRestTimes().get()`

yup this seems to be the issue!
