### ISSUE TITLE
Lab 6 Level 3 - Implementation of ImmutableMap

### ISSUE THREAD

**Issue by chianxintong** [nus-cs2030/2223-s2#489]
# Summary

Hello! May I ask how should I go about implementing ImmutableMap<String, Assessment> in Module? (and hence implementing ImmutableMap in KeyableMap)

## Description:

e.g. For Module class, 
I defined my class to be class Module extends KeyableMap<Assessment>, where there are 2 variables associated with this class (a string - **uniqueID ie. modName**, and **a ImmutableMap<String, Assessment>**. 

However, I am not sure how to implement the ImmutableMap<String, Assessment> since this suggests that 1 module is only associated with 1 assessment (since 1 key only has 1 value) - but that's not the case...  

## Code Snippets

![image](https://user-images.githubusercontent.com/122260095/226331058-357fde9e-cd69-4aa4-853b-345b4e2f1449.png)

This is what I have now, but it will result in this...................... 
![image](https://user-images.githubusercontent.com/122260095/226331175-1bb5f7c2-25b5-4f84-b2ec-7279bfc00264.png)

**Comment by geoffong11** [comment]
You should put newKeyable.getKey() value into the map in keyablemap.

**Comment by justineeyx** [comment]
shld be this.map.put(newKeyable.getKey(), newKeyable)

**Comment by chianxintong** [comment]
> shld be this.map.put(newKeyable.getKey(), newKeyable)

omg ya i got it thanks :DD
