### ISSUE TITLE
CodeCrunch: Use of restricted API detected. But none was used. (Exercise 2)

### ISSUE THREAD

**Issue by Xequil1** [nus-cs2030/2223-s2#49]
I ran to this problem on CodeCrunch, but the checkstyle passed everything for me. I did not import any APIs except for the one ImList.java imported. So I am unsure what is the problem.

![Screenshot (151)](https://user-images.githubusercontent.com/122268182/216221061-cc801b7e-7160-4b90-98af-9301846b696b.png)

**Comment by SimonSeeYongsheng** [comment]
> I ran to this problem on CodeCrunch, but the checkstyle passed everything for me. I did not import any APIs except for the one ImList.java imported. So I am unsure what is the problem.
> 
> ![Screenshot (151)](https://user-images.githubusercontent.com/122268182/216221061-cc801b7e-7160-4b90-98af-9301846b696b.png)

That's funny, the compilation error is saying that the java.util.Objects is the restricted API.
But java.util.Objects is the basis of the whole java util package

**Comment by danqiye1** [comment]
Hi, can I have the submission id to take a look at your code?

**Comment by e0959170** [comment]
maybe you have a private final constant that is not declared as static..?

**Comment by Xequil1** [comment]
> Hi, can I have the submission id to take a look at your code?

Latest: 2449381

**Comment by Xequil1** [comment]
> maybe you have a private final constant that is not declared as static..?

So I am not sure why the checkstyle will flag a constant like that but yes that seems to be the issue. Thanks.
Also hopefully we are given access to CodeCrunch's checkstyle to prevent issues like this...

**Comment by danqiye1** [comment]
> > maybe you have a private final constant that is not declared as static..?
> 
> So I am not sure why the checkstyle will flag a constant like that but yes that seems to be the issue. Thanks. Also hopefully we are given access to CodeCrunch's checkstyle to prevent issues like this...

Yeah most likely it is the lack of static modifier. This is probably not flagged by CodeCrunch’s checkstyle, but rather the custom testing scripts loaded. I am checking why it triggers the restricted API error with Prof Henry.
