### ISSUE TITLE
5.2 

### ISSUE THREAD

**Issue by shakerfries** [nus-cs2030/2223-s2#490]
# Summary

hello ! initially i could pass lab 5.1 test cases but after doing lab 5.2 , my customer is waiting at the wrong server? pls help thankyou

![Screenshot (987)](https://user-images.githubusercontent.com/124678556/226339365-7b78e172-29b1-4a5b-8561-580fd74578a9.png)

**Comment by prisciliapangg** [comment]
Hi, I think you should check if you updated your queue, because it seems like your queue is not being updated correctly (can try to debug by printing the server's queue)

**Comment by shakerfries** [comment]
> 

ooo i think i got it thanks!
