### ISSUE TITLE
5.2 9_9 time limit exceeded 

### ISSUE THREAD

**Issue by shakerfries** [nus-cs2030/2223-s2#492]
# Summary

hello anyone has this error? i know theres an infinite loop somewhere but i am not sure where ... please help thankyouu 

![Screenshot (989)](https://user-images.githubusercontent.com/124678556/226340526-25b3b880-6b77-4569-8847-b0038af54493.png)

**Comment by shakerfries** [comment]
> # Summary
> hello anyone has this error? ik theres an infinity loop somewhr but im not sure where. please help thankyou.
> 
> ![Screenshot (989)](https://user-images.githubusercontent.com/124678556/226340526-25b3b880-6b77-4569-8847-b0038af54493.png)

**Comment by prisciliapangg** [comment]
Hmm, can't know for sure just based on this, I suggest debugging by printing "[EventName]" at each Event Class's String toString() method and see where the loop is. Good luck!
