### ISSUE TITLE
Lab 05 Test Case 9_04

### ISSUE THREAD

**Issue by YyannW** [nus-cs2030/2223-s2#493]
# Summary

It seems the rest time is not updated correctly

## Description:

I update the rest time for the human counter in the Done event but it seems they dont rest...Any idea on how to fix this issue??

## Code Snippets

![image](https://user-images.githubusercontent.com/117875336/226346906-530198c1-f795-4b69-b424-deb616d55134.png)

## Screenshots
![image](https://user-images.githubusercontent.com/117875336/226346764-cec7a1b8-4fea-42ec-aaf7-2cabd0bdd1ff.png)

**Comment by prisciliapangg** [comment]
Hi, you might want to check if you updated your serverList in your simulator class (given that this is a DoneEvent and you may have skipped past it). Based on your code snippet, I am quite certain it is correct, provided your .updateRest() method in Server is implemented correctly.

**Comment by YyannW** [comment]
EDIT: problem solved, I updated wrong time in the Wait event (T⌓T)

**Comment by haoyanggggg** [comment]
hi @YyannW can u elaborate more about "updated wrong time in wait event" bc im facing the same issue as u and i cant find the mistake in my code
