### ISSUE TITLE
Lab 5.2 test case 9_14

### ISSUE THREAD

**Issue by Leeeef552** [nus-cs2030/2223-s2#495]
![image](https://user-images.githubusercontent.com/104271512/226357761-e325605b-a8ab-4470-87ad-8d7907973bf0.png)
![image](https://user-images.githubusercontent.com/104271512/226357892-3376b904-2f67-4147-aa44-9e3a012001d2.png)

Has anyone faced a similar problem? Not sure why my customer queue is being affected. For my implementation, if the server is not a self check i actually dont change my code from labs5.1

**Comment by fy17ohhh** [comment]
umm not sure about your detailed implementation, but you should first check you updated your server 1 queue properly so that when 10 arrives, server 1 is full so that 10 waits at 2 instead

**Comment by prisciliapangg** [comment]
I did not face this problem but after looking at your error I suggest creating your own test case (such that customers begin waiting at selfcheckout counters). With this test case, print out the server queue (because it seems like server 1's queue was updated correctly but became empty suddenly, could be from selfcheckout since you said you did not change your code from lab 5.1).

**Comment by Leeeef552** [comment]
> I did not face this problem but after looking at your error I suggest creating your own test case (such that customers begin waiting at selfcheckout counters). With this test case, print out the server queue (because it seems like server 1's queue was updated correctly but became empty suddenly, could be from selfcheckout since you said you did not change your code from lab 5.1).

ok thanks. But i am just confused at their test case. From the code, we can infer that likely server1's waitlist is full which is why 10 waits at 2 instead of 1. For 5 to be served by 1 (line 31), shouldn't there be a done event to indicate a customer is done before 5 can be served by 1? (they didnt indicate 5 arrive so i can imply 5 was in the waitlist of server1)

**Comment by Leeeef552** [comment]
> I did not face this problem but after looking at your error I suggest creating your own test case (such that customers begin waiting at selfcheckout counters). With this test case, print out the server queue (because it seems like server 1's queue was updated correctly but became empty suddenly, could be from selfcheckout since you said you did not change your code from lab 5.1).

hi, thanks for the feedback. I noticed that from my own test case that the problem arises due to my server rest. For some reason when the server rests, the waitlist is emptied. but im not sure why

**Comment by Leeeef552** [comment]
managed to resolve it. Thanks for the help!
