### ISSUE TITLE
Unable to View Images in Docker Desktop Setup Page

### ISSUE THREAD

**Issue by JYeoZS** [nus-cs2030/2223-s2#5]
# Summary
I refer to https://github.com/nus-cs2030/2223-s2/wiki/Setting-Up-Docker-Desktop

## Description 
I'm not able to see images during the Docker Desktop set up process. Top image in Chrome, bottom image in Safari.
Anyone else facing this problem? How did you resolve it?
Thanks. 

## Screenshots (if any): 
![Screenshot 2023-01-10 at 2 25 32 PM](https://user-images.githubusercontent.com/122290983/211477706-c7eca390-413c-4fdd-9cfe-fef7fb66b2d7.png)
<img width="1342" alt="Screenshot 2023-01-10 at 2 25 25 PM" src="https://user-images.githubusercontent.com/122290983/211477720-daa76578-6dc5-4a8b-80b1-4e2a5c943929.png">

**Comment by danqiye1** [comment]
Hmm is anyone else having this issue? I can't seem to reproduce this problem as the images show up in my browsers.

**Comment by JYeoZS** [comment]
strange, tried it on phone, also cannot view images on mobile device.

But tried installing Docker with the captions, was successful. (I hope, at least app not giving problems at moment. 👍 )

**Comment by piglisa** [comment]
same issues here, tried it with three different browsers and none of them will show the image

**Comment by danqiye1** [comment]
Here is a workaround for now: https://github.com/nus-cs2030/2223-s1/wiki.

**Comment by danqiye1** [comment]
Closing issue. Reopen if there are further issues.
