### ISSUE TITLE
Lab 6 Level 6 Test Case 6 (Roster only allowing students to take max 1 mod)

### ISSUE THREAD

**Issue by chianxintong** [nus-cs2030/2223-s2#500]
# Summary

Roster only allows 1 student to take 1 module in codecrunch, but it worked in jshell. 

## Description:

I included a System.out.println(roster) after adding a record to the roster. It seems that roster constantly updates itself to have 1 student taking 1 mod max. 
![image](https://user-images.githubusercontent.com/122260095/226513772-f7807050-dbd7-49de-b860-13246b199edf.png)

This is my while loop for adding a record to the roster in Main.java
![image](https://user-images.githubusercontent.com/122260095/226513968-dc4234bc-bb7f-4c04-9965-2784ac1e6461.png)

However, it works when I manually tested the add( ) function of the roster on jshell.
![image](https://user-images.githubusercontent.com/122260095/226514014-ad539c29-990d-4255-b1b8-5f315a220d38.png)

Send help pls~

**SOLVED------------------------------------------------------------------------------------------------------------------------------**
Did anyone encounter a similar problem with their assessment name? not sure why mine just shows midterms :o

![image](https://user-images.githubusercontent.com/122260095/226409616-23f9d577-73a1-46c2-9242-1a72828667d7.png)

**Comment by territxl** [comment]
I think you can try to System.out.println() to check that your roster is updated correctly in order to obtain desirable output from getGrade().

**Comment by chianxintong** [comment]
> Not sure what is wrong, but I think you should check if your arguments for .getGrade() are correct (specifically String assessment). Based on your output, it seems like your input for String assessment did not update properly, but String name and String module were correct. I think you can try storing the String and printing them out.

thanks haha i solved the part for assessment

**Comment by Delocy** [comment]
in ur roster u shud check if that student is exist before in the roster and then check if the module exist before also if it exists then u extract the map out for that studen tthen add the assessment in

**Comment by j0205m** [comment]
currently facing the same problem.. works on jshell but not on codecrunch

**Comment by trickypepe** [comment]
> currently facing the same problem.. works on jshell but not on codecrunch

It could be the part of the code that checks if the student exists. I encountered a similar problem using "==", it worked after I switched to compareTo.

**Comment by j0205m** [comment]
> currently facing the same problem.. works on jshell but not on codecrunch

update i finally found the bug... if you are using == in any of your method change it to equals(), can check your keyablemap especially!

**Comment by chianxintong** [comment]
Thanks all for your help!! I think using .orElse() is crucial in Roster, but the problem i encountered was using == instead of equals() as mentioned by @j0205m
