### ISSUE TITLE
how do i start lab6?

### ISSUE THREAD

**Issue by hcyrr** [nus-cs2030/2223-s2#501]
# Summary

not sure what is the interface Keyable for.. is Assessment supposed to implement Keyable? or/and extend ImmutableMap? i am quite lost for this topic, any help will be appreciated thank you

**Comment by calvnleong** [comment]
you can think of assessment, module, student and roster as a dictionary, with a key and value pair. As such, anything that works like a dictionary should implement  Keyable. ImmutableMap can be thought of as an ImList of key-value pairs.

**Comment by territxl** [comment]
I think you can read through the lab6 till level 3. Essentially having KeyableMap kinds of define the methods you want for the other classes generically since those methods are rather similar. The idead of obtaining the key and value is similar to Python Dictionary. Hope this helps!

**Comment by hengbl** [comment]
All the classes should either implement Keyable or extends KeyableMap. Personally I was a little confused by the toString(), you should take note that the ImmutableMap in each class should take in T.getKey() as the key and T as the value and the toString() only shows the values of the ImmutableMap.

**Comment by nicholasteow** [comment]
For early levels, you can simply implement keyable and maybe have immutableMaps as an attribute.

**Comment by Maxxtucker** [comment]
You can do level 3 first

**Comment by dlyxxx** [comment]
i just put that it extends KeyableMap and implements Keyable not sure if this will affect the rest a lot

**Comment by UmpoDumpo** [comment]
It's important to note that the put method in module takes assessmentID as a key, and an assessment (with its own key - assessmentID and value - grade which are both Strings) as its value. This should help you start the lab!
