### ISSUE TITLE
Use of restricted API - java.util.Set? 

### ISSUE THREAD

**Issue by calista03** [nus-cs2030/2223-s2#502]
Hi guys, after submitting my code on CodeCrunch, I got this: 

![Screenshot 2023-03-21 at 1 47 23 AM](https://user-images.githubusercontent.com/124029739/226427086-b0ba0326-91db-47de-84ec-794eeadecb9c.png)

I've run through all of the test cases and my output matches the test cases exactly, yet I'm facing this issue. 
I'm not sure why this is happening, as all of my classes do not 'import java.util.Set' (except for ImmutableMap, which was already given to us). Has anybody faced a similar issue as me? Any advice would be greatly appreciated!!

**Comment by hengbl** [comment]
hello, you probably used entrySet() or keySet() from ImmutableMap inside your code hence the error. It wasn't explicitly stated but we are not allowed to use any of the methods that return a Collection or Set even though they are not private.

**Comment by calista03** [comment]
Hi there! I managed to solve it already! You are right, the problem was indeed with the entrySet() that i used in my code. Thanks so much!
