### ISSUE TITLE
Lab 5 9_03

### ISSUE THREAD

**Issue by alvintjw** [nus-cs2030/2223-s2#506]
# Summary
How should the Intermediate Wait call for the serve event? Having trouble with customer 10 getting served without accounting the restTime after is being done serving.
Description of the question / problem here.

## Description:

Clarifications or details with respect to the issue you are facing

## Code Snippets
<img width="545" alt="Screenshot 2023-03-21 at 4 22 10 AM" src="https://user-images.githubusercontent.com/65883895/226456831-0e708c69-e073-4f94-bb9a-767644593374.png">
<img width="723" alt="Screenshot 2023-03-21 at 4 22 45 AM" src="https://user-images.githubusercontent.com/65883895/226456921-70dda658-80f9-4cc2-814f-20146c460a20.png">
<img width="691" alt="Screenshot 2023-03-21 at 4 23 07 AM" src="https://user-images.githubusercontent.com/65883895/226456994-4fb67010-1d9c-4e97-90dd-e72e76a5810d.png">
<img width="691" alt="Screenshot 2023-03-21 at 4 23 28 AM" src="https://user-images.githubusercontent.com/65883895/226457073-917d1748-c45d-45a7-821b-16f521c2f18e.png">

Attach code snippets (if any)

## Screenshots

Screenshots (if any)

**Comment by kmkmkmkmkmkmmm** [comment]
hi, i faced the same problem as you, though im not sure where u added ur rest time, im guessing u put it in done? i had two wait events like u at first but realised the problem is the buffer between done (rest) and the next serve or wait event, so i made a rest event just to make sure the server's new availtime is updated, scraped the second wait event. then in my wait event i just checked if this.getTime() == server.getAvailTime() && queue.get(0).getN() == this.getCust().getN(), hope this helps!

**Comment by ghost1nthemachine** [comment]
Hey my impl is similar to urs. In your pendingserve class, perhaps you change the condition of the if else to this.time <= updated servernextavailtime.

**Comment by hcyrr** [comment]
like the comments above, i only generated a serve event if the wait event's timestamp is >= server's next avail time

**Comment by alvintjw** [comment]
@kmkmkmkmkmkmmm I did not add a rest event. I just obtain the rest time in my done event and updated the server's list

**Comment by alvintjw** [comment]
@hcyrr @ghost1nthemachine I don't quite understand the point of that because this.time <= updatedServer endTime would always be true.

**Comment by ghost1nthemachine** [comment]
> @hcyrr @ghost1nthemachine I don't quite understand the point of that because this.time <= updatedServer endTime would always be true. 
hmm its not alw true if this customer is not the next one in the queue (the case where multiple customers comes at the same time)

**Comment by alvintjw** [comment]
@ghost1nthemachine I changed my pendingserve to >= but still having that issue :/
