### ISSUE TITLE
Exercise 2 Codecrunch - Level 3

### ISSUE THREAD

**Issue by kayeugenia** [nus-cs2030/2223-s2#51]
Hi! I am a bit confused as to how to keep track of the number of Loaders that have been deployed, i.e. how to count the number of instances of Loader objects that have already been created?
I think I need to do that because the loader number does not always start from 1 for every cruise that arrives. Is there any other way instead of keeping a public static counter variable within Loader class and increment it by one every time Loader object is constructed?

**Comment by jhsoh** [comment]
You can create a variable called numLoaders = 0 inside the level3.jsh file. Whenever you need to create a new loader,  numloaders++ then create new Loader(numLoaders)

**Comment by timothysashimi** [comment]
Maybe you can get the size of the list of active and expired service queues and add them together? That'll give you the number of loaders that have been created in total

**Comment by Jovan131** [comment]
You can keep the counter variable you mentioned within the serveCruises() method in your level3.jsh file

**Comment by granolaluvr69** [comment]
Just initialise a variable to count the loader number starting from 1 outside the loop and remember to loadNo++ after every loader created. Hope it helps!
