### ISSUE TITLE
Lab 6 Level 3 KeyableMap implementation

### ISSUE THREAD

**Issue by clarwen** [nus-cs2030/2223-s2#510]
hi all,

I understand that from codeCrunch, class Module and Student must extends KeyableMap as it is an instance of it. There should also be an overriding method put() in Module/Student.

However, I face so many compilation issues. A screenshot is one example. How do we properly extends generic classes? i.e. KeyableMap? Am I suppose to call super() in the constructor and the rest of the body in Module and Student? 

kind of confused of the implementation of generic classes :(

![Screenshot 2023-03-21 at 1 29 06 PM](https://user-images.githubusercontent.com/119107037/226525772-b37f808b-3d6c-4030-b79e-5bbe6ff361f4.png)

**Comment by leroyteojy** [comment]
how did you define the constructor of KeyableMap? a possible constructor you can try is -> 
KeyableMap(String key, ImmutableMap<String,V> map)

**Comment by Nicknzk** [comment]
in student class, what I did for KeyableMap is 
class Student extends KeyableMap<Module>
maybe u can try that first

**Comment by Delocy** [comment]
student extends keyableMap shud have have type in this case it should be module

**Comment by shionhigashi** [comment]
you can check if your student class extends KeyableMap<Module> and within student class call your 2 super class constructors with V type as Module

**Comment by haqanh** [comment]
Looks like maybe you have not declare the type of your ImmutableMap that you will take in in your constructor?

**Comment by e0969533** [comment]
your class Student extends KeyableMap<V> where V is one of the subclasses

**Comment by dlyxxx** [comment]
maybe you wanna check that in your KeyableMap, the ImmutableMap has the correct identifiers e.g. ImmutableMap<String, V>

**Comment by andersooi** [comment]
For those that faced the same issue, maybe you can try taking a look at my reply for issue #465

**Comment by clarwen** [comment]
got it, my issue was not putting in the parameter V correctly. Thanks all!
