### ISSUE TITLE
lab 5.1 failed test case 9_03

### ISSUE THREAD

**Issue by ngshiyingg** [nus-cs2030/2223-s2#511]
# Summary

Hi! I know that others have faced a similar issue, but I think I ran into a slightly different problem. (customer 3, 4, and from customer 12 onwards)

## Description:
I have a Done event and a Rest event. My Done event just returns a new RestEvent. In my RestEvent, I call restTimes.get() in the constructor and increase my server's nextFreeTime by the random rest time generated (and use the updated server to update my serverlist in the Simulator class too). I made sure to use the updated server in every event, as well as have my check (if server is free) to be time >= nextFreeTime, so Im not sure where the problem could be:(  

I also tried to shift the calling of restTImes.get() to Done event as well (tried to put in the constructor of Done event, and in the NextEvent() method) but all give the same error.

thanks in advance!!

## Screenshots
<img width="536" alt="Screenshot 2023-03-21 at 1 31 40 PM" src="https://user-images.githubusercontent.com/122260950/226526096-948233e3-816d-4be7-b982-ced7a06f3078.png">

<img width="540" alt="Screenshot 2023-03-21 at 1 30 10 PM" src="https://user-images.githubusercontent.com/122260950/226525900-16e7f75f-0a99-4cca-a40a-0bc0fdbdc8e7.png">

**Comment by calvnleong** [comment]
The only thing I can think of right now would be that when creating the serve event, you are using a server that is not updated to rest yet. This could happen if your constructor for serve takes in a serverList or a server, and you are using the the non updated version of serverList or server. The serverList in the simulator class may be updated but the one that you input while creating the Serve event may be different, causing the starttime of the Serve event to differ

**Comment by tallkoh** [comment]
i think your rest time is updating wrongly

**Comment by ngshiyingg** [comment]
hi thank you all, turns out my mistake was --> In Simulator class, I had a check whereby if the event does not have a next event, the next event will not be added back to pq, and I accidentally placed my serverUpdate line in this if block. Since my server update for the rest time is in my RestEvent and my RestEvent returns false for the next event check, the server time is not updated by the rest time. hope this helps!
