### ISSUE TITLE
toString() implementation

### ISSUE THREAD

**Issue by sethteo** [nus-cs2030/2223-s2#512]
Hi currently for my toString I was thinking of using map.entrySet.size() in order to decide when to add "," or to end the toString with a  "}"  for my KeyableMap however I think its restricted?

<img width="326" alt="Screenshot 2023-03-21 at 2 39 49 PM" src="https://user-images.githubusercontent.com/119569146/226534613-0b66a4cf-6166-432a-b621-76a1a6d689c7.png">

If so may I get some ideas on how else to generate the toString()

Thanks everyone in advance !!

**Comment by shakerfries** [comment]
hello, you might want to follow the code given in the pdf u would not need to import set.

**Comment by prisciliapangg** [comment]
You might want to try importing map instead and if I am not wrong, you cannot use .entrySet()

**Comment by Delocy** [comment]
you can try using map.entry for the for loop

**Comment by jiangen16** [comment]
hi i encountered the same issue, entrySet() is not allowed.  you can try this method, given in the question

for (Map.Entry<String,Integer> e: map) {
   ...>    .....

**Comment by ryantangmj** [comment]
You might have used entrySet() somewhere in your code

**Comment by ouhznay** [comment]
you can try using an integer counter to keep track of which string you are printing & use if-else statements to decide whether to add the comma or not

**Comment by sethteo** [comment]
Thanks all! Solved :)
