### ISSUE TITLE
Lab 5 Cyclic Dependency

### ISSUE THREAD

**Issue by prisciliapangg** [nus-cs2030/2223-s2#513]
I tried to create a new SelfCheckOut Class but faced this error, anyone knows what could be wrong? Thank you!

<img width="354" alt="Screenshot 2023-03-21 at 3 23 14 PM" src="https://user-images.githubusercontent.com/123915785/226542919-e2e05615-c36d-4f6b-80ca-1ad28bcd9b0f.png">

**Comment by shakerfries** [comment]
hello! ive faced this error too! do you maybe want to check whether you did your child-parent rs correctly? did u override all the existing methods???

**Comment by prisciliapangg** [comment]
> hello! ive faced this error too! do you maybe want to check whether you did your child-parent rs correctly? did u override all the existing methods???

Hmmmm, okay! I will check it. Thank you!

**Comment by bevteo** [comment]
Hi I'm currently facing the same issue and I've already overrided all the existing methods. Is there anything else that can be causing the cyclic dependency. Currently my implementation involves the SelfServer extending from the original Server class
