### ISSUE TITLE
Lab 6 level 1

### ISSUE THREAD

**Issue by jianjiezzz** [nus-cs2030/2223-s2#514]
For .get(), I am thinking to use the key to access the map within my module --> create a new assessment and wrap it back in optional.
But when i do this.map.get(key), i get a optional value of String. How do I get like the value and not the optional value? Very confused :O

**Comment by 0liverkong** [comment]
you shouldn't need optional in level 1,unless this is for other levels...?

**Comment by 0liverkong** [comment]
you shouldn't need optional in level 1,unless this is for other levels...?

your module should store a map that takes in key string and value assessment, and your assessment should have a toString() override
