### ISSUE TITLE
failing test case 6 lab 6 out of bound

### ISSUE THREAD

**Issue by sporobolous** [nus-cs2030/2223-s2#516]
<img width="833" alt="Screenshot 2023-03-21 at 6 36 36 PM" src="https://user-images.githubusercontent.com/110991431/226581872-b3ec7bb5-9ee0-4c59-8660-d736b01f4833.png">

I thought it would be the query part of level 6 so I changed and has a sc.hasNext(). 

could it be that my issue is when I take in int I used sc.nextInt()?

**Comment by sporobolous** [comment]
wait sorry I tried googling with using Integer.parse___ and it worked. Can someone explain why is this so? I understand that sc.nextInt() takes in the int, could it be that the input of the user is via the next line and that I have to consider that?

**Comment by 0liverkong** [comment]
are you following the Main.java from the lab slides? if so then you just need sc.next() to store the queries.

**Comment by sporobolous** [comment]
ahh right, thanks! I guess it was out of habit 1010j!
