### ISSUE TITLE
lab 6 level 1

### ISSUE THREAD

**Issue by jianjiezzz** [nus-cs2030/2223-s2#517]
Is my implementation correct? I was doing halfway and doesnt feels rite :(

Assessment 
    -String name
    -String grade
Module
    - String name
    - ImmutableMap<String,String> assessmentmap

**Comment by justineeyx** [comment]
for module, shld be immutablemap<string,assessment>

**Comment by jianjiezzz** [comment]
> for module, shld be immutablemap<string,assessment>

I think I don't get how a module store multiple assessment then? like what is the keys for the assessments?
