### ISSUE TITLE
Ex 4 Level 6

### ISSUE THREAD

**Issue by wongjingwen** [nus-cs2030/2223-s2#521]
![Screenshot 2023-03-21 213938](https://user-images.githubusercontent.com/120257984/226623776-e5d9d34c-4ad8-4105-8722-4a7e6fdfa408.jpg)

Hi, the isEmpty() method cannot be called by the var other since it is private.  Is there other way we can return a boolean value (i have tried using the or method but iam only able to return a ? extends T and not T itself

**Comment by fy17ohhh** [comment]
try using orElse()

**Comment by wongjingwen** [comment]
I have tried orElse() but it returns a ? extends T

**Comment by granolaluvr69** [comment]
The map, filter and orelse methods will come in handy here.

**Comment by wongjingwen** [comment]
> > Your orElse method in maybe class should return T
> 
> My orElse returns a T. I m not able to extract the value in the supp.get()
