### ISSUE TITLE
Lab 6 Level 5: how to override the existing record?

### ISSUE THREAD

**Issue by j0205m** [nus-cs2030/2223-s2#523]
for my level 5 implementation i used orElse() to check for existing key, and if it does i put new Student/Module/Assessment inside accordingly. however, i'm not sure how i can go about updating the current roster by replacing/adding the new values inside without losing previous inputs in the case where the studentName is already inside the roster. any help is much appreciated!

**Comment by e0970430** [comment]
i did the same method as you! and then after i generated the updated/new student, since my put method uses the key to get the initial value from the immutable map and replaces the value in the immutable map (if any) with the updated value, i just used the roster's put method to put the student into the map

**Comment by dlyxxx** [comment]
what i did was to create a new method called remove in the keyable map which removes an item from the immutable map, e.g. my remove method in Module takes in an Assessment to be removed and returns a new Module without that assessment. Then i simply call remove(Assessment) and then put the new assesment in

Not sure if this is the most efficient way but it works!

**Comment by j0205m** [comment]
> i did the same method as you! and then after i generated the updated/new student, since my put methods uses the key to get the initial value from the immutable map and replaces the value in the immutable map (if any) with the updated value, i just used the respective put methods to put the assessment into the module, module into the student, then student into the map

<img width="735" alt="Screenshot 2023-03-22 at 01 03 49" src="https://user-images.githubusercontent.com/124303065/226686575-4e0eb12e-136a-46d4-8241-4e093c47a1af.png">
is your implementation something similar to this? currently im passing all test cases for level 5 but the roster is not updated accordingly when it comes to level 6... really unsure of what went wrong

**Comment by j0205m** [comment]
thanks everyone
