### ISSUE TITLE
Lab 5 Test Case 9_03 (Lab 5.1)

### ISSUE THREAD

**Issue by rshalinisai** [nus-cs2030/2223-s2#524]
I pass the 3 public test cases but I'm failing the test case 9_03.

![image](https://user-images.githubusercontent.com/122519417/226688817-68ec1696-df3d-474a-83b2-b965b7350e38.png)
![image](https://user-images.githubusercontent.com/122519417/226688913-c81676de-c720-4b9f-88df-2dcdd4f31c74.png)
![image](https://user-images.githubusercontent.com/122519417/226688978-5fe1546a-2b91-49b6-a084-9d549ce6cddd.png)

did anyone else face this issue/ how did u resolve it, thank you!

**Comment by trwstin** [comment]
#518
