### ISSUE TITLE
lab 5.1 - how to start? - seed, probability

### ISSUE THREAD

**Issue by gracico** [nus-cs2030/2223-s2#526]
# Summary
## Description:

I am really confused about the seed part. Tried finding info regarding seeds at the java.util.random api but i cant seem to find anything useful. 

can someone enlighten me regarding this, are we supposed to just use the 1L seed to generate all the rest times or must we create a seed for each server?

> Notice that the first random value generated right after seeding with the same seed (here we use the long value representation of one, or 1L) is always the same. Hence, every unique seed provides a unique sequence of random numbers via subsequent calls to nextDouble().

Also, any tips on implementing the probability ?

**Comment by koiljat** [comment]
hi you do not need to worry about the seed at all. think of the rest time as simply as supplier that gives a value. hence all you need to do is to call the `get()` method of the supplier at the correct event to simulate the resting of the server.

**Comment by secretApple** [comment]
the implementation for getting rest time is almost exactly like what lab 3 required for servicetime, except the location of the methods, so like above said there's no need to know anything about the seed

**Comment by meljwang** [comment]
The service time and the rest time are defined in the Main class which you don't really have to worry about, you just need to call the get() method correctly in the respective Event classes.

**Comment by Maxxtucker** [comment]
Seed is for the codecrunch to check your answer. You don't have to is

**Comment by haqanh** [comment]
hi! you don't need to worry about the seed and probability - they should all be provided in the Main.java file and the codecrunch test cases already. You just have to build classes to work with the Main output - think of it like a black box like in lecture!

**Comment by Delocy** [comment]
You dont need to worry about that, you just need to pass in the supplier into ur server and then create a .get inside

**Comment by tallkoh** [comment]
you can ignore that, just understand how to use supplier (which presumably you should understand if u could get the servicetime supplier right)

**Comment by gracico** [comment]
thanks guys, my badd. I wasn't in the right mind and didn't check the main file
