### ISSUE TITLE
Lab 6 Level 6

### ISSUE THREAD

**Issue by xz-tan** [nus-cs2030/2223-s2#527]
Are we not allowed to use Optional.get() and Optional.isPresent() in our code? This is the error I get from CodeCrunch.
![image](https://user-images.githubusercontent.com/92637532/226803849-50ecbc3a-6ab8-447d-bb34-870b5762ad9d.png)

**Comment by sethteo** [comment]
Optional.get() , Optional.isPresent() is banned on codecrunch you can try using orElse() instead :)

**Comment by clarwen** [comment]
orElse() works!
