### ISSUE TITLE
Lab 6 Level 6: roster not updating properly

### ISSUE THREAD

**Issue by j0205m** [nus-cs2030/2223-s2#530]
when i manually add each input into my jshell the roster is updated correctly, but when i pass into codecrunch somehow there's a problem updating it (used println to see whether the roster is updated accordingly). does anyone know what's going on T_T i have changed my implementation for level 5 a few times too but it still gives the same error

<img width="604" alt="Screenshot 2023-03-22 at 13 49 02" src="https://user-images.githubusercontent.com/124303065/226814442-6c7f160a-11b8-4e92-a911-de6355c942fc.png">

this is the current implementation for updating the roster in my main class
<img width="1463" alt="Screenshot 2023-03-22 at 13 42 37" src="https://user-images.githubusercontent.com/124303065/226814289-eae571c0-43bc-4a4d-9b3e-e1f3977c70c8.png">

**Comment by stxe09** [comment]
after you've added students to the roster, you need to add another loop to get their grades, with roster.getGrade().
so your output will be grades rather than the roster.

**Comment by j0205m** [comment]
> after you've added students to the roster, you need to add another loop to get their grades, with roster.getGrade().
> so your output will be grades rather than the roster.

yes i do have an additional loop below! but the problem lies in this part of my code as my roster is not updated properly...

**Comment by trickypepe** [comment]
Hi, maybe you can check if inputting in your terminal (not jshell) like:   java Main<1.txt   works? 
Copy the input into some text file then print roster from your Main and check if the roster is correct. 

Maybe you can also println() some logic statements to ensure that your check for student exists is working as intended. I had a similar issue and when I assigned studentName = sc.next(), I printed (studentName == "Jack") and found out it was false even for the first 2 lines, so I had to fix that. Depending on implementation you might have to print something different.

Also discussion in [500](https://github.com/nus-cs2030/2223-s2/issues/500) might help

**Comment by xz-tan** [comment]
Personally, I didn't use sc.nextLine(). I think sc.next() is enough as it will go to the next input automatically!
