### ISSUE TITLE
Lab 5.1 - NoSuchElementException?? 

### ISSUE THREAD

**Issue by calista03** [nus-cs2030/2223-s2#535]
Hi guys, when I try to run my code using the given testcases, I keep facing this issue: 

![Screenshot 2023-03-22 at 6 41 49 PM](https://user-images.githubusercontent.com/124029739/226879035-12776698-62bf-4d70-88cd-23ae56567fd1.png)

I am really not sure what the problem is here, I've looked through all my classes and nothing seems to be wrong. When I submit my files on codecrunch, the output is correct, but when I test it on my own computer this happens. This makes it really difficult for me to test out my code and debug on my own.....has anyone faced the same issue? Can someone please give me some advice? Thank you so much!

**Comment by calista03** [comment]
This issue somehow disappeared immediately after I tried again after posting this query......but it wasn't working for the past day.....

**Comment by easypzlemonsqueezy** [comment]
hi! i had the same issue but it disappeared after resubmitting my files for whatever miraculous reason, i'm not too sure why this happens too
