### ISSUE TITLE
Lab 5.2 Test Case 16

### ISSUE THREAD

**Issue by kevincgm** [nus-cs2030/2223-s2#536]
Anyone run into this problem of a customer just disappearing into a black hole and never to be seen again; specifically customer 12.

<img width="442" alt="image" src="https://user-images.githubusercontent.com/93082361/226906225-3f26d312-73d9-463c-9cd5-73f66bd07a3c.png">

I believe this 1 guy disappearing is messing up all the subsequent events cos the queue at server 1 won't move, as well as the supplier will supply the wrong service time to all the customers that follow. Any suggestion is appreciated! Thankss

**Comment by leonardwx** [comment]
hi, i think you need to check all the conditions of the event and ensure the servers/customers are being updated according to the particular event. Based on the testcase, i think u might have missed out some updating of list

**Comment by kevincgm** [comment]
Thanks for the input! Managed to find the bug between my Wait event and Buffer event that comes before the Serve event. Was just surprised it passed all the test case from 5.1 initially so I thought there was no more bug for that part of the code. Thank you!
