### ISSUE TITLE
Lab 5.2 Test Case 9_11

### ISSUE THREAD

**Issue by Blackknight25** [nus-cs2030/2223-s2#537]
Hi, does anyone face this issue where the events are jumbled up even after using the comparator? Could it be because the events with the earlier times were generated later and how can I solve this,,, thank you
<img width="622" alt="Screenshot 2023-03-22 at 10 38 19 PM" src="https://user-images.githubusercontent.com/109853328/226938861-034010b6-bdb3-4c7d-9042-307121b0cc53.png">

**Comment by trwstin** [comment]
![image](https://user-images.githubusercontent.com/68576751/226995329-330605f4-7887-45ff-a4c5-252141165a4b.png)

this kinda looks like you made an oopsie with your service times
