### ISSUE TITLE
level 4 issue with flatmap()

### ISSUE THREAD

**Issue by ouhznay** [nus-cs2030/2223-s2#539]
# Summary
I can't compile my Roster Class due to my getGrade() method. the error Can't find symbol keeps occurring even when I imported the optional package and also returned the optional type for my get() methods. not too sure what is causing the issue here 
for the screenshot:
method: getGrade() in Roster
this - roster instance
id - student name
code - module code

## Description:

Clarifications or details with respect to the issue you are facing

## Code Snippets

Attach code snippets (if any)

## Screenshots
<img width="647" alt="Screenshot 2023-03-23 at 12 19 07 AM" src="https://user-images.githubusercontent.com/109010856/226970172-9365ae82-90ca-4903-9681-f456fdabb9c3.png">

Screenshots (if any)

**Comment by oofpouf** [comment]
M  in "flatMap()" should be capitalized
