### ISSUE TITLE
java.util.set not allowed

### ISSUE THREAD

**Issue by gi2328** [nus-cs2030/2223-s2#540]
# Summary

Why am I getting this error when it is in the ImmutableMap?

## Screenshots

<img width="719" alt="Screenshot 2023-03-23 at 12 52 37 AM" src="https://user-images.githubusercontent.com/113605010/226979876-ea6fe42a-611b-48ac-89c9-f290754c7aff.png">

**Comment by weitatftw** [comment]
did you use keySet() in your code?? keySet returns a set which could be triggering this error

**Comment by xz-tan** [comment]
Cannot use entrySet() when iterating through the ImmutableMap! Use for (Map.Entry<String,Integer> e: map) instead.

**Comment by ayevxn** [comment]
I faced this same issue because I used keySet(), I had to change my add method. You can consider using orElse method in navigating the logic instead of brute forcing your way through (which I originally tried to do).

**Comment by guanquann** [comment]
Follow the documentation from the lab pdf to iterate it
