### ISSUE TITLE
Ex 4 Level 5

### ISSUE THREAD

**Issue by calvnleong** [nus-cs2030/2223-s2#543]
Is there an underlying assumption that the Function that is passed into flatmap() would not return a Maybe<Maybe<R>>? Below is a code that runs if the function that i pass into flatmap returns a Maybe<Maybe<R>>

If the assumption is true then i guess my code will work fine, but if not, am i supposed to use recursion to solve this problem? I saw some hints given on github but I still can't seem to get a code that works if the above assumption is false.
<img width="800" alt="image" src="https://user-images.githubusercontent.com/124434962/227094921-054fa644-0459-4689-97ec-bc4a965c49d2.png">

**Comment by yugan01** [comment]
I believe your assumption holds. I think the functions that are passed into flatMap returns a Maybe<R> 
not Maybe<Maybe<R>>
