### ISSUE TITLE
Lab 6 Test case 4 error

### ISSUE THREAD

**Issue by hello-world-cell** [nus-cs2030/2223-s2#546]
I am unable to pass test case 4 for lab 6. Could anyone help with pointing out where the error might be?

<img width="876" alt="Screenshot 2023-03-23 140447" src="https://user-images.githubusercontent.com/67591893/227118474-14c65062-41ba-46df-ab42-48c75e51d7cf.png">

**Comment by sethteo** [comment]
<img width="660" alt="Screenshot 2023-03-23 at 2 28 00 PM" src="https://user-images.githubusercontent.com/119569146/227121559-9fa7a94c-ef88-48b3-98e3-f6238f321756.png">
the inside of your getGrade() should look something like this (replace the values of the flatmap) where you can make use of an orElse in the case that the grade is not found or just returning the grade if found

**Comment by hello-world-cell** [comment]
> <img alt="Screenshot 2023-03-23 at 2 28 00 PM" width="660" src="https://user-images.githubusercontent.com/119569146/227121559-9fa7a94c-ef88-48b3-98e3-f6238f321756.png">
> 
> the inside of your getGrade() should look something like this (replace the values of the flatmap) where you can make use of an orElse in the case that the grade is not found or just returning the grade if found

this is how my getGrade method() looks now
<img width="550" alt="image" src="https://user-images.githubusercontent.com/67591893/227122518-4d2a10dd-02d1-4b58-b3d1-3abb4e32545b.png">

**Comment by sethteo** [comment]
mcode and atitle are variables so you shouldnt enclose them in "" if not it will be computed as a string resulting in you unable to find the module/assessment :)

**Comment by hello-world-cell** [comment]
> mcode and atitle are variables so you shouldnt enclose them in "" if not it will be computed as a string resulting in you unable to find the module/assessment :)

omg thank you, i completely overlooked that
