### ISSUE TITLE
Lab 6 level 1 output

### ISSUE THREAD

**Issue by tryngmyhardest** [nus-cs2030/2223-s2#547]
not sure why my output is like this, any advice? thanks

![695C24CA-4255-4DF5-A379-2A364B31B6E3](https://user-images.githubusercontent.com/127404598/227118808-097b28c2-b6ff-4946-861f-c7e893a74c77.jpeg)

**Comment by sethteo** [comment]
e.getValue() is enough for your loop dont have to use e.getKey() ":" e.getValue() 
hope it helps :)

**Comment by tinghwei** [comment]
You shouldn't be using ImmutableMap's toString() method. Instead, you need to create a for loop (which is shown in the example) to loop through the ImmutableMap of Assessments and call getValue() each time

**Comment by koiljat** [comment]
In your toString() implementation you can call the value of the the record directly.

**Comment by hcyrr** [comment]
hi all, does put return a String or immutablemap?

**Comment by territxl** [comment]
yep! thats why the put is an overriding method since it has to return a Student etc. you can refer to the test case given where natasha = natasha.put(...)

**Comment by tryngmyhardest** [comment]
thanks everyone! can i ask whats the correct for loop i shld use?
ive tried (Map.entry<String,Assessment> entry: this.map) { 
but i get an error cannot convert from element type Map.Entry<String,Assessment> to Map.entry

**Comment by tinghwei** [comment]
@tryngmyhardest it shld be Map.Entry<.....> with a capital E ! i made the same mistake too hahaha
