### ISSUE TITLE
Lab 6 Level 3

### ISSUE THREAD

**Issue by eesean** [nus-cs2030/2223-s2#549]
Hi all,

Whilst compiling KeyableMap I received a warning of unsafe or unchecked operations, which happens when I have raw types. Not really sure what raw types means but generics is required for KeyableMap, so how should I go about fixing this?

**Comment by ugchongg** [comment]
hi, I am facing the same issue, may I ask what is the difference between KeyableMap object and KeyableMap?

**Comment by eesean** [comment]
Hi sorry I think I can elaborate abit further on what I meant.

Essentially because KeyableMap takes in any class V that extends Keyable, we need to write the following:

KeyableMap<V> method()

instead of 

KeyableMap method()

because KeyableMap is a raw type. When using raw types, java does not check for type error during compile time hence we receive the warning. Hence it is necessary to do type witness by including generic type V encased in <> when defining the return type.

Hope my explanation makes sense! There is a similar post on this too #557
