### ISSUE TITLE
Lab 5.2 Test Case 9_9

### ISSUE THREAD

**Issue by lsy8117** [nus-cs2030/2223-s2#551]
# Summary

Not sure what is wrong here since the complete output is also not shown on codecrunch

## Description:

Might be problems associated with order or customer being served? but not very sure actually
I in the event after Wait and before Serve I have ensured thatthey will check the next available self chekout counter, but still there's some problem here

## Screenshots
![Screenshot 2023-03-23 at 3 55 29 PM](https://user-images.githubusercontent.com/123756364/227138644-e0836a39-98e8-407e-a739-bd3e135cc014.png)

**Comment by lsy8117** [comment]
And also any idea how many private test case they have for 5.2 T_T just want to get a hint on how far away I am right now

**Comment by cheng-yee** [comment]
It looks like the order that you call Supplier's .get() method for service time could be wrong. If you have passed all test cases till 5.1, your implementation of self-check could be mixing up the order.

**Comment by lsy8117** [comment]
> It looks like the order that you call Supplier's .get() method for service time could be wrong. If you have passed all test cases till 5.1, your implementation of self-check could be mixing up the order.

Thanks that's the reason! problem solved:))
