### ISSUE TITLE
Lab 6 Test case 2

### ISSUE THREAD

**Issue by jamiepngg** [nus-cs2030/2223-s2#552]
uh not sure why i have this error?? help

<img width="1346" alt="Screenshot 2023-03-23 at 4 10 45 PM" src="https://user-images.githubusercontent.com/122249338/227141722-e1f36524-1bee-40c2-a564-51f7c7afdcef.png">

**Comment by reinatng10** [comment]
Hi Jamie, maybe you want to check ur file directory

**Comment by jamiepngg** [comment]
@reinatng10 Hi reina, you're right. turns out i was missing a file that i moved around. thanks!
