### ISSUE TITLE
Lab6 level 6

### ISSUE THREAD

**Issue by alvintjw** [nus-cs2030/2223-s2#554]
# Summary
Hello, when I manually input the roster using jshell and my classes, the output is correct but when I try to input the test case into Main, the roster does not seem to be added correctly? Is there something wrong with the way I am scanning for input? thanks for the help:)))
Description of the question / problem here.

## Description:

Clarifications or details with respect to the issue you are facing

## Code Snippets
![Screenshot 2023-03-23 at 4 37 39 PM](https://user-images.githubusercontent.com/65883895/227147798-947d68d6-95e2-4765-a686-3c48ab132b8c.png)
![Screenshot 2023-03-23 at 4 37 53 PM](https://user-images.githubusercontent.com/65883895/227147848-9dbcce46-af00-4108-895d-f6c2a0ccaf95.png)
![Screenshot 2023-03-23 at 4 38 04 PM](https://user-images.githubusercontent.com/65883895/227147894-126697b9-1314-461f-a96c-a669c7410f77.png)

Attach code snippets (if any)

## Screenshots

Screenshots (if any)

**Comment by yugan01** [comment]
i'm not too sure if this helps but you can try deleting the sc.nextLine() on line 8 and the sc.next() on line 19. I believe the issue is with the sc.next() on line 19, as it goes to the next variable.

**Comment by alvintjw** [comment]
@yugan01 Hi yugan thanks for the help. it was just a logical error in my while loop HAHAHAH
