### ISSUE TITLE
fork: retry: No child processes 

### ISSUE THREAD

**Issue by Ma-Xizi** [nus-cs2030/2223-s2#555]
# Summary

Good afternoon everyone! I have been polishing my lab5.1 by removing the unused getters(getCust() and getSer()) in event classes and type attribute in event classes("Wait"). However, the changed version encountered such error messages on codecrunch : /tmp/run-AZmJYY: fork: retry: No child processes
/tmp/run-AZmJYY: fork: retry: No child processes
/tmp/run-AZmJYY: fork: retry: No child processes
/tmp/run-AZmJYY: fork: retry: No child processes
/tmp/run-AZmJYY: fork: Resource temporarily unavailable

Has any person encountered similar issues? My changed code is perfectly compilable and functional on my terminal so I am not sure how I can debug.

## Description:

Clarifications or details with respect to the issue you are facing

## Code Snippets

Attach code snippets (if any)

## Screenshots

Screenshots (if any)

**Comment by secretApple** [comment]
Hello i faced the same problem for lab 6, but the issue went away when I uploaded the exact same files but after around an hour for some reason

**Comment by Ma-Xizi** [comment]
Thanks everyone! My TA said the codecrunch server was down earlier this afternoon. After reuploading, it was okay!

**Comment by ronnymuffins** [comment]
hi everyone, am encountering the same problem now, anyone knows if the codecrunch server is down now?
