### ISSUE TITLE
Lab 3 (Problems with updating server's next free time)

### ISSUE THREAD

**Issue by chianxintong** [nus-cs2030/2223-s2#556]
# Summary

1. Problem 1: Updated Server's nextFreeTime in ServeEvent, but updated nextFreeTime is not reflected in QueueEvent. 
2. Problem 2: Hmm somehow my implementation will cause .simulate() to look through each event twice, but only one toString() per event is printed... this is not normal right?

Has anyone encountered such problems before?

## Description
My thought process: when cust joins queue of server ARRIVE -> WAIT -> QUEUE -> SERVE -> DONE
Attributes of each event: customer, serverNo, timeStamp, serverList
- ARRIVE just returns WAIT event, with serverNo of the server that cust is queueing at
- WAIT returns QUEUE event, serverList updated since a customer is added to serverQueue) this is done by using .set() for serverQueue
- QUEUE: if customer is the first customer in the queue, I will return a SERVE event (with timestamp of nextFreeTime of server). Say customer 2 is the first customer of the queue, and server 1 is currently serving customer 1 (with arr time of 0.5), server 1 will serve customer 2 at 1.5, which explains why a timestamp of nextFreeTime is used when I return a new SERVE event. 
- SERVE: only updates serverList with new nextFreeTime (this is done by super.timeStamp + super.cust.getServiceTime()) - only time where getServiceTime() is called + .remove(0) to remove first customer from serverqueue if any
- DONE: ya done! 

## Code Snippets

This is a while loop under .simulate() method of my Simulator class. ServerList was initialised outside the while loop and constantly updated. My next() method of each event generates a pair, consisting of the subsequent event and most updated serverList. Then, next() method of each event from PQ will make use of updated serverList each time... - could this be the reason why .simulate() loops through each event twice?
![image](https://user-images.githubusercontent.com/122260095/227167126-44e0bcfe-8851-41f0-b886-4f64ae8db4a1.png)

## Screenshots

I used system.out.println to print the timestamp of every event, and server's nextFreeTime in QueueEvent and ServeEvent respectively. It can be seen that the nextFreeTime of the server after serving customer 1 should be 1.5, but it somehow went back to 0.6 when looking at the QueueEvent of customer 2. send help...
![image](https://user-images.githubusercontent.com/122260095/227170077-cea32fe9-d670-4e4d-8b13-0887f6aedc5a.png)

Thank youuuu :")

**Comment by hcyrr** [comment]
hi, regarding the generating too many service time problem, i think u should make sure that u only generate a service time for a customer in the serve event, and only generate it exactly once for each customer

**Comment by niclee1219** [comment]
you should only generate getservicetime once during serve

**Comment by koiljat** [comment]
hi, you should only call the get method of the supplier when you call the serve event
