### ISSUE TITLE
No child processes

### ISSUE THREAD

**Issue by prisciliapangg** [nus-cs2030/2223-s2#559]
Hello, does anyone know what this means? Thank you in advance!
<img width="525" alt="Screenshot 2023-03-23 at 8 24 13 PM" src="https://user-images.githubusercontent.com/123915785/227202889-00629dd4-d841-40a9-a520-7193d899e30c.png">

**Comment by lershuan** [comment]
I'm having the same problem now

**Comment by lershuan** [comment]
> is it related to polymorphism?

Codecrunch was just wonky! resubmitted after a few minutes and it works fine!
