### ISSUE TITLE
Test Case 9_01 Private Cases: Customer leaving instead of waiting in queue

### ISSUE THREAD

**Issue by kcslllll** [nus-cs2030/2223-s2#561]
## Description:

Currently Customer 10 is leaving when it should be waiting at server 2. Anyone have any tips or advice to give to tackle this issue/problem? Thanks so much! :)

## Screenshots

<img width="589" alt="image" src="https://user-images.githubusercontent.com/122248706/227270049-06a8cdf5-d316-42ac-bb10-d987deda6041.png">

**Comment by meljwang** [comment]
It seems that your server queue for 2 is full when it shouldn't be full. You should check if, for each event, you are using the most updated state of the server. You should also check if your customers are leaving the server queue properly when it is their turn to be served. Hope this helps!

**Comment by leonardwx** [comment]
it appears that maybe your server 2 queue is full, which results customer 10 to leave instead. try to create print statement to debug and check whether the enqueue/dequeue methods are updated once wait the customer waits/leaves
