### ISSUE TITLE
error in student extends keyablemap

### ISSUE THREAD

**Issue by hcyrr** [nus-cs2030/2223-s2#563]
# Summary
not sure why is there this error, this is how i implemented my student class:
class Student extends KeyableMap < Module > implements Keyable
any help will be appreciated thank youu

![02CE65B3-2C77-4F2D-A720-7950E1041AAA_4_5005_c](https://user-images.githubusercontent.com/126330380/227279351-14e11751-66e2-4bc2-a1bc-17d32c106550.jpeg)

**Comment by hcyrr** [comment]
@WXUXIN class KeyableMap<V extends Keyable> implements Keyable

**Comment by hhuilingg** [comment]
hello! u are right that your student class will need to extends KeyableMap<Module> however u do not need to implement Keyable as that is already done in your KeyableMap class. hope it helps!

**Comment by hcyrr** [comment]
@WXUXIN Oh i typed (V extends Keyable) (replace () with <>) not sure why the arrow brackets keep disappearing on me here, but basically i typed the same thing but this error still resurfaces..

**Comment by shannon-jx** [comment]
does the error still show after adding <V extends Keyable> and removing "implements Keyable"?

**Comment by gene2345** [comment]
does your keyableMap compile with no errors?
