### ISSUE TITLE
LAB 5 TEST CASE 9_11 MESSED UP QUEUE

### ISSUE THREAD

**Issue by pnghaanh** [nus-cs2030/2223-s2#566]
# Summary

QUEUE GOT MESSED UP AT SELF-CHECK COUNTERS

## Description:

Somehow, even though 13 and 14 are still in the queue, 15 gets served first. I think I messed up at updating the queue for self-check, but not sure how to check for it. I update the self-check queue at PendingEvent, should I update it at ServeEvent for self-check instead? Any help is appreciated. 

![Picture1](https://user-images.githubusercontent.com/124126901/227304460-a6694fc6-f985-4b6a-8fd5-6f8879979e62.png)

**Comment by leonardwx** [comment]
hi did you ensure the single queue for self check was updated properly? also, rmb to use the lowest availability of the self check counter, (not the first index of the selfcheck) and update the wait event

**Comment by maze508** [comment]
I think you shouldn't think of it as should I check it at a certain event but your checking should be done when certain state changes are made.

**Comment by shannon-jx** [comment]
for me i update my queue in both my Wait class and my Serve class when customers leave and join the queue. try to also check if your events are leading to the next event correctly

**Comment by chanjieru** [comment]
make sure that all your self-check queues are updated together, since they share the same queue

**Comment by kciruos** [comment]
It is generally due to not accounting for state changes when checking to ensure all the updates are done correctly. You can try code tracing to figure out the flow of your next events.

**Comment by littlemidget3** [comment]
to debug, what u can do is to print the state of your queue. But anyway the idea is to ensure u return ur updated serverQ in each event

**Comment by gracico** [comment]
hi you may want to print the state of your queue along with the event it is from to trace your code! thats what i did to debug mine. oh and you could also print the string output in every iteration of the while loop!

**Comment by e0969489** [comment]
hi i experienced this problem also! I made sure that all my self check queues are updated together!

**Comment by keshialimm** [comment]
> hi did you ensure the single queue for self check was updated properly? also, rmb to use the lowest availability of the self check counter, (not the first index of the selfcheck) and update the wait events

Hi! can I check how I should implement this? I'm not too sure how to go about to find the self checkout w the earliest available timing.. right now I'm just using the first index that is free.

**Comment by thwhoai** [comment]
I think mine is doing this but I still face this same issue TT

**Comment by thwhoai** [comment]
Hi I SOLVED IT. and my problem was that after WaitEvent, I generate a Pending Event with the time that the server is BusyUntil (which is later than the earliest next available time for self checkout). I just change the new PendingEvent(server's busy until time.   ) to PendingEvent(this.time.    ) (I have earliest next available time built into PendingEvent class)
Hope this help i'm done with this 5.2 im so happy

**Comment by pnghaanh** [comment]
solved! thanks everyone
