### ISSUE TITLE
Lab 5.1 test case 9_04

### ISSUE THREAD

**Issue by eesean** [nus-cs2030/2223-s2#568]
Hi all,

I have been getting time limit exceeded for this test case even though I have been trying to get the program to run faster. I heard that exceeding time limit is caused by number of iterations and infinite loops (which I have been reduced as much as I could / checking frequently), I was wondering whether there are other factors that could cause time limit to be exceeded?

**Comment by shannon-jx** [comment]
not sure if u already checked for this but nested loops contributed a lot to time limit exceeded for me in the past! do watch out for them

**Comment by gene2345** [comment]
usually it occurs if you return too many wait / waiting class (depending on your implementation). the best way to check what is causing this loop is to print a toString() for each event class so you can see what is actually being called at what time

**Comment by eesean** [comment]
Hmm so far my implementation has only 4 iterations in the simulation, the first two iterations are prior to the polling of events when I create a list of servers and the starting priority queue of arrive events. The other 2 iterations are in my arrive event, during which I start by searching for available servers, then search for available queues in another loop. These 2 iterations are not nested.

Regarding the wait event class I create new wait events when I add the customer into the queue, and when the corresponding customer is at the front of the queue but the server is not available (so as to account for waiting time). Not sure whether this is the cause of the issue?

**Comment by e0968868** [comment]
You probably want to check if theres an infinite loop present in your code as that's what caused the error for me, even though i had nested loops too

**Comment by eesean** [comment]
Update: Thanks for pointing out that I have an infinite loop! Was careless as I found out that my leave event is still added to queue haiz
