### ISSUE TITLE
Exercise 2 Level 5

### ISSUE THREAD

**Issue by EpicSpirito** [nus-cs2030/2223-s2#57]
Are we only allowed to modify `level3.jsh`? Can I add more methods in other classes or create a new class called `RecycledLoader` instead? Thanks!

**Comment by trwstin** [comment]
Should be fine, I modified both level3.jsh and methods in other classes without encountering problems.

**Comment by EpicSpirito** [comment]
Okay, thanks! :)

**Comment by e0959170** [comment]
you should be able to add the methods in other classes provided you are able to access them from wherever you are calling the method
