### ISSUE TITLE
GetServiceTime() returning wrong value?

### ISSUE THREAD

**Issue by llaamaaa** [nus-cs2030/2223-s2#571]
# Summary

Hi, not sure where my code went wrong- service time supplier is giving different value :( any help would be appreciated! thanks!

## Description:

Clarifications or details with respect to the issue you are facing

## Code Snippets

Attach code snippets (if any)

## Screenshots
<img width="431" alt="Screenshot 2023-03-24 at 12 03 19 PM" src="https://user-images.githubusercontent.com/121176189/227421484-3fb41ed9-0f2e-41e4-9078-6f18c6744019.png">

Screenshots (if any)

**Comment by leonardwx** [comment]
hi! i think you should put **this.serviceTime** in the customer instead of creating a supplier double in your customer.
For eg. Customer cus = new Customer(...... ,this.serviceTimes)

**Comment by kaiyanggg** [comment]
Hi, can try to check if you are calling the supplier correctly. Can call the customer's getServiceTime method in the serve event class. Another thing u can do is to make sure you followed the implementation of the supplier in the customer class as per documentation as well.

**Comment by pylfmty** [comment]
not sure if it helps but i have a DefaultServiceTime.java 

import java.util.function.Supplier;

class DefaultServiceTime implements Supplier<Double> {
    public Double get() {
        return 1.0;
    }
}
