### ISSUE TITLE
need help in collecting the waittime, failing 9_03

### ISSUE THREAD

**Issue by sporobolous** [nus-cs2030/2223-s2#572]
Here is my implementation: 

1. in Event have method to count wait time
2. in simulator I call the method to "collect" the wait time and the methods only returns smth when it is in the wait event
3. I feel that the issue has to do with how I calculated the waitTime? 

<img width="463" alt="Screenshot 2023-03-24 at 12 27 31 PM" src="https://user-images.githubusercontent.com/110991431/227424408-738bb9e3-2cfa-42e8-adb9-d9f19b8ffa45.png">

5. are there other ways to calculate the wait time?

Here is the code snippet 

    // issue with the wait calculations 
    public Pair<Double,
           ImList<Server>> counterTimeWait(Pair<Double,
                   ImList<Server>> countTimeWait) {
        double time = countTimeWait.first();
        ImList<Server> nServerList = countTimeWait.second();

        //make sure i get the updated one 
        Server wServer = nServerList.get(this.server.getServerID() - 1);

        boolean isNext = wServer.isNext(this.cust);

        if (isNext && this.time <= wServer.getFinishTime()) {
            time += this.time - this.cust.getArrivalTime();   
        }

        // System.out.println(""+ time);
        return new Pair<Double, ImList<Server>>(time, nServerList);
    }

**Comment by chanjieru** [comment]
you can try to calculate wait time in your Serve event, because waitTime = time customer is served - arrival time. hope this helps!

**Comment by secretApple** [comment]
As above, wait time can be calculated by timestamp of serve event - arrival time of customer

**Comment by tinghwei** [comment]
yup, the method mentioned above is more straightforward, you can try that instead! so just create an abstract method waitTime in Event which returns 0 but only the waitTime in Serve returns time customer is served - arrival time

**Comment by nicholasteow** [comment]
all events give 0 in terms of waiting time, only serve event returns an amount

**Comment by littlemidget3** [comment]
yeah serve should be the only event that returns a timing when youre retrieving a wait timing. Essentially it is the time in serve event - customer's arrival time. Ensure your other events dont add to waiting time

**Comment by sporobolous** [comment]
thanks everyone! I got it!
