### ISSUE TITLE
Lab 6_3 issues with javadoc

### ISSUE THREAD

**Issue by ianwonghanli** [nus-cs2030/2223-s2#573]
# Summary

Hi All. Ive been adding Javadoc to some methods in my KeyableMap<V>. However, codecrunch keeps on giving me this error. Does anyone know how to rectify this error?

## Code Snippets
![Screenshot 2023-03-24 130730](https://user-images.githubusercontent.com/99638949/227429543-94f778e8-7148-4119-bc5e-ab42d74f6e04.png)

## Screenshots

![Screenshot 2023-03-24 130703](https://user-images.githubusercontent.com/99638949/227429557-2ec1822c-af86-4707-b0ab-8161a759b133.png)

**Comment by sethteo** [comment]
Maybe you can try just writing (not sure if it will really work, never got this error before)

/*
what you want to comment
*/

**Comment by 0liverkong** [comment]
you should describe what v is in the @/param line

**Comment by ianwonghanli** [comment]
Hi all. Thanks for the comments. I realised that I should've explained what param v is.

**Comment by ianwonghanli** [comment]
Hi all. Thanks for the comments. I realised that I should've explained what param v is.
