### ISSUE TITLE
Lab 7: orElseThrow

### ISSUE THREAD

**Issue by sharlynntan** [nus-cs2030/2223-s2#576]
Does anyone know why codecrunch is showing this error when I am using Optional.orElseThrow?
![image](https://user-images.githubusercontent.com/122287828/227513802-fab2f39d-d87b-4731-b0d6-06a3c9e2c12e.png)

**Comment by choongzhanhong** [comment]
If you're using Lambda, you can probably just write `orElseThrow(() -> new Exception)`

**Comment by JYeoZS** [comment]
strange you're not using Optional's nullable...

Just saying, future submissions codecrunch may have an error that you are using too many orElseThrows.....

**Comment by timothysashimi** [comment]
apparently we can only use one orElseThrow() in the entire code... and i used it in the of method that takes in two arguments alr, can someone help for the method that only takes in one argument?

**Comment by Hannybunny2001** [comment]
You can attempt to use the Optional's nullable

**Comment by hengbl** [comment]
> apparently we can only use one orElseThrow() in the entire code... and i used it in the of method that takes in two arguments alr, can someone help for the method that only takes in one argument?

yo, all you need to do is return Log.<T>of(T, "") can alr!

**Comment by Aron113** [comment]
you need to define a supplier in orElseThrows, something like () -> Exception

**Comment by dlyxxx** [comment]
you can only have one orElseThrow in your method! i faced the same issue but resolved it after chaining the methods together!
