### ISSUE TITLE
lab 5.2 test case 9_11

### ISSUE THREAD

**Issue by chanjieru** [nus-cs2030/2223-s2#580]
I get this problem where customer 16 leaves instead of waiting at self check. I'm thinking that the problem is either with Arrive's getNextEvent, or Serve's getNextServer doesn't update the queue after customer 14. However, I've checked both and I don't think there are any issues. Does anyone have any ideas about where else I could have gone wrong?

Additionally, does anyone know the numbers for this test case? I tried to test this using 2 servers, 2 selfchecks, 3 qmax and 0 restprob, but I get a totally different output from what I get on codecrunch.

<img width="560" alt="9_11" src="https://user-images.githubusercontent.com/122431508/227562553-1bdb271c-633b-4386-bb9e-0965fd83ef3f.PNG">

**Comment by leonardwx** [comment]
hi! did you search for the lowest available counter?

**Comment by jeffkhong11** [comment]
Hi, maybe you can try change the testcase to include 4 selfchecks. Is the selfcheck's queue updating correctly between events?

**Comment by shannon-jx** [comment]
hi! maybe can check your queue for self check counters, maybe it's not updating properly?

**Comment by Hannybunny2001** [comment]
Hi, perhaps you can check whether you have removed and updated the customer from the self check out queue

**Comment by slimzaza** [comment]
I got this same error and it was because I was updating the queue for the self check counters wrongly in my WaitEvent. Do make sure you are updating the queue in the right place as well

**Comment by WXUXIN** [comment]
Hi, did you manage to solve this issue?

**Comment by WXUXIN** [comment]
Hi, I just fixed this issue. Make sure that you are not resetting your waiting list size in any of your other functions, say if you are setting the finish time of a server and you're using an overloading constructor.

**Comment by chanjieru** [comment]
> Hi, I just fixed this issue. Make sure that you are not resetting your waiting list size in any of your other functions, say if you are setting the finish time of a server and you're using an overloading constructor.

sorry what do you mean by resetting waiting list size? i don't have any overloading constructors as well

**Comment by e0968868** [comment]
even though u used 2 2 3 0, the output is different probably because codecrunch generates different service times for each server (because ur Main.java uses default service time of 1.0)

**Comment by wadeyman** [comment]
i see common mention of quickest/ most available / fastest self check server. Anyone knows what is meant when they say most available self check server? does it mean which self check server is already free so using time done serving to check?

**Comment by nicholasteow** [comment]
> i see common mention of quickest/ most available / fastest self check server. Anyone knows what is meant when they say most available self check server? does it mean which self check server is already free so using time done serving to check?

you can just use a forloop or something to return you the next available selfcheck counter(i.e the one with the lowest/ most upcoming finishing time

**Comment by WXUXIN** [comment]
> i see common mention of quickest/ most available / fastest self check server. Anyone knows what is meant when they say most available self check server? does it mean which self check server is already free so using time done serving to check?

also possible to create a comparator and sort the self check list to get the next available one, see which one works best for you :)
