### ISSUE TITLE
Error with Test Case 7

### ISSUE THREAD

**Issue by zxciisdbniel** [nus-cs2030/2223-s2#582]
# Summary

Seems like my Log.of() method is throwing the IllegalArgumentException for the class A object. 

Any idea what might be causing this? The only reason I can think of is if class A extends Log, but then that should be still considered a Log object and the exception should be thrown.

I've tried writing an empty class A and tested it, works fine. Able to pass it through my Log.of().

## Description:

Clarifications or details with respect to the issue you are facing

## Code Snippets

Attach code snippets (if any)

## Screenshots

<img width="1003" alt="image" src="https://user-images.githubusercontent.com/96293687/227586324-9c29acbe-2b71-4f80-a83c-ef5c3899e734.png">

**Comment by choongzhanhong** [comment]
The issue is probably that you're trying to equate two different objects together, as you can see on the output log.
This is the unpredictability with using `==` operator to equate. So should just use `.equals()`

**Comment by geoffong11** [comment]
I also ran into this error, and I fixed it by changing my of() method. Instead of checking if .Equals(Optional.empty) to throw an exception, I instead used filter and flatMap and then orelsethrow on Optional to solve it.

**Comment by zxciisdbniel** [comment]
> The issue is probably that you're trying to equate two different objects together, as you can see on the output log.
> This is the unpredictability with using `==` operator to equate. So should just use `.equals()`

I didn't use == in equals() method, the problem lies in my of() method.

> I also ran into this error, and I fixed it by changing my of() method. Instead of checking if .Equals(Optional.empty) to throw an exception, I instead used filter and flatMap and then orelsethrow on Optional to solve it.

Managed to solve it in the same way. Replaced .equals(Optional.empty()) with map, flatMap, filter functions.

Thanks!!
