### ISSUE TITLE
flatMap() Lab 6 

### ISSUE THREAD

**Issue by OwenChanJF** [nus-cs2030/2223-s2#584]
# Summary

Description of the question / problem here.
I just can't seem to figure this out by using the orElse method... Can someone please provide a clue :')
## Description:

Clarifications or details with respect to the issue you are facing

## Code Snippets

Attach code snippets (if any)

## Screenshots

Screenshots (if any)
<img width="632" alt="image" src="https://user-images.githubusercontent.com/124082348/227635691-ad937213-54d6-4db2-9ab3-9298995537c1.png">

**Comment by e0970430** [comment]
hello! sorry i don't quite get your implementation, what is your CAP#1 class? also, which level is this for?

**Comment by OwenChanJF** [comment]
> hello! sorry i don't quite get your implementation, what is your CAP#1 class? also, which level is this for?

This is for level 4 where we have to implement "flatmap()"... Currently it's 

<R> Optional<R> flatmap(Function<? super Assessment, ? extends Optional<? extends R>> mapper

And I first assign mapper.apply(this) to a Optional<? extends R> and return that.OrElse(an empty optional)

However it seems like OrElse only takes in an <R> type and I can't seem to figure what to put there

**Comment by junhonglow** [comment]
There shouldn't be a need to implement flatmap for level 4, rather we use the flatmap method from the Optional class itself to help with our methods.

**Comment by OwenChanJF** [comment]
> There shouldn't be a need to implement flatmap for level 4, rather we use the flatmap method from the Optional class itself to help with our methods.

omg thank you so much... this solved my problem :')
