### ISSUE TITLE
Lab 7 Level 1

### ISSUE THREAD

**Issue by nigel-tannn** [nus-cs2030/2223-s2#589]
Hi, I've been having troubles getting past this level as the last test of(5, null) returns a NullPointerException instead of the IllegalArgumentException as required.  I've tried doing this 

<img width="658" alt="Screenshot 2023-03-25 at 1 35 30 PM" src="https://user-images.githubusercontent.com/101518315/227698522-a3ddb2f4-bfb4-4ae6-9b94-5a30f9a196ae.png">

Any ideas how to address this?  Thanks!

**Comment by LYEDominic** [comment]
Hi, it might be because the Optional.ofNullable(log) is inside the log. This means that what you end up with is 
Optional(Log<T>(x, Optional.ofNullable(log)).orElseThrow. Since the log is ALREADY created, you have no way of passing in the IllegalArgumentException. Instead, you can try doing Optional.ofNullable(value).filter(...).map(x -> Optional.ofNullable(log)).filter(...).map(generate log here).orElseThrow(...). Hope this helps!

**Comment by nigel-tannn** [comment]
.map(x -> Optional.ofNullable(log))

**Comment by nigel-tannn** [comment]
> Hi, it might be because the Optional.ofNullable(log) is inside the log. This means that what you end up with is Optional(Log(x, Optional.ofNullable(log)).orElseThrow. Since the log is ALREADY created, you have no way of passing in the IllegalArgumentException. Instead, you can try doing Optional.ofNullable(value).filter(...).map(x -> Optional.ofNullable(log)).map(generate log here).orElseThrow(...). Hope this helps!

Apologies but I'm a little confused, 
.map(x -> Optional.ofNullable(log))
this part means that even though we are passing the value in we will not get the value in result of this map?

**Comment by leezhanpeng** [comment]
I mapped x directly with log. If log is null, then your optional will turn empty, so there's no need for the nested log and optional. Hope it helps!

**Comment by taugwa** [comment]
not sure if its this but perhaps for the last test of (5,null), x still has a value while Optional.ofNullable(log) does not. so maybe the result is not exactly empty and theres something still present there, therefore orElseThrow() doesnt work

**Comment by LYEDominic** [comment]
> > Hi, it might be because the Optional.ofNullable(log) is inside the log. This means that what you end up with is Optional(Log(x, Optional.ofNullable(log)).orElseThrow. Since the log is ALREADY created, you have no way of passing in the IllegalArgumentException. Instead, you can try doing Optional.ofNullable(value).filter(...).map(x -> Optional.ofNullable(log)).map(generate log here).orElseThrow(...). Hope this helps!
> 
> Apologies but I'm a little confused, .map(x -> Optional.ofNullable(log)) this part means that even though we are passing the value in we will not get the value in result of this map?
> 
> Wouldn't this mean that we have to generate the log in the last map using the argument value in the method definition, which would defeat the purpose of checking if value is null?

basically if it is not a null value u can change it to another value. e.g T t > String log > Log<T, String>(t, log)

**Comment by Brendan8899** [comment]
Optional.ofNullable(value).filter(...).map(x -> Optional.ofNullable(log)).map(generate log here).orElseThrow(...).
I have did this exactly but cannot solve. I would like to ask what is the predicate?

My predicate is x -> (x instanceof Log).

Would like to hear your advice.

**Comment by SimonSeeYongsheng** [comment]
Hi, after filter, you can just use map and flatmap to check if the Optional context is empty or not empty

**Comment by nigel-tannn** [comment]
> Hi, after filter, you can just use map and flatmap to check if the Optional context is empty or not empty

How do we use map/flatmap to check if the Optional is empty?

**Comment by SimonSeeYongsheng** [comment]
> > Hi, after filter, you can just use map and flatmap to check if the Optional context is empty or not empty
> 
> How do we use map/flatmap to check if the Optional is empty?

So if the Optional context was empty from the start, using map on it will return an empty optional.

You can take advantage of it
for example ,
`Optional.ofNullable(a).flatMap(x -> Optional.ofNullable(b)).map(x ->...`

If a was a null value, flatMap will just return an empty Optional
If b was a null value,  map will just return an empty Optional

Hope this helps!

**Comment by nigel-tannn** [comment]
> > > Hi, after filter, you can just use map and flatmap to check if the Optional context is empty or not empty
> > 
> > 
> > How do we use map/flatmap to check if the Optional is empty?
> 
> So if the Optional context was empty from the start, using map on it will return an empty optional.
> 
> You can take advantage of it for example , `Optional.ofNullable(a).flatMap(x -> Optional.ofNullable(b)).map(x ->...`
> 
> If a was a null value, flatMap will just return an empty Optional If b was a null value, map will just return an empty Optional
> 
> Hope this helps!

Definitely did, thank you!
