### ISSUE TITLE
Allow us to download Assignment PDF file from codecrunch

### ISSUE THREAD

**Issue by SimonSeeYongsheng** [nus-cs2030/2223-s2#59]
Hi guys, it would be great if you allow us to download the assignment pdf file so that we can refer to it on our own devices.
Referring to the assignment questions on code crunch is a bit hard...

**Comment by Cfyjdfk** [comment]
One workaround I did was to use the "Copy Files" function within winSSH, move index.pdf onto the computer's desktop, then emailing the file to myself

**Comment by SimonSeeYongsheng** [comment]
Is there a way for them to upload the pdf on github?

**Comment by Cfyjdfk** [comment]
Yup! I just uploaded the Lab 2 Index.pdf file onto the Issues page. Do check it out
