### ISSUE TITLE
Lab 7 level 5 recursion

### ISSUE THREAD

**Issue by Cfyjdfk** [nus-cs2030/2223-s2#590]
```
REDACTED
```

```
f(3)
$13 ==> Log[1]
1
2 / 2
4 / 2
8 / 2
16 / 2
3(5) + 1
10 / 2
3(3) + 1
```

Hi guys, this is my recursion code for level 5. However, the question wants the logging to be done in the reverse direction instead (starting from 3(3) + 1, 10 / 2, etc). Does anyone know how to reverse the logging?

**Comment by choongzhanhong** [comment]
Do it iteratively instead 😛

**Comment by Xequil1** [comment]
Am I mistaken? Isn't there a no recursion and for loops restriction for this lab?

**Comment by geoffong11** [comment]
I created a helper recursive function which takes in n and a log<Integer>, perform recursion on the input log function and returns a log<Integer>  (preference for me since I feel more control over my output doing that)

**Comment by Cfyjdfk** [comment]
> Do it iteratively instead 😛

How did you do it? I tried and it said that local variables used in lambdas must be effectively final

**Comment by koiljat** [comment]
You can do this iteratively by updating your Log object every iteration.

**Comment by Cfyjdfk** [comment]
Yup managed to solve it already, just needed to use x from the lambda to update the log

**Comment by nigel-tannn** [comment]
A while loop will be much more intuitive, applying flatMap and updating the return value with each iteration.

**Comment by granolaluvr69** [comment]
Just need to swap the position of the f() function and the Log.<>of(...).

**Comment by rayray39** [comment]
hi are u able to give me a hint as to how u solved the issue? thanks

**Comment by koiljat** [comment]
you can use while loop for the non-base case to update the Log object with each loop

**Comment by wadeyman** [comment]
so do u mean have one variable to update the value each time it is mapped?


> you can use while loop for the non-base case to update the Log object with each loop

**Comment by fy17ohhh** [comment]
For those looking for a recursive solution, using an overloaded function will help!

**Comment by Cfyjdfk** [comment]
> hi are u able to give me a hint as to how u solved the issue? thanks

I set a local Log<Integer> variable and used a while loop to update it accordingly if it is odd or even
