### ISSUE TITLE
Lab 07 flatMap() and equals() method

### ISSUE THREAD

**Issue by lsy8117** [nus-cs2030/2223-s2#592]
# Summary

Not sure why cannot pass level 4 test for monad associativity test, although when I print out the output they look exactly the same

## Description:

In my equals() method I returned **this.value == other.value && this.log == other.log**, after checking the other object passed in is also a Log, but seems that the **this.log == other.log** test failed, although when I print it out they look exactly the same to me.
Now i'm not sure if the problem is in my flatMap() method or equals() method, could anyone help me take a look?

## Code Snippets

![Screenshot 2023-03-25 at 2 57 18 PM](https://user-images.githubusercontent.com/123756364/227702136-909fcb98-b8d1-479c-aaeb-8dea94ea4700.png)
![Screenshot 2023-03-25 at 2 58 18 PM](https://user-images.githubusercontent.com/123756364/227702186-018ce0df-cda4-4879-a9d7-c2622ca75a0c.png)

## Screenshots

![Screenshot 2023-03-25 at 2 56 55 PM](https://user-images.githubusercontent.com/123756364/227702107-8ba109a7-2c71-418c-af76-63622bb1976e.png)

**Comment by stxe09** [comment]
facing the same issue...

**Comment by geoffong11** [comment]
I think the problem may be using ==. To compare, it is better to use .Equals method.

**Comment by lsy8117** [comment]
> I think the problem may be using ==. To compare, it is better to use .Equals method.

oh yea you are right! thanks for pointing that out!

**Comment by tjdbryan** [comment]
Hi, if anyone is facing this issue... Do check your output for `map` and `flatMap`. I accidentally added blank lines in my output - hence level 4 was a mess. 

Example:
![image](https://user-images.githubusercontent.com/122286169/227722042-ac477667-ec47-4f0b-8721-50442f3b2f79.png)

**Comment by syafiq9326** [comment]
@tjdbryan how did u solve it? I am facing the same issue, I am not sure why there are extra spaces

**Comment by tjdbryan** [comment]
> @tjdbryan how did u solve it? I am facing the same issue, I am not sure why there are extra spaces

Hi bud, I haven't solved it also... I'm trying to work out each statement one by one and see what's the issue. Cheers!

**Comment by tjdbryan** [comment]
Can refer to #608
