### ISSUE TITLE
Lab 7 level 5

### ISSUE THREAD

**Issue by jayson237** [nus-cs2030/2223-s2#593]
Hi, I was doing something like this for level 5, and obviously this doesn't work. Can anybody advise me on this, as well as the recursion
<img width="639" alt="image" src="https://user-images.githubusercontent.com/110618399/227706126-9d8ce632-3c82-4d79-8741-7fab66641443.png">

**Comment by leezhanpeng** [comment]
`sum` was used for both the function name and the Log.
