### ISSUE TITLE
Cannot find symbol: variable Stream on codecrunch

### ISSUE THREAD

**Issue by weitatftw** [nus-cs2030/2223-s2#594]
# Summary

I tried submitting my answer on codecrunch and everything compiles fine and gives the correct answer on vim but it throws this error when i submit on codecrunch. Does anyone have any idea what may have gone wrong??

## Screenshots
<img width="317" alt="Screenshot 2023-03-25 at 4 42 32 PM" src="https://user-images.githubusercontent.com/79369027/227707100-a00e11ef-3188-4b40-997f-919f5958f619.png">

**Comment by weitatftw** [comment]
I've tried using IntStreams and importing it at the start of the level5.jsh file but I'm still facing this issue on codecrunch

<img width="320" alt="Screenshot 2023-03-25 at 5 13 08 PM" src="https://user-images.githubusercontent.com/79369027/227708343-c125cacf-8211-4d68-8abb-8a0fac3d0ed8.png">

**Comment by fy17ohhh** [comment]
You should import using `import java.util.stream.IntStrea;` and `import java.util.stream.Stream;`

**Comment by weitatftw** [comment]
> You should import using `import java.util.stream.IntStream;` and `import java.util.stream.Stream;`

i've done so already but codecrunch still throws the same error

**Comment by trickypepe** [comment]
> > You should import using `import java.util.stream.IntStream;` and `import java.util.stream.Stream;`
> 
> i've done so already but codecrunch still throws the same error

can you try
int result = java.util.stream.IntStream.rangeClosed(...) 
and see if the error persists?

**Comment by granolaluvr69** [comment]
Is the issue defining a class around the methods? Personally, I just define the methods without any enclosing classes if I'm asked to create a jsh script.

**Comment by weitatftw** [comment]
> > > You should import using `import java.util.stream.IntStream;` and `import java.util.stream.Stream;`
> > 
> > 
> > i've done so already but codecrunch still throws the same error
> 
> can you try int result = java.util.stream.IntStream.rangeClosed(...) and see if the error persists?

thanks! it managed to resolve the error once i did this

**Comment by weitatftw** [comment]
> Is the issue defining a class around the methods? Personally, I just define the methods without any enclosing classes if I'm asked to create a jsh script.

i didn't define a class around the methods, but apparently codecrunch insists that i use java.util.stream.IntStream instead of IntStream alone otherwise it throws an error
