### ISSUE TITLE
level 2 How to map?

### ISSUE THREAD

**Issue by jianjiezzz** [nus-cs2030/2223-s2#596]
my plan to get the mapped value and create new Log.<R>of(). But my mapped value and log is in optional wrapped. Can anyone give me suggestions or what can be done since .get() is banned to access the value.

**Comment by jianjiezzz** [comment]
Both the value and log properties should be stored in optional rite?

**Comment by leonlu178** [comment]
hi i didnt store value and log in Optional. i believe u did that for the of() method but using Optional.ofNullable() doesn't require them to be Optional

**Comment by cheng-yee** [comment]
I dont think you need to store value and log an optional except for level 1's of method. You can refer to lecture 9 for some clues on writing a map method for a wrapper class.

**Comment by nigel-tannn** [comment]
Personally didn't store both the value and log in Optionals
