### ISSUE TITLE
Lab 6 test case 6/6

### ISSUE THREAD

**Issue by coderlimjingcheng** [nus-cs2030/2223-s2#597]
# Summary

Problem with my last test case test case 6/6

## Description:

I was able to get the outputs correctly, but I got an error message on top for some reason. It will be nice if anyone can advise me on this error. Thank you!!

## Screenshots

<img width="737" alt="image" src="https://user-images.githubusercontent.com/124959195/227711321-eb1c6165-e8e1-4c88-af10-a5d380beff46.png">

**Comment by Cfyjdfk** [comment]
You can check if you have a System.out.print somewhere

**Comment by trickypepe** [comment]
Are you able to check if your scanner stops scanning at the appropriate time (using something like hasNext())?

**Comment by shuyaoao** [comment]
You need to check whether there is a next line before every loop

**Comment by coderlimjingcheng** [comment]
I figure out the problem! Thank you guys!

My problem was that I used "^D" as the breaking point for the while loop instead of sc.hasNext() in my Main class.
