### ISSUE TITLE
test case 5

### ISSUE THREAD

**Issue by hcyrr** [nus-cs2030/2223-s2#598]
# Summary
hi, i am confused how to properly implement add().. below is my code snippet which looks very messy, and i dont think its the right way to do it, any advice on how to improve will be appreciated thank you :)

also from test case 5, am i supposed to change the grade of the existing assessment? how can i do it in orElse()..?

## Code Snippets

![06BCDE4C-B80C-4F18-94A3-3F616FA1C44F_4_5005_c](https://user-images.githubusercontent.com/126330380/227714230-0b513dc9-bed7-480c-95e9-c3c8cc0d873b.jpeg)

## Screenshots

![BB24553A-3476-48A0-AB71-1F6CFC55C8AA](https://user-images.githubusercontent.com/126330380/227714185-d023628a-bbf6-4e28-93da-e337a7d207d5.jpeg)

**Comment by tallkoh** [comment]
for assessment, don't need to get the old data, just always make a new one

**Comment by hcyrr** [comment]
@tallkoh thank you it worked :)

**Comment by ghost1nthemachine** [comment]
thanks this helped me out too
