### ISSUE TITLE
Use of restricted API detected

### ISSUE THREAD

**Issue by shuyaoao** [nus-cs2030/2223-s2#60]
Hi does anyone know what caused codecruch to throw this error? What kind of API are we not supposed to use?
![Screenshot 2023-02-03 at 20 40 40](https://user-images.githubusercontent.com/124263084/216606088-4ffd1b18-9888-4aa1-bdfa-e89544aeb93e.png)

**Comment by e0959170** [comment]
i think there are some APIs we are not allowed to use for certain labs :( i remember for the Lab Ex2 (Cruise),  i was unable to use comparator but it would be useful if we had a list so i don't have to wait until we submit to find out hahaha

**Comment by hwkchia** [comment]
Please check whether you have constants declared as `final` but missing `static`.
