### ISSUE TITLE
Lab 6 lvl 4

### ISSUE THREAD

**Issue by yueyaozzz** [nus-cs2030/2223-s2#600]
# Summary

My implementation of getGrade() doesn't work and it also fails when I try to directly use map or flatmap function in jshell. Does that mean my get(String s) method in KeyableMap is wrong?

## Description:

Clarifications or details with respect to the issue you are facing

## Code Snippets

Attach code snippets (if any)

## Screenshots

<img width="357" alt="Screenshot 2023-03-25 at 8 52 31 PM" src="https://user-images.githubusercontent.com/122427063/227718497-8ee32c67-c59f-4bdd-8472-f5689bc241ec.png">
<img width="666" alt="Screenshot 2023-03-25 at 8 53 39 PM" src="https://user-images.githubusercontent.com/122427063/227718498-d5540d1d-3904-4459-965d-05bd63da1119.png">

**Comment by shuyaoao** [comment]
What types do you wrap in your immutableMap in the various classes? That could affect your get() and therefore your getGrade()

**Comment by yueyaozzz** [comment]
> What types do you wrap in your immutableMap in the various classes? That could affect your get() and therefore your getGrade()
Roster is<String, Student>, Student is<String, Module>, Module is<String, Assessment>

**Comment by shuyaoao** [comment]
Actually, there is no need to use a map() method to get the values, you can directly call get(Key). For example, tony.get("CS2030").orElse(...).get("Lab1").orElse(...).getGrade()

**Comment by yueyaozzz** [comment]
> Actually, there is no need to use a map() method to get the values, you can directly call get(Key). For example, tony.get("CS2030").orElse(...).get("Lab1").orElse(...).getGrade()
By doing this I'll get an warning: unchecked call to orElse(T) as a member of the raw type java.util.Optional, as well as an error for cannot find symbol for method get()

**Comment by junhonglow** [comment]
What type are you returning in get(String s)?

Are you returning an Optional rather than an Optional<V>, that could be the source of error for the raw typing, and it could possibly solve the other errors as well.

**Comment by yueyaozzz** [comment]
> What type are you returning in get(String s)?
> 
> Are you returning an Optional rather than an Optional< V >, that could be the source of error for the raw typing, and it could possibly solve the other errors as well.

I am indeed returning Optional<V>

**Comment by junhonglow** [comment]
Does your method definition of get(String s) look something like the following?
                V I have a feeling this might be missing
Optional**< V >**  get(String s) {
...
}

**Comment by yueyaozzz** [comment]
> Does your method definition of get(String s) look something like the following?
> 
> Optional< V > get(String s) { ... }
It's like this:
public Optional<V> get(String keyIn) {
        return this.vMap.get(keyIn);
    }

**Comment by junhonglow** [comment]
> > Does your method definition of get(String s) look something like the following?
> > Optional< V > get(String s) { ... }
> 
> It's like this: public Optional< V > get(String keyIn) { return this.vMap.get(keyIn); }

Hmm, the last thing I can thing of is to check that all your classes which extend KeyableMap have a type witness.
E.g Module extends KeyableMap< Assessment > same thing for Roster and Student as well.

**Comment by yueyaozzz** [comment]
> Hmm, the last thing I can thing of is to check that all your classes which extend KeyableMap have a type witness.
> E.g Module extends KeyableMap< Assessment > same thing for Roster and Student as well.


yes I have that oso haha

**Comment by yueyaozzz** [comment]
> Hmm, the last thing I can thing of is to check that all your classes which extend KeyableMap have a type witness.
> E.g Module extends KeyableMap< Assessment > same thing for Roster and Student as well.


wait sorry i just realised I forgot to put the type witness for Module class omg tysm

**Comment by gracico** [comment]
> By doing this I'll get an warning: unchecked call to orElse(T) as a member of the raw type java.util.Optional, as well as an error for cannot find symbol for method get()

hi shuyao, could you explain more on how to go about doing so? since I dont think we are allowed to return a string in orElse
