### ISSUE TITLE
Lab 07 Level 2 

### ISSUE THREAD

**Issue by ianwonghanli** [nus-cs2030/2223-s2#602]
# Summary

Hi all. Currently, I am facing this issue. From my understanding of the screenshot, it seems that the function input requires a class A type while the map function inputs a class B type. However, I am not sure on how to solve the difference between class A and B. Help would be appreciated.

## Screenshots
![Screenshot 2023-03-25 211808](https://user-images.githubusercontent.com/99638949/227719543-6502d5f2-63d8-468c-a74d-64acaf32841e.png)

**Comment by junhonglow** [comment]
You may have forgotten to include bounded wildcards in your map method.

**Comment by ianwonghanli** [comment]
> You may have forgotten to include bounded wildcards in your map method.

Thanks junhong! turns out I forgot to include the wildcard!
