### ISSUE TITLE
Lab 6 Level 6 

### ISSUE THREAD

**Issue by lynettelcl** [nus-cs2030/2223-s2#604]
running into this error at test case 6
![Screenshot (97)](https://user-images.githubusercontent.com/124801803/227720853-dd2b43e7-753f-474f-988b-22b7044b468b.png)

**Comment by aarontxz** [comment]
I think one possible issue might be in your main class, when you scan the next string you might be scanning a wrong input and thus possibly putting something wrong in your roster. Thus your code returns no such record for all query. How did you handle scanning the name mod code and assignment code in one line?

**Comment by lynettelcl** [comment]
oh got it, accidentally had an extra sc.next() in the loop
