### ISSUE TITLE
Test case 7 

### ISSUE THREAD

**Issue by joshuagohez** [nus-cs2030/2223-s2#605]
# Summary

Checking why should this statement return true --> Log.of(new A()).equals(Log.of(new A()))
From my understanding both new A() have different memory addresses since they are different instances of class A.. so why would the equality check for this line return true?

## Screenshots

<img width="859" alt="Screenshot 2023-03-25 at 10 12 01 PM" src="https://user-images.githubusercontent.com/96434745/227722405-f3ada81b-2e26-479d-b9c6-3b39e4f2de75.png">
<img width="280" alt="Screenshot 2023-03-25 at 10 13 38 PM" src="https://user-images.githubusercontent.com/96434745/227722501-88b0bc68-39da-47a4-ba33-22836534c988.png">

**Comment by granolaluvr69** [comment]
Using the `==` operator compares memory addresses, whereas using `.equals()` compares the actual content of the object. 
As defined by the preamble for level 4 on codecrunch, 
"Two loggers are equal if and only if both the wrapped value as well as the logs are the same."
Since we already accounted for the case where either value is null, we do not need to check for that condition. We only need to check for equality of these two criteria.

**Comment by fy17ohhh** [comment]
Hello, I have faced the same issue, may I ask how you checked in this circumstance when `new A().equals(new A()) == false`?

**Comment by joshuagohez** [comment]
hmm thats what i did... 
`if (!(other instanceof Log<?> o)) {
            return false;
        } else {
            if (this.get().equals(o.get()) && this.getLog().equals(o.getLog())) {
                return true;`

could it because I'm type casting other to Log<?> ?

**Comment by fy17ohhh** [comment]
> > Using the `==` operator compares memory addresses, whereas using `.equals()` compares the actual content of the object. As defined by the preamble for level 4 on codecrunch, "Two loggers are equal if and only if both the wrapped value as well as the logs are the same." Since we already accounted for the case where either value is null, we do not need to check for that condition. We only need to check for equality of these two criteria. Hope this helps!
> 
> Hello, I have faced the same issue, may I ask how you checked in this circumstance when `new A().equals(new A()) = false`?

managed to solve the issue! lol I did not realize that the test case have overrides the equals() method for classA so new A().equals(new A()) is in fact true

**Comment by fy17ohhh** [comment]
> hmm thats what i did... `if (!(other instanceof Log<?> o)) { return false; } else { if (this.get().equals(o.get()) && this.getLog().equals(o.getLog())) { return true;`
> 
> could it because I'm type casting other to Log<?> ?

I think you do not need getters in equals() methods in fact

**Comment by joshuagohez** [comment]
seh... solved too. @fy17ohhh you're right class A had its own overridden equals method and I just needed to resubmit after changing to equals(). Cheers guys @granolaluvr69 @fy17ohhh

**Comment by tjdbryan** [comment]
Hi, may I ask how you solved it?

My `equals` method in Log does not use `==`  nor getters. But I'm still failing these 2 test cases.

![image](https://user-images.githubusercontent.com/122286169/227746235-8485c9fa-d8b0-44c2-b7a1-94981928db96.png)

Thanks!

**Comment by fy17ohhh** [comment]
> explicit typecasting

I would suggest you not using explicit typecasting but use instanceof to check and then check their wrapped values
