### ISSUE TITLE
Lab 5.2 Test Case 9_11

### ISSUE THREAD

**Issue by keshialimm** [nus-cs2030/2223-s2#606]
I've been stuck here for test case 11 and I'm not too sure how to go about it. Has anyone encountered this and managed to fix it? Thank you so much in advance!

## Screenshots
<img width="750" alt="Screenshot 2023-03-25 at 10 32 40 PM" src="https://user-images.githubusercontent.com/122249974/227723725-8fab84c3-eab2-4574-88c7-d8ba21ec7f21.png">

Screenshots (if any)

**Comment by omarsfs** [comment]
hi, you need to make sure that under your wait class, the server that has finished serving is able to serve. for human servers, it doesnt matter since the queue you are at does not change which server you are getting served by. for self checkout, any of the self checkouts can be free so you need to loop through the selfcheckout servers to see which one is free at the earliest time

**Comment by keshialimm** [comment]
> hi, you need to make sure that under your wait class, the server that has finished serving is able to serve. for human servers, it doesnt matter since the queue you are at does not change which server you are getting served by. for self checkout, any of the self checkouts can be free so you need to loop through the selfcheckout servers to see which one is free at the earliest time

ahhh ok! thank you, but can I check if it matters if all my self checkouts have the same queue, or must only the first one have the queue? cos im not sure if that's the issue right now.

**Comment by junhonglow** [comment]
> > hi, you need to make sure that under your wait class, the server that has finished serving is able to serve. for human servers, it doesnt matter since the queue you are at does not change which server you are getting served by. for self checkout, any of the self checkouts can be free so you need to loop through the selfcheckout servers to see which one is free at the earliest time
> 
> ahhh ok! thank you, but can I check if it matters if all my self checkouts have the same queue, or must only the first one have the queue? cos im not sure if that's the issue right now.

As long as you are updating the queue of the servers correctly, it shouldn't matter how you implement the "all self checkout servers have the same queue" restriction, but just maintaining a single queue at one self checkout counter may be less hassle than having to update all of them to have the same queue.

**Comment by leonardwx** [comment]
according to the picture, it suggests that customer 12 is served by self check 4 instead of waiting at 2. there could a issue of filling your human server queue that results the next customer to approach to self check instead

**Comment by Jeko1239** [comment]
since customer 11 waited at server 2 but not customer 12, there could have been a problem with the updating of time for the self-check counters. it seems by the time 0.767, self-counter 4 is already assumed to be done, instead of the actual time 0.862 where customer 9 was done being served.

**Comment by Aron113** [comment]
could possibly be the queues and server free time are not being updated accurately. Try taking a look at the Served event

**Comment by keshialimm** [comment]
Hi, I managed to solve this! Issue was in my Wait and Buffer events. Wait Event should always return a Buffer for a self check server. Only in Buffer then I find the earliest available server and decide if it cans serve the customer. 

Hope this helps anyone else who may encounter the same problem!

**Comment by keshialimm** [comment]
Hi, I managed to solve this! Issue was in my Wait and Buffer events. Wait Event should always return a Buffer for a self check server. Only in Buffer then I find the earliest available server and decide if it cans serve the customer. 

Hope this helps anyone else who may encounter the same problem!
