### ISSUE TITLE
Lab 7 Level 4

### ISSUE THREAD

**Issue by syafiq9326** [nus-cs2030/2223-s2#608]
# Summary

Hi, I am facing some issue with clearing level 4 from the monad left side onwards. 
![image](https://user-images.githubusercontent.com/50677984/227729404-feffabce-16d4-4c7a-8b87-9f81fbcddb11.png)

## Description:

I suspect that it could be due to my .of and flatmap returning excess spaces altho I am not sure why there are even extra spaces  as I am able to pass all the private cases up to level 4. I am also using equals instead of "==" so I am kinda stuck now. I was hoping someone who had a similar issue can help, would appreciate any assistance, thanks!

## Code Snippets
![image](https://user-images.githubusercontent.com/50677984/227729580-9fa30f2c-3ef1-4b50-a9f9-b275585a5646.png)

**Comment by jeffkhong11** [comment]
Yeah I had this issue, it may be inside the flatMap(), where you have to consider that log could be empty.

**Comment by syafiq9326** [comment]
Yup, you were right, thanks!

**Comment by calista03** [comment]
hi there, i'm currently facing the same issue that you did.... what do you mean by 'the log could be empty'?

**Comment by syafiq9326** [comment]
Hi, for mine I had 2 issues.

1. My of method was filtering out by literally comparing to an optional.empty but I realised that I should not be using any optional.empty and is fine to just filter out non instances of log only for the value part.

2. My flatmap was only comparing the new inputted string from the function to an empty string but I realised I did not compare the old string log. What I did was to just add an extra else if to compare my original string log to ""  and just return 
new Log.<R>of(logObj.getValue(),this.log); for that part. Yours could be the other way round also.

I think you can try doing what I did first by printing out both flatmap and of method to see which one has excess spaces to help you identity where it went wrong , it may just be issue 1 or 2 and not both. Hope this helps!

**Comment by calista03** [comment]
> Hi, for mine I had 2 issues.
> 
> 1. My of method was filtering out by literally comparing to an optional.empty but I realised that I should not be using any optional.empty and is fine to just filter out non instances of log only for the value part.
> 2. My flatmap was only comparing the new inputted string from the function to an empty string but I realised I did not compare the old string log. What I did was to just add an extra else if to compare my original string log to ""  and just return
>    new Log.of(logObj.getValue(),this.log); for that part. Yours could be the other way round also.
> 
> I think you can try doing what I did first by printing out both flatmap and of method to see which one has excess spaces to help you identity where it went wrong , it may just be issue 1 or 2 and not both. Hope this helps!

thank you so much for your help!!!!
