### ISSUE TITLE
Lab 5.2 Test Case 9 Mysterious Output

### ISSUE THREAD

**Issue by Brendan8899** [nus-cs2030/2223-s2#611]
![image](https://user-images.githubusercontent.com/80048882/227733259-ae521d5a-1f7a-444f-b078-5757bcf6f13c.png)
Hi I would like to ask, what could be the reason for the issue? Its so weird given that I have already created Human Server 1, and it alr passed the test cases in front.

**Comment by junhonglow** [comment]
There shouldn't be any human servers for this test case. Did any of your events return a Server instead of a self checkout counter?

**Comment by Brendan8899** [comment]
Yeah, you are right shouldnt have any human Servers. I ran the test in my Cmd and used 0 2 0 0.5 and added System.out.println() in my Server List Constructor method to see whether any Human Servers were wrongfully created. I will go ahead and add System.out.println to my toString method for Server. Might Need to do further digging. Weird because it passed the test case provided in Code Crunch.

**Comment by junhonglow** [comment]
> Yeah, you are right shouldnt have any human Servers. I ran the test in my Cmd and used 0 2 0 0.5 and added System.out.println() in my Server List Constructor method to see whether any Human Servers were wrongfully created. I will go ahead and add System.out.println to my toString method for Server. Might Need to do further digging. Weird because it passed the test case provided in Code Crunch.

From what I can see, I would try looking into the Wait event first. The error in your case seems to occur after a wait event is generated for Customer 3 at a self checkout counter. Additionally, the code crunch public test case do not include any Wait events for self checkout counters so it may have passed the test case without generating any issues.

**Comment by Brendan8899** [comment]
Thanks Guys, Issue solved. Huat ah
