### ISSUE TITLE
Lab 6 lvl 4: how to implement orElse

### ISSUE THREAD

**Issue by gracico** [nus-cs2030/2223-s2#612]
# Summary

any tips on how to implement orElse? I don't quite get how to use it. Tried chaining the functions together but it seems way more complicated than that.

**Comment by nicholasteow** [comment]
try chaining the map & flatmap to see if the student name, modName, assessmentName are available. 

if not , that's where you add the "orElse" at the back to be able to return the "No such record:"

**Comment by Jeko1239** [comment]
![image_2023-03-26_05-09-11](https://user-images.githubusercontent.com/124948961/227742083-22741762-6012-48e1-bd33-117158d3f828.png)

u can reference the exact instructions that they give in level 4, with an  .orElse(String xxx) at the back with the no such record

**Comment by gracico** [comment]
> ![image_2023-03-26_05-09-11](https://user-images.githubusercontent.com/124948961/227742083-22741762-6012-48e1-bd33-117158d3f828.png)
> 
> u can reference the exact steps they took to get grade in level 4, with an addition of the .orElse(String) at the back

thanks! managed to solve. 

by any chance could you advice on level 5? I'm using the get(student).orElse(new Student) but I'm not sure how to add all the different stuff back into a Roster obj

**Comment by Jeko1239** [comment]
i would recommend looking at #462 where it was mentioned that a possible step is
student = map.get(student).orElse(new Student);
module = map.get(student).get(module).orElse(new Module);
then returning a statement with the assessment put into module which is put into student

this is to create a new student if the studentID is not found and a new moduleCode if it is similarly not found in the Roster

**Comment by gracico** [comment]
> i would recommend looking at #462 where it was mentioned that a possible step is student = map.get(student).orElse(new Student); module = map.get(student).get(module).orElse(new Module); then returning a statement with the assessment put into module which is put into student which is put into the current roster
> 
> this is to create a new student if the studentID is not found and a new moduleCode if it is similarly not found in the Roster

thanks jeko!

**Comment by rshalinisai** [comment]
> > ![image_2023-03-26_05-09-11](https://user-images.githubusercontent.com/124948961/227742083-22741762-6012-48e1-bd33-117158d3f828.png)
> > u can reference the exact steps they took to get grade in level 4, with an addition of the .orElse(String) at the back
> 
> thanks! managed to solve.
> 
> by any chance could you advice on level 5? I'm using the get(student).orElse(new Student) but I'm not sure how to add all the different stuff back into a Roster obj

For student, module and assessment you can use get.OrElse method which will get that or if it does not currently exist, it will create a new student, module, assessment respectively.

Next, you can use the put method to put assessment in module, then put the module in the student and the student in the roster.

Finally, return this new roster.
