### ISSUE TITLE
Test Case 7 (.equals() method)

### ISSUE THREAD

**Issue by territxl** [nus-cs2030/2223-s2#616]
## Description:

hi! I'm currently facing this issue and in my current implementation, I have only used ,equals() to check for the wrapped values but is still facing this problem. Is there anything else that I might have missed out?

## Screenshots
<img width="415" alt="image" src="https://user-images.githubusercontent.com/122513546/227759762-78cfbafe-910c-4c1d-8418-58189cf92bff.png">

**Comment by geoffong11** [comment]
The test case added a extra line for the log, hence you have to remove the escape character in order for both logs to be the same.

**Comment by territxl** [comment]
Hi! What do you mean by an additional line in the log? For the logs to be the same, is it insufficient to merely compare the wrapped values (i.e. string and value)?

**Comment by ianwonghanli** [comment]
I faced this issue earlier. To understand the issue, the otherLog is the **parent class** of this. I solved it by changing the wildcard option of my equals function.

**Comment by territxl** [comment]
then is it necessary to still remove the escape character? I would think that seems hard-coded...

**Comment by territxl** [comment]
@ianwonghanli thx for explain! I managed to resolve the issue :)
