### ISSUE TITLE
issue with submission of level5.jsh

### ISSUE THREAD

**Issue by taugwa** [nus-cs2030/2223-s2#617]
hi! i was trying to submit files to codecrunch and im getting this error :( i definitely imported Function and my code works in my jshell...so does anyone know why this is happening? addtionally, if yall did not use Function, what did yall use? thank you in advance
<img width="610" alt="Screenshot 2023-03-26 at 2 54 56 PM" src="https://user-images.githubusercontent.com/122268711/227760554-fadaf8ce-1d9b-4985-b93a-dadcb4c00316.png">
<img width="362" alt="Screenshot 2023-03-26 at 2 59 58 PM" src="https://user-images.githubusercontent.com/122268711/227760573-f4e081a4-77d4-4e63-8309-0a22e263cfe7.png">

**Comment by ianwonghanli** [comment]
Did u create custom classes for Collatz? For me, i just defined the two methods for sum and collatz in one level5.jsh file, with no modifications.

**Comment by Sangobionn** [comment]
i didnt use function in my level5.jsh. i just created 2 methods in the file - sum and collatz. for collatz use iteration instead of recursion

**Comment by 0liverkong** [comment]
you need to import java.util.function.Function.

**Comment by briannoelkesuma** [comment]
hi, got the same error as u. did anyone manage to submit using Function in level5.jsh? have only 2 methods in my jsh file, but used Function in my methods and I also imported java.util.function.Function.

**Comment by 0liverkong** [comment]
> hi, got the same error as u. did anyone manage to submit using Function in level5.jsh? have only 2 methods in my jsh file, but used Function in my methods and I also imported java.util.function.Function.

ok i jst went to look at my code and for some reason importing Function didnt work.. i just used lambdas instead and that worked.

**Comment by taugwa** [comment]
https://github.com/nus-cs2030/2223-s2/issues/579 i havent tried this but apparently someone had a similar issue previously and there was a solution suggested that seemed to work, so if yall want can try
