### ISSUE TITLE
map() in level 2

### ISSUE THREAD

**Issue by jiangen16** [nus-cs2030/2223-s2#620]
# Summary
hi guys, im experiencing issues with defining the return value of Function in map(). 

I used Log<T> map(Function<T, T> fn) {...} , which works until the last test case provided, with this error msg

![image](https://user-images.githubusercontent.com/123716826/227767771-8a3f332f-7b0e-4299-a0f9-cb1cf84caea7.png)

afterwards, I tried to change the result of the Function to return a generic type R to accommodate to the String , but I couldn't compile

![image](https://user-images.githubusercontent.com/123716826/227767888-3565a33f-6de7-4dc1-a657-0f2137478661.png)

May I know how am I supposed construct the map()? Thanks
Description of the question / problem here.

## Description:

Clarifications or details with respect to the issue you are facing

## Code Snippets

Attach code snippets (if any)

## Screenshots

Screenshots (if any)

**Comment by Hannybunny2001** [comment]
DId u declare <R> in front of your map method. I think it'll also be clearer if you could send your map method in your code.

**Comment by jiangen16** [comment]
yup I forgot to declare LOL thankss

**Comment by tjdbryan** [comment]
Hi, you should declare your R in front of your method!

**Comment by tjdbryan** [comment]
Hope it helps!
