### ISSUE TITLE
lab 7 level 3 Wrong output 

### ISSUE THREAD

**Issue by justineeyx** [nus-cs2030/2223-s2#624]
Currently my output is this
![image](https://user-images.githubusercontent.com/122433748/227785849-e7b34e17-5f35-4cf6-89da-0151fc81631c.png)
and my current code is 
![image](https://user-images.githubusercontent.com/122433748/227785902-cc779eee-a0e9-4657-8a52-b451ae63714e.png)
How to ensure the string "five" is still being shown?

**Comment by koiljat** [comment]
when you flatMap you are likely removing the existing log String. you can get the log String and then add the new log String to the existing log String

**Comment by orangejunhui** [comment]
your code doesn't update the log string in the existing one, instead, it returns the new Log that only has "add 1". i think you need to return a new Log with the updated value from mapper and the original log + additional log.

**Comment by sporobolous** [comment]
> when you flatMap you are likely removing the existing log String. you can get the log String and then add the new log String to the existing log String

sorry could you elaborate how do I add in the log string, as the string log is private and I am unable to use getters as they are different object types i.e T and R

**Comment by tjdbryan** [comment]
> when you flatMap you are likely removing the existing log String. you can get the log String and then add the new log String to the existing log String

That's right! Do take note of the original values in Log.
