### ISSUE TITLE
jshell error: cannot find symbol PQ

### ISSUE THREAD

**Issue by YanQin-Liu** [nus-cs2030/2223-s2#63]
Hi, does anybody have this issue? When I open PQ in jshell and try to create a PQ class, jshell keeps returning "cannot find symbol" on class PQ when I clearly have PQ open in jshell.

I have already opened Event and all its subclasses, as well as EventComp in jshell

Compiling the same code in a java file does not return any errors.

<img width="842" alt="Screenshot 2023-02-04 at 6 58 21 PM" src="https://user-images.githubusercontent.com/123805062/216763837-59308ab9-4fea-4afd-b5fa-9290e9da140e.png">

**Comment by leezhanpeng** [comment]
Opening Pair.java should do the trick. Hope it helps.

**Comment by YanQin-Liu** [comment]
> Opening Pair.java should do the trick. Hope it helps.

That did the trick. TSYM for your help!

**Comment by jeffkhong11** [comment]
> Opening Pair.java should do the trick. Hope it helps.

Had the same issue too, thanks for the help!
