### ISSUE TITLE
Lab 7 Level 4 Testcase 4_1

### ISSUE THREAD

**Issue by justineeyx** [nus-cs2030/2223-s2#630]
Did anyone encounter this error? 
![image](https://user-images.githubusercontent.com/122433748/227859984-3cb00c8c-941d-4e31-bde0-b5745637c956.png)

Perhaps my .equals method is wrong?  I don't think my flat map and map methods has errors as I alr passed up to test case 4 already
![image](https://user-images.githubusercontent.com/122433748/227860467-ebaf72b9-f13b-479c-8960-d918841eeeec.png)

**Comment by Jeko1239** [comment]
i encountered this issue previously. the equals method is supposed to take in an object similar to the maybe of exercise 4.
So boolean equals(Object obj)

**Comment by siruislybro** [comment]
yepp as mentioned above, you can take reference to the lecture 8 notes (computation context) and refer to the overriding equals method in Maybe

**Comment by Jeko1239** [comment]
if (obj instanceof Log<?> other) {
    Log method

you can use the other's log methods

**Comment by justineeyx** [comment]
> if (obj instanceof Log<?> other) { Log method
> 
> you can use the other's log methods

Got it thanks !
