### ISSUE TITLE
Lab 5.2 Test case 9_12

### ISSUE THREAD

**Issue by sp4ce-cowboy** [nus-cs2030/2223-s2#631]
Hi guys, for testcase 9_12 I seem to be having this problem where a customer arrives but leaves instead of waiting at the self-checkout, which doesn't make sense because all the previous testcases passed. I narrowed down the problem, to what I think is the transition Arrive to Leave being executed instead of Arrive to Wait. I double checked my code and everything seems fine. So far  this code gets 12/18 test cases correct so I assume there shouldn't be a problem with the general transition of Events in my implementation, because otherwise the previous test cases wouldn't pass, but I can't seem to figure out what the specific problem with this test case is.

<img width="753" alt="image" src="https://user-images.githubusercontent.com/19762596/227870701-d5254230-6208-47b1-97cc-aae1a9ca19d7.png">
<img width="749" alt="image" src="https://user-images.githubusercontent.com/19762596/227871866-48fcf179-e46f-4d87-883b-e00c6848dce6.png">

**Comment by Chuacx13** [comment]
might be a "<=" or "<" issue(?) when checking the length of your queue of self-checkout OR you might not have updated the self-checkout queue properly somewhere (i updated them in arrive and serve class, not v sure about your implementation)

Cause from what i see, 
customer 222 and 223 not able to wait but
after customer 201 is done serving by selfcheck4, customer 224 arrives and customer 224 can wait at selfcheck 4
