### ISSUE TITLE
Lab 5.2 Shop vs ServerList Implementation

### ISSUE THREAD

**Issue by sp4ce-cowboy** [nus-cs2030/2223-s2#632]
In my current implementation, my Events trigger a nextEvent which returns a Pair<Event, ImList<Server>> which I then parse to continue with the rest of simulation. My Servers have an integer representing the number of customers in queue. It worked fine for 5.1 and for the first 3 test cases of Lab 5.2 (10/18, 11/18, 12/18) but in implementing self-checkouts it seems like all my Events have their code become overly complicated having to account for servers and self-checkouts separately, now also making it harder to read and debug. Would having a Shop class for e.g. containing a list of servers/self-checkouts etc encapsulating the functions of servers and self-checkouts and their individual queues (and my Events therefore returning Pair<Event, Shop>) be a better design or would that be more complicated? Has anyone tried this? Did it simplify the code or introduce more problems?

**Comment by sethteo** [comment]
I had the same implementation for 5.1 (not involving a shop), however I went to implement a Shop for 5.2 as I believed it made the code much neater and easier to debug since everything is abstracted out of the events. However you can also stick to your current implementation and have the first self-check-out server having the integer representing queue while the other SCOs dont have the integer representing queue

**Comment by leonardwx** [comment]
I didnt have a Shop class during my 5.1 however I implemented it in 5.2 for better clarity and it contains more properties to better keep track of my self check counters.

**Comment by Nicknzk** [comment]
for 5.2, my implementation was that I extend server with a Counter class and there would be a main Counter that has a list of Counters within it. 
so each time eg. 1 C arrive --> go into main Counter list and retrieve Counter 1 to continue the event. 
However this meant that there was many lines for updating and retrival of the Counter and Main Counter. 
Maybe you could try this if it helps

**Comment by sp4ce-cowboy** [comment]
Thanks guys
