### ISSUE TITLE
FAIL TEST CASE 2_1

### ISSUE THREAD

**Issue by pnghaanh** [nus-cs2030/2223-s2#634]
# Summary

method map in class Log<T> cannot be applied to given types;

## Description:

I'm not sure what's going on here... anyone encountered the same issue? Any help or suggestion is appreciated.

## Code Snippets

This is my code snippet for method map in class Log.

![Picture1](https://user-images.githubusercontent.com/124126901/227901562-d87e9c2a-292c-4944-be0a-07a178a2ebc9.png)

## Screenshots

![Picture1](https://user-images.githubusercontent.com/124126901/227900489-de8e3460-39ec-4a5e-a0ea-43858a1ae354.png)

**Comment by pnghaanh** [comment]
> hi!! you have to include wildcard for your Function

Hi! I'm not sure how to do this, can you explain a bit further?

**Comment by pnghaanh** [comment]
> hi!! you have to include wildcard for your Function

Hi, do you mean I should use <? extends R> or something like that instead or <R>?

**Comment by WXUXIN** [comment]
do this : Function(? super T, ? extends <? extends R> f)

**Comment by pnghaanh** [comment]
> Hi, I tried this and the file was uncompilable due to illegal start of type

**Comment by tinghwei** [comment]
you should be writing `map(Function<? super T, ? extends R> f)` !

**Comment by WXUXIN** [comment]
> you should be writing `map(Function<? super T, ? extends R> f)` ! you can refer to lecture 08 slides 

yup this is right sorry thought it was flat map

**Comment by pnghaanh** [comment]
> you should be writing `map(Function<? super T, ? extends R> f)` ! you can refer to lecture 08 slides

solved! tysm!
