### ISSUE TITLE
level 5 sum() using iteration 

### ISSUE THREAD

**Issue by jiangen16** [nus-cs2030/2223-s2#644]
# Summary
hi all, im trying to use iteration to do sum() for level 5's sum(), but i ran into some issues which i dont really understand

![image](https://user-images.githubusercontent.com/123716826/228191791-02357c27-4e77-4653-8ef9-29b119323281.png)

![image](https://user-images.githubusercontent.com/123716826/228191885-acf3dbcd-62be-4244-8484-d82b50cecbf7.png)

I dont understand why i cant use the start variable again, as i thought the flatMap() will result new Log<Integer> Object. Thereafter, I can use flatMap() on a new Log object each time until i have finished iterating.

also, am i not allowed to do "x + i" for the summing of values in the lambda?

Thanks!

## Description:

Clarifications or details with respect to the issue you are facing

## Code Snippets

Attach code snippets (if any)

## Screenshots

Screenshots (if any)

**Comment by Delocy** [comment]
you should use the sum method they gave as a base and modify it, which is using recurssion

**Comment by briannoelkesuma** [comment]
try using another variable that is final. can consider other variables u can assign to?
this is because u cannot change the value of start continuously because of the way lambda functions work in java.

**Comment by tjdbryan** [comment]
Hi, you can consider using recursion following the skeleton code provided! It should be easier

**Comment by jiangen16** [comment]
thanks all resolved!
