### ISSUE TITLE
Lab 7 level 3

### ISSUE THREAD

**Issue by DavidLawCheng** [nus-cs2030/2223-s2#645]
# Summary

Description of the question / problem here.

## Description:

Any clues for level 3 on how to make flatMap method? Sorry, so confused...

## Code Snippets

Attach code snippets (if any)

## Screenshots

Screenshots (if any)

**Comment by trwstin** [comment]
have you done ex4? how you apply the mapping function should be similar to what you did in flatmap for ex4, which will be assigned to a new log object.

however, you cannot directly return this new log object obtained after mapping as it doesnt include the updated string.

so i suggest creating a new string object and using that to concantenate the current log's string with the new log's string.

then return a new log object using the Log(T value, String log) constructor.

you can make use of getters if you want :)

**Comment by kaiyanggg** [comment]
Hi, I did the same way as trwstin said. 
A further note would be to remember to consider the fact that there may be an empty String log that cause you to print a new line even when you don't need to, which you may have to use conditionals for! (May cause issues for level 4)

**Comment by DavidLawCheng** [comment]
Hmm I did not complete exercise 4 so Im not sure, any reason why I get this error? CAP#1 cannot be converted to Log<R>. I did a mapper.apply in this function<R> Log<R> flatMap(Function<? super T, ? extends Log<? extends R>> mapper) , but it gave this error. 
 However when I manually typed it out, it can return a new Log below. 
Function<Integer, Log<Integer>> f = x -> Log.<Integer>of(x + 1, "add 1")
f.apply(5)
$59 ==> Log[6]
add 1

**Comment by e0958049** [comment]
> Hmm I did not complete exercise 4 so Im not sure, any reason why I get this error? CAP#1 cannot be converted to Log. I did a mapper.apply in this function Log flatMap(Function<? super T, ? extends Log<? extends R>> mapper) , but it gave this error.
> However when I manually typed it out, it can return a new Log below.
> Function<Integer, Log> f = x -> Log.of(x + 1, "add 1")
> f.apply(5)
> $59 ==> Log[6]
> add 1

I had the same issue, its because are probably returning Log.of(mapper.apply(this.value)) and you can't Log.of(Log) so what I did was I did mapper.apply() and stored the result before using getters on them to get the value and log then finally returning a new Log using the new value and log(after adding it to the original log).

**Comment by gene2345** [comment]
i think you can just use mapper.apply() for the number part. but for the strings part you shd try to concet the strings together. den return a new log object with the number part and the new concatenated string

**Comment by DavidLawCheng** [comment]
Okay nvm I solved it thanks all!
