### ISSUE TITLE
Lab 07 Test Case 4_1

### ISSUE THREAD

**Issue by iwanttogiveupalr** [nus-cs2030/2223-s2#647]
idk how to deal with A, B and C cos i think my method is comparing the address of the object and not the object itself
<img width="605" alt="Screenshot 2023-03-28 at 10 18 26 PM" src="https://user-images.githubusercontent.com/114241008/228268513-561cec47-b43b-4275-a158-d89da3a4e9f9.png">
<img width="998" alt="Screenshot 2023-03-28 at 10 20 40 PM" src="https://user-images.githubusercontent.com/114241008/228268791-c127a003-ebf1-4444-a586-9e55252263f5.png">

**Comment by iwanttogiveupalr** [comment]
it still doesn't work :(

**Comment by tjdbryan** [comment]
Hello, you can try writing your equals method without using getters (e.g., this.value instead of this.getValue()). Somehow it worked for me (and other people on Github also)!
