### ISSUE TITLE
Lab 7 Level 1 Exception Error 

### ISSUE THREAD

**Issue by user1914** [nus-cs2030/2223-s2#648]
# Summary

I keep getting this error:
jshell> try { Log.<Object>of(hello); }
   ...> catch (Exception e) { System.out.println(e); }
|  Error:
|  cannot find symbol
|    symbol:   variable hello
|  try { Log.<Object>of(hello); }

How can I fix it?

## Description:

Clarifications or details with respect to the issue you are facing

## Code Snippets

Attach code snippets (if any)

## Screenshots

Screenshots (if any)

**Comment by trickypepe** [comment]
hello is a variable from earlier in the example. You need to run this before you test if you can catch the exception.

jshell> Log<String> hello = Log.<String>of("Hello")
hello ==> Log[Hello]

**Comment by nigel-tannn** [comment]
Hi, is it possible that you did not run the previous lines of code prior to this?  It seems that hello has not been initialised

**Comment by tjdbryan** [comment]
^ Try running the previous test cases into your jshell before testing the try-catch block!

**Comment by haqanh** [comment]
Hi you need to run the test case in sequential order, as hello was a variable that was initialized earlier!

**Comment by shawncch** [comment]
you need to initial the Log<String> hello = Log.<String>of("Hello") in level 1's first sample run!
