### ISSUE TITLE
Updating toString() of Recycled Loader: Exercise 2 Level 5

### ISSUE THREAD

**Issue by poon-zx** [nus-cs2030/2223-s2#65]
hi! anyone have any idea how should I update the toString() of the Recycled Loaders in level5.jsh to reflect the word "Recycled" in the output?

**Comment by SimonSeeYongsheng** [comment]
One way is to create a new RecyledLoader class

**Comment by poon-zx** [comment]
@SimonSeeYongsheng did you face a problem where codecrunch doesnt accept your code since the property in Loader is defined as protected final instead of private final? to allow RecycledLoader to inherit the property

**Comment by poon-zx** [comment]
@SimonSeeYongsheng did you face a problem where codecrunch doesnt accept your code since the property in Loader is defined as protected final instead of private final? to allow RecycledLoader to inherit the property

**Comment by SimonSeeYongsheng** [comment]
> @SimonSeeYongsheng did you face a problem where codecrunch doesnt accept your code since the property in Loader is defined as protected final instead of private final? to allow RecycledLoader to inherit the property

RecycledLoader shares the same methods as Loader, so you don't need to override much.
Just need to override the toString() method
