### ISSUE TITLE
Lab 7 Level 1 Test Case 1

### ISSUE THREAD

**Issue by secretApple** [nus-cs2030/2223-s2#651]
# Summary
Does anyone know what could be the reason for this error? Why is there a missing exception at the end

## Screenshots

![image](https://user-images.githubusercontent.com/126102015/228493426-6dc0b23b-99f6-4212-bedf-d650458555e0.png)

**Comment by Maxxtucker** [comment]
You have to check both value and log, using flatmap and optional.ofnullable

**Comment by slimzaza** [comment]
your of method which is in the try block did not throw the exception correctly, try double checking how you are using the orElseThrow in the of method

**Comment by secretApple** [comment]
I did optional.ofnullable(t) then filtered for x not instance of Log then map optional.ofnullable(log) then map to create new log, orelse throw the exception. Did I do any of the steps wrongly?

**Comment by minhphongle** [comment]
Following. I also have this issue as well

**Comment by Aron113** [comment]
your orElseThrow should throw a supplier of the exception

**Comment by secretApple** [comment]
Thanks for the replies! The problem was fixed when I nested the creation of new Log in the flatmap
