### ISSUE TITLE
cannot find symbol error

### ISSUE THREAD

**Issue by yx420** [nus-cs2030/2223-s2#653]
hi any idea why im getting this compilation error?

<img width="374" alt="image" src="https://user-images.githubusercontent.com/122374639/228509240-3212c067-81f3-4338-8d55-8dbb6924d23d.png">

**Comment by jorwong** [comment]
That is because R is not declared. In order to do that add in R as such
public <R> Log<R> ...,

**Comment by yx420** [comment]
ooo rigth i miss out that part tysm
