### ISSUE TITLE
Lab 5.2 Test Case 9_11

### ISSUE THREAD

**Issue by Fliprun** [nus-cs2030/2223-s2#654]
# Summary

There's straight up no output for this test case.

## Description:

Code seems to work fine for every test case until this one where it just stops. Anyone know why this happens?

## Screenshots

![image](https://user-images.githubusercontent.com/128240191/228563903-902f5c59-0cc7-46c6-9cd8-8387e2f069f1.png)

**Comment by jiarui22** [comment]
maybe you had an infinite loop in your program?  can try to use System.out.println to see where you stuck at and improve your code

**Comment by yugan01** [comment]
I also encountered this problem, if you already have code to get the earliest avaliable self check out counter, then i suggest to look at the code in the wait class that returns another wait event (if you have such logic in your code), my issue was that sometimes my wait event returned another wait event with the same time and it results in an infinite loop

**Comment by Fliprun** [comment]
Found the issue. Was indeed a wait event issue. Thanks.
