### ISSUE TITLE
Level 5 - Reverse Output

### ISSUE THREAD

**Issue by kayeugenia** [nus-cs2030/2223-s2#657]
# Summary

Hi im trying to fix my level 5 output because right now it's reversed. I used recursion as provided. I understand why it does not work (because the output of the base case will be returned first), and therefore 1 will be returned in the first line, and not 3(11) + 1. But I am unsure how to swap the code around?

## Screenshots
<img width="357" alt="Screenshot 2023-03-29 at 11 58 42 PM" src="https://user-images.githubusercontent.com/122983473/228597801-fd9c3105-2450-4fa6-996a-cdcc936c4948.png">

**Comment by poon-zx** [comment]
i did this using iteration instead of recursion, think its a lot easier!

**Comment by siruislybro** [comment]
you can return the Log with the required statements first before calling on the next `f` through a `flatMap`

**Comment by yinshuennn** [comment]
I faced the same issue as you, I solved it by switching the positions of my Log and function in FlatMap!

**Comment by slimzaza** [comment]
I managed to solve this by recursion using a helper function that takes in the int n and a Log object which was initialized using he original n input to the f method, hope this helps

**Comment by dlyxxx** [comment]
i did it iteratively as well, and used the flatmap function to update the log! hope this helps

**Comment by briannoelkesuma** [comment]
hi, i did something like tail recursion. u can consider implementing something similar, can refer to this week's recitation.

**Comment by rayray39** [comment]
> I faced the same issue as you, I solved it by switching the positions of my Log and function in FlatMap!

May i ask how does this solve the issue, i dont really understand why it works

**Comment by Aron113** [comment]
try doing it iteratively and in sequence. i think its easier than using a recursive method

**Comment by DavidLawCheng** [comment]
yup did so iteratively, for the second qns I used a while loop to hit base case

**Comment by minhphongle** [comment]
you can try the iterative approach instead (which my friend did)! recursion works too but takes much more efforts in refining the code.

**Comment by e0968868** [comment]
I used a while loop because it was more intuitive for me!

**Comment by kayeugenia** [comment]
thanks all! managed to solve it with while loop. I think using tail recursion (similar to this wks lab) might be a possible implementation too
