### ISSUE TITLE
Lab 7 of (T, String) method

### ISSUE THREAD

**Issue by eesean** [nus-cs2030/2223-s2#658]
Hi all,

Would like to ask how is it possible to map 2 optionals (e.g. Optional.ofNullable(t) and Optional.ofNullable(string)) for the of(t, string) method such that I get a Log object? I get that there is a need to check both elements for nullity but they also can't be independent variables, so do they have to be a stream of pairs?

**Comment by e0970430** [comment]
I didn't do it this way (mapping or using streams) so I'm not very sure if it could work but I would suggest against doing that because then it will be hard to throw the error especially since we can only use .orElseThrow once

**Comment by e0970430** [comment]
Instead, perhaps you could consider using .orElse for the Optional.ofNullable(_string_) to get a String _newString_ if the _string_ is a null value, and then filter the Optional.ofNullable(t) to make sure that the conditions for Log (eg instanceof Log, _string_ is not null) are met, if not .orElseThrow the exception. Then, since the code would only proceed if the conditions are met, return Log(t, string) (i.e. the constructor)

**Comment by eesean** [comment]
So is the sequence like this (sorry i'm very confused)?

1. Check the string for nullity
2. filter Optional.ofNullable(t) using orElse? (getting incompatible types though)
3. throw exception
4. return Log if conditions are met

**Comment by chanjieru** [comment]
> So is the sequence like this (sorry i'm very confused)?
> 
> 1. Check the string for nullity
> 2. filter Optional.ofNullable(t) using orElse? (getting incompatible types though)
> 3. throw exception
> 4. return Log if conditions are met

hello this is what i did:
1. check that t is not null
2. filter that t is not of type Log
3. check that log is not null (using flatMap)
4. use nested map to create Log object
5. orElseThrow exception

**Comment by eesean** [comment]
hmm but how do I go from step 2 to 3? Because Optional.ofNullable takes in only 1 value, if I start by checking t I can't jump over and check the string, the types would be incompatible.

**Comment by eesean** [comment]
Hmm I tried the orElseThrow exception as the last part, but I do not receive the exception on the test cases. I placed it in the sequence as what you suggested, does it make a difference if I put orElseThrow after checking for t and log respectively?

**Comment by rayray39** [comment]
hi remember that orElseThrow takes in a supplier, so the supplier needs to provide the exception. it shouldnt matter as long as its your last chained method i think, cos if your filter of flatmap returns an Optional.empty, it will just throw the error inside the orElseThrow
