### ISSUE TITLE
ArrayLists in Java vs Python

### ISSUE THREAD

**Issue by kciruos** [nus-cs2030/2223-s2#66]
In CS1010S, we learn in python lists that lists can be heterogeneous and can include different types within it. But in Java, so far we have seen that each ImList/ArrayList can only include items of the same type. Is this always true? Is there a 'container' where we can store items on differeing types in Java?

**Comment by VanyaPriscillia** [comment]
I think ImList and ArrayList can be heterogeneous through using the Object class.

**Comment by 0liverkong** [comment]
what vanya said is right. also it forces us to think whether there are better data structures for homogenous data that we want to store (maybe Pair)
