### ISSUE TITLE
Lab 5.2  Test Case 9_11 infinite loop

### ISSUE THREAD

**Issue by subhadhra-m** [nus-cs2030/2223-s2#661]
I am stuck in an infinite loop for this question. I tried to replicate this test case, however, with a default servicetime of 1.000. This is my output.  The loop is occurring in my checkevent. In my checkevent, this is how I return events if it is a self-checkout server. Could anyone help to suggest what might be causing this and how I can rectify this issue.
<img width="350" alt="Screenshot 2023-03-30 at 9 15 23 PM" src="https://user-images.githubusercontent.com/125443673/228854961-4e656324-7a4b-4b04-a7ce-c31efb4c84e8.png">
<img width="337" alt="Screenshot 2023-03-30 at 9 15 42 PM" src="https://user-images.githubusercontent.com/125443673/228855182-569d5e59-25fe-4153-ab7a-0b45d55deb13.png">

<img width="698" alt="Screenshot 2023-03-30 at 9 39 24 PM" src="https://user-images.githubusercontent.com/125443673/228855215-af38dc0a-d1a9-465f-9732-acf9195b9a4f.png">

**Comment by subhadhra-m** [comment]
Thanks a lot for ur input. I actually put System.out.println in the priority queue. The empty lines are check events as my toString method for checkevent is "". The standalone arrivaltimes are the arrivaltimes of customers that go through checkevent each time.

**Comment by ghost1nthemachine** [comment]
likely it is returning the same event many times. try to put more system.out.println within your if else loop and check exactly where customers are going. i faced a similar issue in my arrive event, and realised that it was bc my if conditions just did not work properly.

**Comment by subhadhra-m** [comment]
Thank you so much for ur help guys, managed to get rid of my infinite loop, however, got stuck here 
<img width="600" alt="Screenshot 2023-03-31 at 9 54 12 AM" src="https://user-images.githubusercontent.com/125443673/229003071-c2f70459-0dbc-4c42-90f0-d5a4fe9d8a78.png">

**Comment by SimonSeeYongsheng** [comment]
> Thank you so much for ur help guys, managed to get rid of my infinite loop, however, got stuck here <img alt="Screenshot 2023-03-31 at 9 54 12 AM" width="600" src="https://user-images.githubusercontent.com/125443673/229003071-c2f70459-0dbc-4c42-90f0-d5a4fe9d8a78.png">

This issue probably has to do with getting the next Server that ends the earliest.
You should check if your implementation for getting the next earliest server is correct

**Comment by ghost1nthemachine** [comment]
yep, agree with the above. depending on ur impl, u need to find a way to loop through ur list of self check servers and return server with the lowest next avail time. for me i did this in my wait and waitagain events.

**Comment by keshialimm** [comment]
Hi, regarding the new issue, what you can make sure is to check for the earliest available server in all ur intermediate events! even if the customer has to continue waiting, they should be "assigned" the timestamp for the earliest available server at that moment. 

If you've already done this, then I agree with the above as well. Your implementation for getting the earliest available server may be wrong

**Comment by subhadhra-m** [comment]
For my implementation, every wait event will go to a check event. The check event returns serve event, if the customer is first in line. If its not, it will return a checkevent again. 

Following your suggestion, I created this method and implemented it in both wait and checkevent. So if it is to be served by a self-check, my wait event's next event method returns a check event with the nextFree server's totaltime. 

<img width="681" alt="Screenshot 2023-04-01 at 10 04 45 AM" src="https://user-images.githubusercontent.com/125443673/229260867-baf8c481-1349-4757-993f-5173f5143c44.png">

This is how my checkEvent's next event method for selfcheck servers is like
<img width="779" alt="Screenshot 2023-04-01 at 10 19 52 AM" src="https://user-images.githubusercontent.com/125443673/229261341-07e86208-000b-4d7e-9ab8-e1a0c3fb2753.png">

However, im still getting this same output!

**Comment by ghost1nthemachine** [comment]
hmm looking the cc test case, it seems like maybe its the way ur managing the self checkout queue. mayb check the qmax method or how u add/remove customers. i.e. 16 leaves bc it thinks the queue is full but its not and is 13/14 eventually served or did they disappear? secondly id recommend u double check how u reference the timings of each self check server, and use the updated servers from the imlist rather than the ones that you are "pass" into the class

**Comment by subhadhra-m** [comment]
13 and 14 do get served by selfcheck 3. However, self-check 4 doesnt serve any customer after the first.
