### ISSUE TITLE
Lab 5.1 infinite loop - test case 9_9

### ISSUE THREAD

**Issue by gracico** [nus-cs2030/2223-s2#662]
# Summary

edit: getting an infinite loop

## Description:

works well for all the public test cases. I think the issue occurs when number of self-check is set to 0.

Im not sure why the error occurs in the middle..?

## Screenshots
 this is the output when the following inputs are used
0 2 2 0.5
0.000000
0.313508
1.204910
2.776499
3.876961
3.909737
9.006391
9.043361
9.105379
9.159630
<img width="871" alt="Screenshot 2023-03-31 at 1 17 45 AM" src="https://user-images.githubusercontent.com/122587013/228915320-8a0ff157-60e4-4edb-9291-bc06b7568ece.png">

**Comment by gracico** [comment]
thanks for the suggestion, added the print statements and it seems to be stuck at my continueWait event

**Comment by gracico** [comment]
> You could try to add debugging print statements in your code to check whether your server queue is initialized correctly or whether the right events are added into the events PQ

thanks for the suggestion, added the print statements and it seems to be stuck at my continueWait event

**Comment by sethteo** [comment]
> > You could try to add debugging print statements in your code to check whether your server queue is initialized correctly or whether the right events are added into the events PQ
> 
> thanks for the suggestion, added the print statements and it seems to be stuck at my continueWait event

You might not be getting the most updated nextavailabletime for the current server as if you use this.server.nextAvailTime() it is not the MOST updated server, instead you should make a Server updatedServer = ImList.get(this.server.id() - 1)

**Comment by Aron113** [comment]
It could be your Wait or Checker event returning itself infinitely if their event time isn't updated correctly

**Comment by youthfrost** [comment]
You may want to check if u updated your server's available time correctly before and after every event, because it seems like your server 6 arrives but it sees self check 1 as available

**Comment by gracico** [comment]
solved! realised i added my tostring in the wrong order and the infinite loop was caused by the way i set my manager's available time
