### ISSUE TITLE
Lab 5.2 Test Case 9_11

### ISSUE THREAD

**Issue by bobafreshmilk** [nus-cs2030/2223-s2#663]
# Summary

Hi there, I am stuck on this test case and I am not sure how to solve it. 

## Description:
It seems like my self-check server queue is not updated after serving customer 9 as self-check 4 should start serving customer 13 while mine gave an empty output in line 33.
My self-check servers will all be updated when there is a change to the queue in the respective events.

Can any kind soul shed some light on this issue that I am facing? Thanks!

## Screenshots

<img width="580" alt="Screenshot 2023-03-30 at 10 35 48 PM" src="https://user-images.githubusercontent.com/122723083/228871994-acf232d1-3ac6-4f97-a276-da4f15cd5f15.png">

**Comment by kaiyanggg** [comment]
Hi, I just ran into and solved the same issue. As said above, I checked that the customer should be served by the self check out with the closest available time in both my wait and intermediate wait events(if you have those), using a for loop. It appears as though your customer 13 is waiting for the self check out 3 instead of being served by 4.

**Comment by bobafreshmilk** [comment]
> You may be forgetting to check that the customer should be served at the checkout counter with the shortest waiting time. It seems like none of your customers are being assigned to self checkout 4 if they have a wait event created.
> 
> You could perform a check such that if the customer is waiting for a self check out counter, loop through all the self checkout counters to find the one which has the shortest waiting time.

Thanks! It solved my problem:D

> Hi, I just ran into and solved the same issue. As said above, I checked that the customer should be served by the self check out with the closest available time in both my wait and intermediate wait events(if you have those), using a for loop. It appears as though your customer 13 is waiting for the self check out 3 instead of being served by 4.
Thanks! It solved my problem:D

**Comment by bobafreshmilk** [comment]
> You may be forgetting to check that the customer should be served at the checkout counter with the shortest waiting time. It seems like none of your customers are being assigned to self checkout 4 if they have a wait event created.
> 
> You could perform a check such that if the customer is waiting for a self check out counter, loop through all the self checkout counters to find the one which has the shortest waiting time.



> Hi, I just ran into and solved the same issue. As said above, I checked that the customer should be served by the self check out with the closest available time in both my wait and intermediate wait events(if you have those), using a for loop. It appears as though your customer 13 is waiting for the self check out 3 instead of being served by 4.

Thanks!! It solved my issue :D

**Comment by bobafreshmilk** [comment]
issue resolved

**Comment by bobafreshmilk** [comment]
> omg facing the same issue rn :"(

Hi! You might want to refer to the comments, they managed to solve my problem
