### ISSUE TITLE
equals & flatmap methods

### ISSUE THREAD

**Issue by veviana** [nus-cs2030/2223-s2#664]
any advice on the flatmap and equals method? for flatmap, i add a new line for each log. im not too sure if that is the reason why i cant pass the monad right identity in the equals method. when i removed the newline \n, i managed to pass the monad right identity, but it will mess up the output when simply using flatmap()
![image](https://user-images.githubusercontent.com/94920324/228893450-0957194f-1cb5-4c11-9515-5b74a3f41429.png)
![image](https://user-images.githubusercontent.com/94920324/228893688-8d88cac2-c327-4847-b451-c38bbaa80fc2.png)

**Comment by junhonglow** [comment]
You could a perform a check to see if the new log is an empty string, if it is you could just use the current log.
If it is not empty, then you can append the newline character alongside the new log.

**Comment by aa01xx** [comment]
I have encountered a similar problem, perhaps try to printout what your string log is for each instance and check if they are the same? I ended up rewriting flatmap as well to get the right output because my printouts were different for the supposedly same instance.

**Comment by kaiyanggg** [comment]
Hi, it appears as though your flatmap method has an issue. For my flatmap, i had a conditional in which if the initial string log is empty, I add the new log without adding a new line. However, if it is not I add it with a new line

**Comment by veviana** [comment]
thankyou all! managed to solve it by doing the conditional check in my flatmap!

> Hi, it appears as though your flatmap method has an issue. For my flatmap, i had a conditional in which if the initial string log is empty, I add the new log without adding a new line. However, if it is not I add it with a new line
