### ISSUE TITLE
Lab 7 level 3 

### ISSUE THREAD

**Issue by tryngmyhardest** [nus-cs2030/2223-s2#665]
been stuck on this for awhile. how exactly do I store the string log such that I can concatenate the new string with the old one? adding an attribute would mean that it cant be private final..

how do i store a new log? I got this error: The parameterized method of(R, String) of type Log is not applicable for the arguments (capture#18-of ? extends Log<? extends R>, String)

any advice? thanks

**Comment by clarwen** [comment]
There is no adding of attributes, the updated string is in the new Log(T, updatedString). Just have to create a variable updatedString

**Comment by e0958049** [comment]
apply the function first then use getters to get the new log which is a string to be added, then create a string variable to concatenate the 2 strings by adding this.log with the new log string, then lastly create a new Log() object

**Comment by tryngmyhardest** [comment]
thanks a lot! @e0958049 how should I store this new log? I keep getting an error: The parameterized method <R>of(R, String) of type Log is not applicable for the arguments (capture#18-of ? extends Log<? extends R>, String)

**Comment by aa01xx** [comment]
What i did was to overload the constructor of the Log class so that the log can be updated.

**Comment by e0958049** [comment]
> thanks a lot! @e0958049 how should I store this new log? I keep getting an error: The parameterized method of(R, String) of type Log is not applicable for the arguments (capture#18-of ? extends Log<? extends R>, String)

all the logs are actually of type String, so after you apply the function, use a getter to get your new log and store it with a String type variable will do. Subsequently add this.log to this variable to obtain the concatenated log

**Comment by haqanh** [comment]
What I did was overload my constructor with one that can take in the new updated Log (I stored them in a ImList)

**Comment by Aron113** [comment]
You could add the new String to the current String and pass it into a new Log object

**Comment by cher212** [comment]
You can store the string log by just creating a new String variable and adding the new log to this.log. To create the final Log() object, you can use "new Log<R>(... , ...)" instead of the "of" method

**Comment by tryngmyhardest** [comment]
thanks all! got the output 👍
