### ISSUE TITLE
fail test case 9_11

### ISSUE THREAD

**Issue by yx420** [nus-cs2030/2223-s2#668]
<img width="445" alt="image" src="https://user-images.githubusercontent.com/122374639/228936288-ecc8b559-7308-44ce-9f81-8d999e735411.png">

Need help figuring out what is causing the error in this test case TT

**Comment by EpicSpirito** [comment]
Are you looping through selfcheckouts to get the shortest available time so customers can go to that selfcheckout?
I think customer 13 is being served by self-check 3 which he first waited at instead of being served by self-check 4

**Comment by leonardwx** [comment]
check the shared queue of the self check to ensure they are updated correctly then search the next available self check

**Comment by yx420** [comment]
ooo yes i realised that in my wait event it loop through the self checks to see if anyone's available to serve and now i think the problem is when both counters are available, it will just take the counter with smallest Id, but i have no idea how to fix this TT

**Comment by leonardwx** [comment]
u can compare with the available time of the self checks

**Comment by yx420** [comment]
okay lemme try tysm

**Comment by kaiyanggg** [comment]
Hi, can do a for loop(in both wait and intermediate wait event) to check for the minimum available time of all the self checkout counters! Be careful with the events that you return as well remember to check that you are returning the correct times
