### ISSUE TITLE
Detected checking other class types using instanceof. Grading terminated.

### ISSUE THREAD

**Issue by joshuagohez** [nus-cs2030/2223-s2#67]
# Summary

Decided to use instanceof operator for lab 2 since it was introduced in recitation 2, but codecrunch terminated the grading.

## Description:

Is the use of instanceof not encouraged or is it undermining the design principle we ought to follow for CS2030? If so, is there any advice or workarounds for checking class types?

## Screenshots
<img width="411" alt="Screenshot 2023-02-05 at 2 44 44 AM" src="https://user-images.githubusercontent.com/96434745/216784268-5d6dbff1-d0d0-49f5-8593-a72276d89f3d.png">

**Comment by 0liverkong** [comment]
i personally opted to use static typeids for each event. not sure if thats recommended either.

**Comment by guanquann** [comment]
My TA mentioned that using isinstance is a little problematic in codecrunch and discouraged us from using it.

**Comment by SimonSeeYongsheng** [comment]
instanceof and getclass are considered evil methods by the prof.
If you are allowed to use these methods, there is no need for polymorphism.

Only allowed in equal method.

**Comment by clementlemon02** [comment]
Maybe other than checking the class type using instanceof, you can try assigning something else to the class and check from there

**Comment by joshuagohez** [comment]
Thanks all decided to handle it with polymorphism with general methods e.g `handleNextEvent()` and override the specific logic in each child event class. Works great. Will be closing this.
