### ISSUE TITLE
On slide 6, it is mentioned that Functions are first-class citizens, does "Functions" refers to the class "Function" only? Or does it applies to methods in a class?

### ISSUE THREAD

**Issue by GreenTea749** [nus-cs2030/2223-s2#670]
# Description

Description of the question here.

## Topic:

Specific Topics this question is related to (If Any)

## Screenshots

Screenshots (if any)

**Comment by 0liverkong** [comment]
it applies to lambda functions as well, you can pass them as arguments into constructors of functional interfaces.

**Comment by GreenTea749** [comment]
Thanks! I understand why lambda functions are considered 1st class as well, but is it true that all functions are first class citizens? My confusion lies in instance methods and abstract class methods ( non lambda).

**Comment by hwkchia** [comment]
That's a good question.  Do you realize when we say "passing a functionality" (either as lambda or anonymous inner class) to another method, it really means passing an implementation of an interface (which is actually an object)?  Ultimately, Java being a OO language can only have objects and primitives as first class citizens.

**Comment by GreenTea749** [comment]
Ok thank you!
