### ISSUE TITLE
Lab 5.2 Test Case 9_9

### ISSUE THREAD

**Issue by eesean** [nus-cs2030/2223-s2#671]
Hi all, encountered this exception which I thought I have already accounted for:

<img width="712" alt="Screenshot 2023-03-31 163107" src="https://user-images.githubusercontent.com/110977266/229118188-317867d9-811f-4850-8f41-d0ce4d38943b.png">

What is supposed to happen during serve event is that I will retrieve a server from the list of servers (using get( )), after which I add the corresponding customer into the server. This exception did not appear when I submitted 5.1 but only when I tried a submission on condecrunch earlier today.

Although I have yet to pass the test case as per 4.in, I would like to ask whether anyone has encountered a similar issue and how I could deal with the exception?

**Comment by youthfrost** [comment]
Try printing out all the server index and see if your have - 1. If so it means that the server you trying update is not found in the list. You might want to check if the server or the list is outdated

**Comment by Nora-Ruoming** [comment]
I encountered a similar error and solved it, I figured out it should be the issue of the server list order. What I did as youthfrost suggested, I tried to print out the index of the server and customers to see whether they are following a synchronously updated sequence and changed the logic of somewhere the servers(customers) lie.

**Comment by eesean** [comment]
Thanks for the inputs! Yea I have to check consider whether the list of servers is empty and whether the number I use to retrieve the server is positive.
