### ISSUE TITLE
Perplexing Problem from 9_11 onwards

### ISSUE THREAD

**Issue by mavisczx** [nus-cs2030/2223-s2#673]
# Summary

There are a lot of queries regarding 9_11 test case, but I have already created many system.out.print statements to check.
I also created a test case with only 2 self-check servers, with 2 customers (9 and 10) arriving at the same time. 

I ended up with an infinite loop of customer 10 not being able to pass the "first in the queue condition", and when it was time for 10 to be processed, customer 9 was still in the queue...? 

My general flow is once arrival->wait class and add customer to queue in wait, remove customer in serve. From wait class go straight to queue class (intermediate) and then from there decide to serve or queue again. What is perplexing is that the same logic works completely fine for only human servers. 

## Description:
I checked the adding and removing of customers, updating the times of the servers and it all seemed fine. 

Any help would be greatly appreciated, thank you very much and have a nice day! 

## Code Snippets
Additionally, I also created a condition to check for the earliest free time in my queue class (intermediate wait event).  

<img width="747" alt="image" src="https://user-images.githubusercontent.com/122339026/229144905-7f45b718-287b-47a5-b0b8-8979d4b9e5aa.png">

## Screenshots
This is the condition to check if customer is first in queue. 
<img width="751" alt="image" src="https://user-images.githubusercontent.com/122339026/229144632-b2bf83c9-3a55-468b-9c47-975fd87900ee.png">

**Comment by mavisczx** [comment]
@ghost1nthemachine Yep its one queue. I made sure to remove only from the first selfcheckserver's queue.

**Comment by andersooi** [comment]
I think I might have faced a simiilar issue to you. What helped me was to check for the earliest self-checkout counter in both the Wait event and intermediate Wait event. Not sure if that helps or if you have already done that.

**Comment by mavisczx** [comment]
I have solved the issue! Thanks everyone! 
For anyone with a similar problem:
My problem was: I always remove from queue first then update the timings (in serve), but if its first self-check that is actually serving, then i removed cust from queue but i used the outdated server to update the timings
