### ISSUE TITLE
Level 4: Difference between Frac class and Fraction class

### ISSUE THREAD

**Issue by ianwonghanli** [nus-cs2030/2223-s2#674]
# Summary

Hey all. I am confused by the wording of Frac class and Fraction class. Specifically, I do not know how the Fraction class differs from the Frac class. Furthermore, I do not understand how to implement the Fraction class with respect to the question's requirements. Explanations would be much appreciated!

**Comment by haqanh** [comment]
Hint: it is specified that Fraction inherits from AbstractNum, which has the static .of() method to create a new AbstractNum. Think of how you can make use of Frac to get the input for this .of() that you will implement in Fraction!

**Comment by maze508** [comment]
It should be kind of similar to your Num implementation

**Comment by fy17ohhh** [comment]
You are not supposed to write toString method yourself, so you are basically using the toString method from AbstractNum class. Consider what to wrap inside opt for Fraction class so that you will get a single NaN output when the opt is empty

**Comment by granolaluvr69** [comment]
A Fraction is an AbstractNum<Frac> and a Frac is a pair of 2 natural numbers.

**Comment by stxe09** [comment]
Think of Frac as an intermediate class helping you to implement Pair<Num,Num>
