### ISSUE TITLE
Failing testcase 2_1

### ISSUE THREAD

**Issue by Xuehann** [nus-cs2030/2223-s2#675]
# Summary
Hi, may I know if anyone has encountered similar issues? 

## Screenshots

![Screenshot 2023-03-31 224128](https://user-images.githubusercontent.com/122248833/229152535-ec78a51e-e5ae-4434-83cd-12db39ebc90d.png)

**Comment by junhonglow** [comment]
Did you include bounded wildcards in your map method?

**Comment by ianwonghanli** [comment]
As seen in the screenshot, the function f takes in class A and outputs class C. Since B is the child class of A and C is the child class of B, you should include the appropriate wildcards/
