### ISSUE TITLE
Level 1 of() method

### ISSUE THREAD

**Issue by gi2328** [nus-cs2030/2223-s2#676]
How do you get the exception for the of(T value) method? 

At first I threw an exception but it is not allowed in code crunch so are we supposed to do it the same as the of(T value, String log) method by having the Optional.ofNullable(... ?

**Comment by leonardwx** [comment]
u can throw exception through checking whether is both value and log.  something like
Optional.ofNullable(value).filter().flatMap().map().orElseThrow()

**Comment by vivyanliew** [comment]
you can do one throw in the of(value, string) then call it in the of(value)

**Comment by Waynelearn** [comment]
Optional.ofNullable(value) // Optional empty if value is null
then You can try mapping to log, if either of them are null, it will become Optional.empty
then can map to a new Log object then throw exception if either log and value is null

**Comment by andersooi** [comment]
You can refer to my reply here #678, hope that it helps

**Comment by haqanh** [comment]
Like others have mentioend, you can create an Optional.ofNullable() which will either store a value or a null. then at the end of the pipeline you can have an orElseThrow() which would either return the value T itself, or throw an exception if the value is null

**Comment by ouhznay** [comment]
hm i just returned another log of with 2 inputs, except the string is empty, hopefully that helps!
