### ISSUE TITLE
Lab8 Level 5 add, sub and mul for Fraction Class

### ISSUE THREAD

**Issue by fy17ohhh** [nus-cs2030/2223-s2#677]
Hi, so for level 5 we are supposed to implement the add, sub, and mul functions for Fraction Class;
However, since I wrapper Frac using Optional in Fraction Class and we are not allowed to use getters for Optional Class,
I was not able to get the Num values in Frac in Fraction
May I ask if anyone have any ideas how we get the Nums wrapper inside Frac? Or are there any other ways to implement Fraction Class?

**Comment by fy17ohhh** [comment]
> think you can consider using FractionInstance.opt.map(x -> x.first()) to retrieve the abstract numbers of the Num itself.

I thought we are not allowed to write addition lambda functions

**Comment by jaejayrome** [comment]
I asked my TA on this though because the question mentioned "arithmetic lambda expressions", in this case we aren't performing anything arithmetic at all we are just retrieving the individual numbers from the fraction

**Comment by jaejayrome** [comment]
update: what I did was to use .first() .second() to get each Num, then proceed to flatMap and an inner map to perform .add()/.sub()/.mul() of the 2 Nums wrapped in both optionals then returning it under an optional

**Comment by trickypepe** [comment]
> update: what I did was to use .first() .second() to get each Num, then proceed to flatMap and an inner map to perform .add()/.sub()/.mul() of the 2 Nums wrapped in both optionals then returning it under an optional

I did something similar to this, though I couldn't figure out how to operate on 2 Optional Num. Instead I retrieved the Optional<Integer> out with flatmap(x -> x.opt) and operated on that (might need to add a new static of in Num for this to work).

**Comment by wongjingwen** [comment]
> update: what I did was to use .first() .second() to get each Num, then proceed to flatMap and an inner map to perform .add()/.sub()/.mul() of the 2 Nums wrapped in both optionals then returning it under an optional

How did you retrieve .first() and second() since it is stored in an Optional<Frac>?

**Comment by jaejayrome** [comment]
> > update: what I did was to use .first() .second() to get each Num, then proceed to flatMap and an inner map to perform .add()/.sub()/.mul() of the 2 Nums wrapped in both optionals then returning it under an optional
> 
> How did you retrieve .first() and second() since it is stored in an Optional(Frac)? Using this.opt.map(x -> x.first()) will return an error since Optional(Obj) cannot be converted to Num

I don't understand your question because the Frac class extends the Pair class so it inherits the first() and second(), using this.opt.map(x -> x.first()) would change it from an Optional<Frac> to an Optional<Num>, it would still be wrapped within the Optional.

**Comment by fy17ohhh** [comment]
> 

May I ask how you use flatMap and map to perform add() sub() and mul() on Optional(Num)?

**Comment by fy17ohhh** [comment]
> > > update: what I did was to use .first() .second() to get each Num, then proceed to flatMap and an inner map to perform .add()/.sub()/.mul() of the 2 Nums wrapped in both optionals then returning it under an optional
> > 
> > 
> > How did you retrieve .first() and second() since it is stored in an Optional(Frac)? Using this.opt.map(x -> x.first()) will return an error since Optional(Obj) cannot be converted to Num
> 
> I don't understand your question because the Frac class extends the Pair class so it inherits the first() and second(), using this.opt.map(x -> x.first()) would change it from an Optional(Frac) to an Optional(Num), regardless it would still be wrapped within the Optional so it should be valid

May I ask how you use flatMap and map to perform add() sub() and mul() on Optional(Num)?

**Comment by wongjingwen** [comment]
> > > update: what I did was to use .first() .second() to get each Num, then proceed to flatMap and an inner map to perform .add()/.sub()/.mul() of the 2 Nums wrapped in both optionals then returning it under an optional
> > 
> > 
> > How did you retrieve .first() and second() since it is stored in an Optional(Frac)? Using this.opt.map(x -> x.first()) will return an error since Optional(Obj) cannot be converted to Num
> 
> I don't understand your question because the Frac class extends the Pair class so it inherits the first() and second(), using this.opt.map(x -> x.first()) would change it from an Optional(Frac) to an Optional(Num), regardless it would still be wrapped within the Optional so it should be valid

Oh my bad wrongly interpreted. However, from a Optional(Num) how are we supposed to retrieve the inner value to do arithmethic calculation?

**Comment by fy17ohhh** [comment]
> > > > update: what I did was to use .first() .second() to get each Num, then proceed to flatMap and an inner map to perform .add()/.sub()/.mul() of the 2 Nums wrapped in both optionals then returning it under an optional
> > > 
> > > 
> > > How did you retrieve .first() and second() since it is stored in an Optional(Frac)? Using this.opt.map(x -> x.first()) will return an error since Optional(Obj) cannot be converted to Num
> > 
> > 
> > I don't understand your question because the Frac class extends the Pair class so it inherits the first() and second(), using this.opt.map(x -> x.first()) would change it from an Optional(Frac) to an Optional(Num), regardless it would still be wrapped within the Optional so it should be valid
> 
> May I ask how you use flatMap and map to perform add() sub() and mul() on Optional(Num)? I ended up having sth like Num.mul(Optional(Num))

update: I realise that `a.flatMap(x -> b.map(y -> x.mul(y)))` would help!

**Comment by jaejayrome** [comment]
> > > > update: what I did was to use .first() .second() to get each Num, then proceed to flatMap and an inner map to perform .add()/.sub()/.mul() of the 2 Nums wrapped in both optionals then returning it under an optional
> > > 
> > > 
> > > How did you retrieve .first() and second() since it is stored in an Optional(Frac)? Using this.opt.map(x -> x.first()) will return an error since Optional(Obj) cannot be converted to Num
> > 
> > 
> > I don't understand your question because the Frac class extends the Pair class so it inherits the first() and second(), using this.opt.map(x -> x.first()) would change it from an Optional(Frac) to an Optional(Num), regardless it would still be wrapped within the Optional so it should be valid
> 
> May I ask how you use flatMap and map to perform add() sub() and mul() on Optional(Num)? I ended up having sth like Num.mul(Optional(Num))

what I did was to use Optional(Num).flatMap(x -> Optional(YourSecondNum).map(y -> y.mul(x))

**Comment by jaejayrome** [comment]
> 

yes, hahaha this was what I meant by the inner map calling within the flatmap function from the start!!

**Comment by jaejayrome** [comment]
> > > > > update: what I did was to use .first() .second() to get each Num, then proceed to flatMap and an inner map to perform .add()/.sub()/.mul() of the 2 Nums wrapped in both optionals then returning it under an optional
> > > > 
> > > > 
> > > > How did you retrieve .first() and second() since it is stored in an Optional(Frac)? Using this.opt.map(x -> x.first()) will return an error since Optional(Obj) cannot be converted to Num
> > > 
> > > 
> > > I don't understand your question because the Frac class extends the Pair class so it inherits the first() and second(), using this.opt.map(x -> x.first()) would change it from an Optional(Frac) to an Optional(Num), regardless it would still be wrapped within the Optional so it should be valid
> > 
> > 
> > May I ask how you use flatMap and map to perform add() sub() and mul() on Optional(Num)? I ended up having sth like Num.mul(Optional(Num))
> 
> update: I realise that `a.flatMap(x -> b.map(y -> x.mul(y)))` would help!
yes, this was what I meant from the start by calling an inner map function within the flatmap, my apologies should have written out in code form

**Comment by fy17ohhh** [comment]
> > > > > > update: what I did was to use .first() .second() to get each Num, then proceed to flatMap and an inner map to perform .add()/.sub()/.mul() of the 2 Nums wrapped in both optionals then returning it under an optional
> > > > > 
> > > > > 
> > > > > How did you retrieve .first() and second() since it is stored in an Optional(Frac)? Using this.opt.map(x -> x.first()) will return an error since Optional(Obj) cannot be converted to Num
> > > > 
> > > > 
> > > > I don't understand your question because the Frac class extends the Pair class so it inherits the first() and second(), using this.opt.map(x -> x.first()) would change it from an Optional(Frac) to an Optional(Num), regardless it would still be wrapped within the Optional so it should be valid
> > > 
> > > 
> > > May I ask how you use flatMap and map to perform add() sub() and mul() on Optional(Num)? I ended up having sth like Num.mul(Optional(Num))
> > 
> > 
> > update: I realise that `a.flatMap(x -> b.map(y -> x.mul(y)))` would help!
> > yes, this was what I meant from the start by calling an inner map function within the flatmap, my apologies should have written out in code form

hahaha just realize how to play the trick here to unfold multiple Optionals! thx a lot @jaejayrome 
and also thx for the replies guys! @wongjingwen @trickypepe 
atb!

**Comment by fy17ohhh** [comment]
> > > > > > > update: what I did was to use .first() .second() to get each Num, then proceed to flatMap and an inner map to perform .add()/.sub()/.mul() of the 2 Nums wrapped in both optionals then returning it under an optional
> > > > > > 
> > > > > > 
> > > > > > How did you retrieve .first() and second() since it is stored in an Optional(Frac)? Using this.opt.map(x -> x.first()) will return an error since Optional(Obj) cannot be converted to Num
> > > > > 
> > > > > 
> > > > > I don't understand your question because the Frac class extends the Pair class so it inherits the first() and second(), using this.opt.map(x -> x.first()) would change it from an Optional(Frac) to an Optional(Num), regardless it would still be wrapped within the Optional so it should be valid
> > > > 
> > > > 
> > > > May I ask how you use flatMap and map to perform add() sub() and mul() on Optional(Num)? I ended up having sth like Num.mul(Optional(Num))
> > > 
> > > 
> > > update: I realise that `a.flatMap(x -> b.map(y -> x.mul(y)))` would help!
> > > yes, this was what I meant from the start by calling an inner map function within the flatmap, my apologies should have written out in code form
> 
> hahaha just realized how to play the trick here to unfold multiple Optionals! thx a lot @jaejayrome and also thx for the replies guys! @wongjingwen @trickypepe atb!

**Comment by wongjingwen** [comment]
However, once you get an Optional(Num) for numerator and denominator how were you able to put it into the new Frac

**Comment by poon-zx** [comment]
@wongjingwen i did this by creating a new Fraction constructor that took in Optional<Frac> then new Fraction(top.flatMap(x -> bot.map(y -> Frac.of(x, y)))

**Comment by lershuan** [comment]
> 

wow thanks. this really helped to clear level5.
