### ISSUE TITLE
Lab 07 Level 4 

### ISSUE THREAD

**Issue by aseah15** [nus-cs2030/2223-s2#680]
Anyone able to explain how to go about implementing level4? Been reading the test cases but still get very confused and don't fully understand them either....

**Comment by cher212** [comment]
It is similar to the overriding of equals method in lecture 8 notes pg 9. The general idea is to use .equals() to check whether both the value and the string log of the argument are the same as this.value and this.log

**Comment by vivyanliew** [comment]
it's v similar to ex4's equals method where you can pass in an object and check if it is an instanceof Log before checking the value and string

**Comment by Dayn-Ang** [comment]
if you need another example you can refer to the implementation of Lab 8's AbstractNum equals method as well!

**Comment by nicholasteow** [comment]
rmb to check for both the value and the log !

**Comment by secretApple** [comment]
you can refer to lecture 8's method, but modify it as you don't have to check if its empty, and have to add in checking the log

**Comment by aseah15** [comment]
i reimplemented from level 1 but my test cases still doesnt pass. the ones that test for monad right and left identity and the last test case zz any other hints...?

**Comment by jon3r4de** [comment]
The problem could like in your flat map, i had problems with my level 4 due to my flat map.

hint: your flat map should consider 4 different conditions

**Comment by andersooi** [comment]
You can take a look at the equals method in Recitation 2. The implementation of the equals method in Lab 7 should be almost the same as that in the recitation. If it still doesn't work, then as mentioned, there may be an issue with the flatMap. 

For my flatMap, I didn't have 4 different conditions, but I just used a ternary operator (`condition ? do this if true : do this if false` to combine the different conditions into one.

**Comment by Yihao2001** [comment]
ternary operators are really helpful here, managed to make my code a one liner
