### ISSUE TITLE
Lab 8 - State Engine Terminated

### ISSUE THREAD

**Issue by Dayn-Ang** [nus-cs2030/2223-s2#681]
# Summary

Description of the question / problem here.

## Description:
Hi, has anyone faced this error before / have any idea what could be the problem?
Thank you!

Clarifications or details with respect to the issue you are facing

## Code Snippets

Attach code snippets (if any)

## Screenshots

Screenshots (if any)
<img width="814" alt="image" src="https://user-images.githubusercontent.com/122296979/229186780-4ff7c96f-e2ed-4b37-8aee-049b9c2c3fb6.png">

**Comment by jaejayrome** [comment]
sorry may I know which test case is this?

**Comment by Dayn-Ang** [comment]
hi, sorry I have edited the image attached, this is test case 3_1

**Comment by trickypepe** [comment]
Could your .mul be making an infinite loop?

**Comment by Dayn-Ang** [comment]
update: 
My methods for add and mul were quite inefficient so I think its a timeout thing.
I tried doing large numbers of add & multiplication and realised that the output visibly takes a little while to generate. 
In case anyone faces the issue, you can consider that!
