### ISSUE TITLE
Lab 8 Level 5

### ISSUE THREAD

**Issue by Brendan8899** [nus-cs2030/2223-s2#683]
For Level 5 we are supposed to achieve this:
![image](https://user-images.githubusercontent.com/80048882/229259922-5681c705-89de-4919-b2e3-39b1bb6586a5.png)
This issue is that when I need to access the Num inside Fraction, I will use Fraction.opt and use then Optional Context to do Map and Flatmap to do Multyiplication and Addition. All these operations return an Optional<Num> which is unable to be fed into Frac as Frac takes in (Num1 and Num2). Do you have any suggestions?

**Comment by jaejayrome** [comment]
Hi Brendan, the trick here lies within the AbstractNum class. what I did to circumvent this was to add pass the optional into a new AbstractNum<Frac> then pass this into a new Fraw(new AbstractNum<Frac> (your optional));

Hope this helps!!

**Comment by Brendan8899** [comment]
Ooh tats very innovative!

**Comment by wongjingwen** [comment]
So we need to create another constructor in the fraction class that takes in an AbstractNum?

**Comment by Brendan8899** [comment]
I doing Pair -> List -> Stream as my tutor advised, will update on the feasibilty

**Comment by wongjingwen** [comment]
so you converted pair into a list?

**Comment by Brendan8899** [comment]
Yeap

**Comment by wongjingwen** [comment]
Frac converted to a list?

**Comment by Brendan8899** [comment]
Err yeah I guess you could say so, I am taking advantage of the fact that Frac is a child of Pair to extract the inside stuff.

**Comment by wongjingwen** [comment]
However, you wont be able to update the values in the frac class?

**Comment by Brendan8899** [comment]
You can always create new objects

**Comment by wongjingwen** [comment]
> Hi Brendan, the trick here lies within the AbstractNum class. what I did to circumvent this was to add pass the optional into a new AbstractNum then pass this into a new Fraw(new AbstractNum (your optional));
> 
> Hope this helps!!

Sorry dont quite understand

**Comment by EpicSpirito** [comment]
I created an Optional Frac by chaining flatmap and map of Optional Num and passed it into AbstractNum, see whether it works

**Comment by NeoHW** [comment]
Im not sure about this part as Frac accepts Num as its params for the constructors, I don't think it would be able to accept AbstractNum as AbstractNum is a superclass of Num?

**Comment by Huanqing-Mao** [comment]
Hi can I ask whether we are allowed to create our own lambda functions? so long as it does not use +-*% etc?

**Comment by Brendan8899** [comment]
Yes you can create yr own lambda

**Comment by haqanh** [comment]
Hi, for me I used map and flat map to take out the nominator/denominator, then feed it back into the Fraction as a new Frac. Hope this helps

**Comment by Brendan8899** [comment]
ok boys nice discussion, I close the comment!
