### ISSUE TITLE
Mock PE Week 11 - Instance properties/constants detected.

### ISSUE THREAD

**Issue by JYeoZS** [nus-cs2030/2223-s2#685]
Hi, any idea what this problem may be? I have no usage of instanceOf in code...

Much thanks.

<img width="446" alt="Screenshot 2023-04-01 at 11 02 54 AM" src="https://user-images.githubusercontent.com/122290983/229262778-ac137d9d-6427-48bc-8c15-baf10b0396aa.png">

**Comment by jaejayrome** [comment]
I suspect that you might have add in a property within ur Fraction or Num class; in other words, if your constructor in either of the Fraction or Num class requires you to initialise any of the variables that you might have defined. It's not allowed and you should only work with the Optional<T> within the AbstractNum class. Hope this helps!

**Comment by JYeoZS** [comment]
Ah icic, I created a static constant for .one() method, that's why.

Supposed to use .zero() and .succ() to form .one() method.

Much thanks.  :)

**Comment by minhphongle** [comment]
I think it might be because you declare some constants like this? Cuz I also faced the same issue as well!
 ```private static final int ONE = 1;```

**Comment by haqanh** [comment]
I think this means you have declared new constants or static method? Only supposed to use the provided .zero(), .one() and n,s,valid provided in the class

**Comment by xj8423** [comment]
hii can iask 

> I think it might be because you declare some constants like this? Cuz I also faced the same issue as well! `private static final int ONE = 1;`

hii can i ask how did you go about this for the succ() method... i know to use a while loop and a equals() to check but i need an int to use s from AbstractNum.. how do i do that without using a constant 0 as my counter? thanks in advance!
