### ISSUE TITLE
Ex4 Level 5 Question

### ISSUE THREAD

**Issue by trickypepe** [nus-cs2030/2223-s2#686]
![Assignment](https://user-images.githubusercontent.com/122513341/229264112-59de2275-6a7a-42ad-a5aa-2d997ffdc5d1.png)

A bit confused as to how flatMap allows assignment when Maybe< Object > clearly cannot take in Maybe< Integer >

**Comment by Yihao2001** [comment]
youre not unwrapping properly for your flatmap, might want to look at the unwrapping part again

**Comment by nigel-tannn** [comment]
When you unwrap you have to assign to a type Maybe<? extends R>, if not there will be some type issues.

**Comment by trickypepe** [comment]
Hmm I think I didn't phrase my question correctly. I'm asking what allows the compiler to bind the Maybe<R> to Object when I do `Maybe<Object> mo = ms.flatMap(g)` while if I simply do `ms.flatMap(g)` <R> is bound to Integer (this flexible binding thing).

The exercise itself is done (the first line works), I'm just playing around with the code.
