### ISSUE TITLE
warning: [rawtypes] found raw type: Log

### ISSUE THREAD

**Issue by Waynelearn** [nus-cs2030/2223-s2#687]
# Summary

I tried Log<T> but it does not work but when I tried Log<?> it works. Why is that?

## Description:

Clarifications or details with respect to the issue you are facing

## Code Snippets

Attach code snippets (if any)

## Screenshots

![image](https://user-images.githubusercontent.com/64724406/229265248-1d64e430-62d7-4222-b32c-8e8085b4d1f8.png)

**Comment by jaejayrome** [comment]
Log would implicitly mean Log(Object) to the compiler but parsing in Log(?) would mean any type of Log, in essence, Log != Log(?) since Log(Object) != Log(?)

**Comment by youthfrost** [comment]
When dealing with generics, its always good to declare the type, and in this case ? means it can take in any type

**Comment by Yihao2001** [comment]
should alway declare the type properly

**Comment by granolaluvr69** [comment]
You just need to type parametrise your factory methods or constructors when using them. For e.g `Log.<Integer>of(1)` or in your case, `o instanceof Log<?> other`.

**Comment by haqanh** [comment]
I think it has to do with the fact that you are wrapping something of type Object in a log, so it has to be <?> instead of any specific type

**Comment by notsushiii** [comment]
I'm not sure why but for me I was able to get away with !(o instanceof Log) without any errors/warning messages where o refers to the `t` in the `Log<T> of(T t, String log)`

**Comment by Lofthesaver** [comment]
Log<T> is a generic typed object with a type T; whenever you use/declare generic types, you need to define the type T (in this case you need to declare T as ?)

**Comment by Waynelearn** [comment]
I understand now, Thanks Everyone!
