### ISSUE TITLE
Lab8 Level 5 add, sub and mul for Fraction Class

### ISSUE THREAD

**Issue by wongjingwen** [nus-cs2030/2223-s2#689]
Hi for the add method, how are we supposed to update the Frac since my numerator and denominator are Optional(Num)

**Comment by jaejayrome** [comment]
same concept of how u obtain the numerator and the denominator in the first place, using flatMap and Map but this time instead of mul(), do something like: numerator.flatMap(x -> denominator.map(y -> Frac.of(x, y)), this returns a Optional(Frac) which you can pass inside a AbstractNum(), this in turn could then be finally passed into a Fraction.of() then check whether it's a valid fraction then return it.

something like:

Fraction.of(new AbstractNum(numerator.flatMap(x -> denominator.map(y -> Frac.of(x, y)))

then u can call the isValid() method to check whether this is even a valid fraction in the first place

**Comment by wongjingwen** [comment]
However fraction.of takes in (int n, int d).

**Comment by fy17ohhh** [comment]
> same concept of how u obtain the numerator and the denominator in the first place, using flatMap and Map but this time instead of mul(), do something like: numerator.flatMap(x -> denominator.map(y -> Frac.of(x, y)), this returns a Optional(Frac) which you can pass inside a AbstractNum(), this in turn could then be finally passed into a Fraction.of() then check whether it's a valid fraction then return it.
> 
> something like:
> 
> Fraction.of(new AbstractNum(numerator.flatMap(x -> denominator.map(y -> Frac.of(x, y)))
> 
> then u can call the isValid() method to check whether this is even a valid fraction in the first place

I think an alternative way which do not need to use AbstractNum is to use the private constructor for Fraction, and just insert your `numerator.flatMap(x -> denominator.map(y -> Frac.of(x,y))` which results in Optional(Frac)

**Comment by fy17ohhh** [comment]
> > same concept of how u obtain the numerator and the denominator in the first place, using flatMap and Map but this time instead of mul(), do something like: numerator.flatMap(x -> denominator.map(y -> Frac.of(x, y)), this returns a Optional(Frac) which you can pass inside a AbstractNum(), this in turn could then be finally passed into a Fraction.of() then check whether it's a valid fraction then return it.
> > something like:
> > Fraction.of(new AbstractNum(numerator.flatMap(x -> denominator.map(y -> Frac.of(x, y)))
> > then u can call the isValid() method to check whether this is even a valid fraction in the first place
> 
> I think an alternative way which do not need to use AbstractNum is to use the private constructor for Fraction, and just insert your `numerator.flatMap(x -> denominator.map(y -> Frac.of(x,y))` which results in Optional(Frac)

Cuz I found that if you use AbstractNum and pass it to Frac.of(Num, Num), it resulted in a Pair instead of Frac, which cannot be passed into Optional to form a Optional(Frac)

**Comment by wongjingwen** [comment]
Hi but how do we extract the invididual Num out to check if it is valid

**Comment by fy17ohhh** [comment]
> Hi but how do we extract the invididual Num out to check if it is valid

check it inside the map

**Comment by fy17ohhh** [comment]
> > Hi but how do we extract the invididual Num out to check if it is valid
> 
> check it inside the flatmap

**Comment by fy17ohhh** [comment]
> > Hi but how do we extract the invididual Num out to check if it is valid
check it inside the flatmap

**Comment by wongjingwen** [comment]
flatmap returns an Optional not a boolean though

**Comment by wongjingwen** [comment]
Thank you  @fy17ohhh @jaejayrome . Managed to solve it

**Comment by wongjingwen** [comment]
Thank you  @fy17ohhh @jaejayrome . Managed to solve it
