### ISSUE TITLE
Lab 07 Level 5

### ISSUE THREAD

**Issue by haphuong1810103** [nus-cs2030/2223-s2#692]
<img width="676" alt="Screenshot 2023-04-01 at 3 06 52 PM" src="https://user-images.githubusercontent.com/122664644/229271215-7d5f36e2-5d92-48bd-9572-f8b0e13f15e4.png">

why I have this issue when I test sum(5)

**Comment by Yihao2001** [comment]
might want to change how you named variables and see if everything is declared properly

**Comment by haqanh** [comment]
Your current variable in the sum method is probably not instantiated or declared yet! e.g. int current = ...

**Comment by vivyanliew** [comment]
rmb to declare it as final as well!! hope this helps!

**Comment by coderlimjingcheng** [comment]
If you are still facing the issue, maybe can show us how you coded it? Seems like there might be some small error in it.

**Comment by NwaterM** [comment]
hello! i had the same issue,, managed to solve it declaring with final!

**Comment by Aron113** [comment]
do declare a variable

**Comment by slimzaza** [comment]
I had this issue and resolved it with final

**Comment by kyledilao777** [comment]
please check if you declared current in all your constructors

**Comment by koojaylynn** [comment]
check if u have declared the current variable!
