### ISSUE TITLE
Level 2 Lab 8

### ISSUE THREAD

**Issue by kelleyhan25** [nus-cs2030/2223-s2#693]
hello! if anyone has any tips for starting the add() method in lab 8 it would be greatly appreciated! I'm just not sure how to do it without using the get() method to access the value of the optional that we're adding. thanks in advance!

**Comment by granolaluvr69** [comment]
Firstly, you need to check for the validity of the two operands.

**Comment by nigel-tannn** [comment]
I personally initialised a Num.zero() as a sort of counter, and in my iterations I used .succ() to increase the counter until the counter is equal to the Num you were supposed to add.

**Comment by taugwa** [comment]
for me i did a while loop and then decreased my counter using the functions provided in AbstractNum

**Comment by haqanh** [comment]
for me, i used a while loop - this time, insetad of declaring a counter e.g. int i = 0, just make use of the .zero() or .one() that is provided for you in AbstractNum!

**Comment by Naughty123456789** [comment]
1. Check Validity of Num
2. Initiate a 0 using the AbstractNum class - this will be used like a counter
3. Initate the num that is going to be added by other ( imma call it A)
4. while loop - as long as counter is not equals to other, we shall keep going; increase counter and  A by one for each loop


the logic  essentially goes like  

If u need to add
8 and 12

Have x = 0
12++ x++
When x is 8 you're done adding - this text is from my TA hope this helps.

**Comment by kelleyhan25** [comment]
thanks!!

**Comment by geraldckj** [comment]
> 1. Check Validity of Num
> 
>     2. Initiate a 0 using the AbstractNum class - this will be used like a counter
> 
>     3. Initate the num that is going to be added by other ( imma call it A)
> 
>     4. while loop - as long as counter is not equals to other, we shall keep going; increase counter and  A by one for each loop
> 
> 
> the logic essentially goes like
> 
> If u need to add 8 and 12
> 
> Have x = 0 12++ x++ When x is 8 you're done adding - this text is from my TA hope this helps.
> 
> Obviously ++ and magic number 0 is not allowed but you got succ() as you did earlier and zero() from AbstractNum class

Very good answer, thanks for this. It really helped
