### ISSUE TITLE
Lab7 Level5 Importing Function in .jsh File

### ISSUE THREAD

**Issue by notsushiii** [nus-cs2030/2223-s2#694]
Hi guys!

I've just completed Level 5 of Lab 7 and my code in the level5.jsh file seems to work on my local jshell (correct output for the two functions using the test cases given, no error messages). However, upon submitting my files onto CodeCrunch, I keep receiving this message :( 

I've tried to add `import java.util.function.Function;` in the .jsh file (not sure if that's how it's supposed to work since the file worked well on my local jshell w/o the import statement) but I still get the same message.

Would really appreciate it if someone can help me identify/fix the issue!
![image](https://user-images.githubusercontent.com/119566170/229277702-e917caa0-36bd-45f3-9f5e-c51b78b45030.png)

**Comment by Chuacx13** [comment]
its a jsh file so i doubt you can "import java.util.function.Function"

**Comment by taugwa** [comment]
i did this too and i couldn't find a way around it. asked my TA and he was not sure too so i think just use lambdas

**Comment by notsushiii** [comment]
Thanks guys! I tried to just use the lambdas directly and it worked out!
