### ISSUE TITLE
Lab 7 .equals() method (test case 7)

### ISSUE THREAD

**Issue by chianxintong** [nus-cs2030/2223-s2#697]
# Summary

Hi, my code worked for all 5 levels, but doesn't seem to work when t is a class object! Could there be something wrong with my .equals() method? send help :0

## Description:

for the overriding of .equals() method in my Log class, i used the typical way of overriding equals method
1. check if Object obj is == to this
2. else if obj is an instance of Log class -> check if their t values and log strings r the same
3. lastly, return false

![image](https://user-images.githubusercontent.com/122260095/229287381-f3624974-01b0-4e40-8f0b-0f93efb5feca.png)

## Screenshots

![image](https://user-images.githubusercontent.com/122260095/229287453-086aa07d-afcb-41af-ad14-bf45ccec3cda.png)

I tried using .getClass() but its not allowed on codecrunch zz

**Comment by junhonglow** [comment]
Could possibly be an issue with the constructor.
Does something like Log.of(6).equals(Log.of(6, "")) return True?

**Comment by madhupolluru** [comment]
> # Summary
> Hi, my code worked for all 5 levels, but doesn't seem to work when t is a class object! Could there be something wrong with my .equals() method? send help :0
> 
> ## Description:
> for the overriding of .equals() method in my Log class, i used the typical way of overriding equals method
> 
> 1. check if Object obj is == to this
> 2. else if obj is an instance of Log class -> check if their t values and log strings r the same
> 3. lastly, return false
> 
> ![image](https://user-images.githubusercontent.com/122260095/229287381-f3624974-01b0-4e40-8f0b-0f93efb5feca.png)
> 
> ## Screenshots
> ![image](https://user-images.githubusercontent.com/122260095/229287453-086aa07d-afcb-41af-ad14-bf45ccec3cda.png)
> 
> I tried using .getClass() but its not allowed on codecrunch zz

instead of using .getClass() you can use instanceof instead!! instanceof is allowed for lab 7 hence it would not be rejected by lab 7

**Comment by Ramanenbh** [comment]
Hi recheck your flatMap if you are doing any extra checks than necessary because I had encountered the same issue as yourself

**Comment by chianxintong** [comment]
> Could possibly be an issue with the constructor. Does something like Log.of(6).equals(Log.of(6, "")) return True?

yupp it returns true XD

**Comment by chianxintong** [comment]
> 

did you use instanceof in equals() other than for checking whether obj is an isntanceof Log<?>

**Comment by chianxintong** [comment]
@junhonglow  @madhupolluru @Ramanenbh omg!! i just solved it :")

in case yall are curious, i missed out a condition for the cdtn where log is an empty string

tq for trying to help me :)
