### ISSUE TITLE
Lab 7 Level 5

### ISSUE THREAD

**Issue by secretApple** [nus-cs2030/2223-s2#698]
For function f, if I want to do it by iteration, how can I have a counter to keep track of the number when all variables have to be final?

**Comment by chianxintong** [comment]
hmm its possible! i did it by the cs1010s way haha by introducing a variable called result and updating it in my while loop, while result is not 1

**Comment by ghost1nthemachine** [comment]
in the while loop i just assigned the counter to a new string and put it in the flatmap

**Comment by ghost1nthemachine** [comment]
yep, that was how i updated it, and no i didnt assign it to be final
