### ISSUE TITLE
Lab 8 level 1 succ() method

### ISSUE THREAD

**Issue by hhuilingg** [nus-cs2030/2223-s2#699]
hi, may i know how should i go about doing the succ() method? I'm stuck as the function s need an integer as input, however my value is an AbstractNum (AbstractNum<Integer> is my property in Num class - not sure if this is right..). Would really appreciate if someone could help! thank you:)

**Comment by madhupolluru** [comment]
hey!! as for the approach to the succ() method, be sure to retrieve the optional of the object, using this.opt before using function s in the map method to be applied on this.opt!!

what the map method does is that, if the optional is non-empty, it would apply the function s on the object inside the optional, and return an optional with the updated object inside it. however, in the event that the optional is empty if the Num object were to be invalid, it would return an empty optional

you can refer to slide 15 of lecture slides 07 to see and have a better idea of how the map method is used!! or you can also take a look at the map method in the java.util.Optional in the Java API 17 online!!

I don't know, if I understand your implementation well but make sure to not have any private final attributes in any of your Num or Fraction as this would cause your submission to fail on codecrunch!! been there, done that!!

**Comment by hhuilingg** [comment]
thankyou so much!!
