### ISSUE TITLE
ImList class file

### ISSUE THREAD

**Issue by SimonSeeYongsheng** [nus-cs2030/2223-s2#7]
Hi guys! During lecture, Prof Henry Chia shared that he would share with us the ImList class file, so that we can implement Immutable List in our program. 

Do any of you know where I can find it? 

Thank you very much!

**Comment by trwstin** [comment]
Hi Simon, you can find the ImList.java file on Canvas > CS2030 > Lecture

**Comment by SimonSeeYongsheng** [comment]
@trwstin Thanks alot! Still a bit new with Canvas

**Comment by SimonSeeYongsheng** [comment]
> Hi Simon, you can find the ImList.java file on Canvas > CS2030 > Lecture

@trwstin Thanks alot! Still a bit new with Canvas
