### ISSUE TITLE
Lab 7 level 4 error

### ISSUE THREAD

**Issue by jhsoh** [nus-cs2030/2223-s2#700]
# Summary

I followed the overriding of the equals method defined in lecture 8, but got an error in this line. Does anybody know why this error is surfacing?

## Description:

Clarifications or details with respect to the issue you are facing

## Code Snippets

Attach code snippets (if any)

## Screenshots

![image](https://user-images.githubusercontent.com/80301620/229295511-fc4a4775-d5d4-4607-95f7-a50c8bf32cea.png)
![image](https://user-images.githubusercontent.com/80301620/229295683-f27d1663-e411-4f26-90d8-00e841e56f52.png)

**Comment by fy17ohhh** [comment]
umm seems like there may be syntax errors prior or after this code section

**Comment by aeraeroaer** [comment]
you probably should check to look for possible missing brackets

**Comment by coderlimjingcheng** [comment]
The code snippet you sent looks fine, maybe it came from somewhere else? (Have a feeling that it might a small syntax error)

**Comment by jhsoh** [comment]
apparently it is an ubuntu error, it is able to pass the test cases on cc. Thanks!
