### ISSUE TITLE
Lab 8 Level 3

### ISSUE THREAD

**Issue by prisciliapangg** [nus-cs2030/2223-s2#701]
<img width="323" alt="Screenshot 2023-04-01 at 10 52 08 PM" src="https://user-images.githubusercontent.com/123915785/229296438-fc1398d5-1cd5-4e00-b9d0-00b4f48c6439.png">

Hello, I am not sure how to return an invalid output (it is returning -1 which is valid). Does anyone know how I should approach the question? Thank you!!!!

**Comment by fy17ohhh** [comment]
use map/filter and AbstractNum.valid to check opt of the result before returning it

**Comment by prisciliapangg** [comment]
> use map/filter and AbstractNum.valid to check opt of the result before returning it

Thank you so much! I have tried it but may I get a clue on how I should proceed (I have an if condition to check for invalid input, which works as I have a system.out.println() to check if it enters the condition, but if I just return that Num, it will still print -1 instead of "invalid")

**Comment by fy17ohhh** [comment]
> > use map/filter and AbstractNum.valid to check opt of the result before returning it
> 
> Thank you so much! I have tried it but may I get a clue on how I should proceed (I have an if condition to check for invalid input, which works as I have a system.out.println() to check if it enters the condition, but if I just return that Num, it will still print -1 instead of "invalid")

ok so if you invoke Num.of(-1) you should have NaN printed, here I assume that your Num.of() checks for validity and uses a private constructor inside Num class. Now you need to make sure that in your add() method, if you are also using the private constructor, it didn't check for validity so you need to create an empty Optional yourself and pass to it

**Comment by prisciliapangg** [comment]
Ohhhh, thank you sooo much!!
