### ISSUE TITLE
Error on Ubuntu

### ISSUE THREAD

**Issue by nurin534** [nus-cs2030/2223-s2#703]
![image](https://user-images.githubusercontent.com/123313531/229298711-a4ca3ce5-24b2-40ba-a1bf-066194d86e7d.png)

Anybody got this error on Ubuntu for equals method... Any advice?

**Comment by shir-err** [comment]
maybe you can check if you're missing a bracket in your previous lines of code? i wrote something similar for the equals method and it works but i didnt use ubuntu,,, if it seems correct maybe you can try submitting on code crunch? it might be an issue with ubuntu?

**Comment by nurin534** [comment]
@shir-err tried to submit it on code crunch...didnt face this issue...

**Comment by aeraeroaer** [comment]
does it pass the test cases on cc?

**Comment by Naughty123456789** [comment]
well i faced this issue too , java doesnt seem allow me to put it that way either. Rather i have to bring it to the next line and typecast it instead 

if  ( obj instanceof Log<?>)  {
    
   Log<?> temp1 = (Log<?>) other;
   //insert content 

}

Apparently it is something to do with java not being updated accordingly  to Source 16 - according to the error message given. 
(at least for my case) 
Regardless, i do not think it matters(?) code crunch accepts both ways. As of why cc allows me to typecast like that im not sure.

Hope it helps

**Comment by Lofthesaver** [comment]
Can you try to check your version of Java (when you enter jshell it will state the version), I think this syntax only works for more recent versions of Java (Java 17)

**Comment by jayson237** [comment]
There is a high chance that your Ubuntu is not updated to the latest java version, which is jdk 17. Can try typing in java -version to check which version of java you have. You may refer to this link for more information on how to update: https://techviewleo.com/install-java-openjdk-on-ubuntu-linux/

**Comment by nurin534** [comment]
> well i faced this issue too , java doesnt seem allow me to put it that way either. Rather i have to bring it to the next line and typecast it instead
> 
> if ( obj instanceof Log<?>) {
> 
> Log temp1 = (Log) other; //insert content
> 
> }
> 
> Apparently it is something to do with java not being updated accordingly to Source 16 - according to the error message given. (at least for my case) Regardless, i do not think it matters(?) code crunch accepts both ways. As of why cc allows me to typecast like that im not sure.
> 
> Hope it helps

yup this works thank you!
