### ISSUE TITLE
Lab 8 level 1

### ISSUE THREAD

**Issue by ghost1nthemachine** [nus-cs2030/2223-s2#704]
been stuck at this level :/

1. for the of method, how shld i check if T is a nat number? 

2. when i added the zero method, i keep getting this error: The method zero() of type Num has the same erasure as zero() of type AbstractNum but does not hide it

3. based on my understanding, we shld return an empty Num if its not nat?

**Comment by aeraeroaer** [comment]
1. i think you can try using AbstractNum.valid to check

**Comment by aeraeroaer** [comment]
1. on an additional note, it is also mentioned in the description that the of method should take in an int i

**Comment by aeraeroaer** [comment]
2. for 2, same erasure error would probably mean that your zero method in Num didn't override the one in AbstractNum

**Comment by aeraeroaer** [comment]
3. if I understand correctly, you should return a Num with .opt as Optional.Empty() if the number is not a natural number

**Comment by aeraeroaer** [comment]
> 1. i think you can try using AbstractNum.valid to check

To further elaborate, you can try to create a constructor in Num to take in an AbstractNum, then wrap input i in an optional, then use AbstractNum.valid to check

**Comment by Naughty123456789** [comment]
i agree with aeraeroaer, i used AbstractNum.valid.test(..) too

**Comment by vancwe03** [comment]
try finding a method from optional class that allows you to use the valid method

**Comment by keshialimm** [comment]
have the same questions as well, can I check how do I return NaN as a Num? using valid will only give me a boolean right?

**Comment by Naughty123456789** [comment]
yep. so in your if statement block  you would return a Num(Optional.empty())

**Comment by keshialimm** [comment]
> yep. so in your if statement block you would return a Num(Optional.empty())

Hi, but now if its invalid, I do not get an NaN, I get an empty string instead. Can I check how to solve this? Thank you!

**Comment by Naughty123456789** [comment]
do you extend Num to AbstractNum? so that Num would follow the toString method stated in AbstractNum instead. i didnt really face this issue so i cant really help here. 

Also i was smoking pot

 in your if statement block you would return a Num(Optional.of(x))
 
 else you return Num(Optional.empty())
 
 yea sorry for the confusion

**Comment by ghost1nthemachine** [comment]
thanks all! but im facing the error of: cannot convert from Optional<Integer> to T, when i try to return a new num. my constructor takes in optional<T>.

is my constructor wrong?

**Comment by jamiepngg** [comment]
@ghost1nthemachine you should specify the type of optional that your constructor is taking in since ur Num extends AbstractNum<Integer> so in this case, it would be Optional<Integer>

**Comment by ghost1nthemachine** [comment]
> @ghost1nthemachine you should specify the type of optional that your constructor is taking in since ur Num extends AbstractNum < Integer > so in this case, it would be Optional < Integer >

@jamiepngg thanks alot! this clarifies it haha
