### ISSUE TITLE
How to flip log output in sum method?

### ISSUE THREAD

**Issue by aeraeroaer** [nus-cs2030/2223-s2#706]
Hello everyone, been stuck on this for a while, but does anyone know how I could flip the output so that I can make the base case come first in level 5? 

Here is a snippet of my code :

if (n == 0) {
        return Log.<Integer>of(1, "hit base case!");
    } else {
        return Log.<Integer>of(n, "adding " + n).flatMap(x -> x + sum(n-1));
    }
Here is the test case I am referring to :
<img width="264" alt="Screenshot 2023-04-02 at 1 33 27 AM" src="https://user-images.githubusercontent.com/122816576/229305950-4110e0fe-b0c9-40be-85e7-e235d11f7969.png">

Thank you very much!

**Comment by Ernestnzx** [comment]
For me what I noticed is that the function returns the Log class, so what I did was

`sum(n-1).flatmap(x -> ..)`

Since the base case of the recursive part will be evaluated first, doing it this way it would give you the reverse order. Hope this helps :)

**Comment by aeraeroaer** [comment]
ah i see, thank you !
