### ISSUE TITLE
Lab 8 Level 5

### ISSUE THREAD

**Issue by weitatftw** [nus-cs2030/2223-s2#708]
# Summary

Does anyone know how to obtain the numerator and denominator for this level so that I can perform the mathematical operations on the Nums?? I've tried different methods but I can't obtain the numerator / denominator without using get() operations. Does anyone have an idea on how should I approach this level?? Or if my approach is wrong??

**Comment by dlyxxx** [comment]
I used flatmap and map to obtain the numerator/denominator (by using first() and second()) and to do operations using Num's methods like add, mul, sub within the map method.

I initially faced a lot of issues, but i think trying out your method on jshell would help a lot!

**Comment by taugwa** [comment]
yep mine is similar to ^^ ... i just obtained a b c d then i got the numerator n denom then i jus flatmap(..map ..) into Frac.of

**Comment by trickypepe** [comment]
You can get the numerator/denominator as Optional<Num> by mapping `x -> x.first()` and second() like dlyxxx mentioned. From there, besides the method described above, you can also retrieve the Optional<Integer> using `flatMap(x -> x.opt)` and kind of build the Num back (either from AbstractNum or from Optional<Integer> directly). Might not be recommended but just giving another option.

**Comment by polytetralhx** [comment]
> You can get the numerator/denominator as `Optional<Num>` by mapping `x -> x.first()` and second() like dlyxxx mentioned. From there, besides the method described above, you can also retrieve the `Optional<Integer>` using `flatMap(x -> x.opt)` and kind of build the Num back (either from AbstractNum or from `Optional<Integer>` directly). Might not be recommended but just giving another option.

with regards to this, you may also find it helpful to define some additional constructors to create your Fraction, such as a `Fraction(Optional<Frac>(...))`, hopefully this helps a little bit

**Comment by ghost1nthemachine** [comment]
> I used flatmap and map to obtain the numerator/denominator (by using first() and second()) and to do operations using Num's methods like add, mul, sub within the map method.
> 
> so for eg to get bd you would have to flat map and get the denominator of the first fraction (a) and the denominator of the second fraction (b) using second(), since both of them are Num you can simply just use a.mul(b)!
> 
> then just repeat for whatever you want to find, and subsequently joining them back again using flatMap and map to convert it into Frac (depending on your implementation)
> 
> I initially faced a lot of issues, but i think trying out your method on jshell would help a lot!

hi, how should i use flatmap in this context to get out Num? ive tried to just directly do flatmap ( x -> ..) but i get this error: Type mismatch: cannot convert from Optional<Object> to NumJ

**Comment by ghost1nthemachine** [comment]
> You can get the numerator/denominator as `Optional<Num>` by mapping `x -> x.first()` and second() like dlyxxx mentioned. From there, besides the method described above, you can also retrieve the `Optional<Integer>` using `flatMap(x -> x.opt)` and kind of build the Num back (either from AbstractNum or from `Optional<Integer>` directly). Might not be recommended but just giving another option.

@trickypepe how should i build up Num from Optional< Integer > ? I cant access the Num constructor since its private

**Comment by yugan01** [comment]
> > I used flatmap and map to obtain the numerator/denominator (by using first() and second()) and to do operations using Num's methods like add, mul, sub within the map method.
> > so for eg to get bd you would have to flat map and get the denominator of the first fraction (a) and the denominator of the second fraction (b) using second(), since both of them are Num you can simply just use a.mul(b)!
> > then just repeat for whatever you want to find, and subsequently joining them back again using flatMap and map to convert it into Frac (depending on your implementation)
> > I initially faced a lot of issues, but i think trying out your method on jshell would help a lot!
> 
> hi, how should i use flatmap in this context to get out Num? ive tried to just directly do flatmap ( x -> ..) but i get this error: Type mismatch: cannot convert from Optional< Object > to Num
> 
> could it be that I defined my Fraction class wrongly? as I extended it from AbstractNum< Frac >

Could you show a snippet of ur code, it should look like this.opt.flatMap(x -> other.opt.map(y -> ...))

**Comment by trickypepe** [comment]
> > You can get the numerator/denominator as `Optional<Num>` by mapping `x -> x.first()` and second() like dlyxxx mentioned. From there, besides the method described above, you can also retrieve the `Optional<Integer>` using `flatMap(x -> x.opt)` and kind of build the Num back (either from AbstractNum or from `Optional<Integer>` directly). Might not be recommended but just giving another option.
> 
> @trickypepe how should i build up Num from Optional< Integer > ? I cant access the Num constructor since its private

Try taking in through another static of() that takes in `Optional<Integer>`, should be very similar to the one taking in `AbstractNum<Integer>`

**Comment by ghost1nthemachine** [comment]
> > > I used flatmap and map to obtain the numerator/denominator (by using first() and second()) and to do operations using Num's methods like add, mul, sub within the map method.
> > > so for eg to get bd you would have to flat map and get the denominator of the first fraction (a) and the denominator of the second fraction (b) using second(), since both of them are Num you can simply just use a.mul(b)!
> > > then just repeat for whatever you want to find, and subsequently joining them back again using flatMap and map to convert it into Frac (depending on your implementation)
> > > I initially faced a lot of issues, but i think trying out your method on jshell would help a lot!
> > 
> > 
> > hi, how should i use flatmap in this context to get out Num? ive tried to just directly do flatmap ( x -> ..) but i get this error: Type mismatch: cannot convert from Optional< Object > to Num
> > could it be that I defined my Fraction class wrongly? as I extended it from AbstractNum< Frac >
> 
> Could you show a snippet of ur code, it should look like this.opt.flatMap(x -> other.opt.map(y -> ...))

<img width="565" alt="Screenshot 2023-04-03 at 12 31 07 PM" src="https://user-images.githubusercontent.com/125187978/229412024-bcd16eee-bf73-4c45-aaf7-d1550f7eebc9.png">

i was intending to get a/b/c/d separately but idk how to use flatmap

**Comment by weitatftw** [comment]
@yugan01 i don't think that you can work with a Num for level 5 since you can't use the functions to extract the Num that is wrapped in the Optional. You would have to work with Optionals and map the functions to perform the necessary computations for the add / sub / mul methods of Fraction before you return a final Fraction with the flatMap and map functions that others have mentioned above to map the n and d values into the Function constructor

**Comment by yugan01** [comment]
> > > > I used flatmap and map to obtain the numerator/denominator (by using first() and second()) and to do operations using Num's methods like add, mul, sub within the map method.
> > > > so for eg to get bd you would have to flat map and get the denominator of the first fraction (a) and the denominator of the second fraction (b) using second(), since both of them are Num you can simply just use a.mul(b)!
> > > > then just repeat for whatever you want to find, and subsequently joining them back again using flatMap and map to convert it into Frac (depending on your implementation)
> > > > I initially faced a lot of issues, but i think trying out your method on jshell would help a lot!
> > > 
> > > 
> > > hi, how should i use flatmap in this context to get out Num? ive tried to just directly do flatmap ( x -> ..) but i get this error: Type mismatch: cannot convert from Optional< Object > to Num
> > > could it be that I defined my Fraction class wrongly? as I extended it from AbstractNum< Frac >
> > 
> > 
> > Could you show a snippet of ur code, it should look like this.opt.flatMap(x -> other.opt.map(y -> ...))
> 
> <img alt="Screenshot 2023-04-03 at 12 31 07 PM" width="565" src="https://user-images.githubusercontent.com/125187978/229412024-bcd16eee-bf73-4c45-aaf7-d1550f7eebc9.png">
> 
> @yugan01 i was intending to get a/b/c/d separately but idk how to use flatmap

This should be a map instead because x.first() is a Num o when we do map(x -> x.first()), the Num is wrapped in the Optional context. 
so Numerator1 is a Optional<Num> not a Num. 
Optional<Num> numerator1 = this.opt.map(x -> x.first());

**Comment by trickypepe** [comment]
> @ghost1nthemachine I don't think that you can work with a Num for level 5 since you can't use the functions to extract the Num that is wrapped in the Optional. You would have to work with `Optional<Num>` and map the functions to perform the necessary computations for the add / sub / mul methods of Fraction before you return a final Fraction with the flatMap and map functions that others have mentioned above to map the n and d values into the Function constructor

A bit out of point but you actually can, though I don't think it's recommended either

**Comment by ghost1nthemachine** [comment]
> uld have to flat map and get the denominator of the first fraction (a) and the denominator of the second fraction (b) using second(), since both of them are Num you can simply just use a.mul(b)!
> 
> then just repeat for whatever you want to find, and subsequently joining them back again using flatMap and map to convert it into Frac (depending on your implementation)

@weitatftw Ive obtained Optional<Num> but how do I make use of Num's add/mul methods?

**Comment by weitatftw** [comment]
> > uld have to flat map and get the denominator of the first fraction (a) and the denominator of the second fraction (b) using second(), since both of them are Num you can simply just use a.mul(b)!
> 
> > 
> 
> > then just repeat for whatever you want to find, and subsequently joining them back again using flatMap and map to convert it into Frac (depending on your implementation)
> 
> 
> 
> @weitatftw Ive obtained Optional< Num >  but how do I make use of Num's add/mul methods?

you can use map / flatMap on the optional and map the Num contained in the optional to the add / mul methods to perform the computations

**Comment by trickypepe** [comment]
With `Optional<Num>` you need to do a bit of currying shown [here](https://github.com/nus-cs2030/2223-s2/issues/689#issuecomment-1492842929)

**Comment by ghost1nthemachine** [comment]
thanks all! :)

**Comment by weitatftw** [comment]
thank you everyone too for the help! i've managed to solve the issue too
