### ISSUE TITLE
Lab 8 lvl 4: how to get NaN output 

### ISSUE THREAD

**Issue by ianwonghanli** [nus-cs2030/2223-s2#709]
# Summary

Hi all. I currently have an issue with getting just a NaN output for outlier numerator and denominator values in the class Fraction

## Description:

I have made my Fraction class extend AbstractNum<Frac> and in my Fraction.of() method, I make a Num class for numerator and denominator respectively. Then, I make a Frac class and a AbstractNum<Frac> class, and then pass the AbstractNum<Frac> class into my constructors.

I am currently facing the issue when my numerator or denominator is NaN. I cant seem to find a solution to just output a Nan value without the other number. Advice is much appreciated!

## Screenshots
![Screenshot 2023-04-02 164806](https://user-images.githubusercontent.com/99638949/229342690-d91f9f5f-f258-41e6-ac96-d598abcd6f6e.png)

**Comment by SimonSeeYongsheng** [comment]
Store private final Num as attributes for numerator and denominator and check if they are isValid.

**Comment by SimonSeeYongsheng** [comment]
I think the best way is to create overload another Constructor method that super an empty Optional. Hope that helps

**Comment by e0968868** [comment]
inside your of method for Fraction you can use if statement to check for validity and return new Fraction(Optional.empty()) if the fraction is invalid

**Comment by leezhanpeng** [comment]
If your numerator or denominator is NaN, checking its validity before returning the frac will do the trick. If they are valid, then do a check on whether it is 0 by using the given functions to minus 1 from the Num to make it -1, and then check the validity. In the case it is invalid, return an empty Frac.

**Comment by yueqianh** [comment]
I checked 

if numerator or denominator is invalid, then return the type with optional empty as the argument

**Comment by haqanh** [comment]
you can implement a check in the constructor of your Fraction - if either your numerator or denominator is invalid, then return a invalid Fraction (can do with optional empty)

**Comment by territxl** [comment]
hi! you can implement conditions to check for the validity of your denominator in your constructor

**Comment by prisciliapangg** [comment]
Instead of returning new Num()... you should return Num.of(). Hence, there should be another of method which takes in an integer!

**Comment by sethteo** [comment]
In your constructor that takes in an Optional frac you can use a filter() to check its validity :)

**Comment by BrendaTan29** [comment]
I managed to solve this by checking the validity of my numerator and denominator in my of method. if one of then isn't valid i returned a Fraction(Optional.empty()

**Comment by ianwonghanli** [comment]
thanks all. I managed to solve it by return a Fraction(Optional.empty() when the conditions isValid is not met for both numerator and denominator!
