### ISSUE TITLE
lab 7 level 5

### ISSUE THREAD

**Issue by yukiang019** [nus-cs2030/2223-s2#710]
# Summary

hello! for lab 7 level 5, I'm having trouble printing the necessary output for sum() and f(). 

## Description:

The main issue is that sum() only prints half of the "adding" lines for some reason (screenshot 1) when my code for f() is also written. However, if I just use the sample f() that is directly given in the question suddenly I'm able to print all the "adding" lines (screenshot 2). So I think sum() is working and the issue must be with f(), but I don't get why the content of f() will make a difference in how sum() works. Has anyone else faced this issue?

## Screenshots
<img width="206" alt="image" src="https://user-images.githubusercontent.com/122513777/229343406-74865799-ceea-443e-861d-c7d3cca5a7b5.png">

<img width="251" alt="image" src="https://user-images.githubusercontent.com/122513777/229343851-5cde08b2-7a20-42ac-8d9c-35d88110fd38.png">

**Comment by cocopear** [comment]
the issue could be that you sum() and f() functions have variables of the same name? considering the fact that sum() works when f() is not present, and that when using the code in the question your own sum() code works.

**Comment by e0969794** [comment]
yup, as mentioned above, you might want to check if any of the variables or methods overlap in sum( ) and f( ). rmb that it is written in jshell, so methods are to be completely separate chunks of code instead of writing it as a class. hope this helps!

**Comment by aeraeroaer** [comment]
> the issue could be that you sum() and f() functions have variables of the same name? considering the fact that sum() works when f() is not present, and that when using the code in the question your own sum() code works.

Sorry just a question, but why would having variables of the same name make a difference? as long as those variables are not global variables, shouldn't it be fine?

**Comment by kyledilao777** [comment]
i think it would be critical to note that they have to be two separate methods and not in the same class. I believe @e0969794  was saying is that if you defined it in the same class, variable name might play a role, depending on how you fit it into your code. However, i would advise not using a class at all, but two different methods in the level5.jsh file instead.
