### ISSUE TITLE
Lab 7 level 5

### ISSUE THREAD

**Issue by NwaterM** [nus-cs2030/2223-s2#711]
# Summary

Hi everyone! I ran into some errors in my f() method and I am not sure how to solve them. I have imported java.lang.String too!
Any help will be appreciated! Thank you

## Description:

<img width="1323" alt="Screenshot 2023-04-02 at 5 52 27 PM" src="https://user-images.githubusercontent.com/122254436/229345863-4f728500-9a2c-4c4f-890c-8084913e1b3c.png">

## Code Snippets

Attach code snippets (if any)

## Screenshots

Screenshots (if any)

**Comment by sparklingwater13** [comment]
Hi not very sure but maybe u didn't open your Log.java file in jshell? I dont think need to import java.lang.String

**Comment by ouhznay** [comment]
i think you forgot to open ur Log file when testing

**Comment by NwaterM** [comment]
> Hi not very sure but maybe u didn't open your Log.java file in jshell? I dont think need to import java.lang.String
the error is still here after opening Log file.. :'(

**Comment by NwaterM** [comment]
> Hi not very sure but maybe u didn't open your Log.java file in jshell? I dont think need to import java.lang.String

the error is still here after opening Log file again :\

**Comment by NwaterM** [comment]
thank u guys! I managed to solve it now, i found an extra "of" typo in my code.
