### ISSUE TITLE
Lab 5.2 self check counters

### ISSUE THREAD

**Issue by eesean** [nus-cs2030/2223-s2#712]
Hi all,

Given that all self check counters can serve the next customer once available, would like to ask whether the self check counter can simply serve the next customer without any regards to checking next available service time, or would there be no difference if the next available service time is checked? Currently my implementation is to only serve if the server (human or self check counter) is vacant and the timestamp of a particular event is not earlier than the next available service time of the server (to account for buffer time for the human server).

**Comment by trwstin** [comment]
are you asking out of curiosity or is something not working as expected?

it probably depends on your implementation, but if you are already comparing service times in your method to retrieve the fastest available counter then i think it's probably redundant to have another condition to check if it is available?
