### ISSUE TITLE
Lab 5.2

### ISSUE THREAD

**Issue by ongjunfeng17** [nus-cs2030/2223-s2#713]
Hi, I have created a selfcheck which acts like a human server (only difference is that its waiting time is 0)

Subsequently, in my events, I checked if the server is a selfcheck and if so:
Arrive:
- if all selfcheck & human servers are not free + selfcheck 1's queue is not full, manager makes customer queue up at selfcheck 1
- returns Wait at customer arrival time

Wait:
- Manager gets first available server
- check if first available server is free
- if yes, check if customer is first in line and return serve 
- if customer is not first in line return wait at selfcheck 1
- if no, return wait at selfcheck 1

Serve:
- manager makes customer queue down at selfcheck 1

However, I seem to encounter an infinite loop and am unsure of what it is I am doing wrong. If anyone can advice me on this, I would be greatly appreciated. TIA!

**Comment by Aron113** [comment]
check that when the customer returns to the wait event, the wait event time is updated with the next free self check time

**Comment by sp4ce-cowboy** [comment]
> check that when the customer returns to the wait event, the wait event time is updated with the next free self check time

Adding on to this, you only have to output the "customer x waits at self-check k + 1" once. As in, in my implementation I had a WaitEvent and a WaitingEvent (for when a Wait event returns a WaitEvent but I don't want the toString to be printed out) and when incorporating the self-checkout counters, you need to ensure that the customer "moves" to wait at the self-checkout that is the earliest available. So at some point in your code you might have to iterate through the ServerList, find Self-Checkouts, and find the earliest available self-checkout. Thus, in some cases, the customer might have "moved" to different self-checkout counters before finally being served by a self-checkout. These intermediary movements are not output with a WaitEvent toString() so they do not matter, as long as they eventually get served by the correct self-checkout. This was the case for my implementation, as I had individual queues for each self-checkout (and my queues were Integers, not ImList<Customer>) but I had a QueueManager class that managed the increment and decrement the queues all together. 

In your implementation you said "if customer is not first in line return wait at selfcheck 1" but this is not the case, the customer might have been "moved" to a different self-check queue and thus "first in line" in that queue. Essentially, for self-checkouts, the service order is actually directly tied to the arrival order of the customers (as opposed to servers where a customer is "committed" to a server). What I suspect to be happening is that the customer keeps going back to the self-check he arrived at and never actually "moves" to the self-check he is supposed to be served at. You might want to consider this in your implementation, as I had similar issues to yours and managed to fix them by fixing the self-check queue process.

**Comment by yugan01** [comment]
I believe the part that is causing the infinite loop is the wait at selfcheck1, u can try getting the earliest free self-checks time and return the wait event with the new time. The time should be later than the current time to avoid the infinite loop

**Comment by gelalallaal** [comment]
i think can try debugging using print, or run through your ID's debugger. high chance is some checks in your implementation keeps on returning false.

**Comment by ongjunfeng17** [comment]
thanks everyone, managed to solve it!
