### ISSUE TITLE
Lab 7 Failed Test Case 3_1

### ISSUE THREAD

**Issue by junglebollz** [nus-cs2030/2223-s2#714]
# Summary
<img width="877" alt="image" src="https://user-images.githubusercontent.com/123968722/229361631-4a638a37-7e5c-4b71-87b3-438061aa8d8e.png">

I think this problem could be due to incorrect wildcard boundaries in my flatMap method, but I don't really understand why either :(. I think I got the correct boundaries for map but it was done through trial and error, hopefully someone can enlighten me on whyyy.

<img width="348" alt="image" src="https://user-images.githubusercontent.com/123968722/229361765-7d08e3b9-8e8f-44ae-86ab-433fedcea3cb.png">

<img width="340" alt="image" src="https://user-images.githubusercontent.com/123968722/229361772-b26cce0c-47ca-42d3-8076-a2857744ac77.png">

Thanks all!

**Comment by leonardwx** [comment]
did your flatMap function take in account of null value?

**Comment by Aron113** [comment]
the flatmap function has a wildcard ? extends Log as well

**Comment by leezhanpeng** [comment]
Can you try without `? extends R`? I think leaving it as R is sufficient. For T, `? super T` should be ok.

**Comment by jiayeet** [comment]
I think the error lies in your flatMap, your flatMap should be ? super T. Map looks okay.

**Comment by BreatheManually** [comment]
> Can you try without `? extends R`? I think leaving it as R is sufficient. For T, `? super T` should be ok.

Worked with this.

**Comment by aeraeroaer** [comment]
I also encountered the same issue, changing ? extends R to R should fix it!

**Comment by junglebollz** [comment]
Thanks all! I tried <R> Log<R> flatMap(Function<? super T, ? extends Log<? extends R>> f) and it now works!
