### ISSUE TITLE
CANNOT COMPILE NUM - VARIABLE OPT MIGHT NOT HAVE BEEN INITIALIZED

### ISSUE THREAD

**Issue by pnghaanh** [nus-cs2030/2223-s2#715]
# Summary

My Num class is not compilable, and returns the message "variable opt might not have been initialized (attached below).

## Description:

I'm not sure how to initialize the constructors with generic supertype. Can someone help me explain how this works and/or what should I do with my code (attached below)?

Any help is appreciated.

## Code Snippets

![Picture2](https://user-images.githubusercontent.com/124126901/229361833-447ecbdc-6a71-4a87-8ab4-e9382d4d133c.png)

## Screenshots

![Picture1](https://user-images.githubusercontent.com/124126901/229361842-fdce6b4b-12ce-4bb6-b5b8-34eb94e522fd.png)

**Comment by aeraeroaer** [comment]
Hello, i think you don’t actually have to create another opt, since the AbstractNum class already has it . Another thing that i notice is that in line 12, this() should be changed to super(), since abstractnum already has that constructor available

**Comment by pnghaanh** [comment]
> Hello, i think you don’t actually have to create another opt, since the AbstractNum class already has it . Another thing that i notice is that in line 12, this() should be changed to super(), since abstractnum already has that constructor available . The reason why your opt variable was not initialised is because you created another opt variable on top of the opt in the super class, therefore when you do super(opt) you are only initialising the opt in AbstractNum and not the one in Num

Hi! Thank u sm for ur response! I removed the private final opt line and it works. but now my of method doesn't work bc "non-static method cannot be referenced from a static context". any idea what's going on?

**Comment by aeraeroaer** [comment]
> > Hello, i think you don’t actually have to create another opt, since the AbstractNum class already has it . Another thing that i notice is that in line 12, this() should be changed to super(), since abstractnum already has that constructor available . The reason why your opt variable was not initialised is because you created another opt variable on top of the opt in the super class, therefore when you do super(opt) you are only initialising the opt in AbstractNum and not the one in Num
> 
> Hi! Thank u sm for ur response! I removed the private final opt line and it works. but now my of method doesn't work bc "non-static method cannot be referenced from a static context". any idea what's going on?

hmm, can you send a snippet of your code?

**Comment by pnghaanh** [comment]
> > > Hello, i think you don’t actually have to create another opt, since the AbstractNum class already has it . Another thing that i notice is that in line 12, this() should be changed to super(), since abstractnum already has that constructor available . The reason why your opt variable was not initialised is because you created another opt variable on top of the opt in the super class, therefore when you do super(opt) you are only initialising the opt in AbstractNum and not the one in Num
> > 
> > 
> > Hi! Thank u sm for ur response! I removed the private final opt line and it works. but now my of method doesn't work bc "non-static method cannot be referenced from a static context". any idea what's going on?
> 
> hmm, can you send a snippet of your code?

![Picture1](https://user-images.githubusercontent.com/124126901/229362990-e581ca67-2d8e-4360-8ea7-c5f4b05e12cc.png)

This is what I have so far

**Comment by aeraeroaer** [comment]
> > > > Hello, i think you don’t actually have to create another opt, since the AbstractNum class already has it . Another thing that i notice is that in line 12, this() should be changed to super(), since abstractnum already has that constructor available . The reason why your opt variable was not initialised is because you created another opt variable on top of the opt in the super class, therefore when you do super(opt) you are only initialising the opt in AbstractNum and not the one in Num
> > > 
> > > 
> > > Hi! Thank u sm for ur response! I removed the private final opt line and it works. but now my of method doesn't work bc "non-static method cannot be referenced from a static context". any idea what's going on?
> > 
> > 
> > hmm, can you send a snippet of your code?
> 
> ![Picture1](https://user-images.githubusercontent.com/124126901/229362990-e581ca67-2d8e-4360-8ea7-c5f4b05e12cc.png)
> 
> This is what I have so far

the of method should be a static method, or else you won’t be able to do Num.of(). Also just a reminder, isValid() cannot check whether the num is a natural number or not, what you should be using is AbstractNum.valid

**Comment by pnghaanh** [comment]
thank you so much

> > > > > Hello, i think you don’t actually have to create another opt, since the AbstractNum class already has it . Another thing that i notice is that in line 12, this() should be changed to super(), since abstractnum already has that constructor available . The reason why your opt variable was not initialised is because you created another opt variable on top of the opt in the super class, therefore when you do super(opt) you are only initialising the opt in AbstractNum and not the one in Num
> > > > 
> > > > 
> > > > Hi! Thank u sm for ur response! I removed the private final opt line and it works. but now my of method doesn't work bc "non-static method cannot be referenced from a static context". any idea what's going on?
> > > 
> > > 
> > > hmm, can you send a snippet of your code?
> > 
> > 
> > ![Picture1](https://user-images.githubusercontent.com/124126901/229362990-e581ca67-2d8e-4360-8ea7-c5f4b05e12cc.png)
> > This is what I have so far
> 
> the of method should be a static method, or else you won’t be able to do Num.of(). Also just a reminder, isValid() cannot check whether the num is a natural number or not, what you should be using is AbstractNum.valid

Thank you so much, I'll try again and update

**Comment by haqanh** [comment]
hi, if you inherit from a superclass, you no longer need to declare that property in the child class - instead, the child class will just go and "search" for this in the parent class. Hence the super() call. Hope this helps!

**Comment by territxl** [comment]
hi! This is because for child classes, you only declare additional attributes in addition to the parent class. Since you are using the same Optional, there is no need to declare that.

**Comment by pnghaanh** [comment]
Solved! Thanks everyone
