### ISSUE TITLE
poll method for priority queue

### ISSUE THREAD

**Issue by eesean** [nus-cs2030/2223-s2#72]
Hi all,

As elements in PQ class are ordered based on a specified comparator, I would like to clarify, if I were to create a comparator that sorts eg integers in descending order, would the poll method return the smallest value as the highest priority element?

For example, in a priority queue of integers [1, 2, 3, 4, 5], would the output be (1, [2, 3, 4, 5]), or the exact opposite?

**Comment by SimonSeeYongsheng** [comment]
> 

https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/Comparator.html#compare(T,T)

In the PQ class, only the first element is guaranteed to be smallest, the rest are not.

**Comment by 0liverkong** [comment]
i would just implement the comparator assuming a certain direction. if the output of poll() appears to be reversed then just multiply everything in compare(Event e1, Event e1) by -1

**Comment by e0959170** [comment]
hi, using the comparator does not sort the pq at all! it will just simply return you the first element that meets your criteria. and the remaining list WITHOUT that corresponding element. 

to give an example, if you have a PQ that looks like this: [3,2,5,6,4] and you want it in descending order, then your PQ.poll should return you (6, [3,2,5,6,4])

**Comment by eesean** [comment]
Thanks for the insights! Yup my mistake I meant (5, [4, 3, 2, 1]) for instance.
