### ISSUE TITLE
ex 5 level 3

### ISSUE THREAD

**Issue by kelleyhan25** [nus-cs2030/2223-s2#721]
hello! does anyone have any tips for how to proceed with ex 5 level 3? i am currently stuck here. it counts the adjacent ones, but I don't know how to get it to differentiate. i.e. for the first test case, Main.countRepeats(List.<Integer>of(0, 1, 1, 1, 1, 2))
$.. ==> 1

I keep getting 3 as my output. 

thanks in advance! 
<img width="450" alt="Screenshot 2023-04-03 at 6 03 05 PM" src="https://user-images.githubusercontent.com/122245700/229478583-8b74c363-e4fb-4038-b0a3-b794c4d921ac.png">

**Comment by 0liverkong** [comment]
check #655 (you can use get())
doing it without get is way harder and i wouldnt reccomend wasting time on it.
