### ISSUE TITLE
Test case 9_13

### ISSUE THREAD

**Issue by eesean** [nus-cs2030/2223-s2#722]
Hi all,

Failed this test case (the rest not shown here are wrong as well) but the issue stems from customer 13 waiting at the human server instead of going to the self check counter.

<img width="410" alt="9_13" src="https://user-images.githubusercontent.com/110977266/229496205-15ee7cd3-f2f2-43e9-aca0-db7ff0371066.png">

I have checked and implemented my arrive event such that the sequence is:
1. Scan for available human server
2. Check that there is no one in the common queue, and the time stamp of the arrive event is not less than the next available service time of the nearest self-checkout counter (I filter out checkout counters that are available into an ImList, then sort them by server number), before returning a serve event
3. If no servers available, check whether a customer can wait at a queue of a human server
4. Else check whether the common queue for self-checkout counters is full
5. Else generate leave event

However I still can't evaluate the 2nd part to be true for this test case. Have tried debugging but not sure how else to continue (although I get that the issue is likely at the 2nd part so I'm still checking on it), would like to ask for any suggestions and, if anyone else has encountered this test case, how did you guys fix it?

**Comment by kyledilao777** [comment]
i think check the state change of self check 3, likely is due to an update issue when the last service transitioned to done, it could had a wrong update time, since it opened again at line 57

**Comment by eesean** [comment]
Hi,

Thanks for the suggestions! Fixed that error as I realised it's an edge case whereby if a self check counter is vacant a customer can just be served regardless of the time stamp.

Stuck in the same test case though :( Customer 17 waits at the first server instead and server 1 has a very large rest time.

<img width="416" alt="update" src="https://user-images.githubusercontent.com/110977266/229694372-a5aefc36-339b-4519-b148-4522e10e6fd4.png">

**Comment by eesean** [comment]
Update: Managed to resolve it and got the A! What happened was that I generated rest times for all servers, then try overwrite the rest time for self checkout counters to be 0, so to get the correct rest times the rest time should only be generated for human servers.
