### ISSUE TITLE
lab 5.2 test case 9_11 

### ISSUE THREAD

**Issue by mkim123** [nus-cs2030/2223-s2#723]
# Summary

Description of the question / problem here.

Dont know why the self-checkout counters doesnt seem to pop up to serve the customers. i passed until test case 11 so i dont know why the self checkout doesnt pop up in the output

## Description:

Clarifications or details with respect to the issue you are facing
![Screenshot 2023-04-03 194754](https://user-images.githubusercontent.com/124948994/229500984-0f95e560-7bdd-4105-b286-2946cd7add2f.png)

## Code Snippets

Attach code snippets (if any)

## Screenshots

Screenshots (if any)

**Comment by slimzaza** [comment]
I got this same error and it was because I was updating the queue for the self check counters wrongly in my WaitEvent. Do make sure you are updating the queue in the right place with the right time as well !
