### ISSUE TITLE
Lab 8 Level 5, checking for validity 

### ISSUE THREAD

**Issue by rayray39** [nus-cs2030/2223-s2#728]
# Summary

 i have implemented the sub method for Fraction. However, if the numerator is negative then my output is NaN : 2 for example (for 1/2 - 1) and not a single NaN. How can i check for validity of the numerator? 
Secondly, i am facing the 'Dependency on java.lang.String' error on codecrunch but i didnt use any Strings in my entire implementation nor have i overriden any toString methods. Anybody knows where i could have gone wrong? (i have a feeling that it could be that i am using .equals() to compare between different Optional Frac and Optional Integer, but i could be wrong)
Any help is appreciated, Thanks!

## Code Snippets

my current sub method looks like this:
this.sub(other):
this.opt.flatMap(x -> other.opt.map(y -> Frac.of(
    (x.first().mul(y.second())).sub(x.second().mul(y.first())),
    x.second().mul(y.second())
                )));
my result is an Optional Frac, i am now checking the result.map(x -> x.first().isValid()) inside an if statement against Optional.Boolean(false)

**Comment by sethteo** [comment]
> > What is your your toString() for Num or Fraction now? Instead of checking validity of the result in the sub, you can check it in the constructor, particularly the contructor that takes in an Optional (which you are using to produce your Fraction in sub)
> 
> my Num's toString is AbstractNum's toString and Fraction is Frac's toString, basically i didnt override any toStrings

What about the part that you said your using .equals() to compare how are you doing it

**Comment by rayray39** [comment]
so for eg in my Fraction of method, i use Num.of(n).opt.equals(Optional.<Integer>empty()) to check if the Num's opt is Optional.empty, if it is then i return a new Fraction(Optional<Frac>.empty())

**Comment by tjdbryan** [comment]
Hi, also facing the same issue (NaN : 8).

Anyone managed to solve it? Thanks!

**Comment by justineeyx** [comment]
for me, what i did to overcome this issue was to map the resultant Fraction's first() and second() values to isValid() and equals it to optional.of(true) for both first() and second(), if true, return said fraction, else just return fraction with an optional empty

**Comment by rayray39** [comment]
ok i managed to solve the issue of 'Dependency on java.lang.String'. I had 2 System.out.print statements for debugging and i forgot to delete those when i submit, after deleting those it worked.

**Comment by rayray39** [comment]
> Hi, also facing the same issue (NaN : 8).
> 
> Anyone managed to solve it? Thanks!

you can do something like what justineeyx mentioned, using equals method to check the Optional.Booleans, which i also did. Thanks all for your help
