### ISSUE TITLE
Lab 8 lvl 5

### ISSUE THREAD

**Issue by calvnleong** [nus-cs2030/2223-s2#729]
# Summary
Instance properties/constants detected.
Grading terminated.

## Description:
I got the error as shown below, my code runs fine in jshell. Does anyone know what this error means?

## Code Snippets

Attach code snippets (if any)

## Screenshots
<img width="225" alt="image" src="https://user-images.githubusercontent.com/124434962/229556857-b35835e8-3d1c-4042-aeee-dad8aed9dbc9.png">

**Comment by calvnleong** [comment]
hmm, i used .equals(Num.zero()) but still got the same error :/

**Comment by aeraeroaer** [comment]
> hmm, i used .equals(Num.zero()) but still got the same error :/

have you tried to create Num.of(1) anywhere in your code? that might be an issue

**Comment by sethteo** [comment]
> hmm, i used .equals(Num.zero()) but still got the same error :/

You can try referring to #685 :)

**Comment by calvnleong** [comment]
Problem fixed, for those who come across this problem in the future, try submitting only Fraction.java and Num.java.
