### ISSUE TITLE
Test output showing weird compilation warning

### ISSUE THREAD

**Issue by leezhanpeng** [nus-cs2030/2223-s2#73]
Hi guys, after submitting lab 2, the test output showed an unfamiliar compilation warning.

![image](https://user-images.githubusercontent.com/96569391/216839742-772dba4c-3a95-4cf0-a09b-1094f5b1ee72.png)

Anyone has any idea what this is about? Thanks in advance!

**Comment by AmanDesai34** [comment]
Hey, I actually am facing the same issue. ^
Will let you know if i can figure it out

**Comment by jhsoh** [comment]
Try submitting it again?

**Comment by e0959170** [comment]
perhaps you could try running javac *.java in your cli to see if there are any issues you missed out?

**Comment by leezhanpeng** [comment]
Hi guys I have resubmitted and surprisingly nothing came up this time. Will be closing this.
