### ISSUE TITLE
Lab 5.2 Test case 9_11

### ISSUE THREAD

**Issue by mkim123** [nus-cs2030/2223-s2#730]
# Summary

My self checkout counters seems to be having separate queues but everytime the custeomer waits for a self checkout counter i loop through the self checkout counters to add to every self checkout counter's queue. Any idea what seems to be the issue?

## Description:

Clarifications or details with respect to the issue you are facing

## Code Snippets

Attach code snippets (if any)

## Screenshots

Screenshots (if any)
![Screenshot 2023-04-03 210641](https://user-images.githubusercontent.com/124948994/229568459-d430e295-9aba-4409-be99-2f9fd2e3a936.png)

**Comment by nathankkh** [comment]
Customers in queue for a self checkout should be served by the first available self checkout - when self-check 4 is done, a serve event should be created for the next customer in queue. 

Depending on the way you handle the transition from a wait to a serve event, you’ll need to add a method to handle the creation of a serve event for the next available self checkout counter

For my Wait implementation, I used the perpetual wait event method that’s been mentioned in other posts (continually create new wait events based on a Server’s next available time and add it to PQ) - I had to modify the timestamp that I created my perpetual wait events with to handle self checkout counters

**Comment by bentoh95** [comment]
I encountered this. I created a list of customers in each server which I populated in the arrive class. This allows me to track the customer queue on the SelfCheckOut server, and I will push the customer in front of the list first. This may not be the most ideal solution, but it helped.
