### ISSUE TITLE
Lab 5 test case 9_9

### ISSUE THREAD

**Issue by sohjoana** [nus-cs2030/2223-s2#731]
Hi, I can't seem to find where the error is, I've passed all public test cases though... I suspect that it might have to do with the waiting. 
Description of the question / problem here.

## Screenshots

Screenshots (if any)
![Screenshot 2023-04-04 at 12 24 40 AM](https://user-images.githubusercontent.com/122262872/229570112-eb00f065-57cf-4d00-ac91-d807be9e097f.png)

**Comment by keshialimm** [comment]
could it be that you’ve started the index of self checks wrongly? now it seems like all the self check indexes are 1 away from the correct one!
