### ISSUE TITLE
Lab 8 Level4 NaN output

### ISSUE THREAD

**Issue by aseah15** [nus-cs2030/2223-s2#734]
any hints on how what to wrap inside opt for Fraction? Currently wrapping Frac but the output when invalid is NaN : NaN instead of one NaN output

**Comment by 0liverkong** [comment]
have you tried using filter?

**Comment by aseah15** [comment]
> have you tried using filter?

no...? but isn't the issue on wrapping the wrong object?

**Comment by 0liverkong** [comment]
can try filter(), checking if both first() and second() are valid Nums.

**Comment by aseah15** [comment]
> can try filter(), checking if both first() and second() are valid Nums. i dont think its an issue of the wrong value being wrapped since a compile time error would be thrown..

ouhh okk yea i used an if statement but yea filter is the cleaner way. my checking is correct...? if any of the values are invalid, i would create new Nums with empty Optionals such that the toString will be NaN since thrs no value. but since i wrap a Frac, the toString of Frac is %s : %s resulting in NaN : Nan instead of one NaN

am i just not seeing the mistake...?

**Comment by 0liverkong** [comment]
yeah.. you create empty nums but you need an empty Fraction - like from level 4

**Comment by normantan1** [comment]
your fraction should take in optional<Frac>, then it should be optional.empty when your output is invalid

**Comment by bentoh95** [comment]
You should try wrapping an Optional<Frac>. This allows you to either attain the value in the Optional which is a Frac or NaN if it is empty. Hope this helps!

**Comment by emilythx** [comment]
Hi! I returned a new Fraction(Optional.empty()), hope this helps!

**Comment by aseah15** [comment]
yeap, realised i wrapped wrongly thanks!
