### ISSUE TITLE
AbstractNum class equals() method

### ISSUE THREAD

**Issue by emmannyyy** [nus-cs2030/2223-s2#736]
# Summary
Equals() method is causing compilation errors

## Description:
Hi guys, I'm getting compilation errors for the equals() method in AbstractNum, despite having made no modifications to the method. Can anyone comment if they had the same issue, and how to fix this? 

Attach code snippets (if any)
![image](https://user-images.githubusercontent.com/122295421/229687074-e6d1ba90-cd76-46ec-a328-c6f57950af3b.png)

**Comment by trwstin** [comment]
did you accidentally delete like a ; or { somewhere in the method

**Comment by bentoh95** [comment]
Can we see a snippet or screenshot of your AbstractNum class equals method?

**Comment by emilythx** [comment]
<img width="423" alt="Screenshot 2023-04-04 at 1 28 49 PM" src="https://user-images.githubusercontent.com/122248580/229695503-e26d5a5f-83fa-4f48-b2ee-50e9698876ec.png">
Hi, this is how AbstractNum equals is supposed to look. Do check if you accidentally make any changes to it :)

**Comment by EpicSpirito** [comment]
Are you using an older version of java? Correct me if I'm wrong, but the syntax of instanceof is different for older java versions

**Comment by e0968868** [comment]
i faced the same issue before but managed to resolve it after updating to java 17

**Comment by WXUXIN** [comment]
check version of java, had the same issue before

**Comment by gene2345** [comment]
I had the same issue, the version of java may be diff
you can just typecast it to solve the issue, change it to this:
if (obj instanceof AbstractNum<?>) {
AbstractNum<?> abs = (AbstractNum<?>) obj;
....

**Comment by timothysashimi** [comment]
Hello! I had the same issue. I believe you need to typecast  obj into an abstractnum and assign it to a variable

**Comment by emmannyyy** [comment]
Thanks guys! 

Figured out why there was this issue.. my java -version showed 17.xx

but javac -version was 11.. Really didn't get why this happened, but had to reinstall java to make the unedited code work! 


If anyone wants to skip that step and typecast, I think it would work too, as follows:
![image](https://user-images.githubusercontent.com/122295421/229973095-0255f049-b6ee-48e0-8413-40c94e6f848d.png)
