### ISSUE TITLE
Lab 8 Test Case 5_1

### ISSUE THREAD

**Issue by stxe09** [nus-cs2030/2223-s2#737]
# Summary

I'm having an issue with Lab 8 Test Case 5_1. Has anyone faced a similar issue?

## Screenshots

![image](https://user-images.githubusercontent.com/122586851/229695357-e3c24fc5-d810-49e9-9139-6b10ad6fa9f8.png)

![image](https://user-images.githubusercontent.com/122586851/229695393-b9d93234-cc46-468a-8ead-3e656ca4a4c8.png)

**Comment by emilythx** [comment]
Hi! You may consider debugging it using your own values of a,b,c,d and apply it to the test case shown (e.g. c.add(d) -> correct output?). From there, you should be able to find out which method (add/sub etc. ) is causing the issue :)

**Comment by VanyaPriscillia** [comment]
I think you make a mistake in your mul method. It should return ac/bd

**Comment by stxe09** [comment]
yes!! i mistyped. thanks!!
