### ISSUE TITLE
Test case 9_12 infinite loop

### ISSUE THREAD

**Issue by edwinhrj** [nus-cs2030/2223-s2#738]
# Summary

hi guys, my current implementation leads to what I presume is an infinite loop for test case 12 as shown in the screenshot below.

From test case 11 to 12; I updated the way my waitEvent works as shown in the code snippets below.

Does anyone have any idea why this infinite loop is occurring? thanks!

## Description:

Clarifications or details concerning the issue you are facing

## Code Snippets

current case 12:
![image](https://user-images.githubusercontent.com/122248645/229698040-5ec53d35-7eda-4550-a72e-788d396c3b14.png)

case 11: 
![image](https://user-images.githubusercontent.com/122248645/229698210-9faaf249-7bc7-48d9-aeaa-6863f24e1f16.png)

## Screenshots

Screenshots (if any)<img width="874" alt="image" src="https://user-images.githubusercontent.com/122248645/229697358-d229d137-2115-4bb1-a3a7-916e90396272.png">

**Comment by emilythx** [comment]
Hi! I'm not sure if this may help, but I did face an infinite loop back in test case 11. For me the issue lies on the "if all self checkout is not free" part. For the earliestAvail, I initialise it as the K+1 (first selfcheckout server)'s time and first selfcheckout's ID and it managed to work. Hope this helps!

**Comment by edwinhrj** [comment]
> Hi! I'm not sure if this may help, but I did face an infinite loop back in test case 11. For me the issue lies on the "if all self checkout is not free" part. For the earliestAvail, I initialise it as the K+1 (first selfcheckout server)'s time and serNo as first selfcheckout's ID and it managed to work. Hope this helps!

thanks, it turns out that was the problem for the infinite loop!!

however when I implemented the change as you said, this is the problem I ran into:

<img width="692" alt="image" src="https://user-images.githubusercontent.com/122248645/229704707-4158cadc-7a5d-4bd4-a654-a4a3595a526d.png">

any ideas how come this occurs? thanks!
