### ISSUE TITLE
[ex2] stuck at lvl2, how do I set up an association between the two classes? implements(?)

### ISSUE THREAD

**Issue by sporobolous** [nus-cs2030/2223-s2#74]
<img width="1152" alt="Screenshot 2023-02-06 at 11 10 04 AM" src="https://user-images.githubusercontent.com/110991431/216875033-4f73cce4-b318-4f7f-b329-00aee9950db9.png">
im pretty sure this is in the lab like its similar to the shapes example, but im not sure how my service.java shld look like...

**Comment by 0liverkong** [comment]
have you finished making you constructor for service()?

**Comment by sporobolous** [comment]
yes I did, its all good I realise that the method service is calling is `getServiceTime()` which I did not create
