### ISSUE TITLE
Lab 8 Level 2

### ISSUE THREAD

**Issue by j0205m** [nus-cs2030/2223-s2#740]
# Summary

i first checked the validity for both operands and used stream for add() but i'm not sure why the outcome is not updated accordingly, any help is much appreciated!

# Code snippet
<img width="682" alt="Screenshot 2023-04-04 at 15 08 15" src="https://user-images.githubusercontent.com/124303065/229715075-5756f781-e3cd-40a7-ab32-3a3b00c4d394.png">

# Output
<img width="836" alt="Screenshot 2023-04-04 at 15 06 08" src="https://user-images.githubusercontent.com/124303065/229715120-bbf4cf17-cb24-45a7-ac4d-468c57be4546.png">

**Comment by 0liverkong** [comment]
(x,y) -> this.succ() seems wrong.

**Comment by justineeyx** [comment]
it shld be x -> !x.equals(number) and @0liverkong is right as well

**Comment by j0205m** [comment]
thank u all ^^

**Comment by Cfyjdfk** [comment]
Hi, can I get some clue on how you solved it? Im completely lost :(
