### ISSUE TITLE
Lab08 level 5 output

### ISSUE THREAD

**Issue by slimzaza** [nus-cs2030/2223-s2#742]
# Summary

For the test case "Fraction.of(1, 4).sub(Fraction.of(1, 2))", instead of getting a single "NaN", I got "NaN : 2" for example. I saw the other posts on level 5 but im still rather confused. From the sub/mul/add methods, I am returning new Fraction (...) but I am stuck figuring how and where to check if it's valid. Can someone advice me? 
Thanks!

## Description:

Clarifications or details with respect to the issue you are facing

## Code Snippets

Attach code snippets (if any)

## Screenshots

Screenshots (if any)

**Comment by sethteo** [comment]
You can use a .filter() in the constructor that you call that returns Fraction within your sub/mul/add classes.

Another approach is that you can check the numerator and denominator are valid by mapping into to a .isValid and using the optional boolean generated to determine whether to return a NaN or an actual fraction

**Comment by Ramanenbh** [comment]
I did Num.of(a).isValid() and checked the same for the rest -> if true then return a new Fraction if not return an empty Fraction that way ur string will 100% be empty and return Nan

**Comment by Ramanenbh** [comment]
As to check if the denominator is 0 or not i used the .equals() method with zero(), I am not sure if there is any better ways of doing it
