### ISSUE TITLE
Lab 5.2 Private Test Case 2 Error

### ISSUE THREAD

**Issue by kcslllll** [nus-cs2030/2223-s2#743]
# Summary

hi! can anyone advise as to why im getting the time limit exceeded error after i implement the self-checkout counters for la5.2. thanks! 

## Screenshots

![image](https://user-images.githubusercontent.com/122248706/229853111-31bdd40f-03b5-43ac-ab2d-8ac57f588dbb.png)

**Comment by kcslllll** [comment]
> hi what methods did you use to implement self check? there could be an infinite loop due to the wait event

hi! i first checked if the server is a self check-out counter, and if it is, and if it is also available to serve when the wait event ends, it will serve the customer. if not, if the customer is the first in line and if the server is available to serve when the wait event ends and if it is not a self check-out counter, it will serve the customer. if not, the nextavailtime will be updated according to the server's next free time. if the server is a self check-out, it will loop through the servers with the condition that the server's next free time is less than the nextavailtime and update accordingly, and this will return a wait event with the nextavailtime!

**Comment by leonardwx** [comment]
i see! for me what i did was a more systematic approach where during my wait event, i checked whether is my server human or counter. if is human, i will push directly it to the next waitmore event. if is counter, i will sort the next available time of the counter and push it to my waitmore event. then inside my waitmore event, i will once again check whether is it a human or counter. then comparing the availability time of the particular human server (get the next available time if is a counter) to consider for a serve event, else a waitmore event.

**Comment by leonardwx** [comment]
perhaps that is a reason why your time limit exceeds when you didnt generate another waitmore event

**Comment by kcslllll** [comment]
> perhaps that is a reason why your time limit exceeds when you didnt generate another waitmore event

ahh i see okay i shall try it out thank u fr the help!

**Comment by kcslllll** [comment]
> i see! for me what i did was a more systematic approach where during my wait event, i checked whether is my server human or counter. if is human, i will push it directly to the next waitmore event. if is counter, i will sort the next available time of the counter and push it to my waitmore event. then inside my waitmore event, i will once again check whether is it a human or counter. then comparing the availability time of the particular human server (get the next available time if is a counter) to consider for a serve event, else a waitmore event.

hi! can i check with you what you mean by "if is counter, i will sort the next available time of the counter and push it to my waitmore event. " ? thanks :)

**Comment by hcyrr** [comment]
hi! another way instead of creating a waitmore event will be to in your wait event, check for the server id of ur server, if the server's id is greater than the number of human servers, you can find the 'correct' server id by looping through the self check counters, and finding the self check with the earliest next avail time/ is free.
also, what i did for my wait event was to only generate a serve event if the customer is the first in queue of this server's queue, and if the timestamp of this serve event is >= the server's nextavailtime (checking for whether human server is resting), or else another wait event with timestamp of the server's next avail time will be generated

**Comment by kcslllll** [comment]
> hi! another way instead of creating a waitmore event will be to in your wait event, check for the server id of ur server, if the server's id is greater than the number of human servers, you can find the 'correct' server id by looping through the self check counters, and finding the self check with the earliest next avail time/ is free. also, what i did for my wait event was to only generate a serve event if the customer is the first in queue of this server's queue, and if the timestamp of this serve event is >= the server's nextavailtime (checking for whether human server is resting), or else another wait event with timestamp of the server's next avail time will be generated

ahh okay ill try to use this method! 
![image](https://user-images.githubusercontent.com/122248706/229983248-e2730084-704d-4226-b17e-a1b707532882.png)
is this the correct way of implementing it? when i do this i get this output that some of my customers are waiting at the server when they should be getting served immediately

**Comment by leonardwx** [comment]
> > i see! for me what i did was a more systematic approach where during my wait event, i checked whether is my server human or counter. if is human, i will push it directly to the next waitmore event. if is counter, i will sort the next available time of the counter and push it to my waitmore event. then inside my waitmore event, i will once again check whether is it a human or counter. then comparing the availability time of the particular human server (get the next available time if is a counter) to consider for a serve event, else a waitmore event.
> 
> hi! can i check with you what you mean by "if is counter, i will sort the next available time of the counter and push it to my waitmore event. " ? thanks :)

hi! this means i will get the first available counter from the serverlist:

Server counter = serverList.getNextAvailableCounter();
return new Pair<ServerList, Event>(serverlist, new WaitMore(......, counter);

**Comment by kcslllll** [comment]
> > > i see! for me what i did was a more systematic approach where during my wait event, i checked whether is my server human or counter. if is human, i will push it directly to the next waitmore event. if is counter, i will sort the next available time of the counter and push it to my waitmore event. then inside my waitmore event, i will once again check whether is it a human or counter. then comparing the availability time of the particular human server (get the next available time if is a counter) to consider for a serve event, else a waitmore event.
> > 
> > 
> > hi! can i check with you what you mean by "if is counter, i will sort the next available time of the counter and push it to my waitmore event. " ? thanks :)
> 
> hi! this means i will get the first available counter from the serverlist:
> 
> Server counter = serverList.getNextAvailableCounter(); return new Pair<ServerList, Event>(serverlist, new WaitMore(super.getCustomer(), counter));

ah i see okay so your getnextavailablecounter() sorts the available time am i right?

**Comment by leonardwx** [comment]
yes the sort the lowest available time from the list of counters

**Comment by kcslllll** [comment]
> yes the sort the lowest available time from the list of counters

ok thanks so much!!! :)

**Comment by kcslllll** [comment]
> yes the sort the lowest available time from the list of counters

btw,,, do u know if there is any way i can retrieve the list of self check out counters in the wait event because i only have the list of self check out in simulator class.. but the other person reccomended another way which uses the list of self-check counters!

**Comment by leonardwx** [comment]
for me i used counter as subclass of servers. so i add all the servers and counters into one serverlist. i used a boolean true false to indicate whether is it a human or server. from there u can extract ur data

**Comment by kcslllll** [comment]
> another way instead of creating a waitmore event will be to in your wait event, check for the server id of ur server, if the server's id is greater than the number of human servers, you can find the 'correct' server id by looping through the self check counters, and finding the self check with the earliest next avail time/ is free. also, what i did for my wait event was to only generate a serve event if the customer is the first in queue of this server's queue, and if the timestamp of this serve event is >= the server's nextavailtime (checking for whether human server is resting), or else another wait event with timestamp of the server's next avail time will be generated

ok!! thank u so much i managed to fix my error :))
