### ISSUE TITLE
Lab 8 Level 5 output

### ISSUE THREAD

**Issue by Delocy** [nus-cs2030/2223-s2#744]
# Summary
Anyone have any ideas why my if condition doesnt go through even though the optional is empty
Description of the question / problem here.

## Description:

Clarifications or details with respect to the issue you are facing

## Code Snippets

Attach code snippets (if any)

## 
<img width="347" alt="Screenshot 2023-04-04 at 11 49 35 PM" src="https://user-images.githubusercontent.com/94375191/229847980-d7e390d3-246d-4806-98a5-8617da2be5f5.png">
<img width="608" alt="Screenshot 2023-04-04 at 11 49 53 PM" src="https://user-images.githubusercontent.com/94375191/229848006-15cbb92e-0859-48f0-b003-76db7c0cb8cf.png">
Screenshots

Screenshots (if any)

**Comment by Leeeef552** [comment]
hi im facing the same issue, how did you resolve it?

**Comment by Delocy** [comment]
> hi im facing the same issue, how did you resolve it?
> 
> 

You need to check if the calculated numer is valid using the given predicate

**Comment by Delocy** [comment]
> hi im facing the same issue, how did you resolve it?
> 
> 

I didnt even filter my resultnumer previously, after doing that it works alrdy
