### ISSUE TITLE
Lab 5.2 Test case 9_12

### ISSUE THREAD

**Issue by edwinhrj** [nus-cs2030/2223-s2#745]
# Summary

Hi guys, I've been getting this output where my customer is leaving instead of waiting at selfCheck 4 for test case 12. 

I'm assuming that the general flow of event transition is correct, as there were no errors in the previous test cases up till now but I cant figure out where the bug is. 

Anybody has any ideas?

## Description:

![image](https://user-images.githubusercontent.com/122248645/229855932-4c937f66-1d60-4cd9-95b6-1eb0a6ec2391.png)

## Code Snippets

here's a portion of my waitEvent that generates the next ServeEvent and updates the serverList:

![image](https://user-images.githubusercontent.com/122248645/229856164-6a4b97c1-5d8e-4a6e-b9b7-098b6bc1c1a2.png)

**Comment by yinshuennn** [comment]
hi, i had this same error and my problem was that I was removing the customer from the selfcheck's queue in my serve event instead of my buffer event before I returned a serve event. Maybe you can make sure that you are removing your customer from the queue in the right place

**Comment by edwinhrj** [comment]
> e event instead of my buffer event before I returned a serve event. Maybe you

hmm could you elaborate on this? because currently, my implementation is that ill remove the customer from the selfCheck's queue in my waitEvent when waitEvent is transitioning to a buffer waitEvent then finally into a ServeEvent

**Comment by alvintjw** [comment]
@edwinhrj Had a similar error. I had the same implementation as @yinshuennn where I add customer into the queue at the Wait event and remove it at the intermediate wait event but I encountered the similar error and realised that I was removing the customer too early. For eg, If C1 waits at 0.0 and is the first customer in Queue and the next available SCO EndTime is 1.0.  My previous intermediate wait was removing the customer at 0.0 but what you should be doing is returning the intermediate wait event again with the time of 1.0 then check if the this.getTime is ==  SCO endtime. i.e Only when the customer is waiting at 1.0 and is the first customer in queue will I then remove the customer from queue. Hope this helps:))

**Comment by niclee1219** [comment]
<img width="848" alt="Screenshot 2023-04-08 at 2 16 14 PM" src="https://user-images.githubusercontent.com/20497341/230706600-a587c888-4855-4e18-ab75-3661cbe26b46.png">
 hi reopening this! our error seems to be similar but I'm not sure where I have implemented wrongly. 
 
 here is my code snippets:
## InterimWait.java (buffer event)
<img width="848" alt="Screenshot 2023-04-08 at 2 16 55 PM" src="https://user-images.githubusercontent.com/20497341/230706621-13ecf203-c8fc-4ea5-8a50-ba7e471923d3.png">

## Serve.java
<img width="848" alt="Screenshot 2023-04-08 at 2 17 26 PM" src="https://user-images.githubusercontent.com/20497341/230706635-9711f35c-bad4-4f77-b7b1-6437daa2d3a1.png">

Thanks so much!

**Comment by niclee1219** [comment]
sorry! worked like a charm. 

i still don't understand the removing customer at my buffer event though. my thought process is

I remove at serve because I 'served' the customer. thanks so much anyways!
