### ISSUE TITLE
5.2 Fail Test Case 9_11

### ISSUE THREAD

**Issue by clarwen** [nus-cs2030/2223-s2#746]
Hi all, 

Does anyone here have similar issue as me for 9_11? I can't seem to solve this :(

My implementation uses SelfCheck counter that extends Server. When I update the queue for SelfCheck, I will loop through the entire loop of SelfCheck and update each SelfCheck queue
![Screenshot 2023-04-05 at 1 03 45 AM](https://user-images.githubusercontent.com/119107037/229865786-5526d21d-5e14-4184-bfcd-b8f6267cc42b.png)

**Comment by weitatftw** [comment]
did you remember to keep searching for the self checkout counter with the earliest next available time?? it appears that your customers are queueing at a self checkout counter that isn't the first available self checkout counter and they are not being served by the first available self checkout counter hence the incorrect output

**Comment by nicholasteow** [comment]
While you ensure that the customers always queue at the first selfcheck do make sure to always check for the next available server to be able to determine whos responsible to serve.

**Comment by ryantangmj** [comment]
You have to re allocate the self checkout servers to the fastest available self checkout server

**Comment by clarwen** [comment]
got it, thanks all! My problem was that I did not dequeue and update the servers properly
