### ISSUE TITLE
Checkstyle error with }

### ISSUE THREAD

**Issue by EmperorAry** [nus-cs2030/2223-s2#75]
# Summary

I'm getting a warn with a checkstyle error for } (Right Curly). I've tried to remove it and redo the indentation but its not working for me

## Screenshots

![image](https://user-images.githubusercontent.com/64073938/216880708-8882f733-c660-4674-aef1-e255376fbb0b.png)

**Comment by SimonSeeYongsheng** [comment]
If I'm not mistaken, it should be like this

if {
...
} else if {
....
} else {
...
}

as the error is pertaining to multiple blocks

**Comment by EmperorAry** [comment]
Thanks, that works. I didn't realise i had to write if-else-if like that.
