### ISSUE TITLE
Private test case 3_1

### ISSUE THREAD

**Issue by syafiq9326** [nus-cs2030/2223-s2#755]
# Summary

I am able to clear all the pdf cases for level 3 but came across this error on CC, not sure what went wrong with my sub(), was wondering if anyone had a similar issue. Would appreciate any assistance, thanks!

## Screenshots

![image](https://user-images.githubusercontent.com/50677984/230050584-d742dc98-546f-4cd7-a7fa-774994b75cda.png)

**Comment by ringleading** [comment]
using a stream to tackle this: "it can be seen as m repeated additions of n, or vice-versa." worked well for me

**Comment by youthfrost** [comment]
probably means u have an infinite loop

**Comment by syafiq9326** [comment]
@ringleading spot on! , realised I was doing it in the opposite way all along. Thanks everyone!
