### ISSUE TITLE
Exercise 5

### ISSUE THREAD

**Issue by emmannyyy** [nus-cs2030/2223-s2#756]
Hey everyone, 

I'm having a bit of issue with Level 3 of Exercise 5.
![image](https://user-images.githubusercontent.com/122295421/230068662-095bdf85-0e61-43db-ada3-38d2d7bc3f50.png)

Can anyone give a clue on how we can get the next element of a stream? I was trying to figure if reduce(), map() or even filter() can be used, but cannot really think of a way to generate the next ement in the stream. 

How can we subsequently find if there are repeats? 

Wld appreciate any clues :-)

**Comment by Ramanenbh** [comment]
HI @emmannyyy, I am currently stuck here now after I do list.stream().distinct()..
Can I ask for a hint or something

**Comment by cweisong** [comment]
> HI @emmannyyy, I am currently stuck here now after I do list.stream().distinct().. Can I ask for a hint or something

Try using IntStream.range(0, list.size() - 1), then compare the numbers using list.get() and equals()

Hope this helps!

**Comment by geraldckj** [comment]
May I ask for a hint / nudge in the right direction too? Am a little lost
