### ISSUE TITLE
Level 5

### ISSUE THREAD

**Issue by syafiq9326** [nus-cs2030/2223-s2#759]
# Summary

Fraction sub() returning NAN:8 instead of NAN, while mul() and add() works fine and will return NAN.

## Description:

I can't figure out how to solve for my sub() method failing as the other 2 is fine for my Fraction class.

In pseudocode, my add(), sub() and mul() will get

1) The first and second item in the respective pairs and will be in the form of Optional[Num]
2) I then use flatmap and map to get my numerators and denominators out (ad, bc, bd). These are in the form of Optional[Num] as well.
3) I finally converted them into a fraction using flatmap and map and frac.of().

Validity were all taken care of in my previous Num class add() and sub() methods (I think since the other cases were fine) and I am just calling them now in my map for point 2.

## Code Snippets
![image](https://user-images.githubusercontent.com/50677984/230154756-e8908692-17f4-4141-bebd-62b7572e4b2a.png)
![image](https://user-images.githubusercontent.com/50677984/230154835-25c99924-35c0-4fa7-b7ab-5ae83f81d1a1.png)

Was wondering if there is a way for me to check the validity of Optional[Num] within my sub() method since the valid predicate is for Optional[Integer] only and we can't use get() to get the Num out to use isValid() either or if I am just missing something here.

Thanks!

## Screenshots

![image](https://user-images.githubusercontent.com/50677984/230153894-d271ffb4-67f0-4066-896c-73e115166b55.png)

**Comment by aeraeroaer** [comment]
Im not sure if this is the best way, but you could try rather than flatmapping out x.first() to get an Optional<Num>, you could try to flatMap to x.first().opt instead to give an Optional<Integer>, and since num has an optional<int> constructor, that way u can use the Num(Optional<Integer>) constructor to help you check the validity, I hope this helps!

**Comment by weitatftw** [comment]
you can use the filter() function to check for the validity of the num before you use the flatMap to create the Fraction

**Comment by syafiq9326** [comment]
Yep managed to clear this with @weitatftw suggestion, thanks guys, really appreciate it!
