### ISSUE TITLE
[Ex2] Need help with getting test case 4

### ISSUE THREAD

**Issue by ZaresTng** [nus-cs2030/2223-s2#76]
I could get all of the cases from the given but when I upload to codecrunch I get an issue regarding the 4th test case, it says this
<img width="845" alt="Screenshot 2023-02-06 at 11 59 36 AM" src="https://user-images.githubusercontent.com/124547607/216882089-4f75e278-684c-4d50-9ac3-fe619568fc06.png">

I dont get why it is giving this error though, because the error line is pointing towards the first for loop and the only problem i can think of would be the get(0) but if cruises does not have any cruise then how is the code going to run
<img width="602" alt="Screenshot 2023-02-06 at 12 12 55 PM" src="https://user-images.githubusercontent.com/124547607/216882178-098d939d-628a-4737-9c8f-5924bda4d4ee.png">

**Comment by VanyaPriscillia** [comment]
You should delete your first for loop and make a little change in your second for loop.

**Comment by ZaresTng** [comment]
thanks it works now :D
