### ISSUE TITLE
Lab 8 making loops more efficient

### ISSUE THREAD

**Issue by Ma-Xizi** [nus-cs2030/2223-s2#760]
# Summary

I realized my mul() method will timeout on code crunch private test cases when numbers are large. I have read related posts on github forum but just not sure how I can amend it and reduce the number of loops. I would appreciate if you could give any suggestions! 

## Code Snippets
public Num mul(Num other) {
        if (this.isValid() && other.isValid()) {
        	if (this.equals(Num.zero()) || other.equals(Num.zero())) {
                    return Num.zero();
                }
            Num counter = Num.one();
            Num addition = other;
            Num res = other;
            while (!counter.equals(this)) {
                res = res.add(addition);
                counter = counter.succ();
            }
            return res;
            
        }
        
        return new Num(Optional.empty());
    }

## Screenshots

Screenshots (if any)

**Comment by andersooi** [comment]
I didn't use a while loop in my implementation as I resorted to using Stream instead. Not sure if you want to try out using Stream instead?

**Comment by WXUXIN** [comment]
follow the question and try not to reverse the logic, you're treating say 1 x 20000 as 20000 x 1, meaning the loop will run for longer than needed

**Comment by ghost1nthemachine** [comment]
hi, for me i fixed this issue but not calling succ() too many times but instead using map() to increase the counter. i only used while loops too

**Comment by edwinleck** [comment]
@WXUXIN is right, you can try using

Num counter = Num.one();
Num addition = this;
Num res = this;
while (!counter.equals(other)) {
res = res.add(addition);
counter = counter.succ();

**Comment by Cepheux** [comment]
I used a while loop but I imposed a few conditions before running it, such as if the value is 1 on one side take the other and I escaped that scenario; though, streams is probably the right way to go about it haha

**Comment by Ma-Xizi** [comment]
> hi, for me i fixed this issue but not calling succ() too many times but instead using map() to increase the counter. i only used while loops too

OwO is it like: Num counter = Num.one();
            Num addition = this;
            Num res = this;
            while (!counter.equals(other)) {
                res = res.add(addition);
                counter = new Num(counter.opt.map(s));
            } 
Thanks so much if you could clarify😭

**Comment by ghost1nthemachine** [comment]
> > hi, for me i fixed this issue but not calling succ() too many times but instead using map() to increase the counter. i only used while loops too
> 
> OwO is it like: Num counter = Num.one(); Num addition = this; Num res = this; while (!counter.equals(other)) { res = res.add(addition); counter = new Num(counter.opt.map(s)); } Thanks so much if you could clarify😭

yep thats what I did

**Comment by Ma-Xizi** [comment]
> > > hi, for me i fixed this issue but not calling succ() too many times but instead using map() to increase the counter. i only used while loops too
> > 
> > 
> > OwO is it like: Num counter = Num.one(); Num addition = this; Num res = this; while (!counter.equals(other)) { res = res.add(addition); counter = new Num(counter.opt.map(s)); } Thanks so much if you could clarify😭
> 
> yep thats what I did

Thank you!

**Comment by Ma-Xizi** [comment]
I have solved this problem in a way that I did not fully comprehend. Like classmates in front said, do not reverse the logic. And if one of them is not valid, return it instead of creating a new Num(optional<Empty>). Not sure how it made the difference...
