### ISSUE TITLE
Ex 4 Level 4

### ISSUE THREAD

**Issue by sp4ce-cowboy** [nus-cs2030/2223-s2#761]
I'm having issues with the or method, my code looks like this

<img width="392" alt="image" src="https://user-images.githubusercontent.com/19762596/230275632-203b2891-301d-4c92-953a-6dcd8b8bcc9d.png">

and my output gives this error:

<img width="1401" alt="image" src="https://user-images.githubusercontent.com/19762596/230275703-d11890a7-d6eb-466c-8780-b627d690e66d.png">

which I understand has something with Integer being a subtype of Object but `Maybe<Integer>` not being a subtype of `Maybe<Object>`. How exactly should I change my code and where should I put my wildcard? I tried `Supplier<Maybe<? extends T>>` and that didn't work either, I get this error instead:

<img width="798" alt="image" src="https://user-images.githubusercontent.com/19762596/230276026-76e4808d-66f5-461a-97cb-e55cb946341e.png">

Which part of my code should I change and how?

**Comment by wjkb** [comment]
As mentioned in CodeCrunch, Maybe context behaves similar to Java's Optional Class, so you can go look at the API to see how the "or" method is calledd

To pass the codecrunch testcases, store the supp.get first and create a Maybe<T> to return

**Comment by smellystank** [comment]
> re the supp.get first and create a Maybe to return

Hi can i clarify what u meant by this... Because to create a maybe i need to use a .of which takes in a value and not a context so should i go about trying to take the value out? 

was also thinking about supplier.get.orElseGet but not sure what to put at the end as well

**Comment by sp4ce-cowboy** [comment]
> > re the supp.get first and create a Maybe to return
> 
> Hi can i clarify what u meant by this... Because to create a maybe i need to use a .of which takes in a value and not a context so should i go about trying to take the value out?
> 
> was also thinking about supplier.get.orElseGet but not sure what to put at the end as well

I managed to fix my issue with `Supplier<? extends Maybe<? extends T>> supp` in the method and then I made a dummy variable called `Maybe<? extends T> temp = supp.get()` which tells the compile that the temp object will definitely be a T, and then you can return `Maybe.<T>of(temp.get()` to get the Maybe inside.
