### ISSUE TITLE
Lab 5.2 How to allocate to fastest SelfCheckOut?

### ISSUE THREAD

**Issue by ahndrayo00** [nus-cs2030/2223-s2#762]
# Summary

Description of the question / problem here.
Currently, all my selfCheckouts share the same queue. However, the Wait/Waiting event was created and tied to the first self checkout.

Hence, even though they all share the same queue, when my other selfCheckOuts are done, the customers in the queue do not get allocated to them. Instead, they continue waiting for the first SelfCheckout counter to be done. How to resolve this issue??

Much appreciated thanks so much!!
## Description:

Clarifications or details with respect to the issue you are facing

## Code Snippets

Attach code snippets (if any)

## Screenshots

Screenshots (if any)

**Comment by sp4ce-cowboy** [comment]
At some point in your code, either the WaitEvent and/or WaitingEvent, you would need a looping function to iterate through the list of servers/selfcheckouts and find the earliest available checkout time. You can try something like this:

![](https://user-images.githubusercontent.com/19762596/230143843-a621f6a5-61d4-4644-9177-737a8575ba40.png)

where isSelf is a method that returns true if it is a Self-Checkout counter, and earliestAvailable is initialized with the current server's (i.e. the self-check tied to the customer) next free time. This loop sets the selfCheckId to the earliest available self-check, and I use the self-checkId to retrieve the relevant self-check from the serverList. After which, when I return an event (WaitingEvent), I associate this self-check and the associated customer to the event . Before a customer gets served, they might get "passed around" (lol) to a different self-checkout before finally being served by that self-checkout.

Also, tho this wasn't mentioned in the lab, I think if another self-checkout has the exact same nextFree time, then the customer will remain at their own self-checkout. The customer will only move if another self-check has strictly a smaller nextFree time. I didn't account for this and my code failed some test cases later on.

**Comment by ahndrayo00** [comment]
@sp4ce-cowboy thanks for the detailed reply! So since it may continue getting passed around to different self-checkouts, does this mean that this loop is also present in Waiting event, apart from Wait?

**Comment by ahndrayo00** [comment]
@sp4ce-cowboy got it to work now! Thanks so much for the help omg!! Yeah the reason for why mine wasnt working was cause I only put it in Wait, and not waiting!
