### ISSUE TITLE
Ex 4 Level 5

### ISSUE THREAD

**Issue by sp4ce-cowboy** [nus-cs2030/2223-s2#764]
I'm having issues with level 5, the last test case where `Maybe<Object> mo = ms.flatMap(g)`. I can't seem to be able to assign the output to a Maybe<Object> and I'm not sure how to fix it. My code is given below.

<img width="1171" alt="image" src="https://user-images.githubusercontent.com/19762596/230303477-43dc8941-bd66-4c89-8598-89ae6e483e1e.png">

<img width="850" alt="image" src="https://user-images.githubusercontent.com/19762596/230303488-f93c21f7-da36-496a-8f7a-f32f64dfe79c.png">

**Comment by zhanyang01** [comment]
that because for the else block you are supposed to return a maybe<R> not a maybe<? extends R> hence you might need to retrieve the R value of the mapper.apply(this.get()) using x.get() amd then create a maybe.of(value) to solve it

**Comment by andersooi** [comment]
Can check out #430

**Comment by sp4ce-cowboy** [comment]
> Can check out #430

thanks!
