### ISSUE TITLE
Lab 5.2 public testcase and arrival event logic

### ISSUE THREAD

**Issue by tali-a** [nus-cs2030/2223-s2#765]
Hi, I get  multiple customers (customer 10) being served by a self check for the public test case in Lab 5. i'm not sure if it's because my current logic for generating a serve event in arrival event is to check based on a server's next free time, while a selfcheckout needs to also check for whether the customers have already hit maximum queue length before being able to generate a serve event, or because the next  available time isn't updating correctly (but wouldn't the wrong behaviour start  earlier?) Or if my waitQueues arent being correctly updated in my serve event and intermediate wait event (i currently have selfCheckout inheriting from server and update all self checkout queues at the same time)

![image](https://user-images.githubusercontent.com/103631647/230317535-0ff7185f-e0bb-4520-9839-37fdebf76203.png)

![image](https://user-images.githubusercontent.com/103631647/230312521-fe836166-63df-4d5b-807a-d3cb3bfee7d7.png)

would be very thankful for any advice ! :)

**Comment by sp4ce-cowboy** [comment]
Are you updating the self-checkout's next available time correctly? It seems as though self-check 2 is not being "registered" as busy by customer 10,  in your logic you are checking if maximum queue length is hit before serving, are you also checking for the self-checkout's availability? I'm not too sure why the maximum queue length needs to be hit before serving, do you mean maximum queue length hit before waiting?

Also the wrong behaviour wouldn't start earlier bc in this test case there is quite a significant gap between some arrival times and done times (6 and 7, which doesn't make sense, this test case a bit funny ngl you can see there's no waiting at any self-checkouts which rly doesn't help with debugging) so you can try to make your own test cases with closer arrival times and debug from there.

**Comment by gelalallaal** [comment]
i think 2 possible areas to check is that is your next avail tim eupdated in the serve event and i think maybe can add another safety check of is this server serving someone else now before executing/printing the serve.

**Comment by vancwe03** [comment]
I think u can check that you are using the most updated self checkouts in your arrival event as it seems that the self checkout is not recorded that it is serving a customer.

**Comment by tali-a** [comment]
thanks everyone! i think the issue is how the next avail time is being updated. currently i update the server list for a self checkout in the same way as i update  the servers, but the next avail time isn't being correctly updated. i rely on the serve function to change the next avail time of a server, and do the same for a self checkout, but it isn't working properly. is this approach a wrong approach to start with?

**Comment by allnotavailable** [comment]
I think that if you pass the cases from lab3 and 5.1 you need not to change the way you update of your server. However it also depends on your implementation. What I did is I also only update the server in serve event for both selfcheck and human server.

**Comment by tali-a** [comment]
thanks! i checked through it and the updatedserver's service times seem correct in DoneEvent, but not in the arrival events

![image](https://user-images.githubusercontent.com/103631647/230698481-40395cf6-974c-4be4-9ad5-bc36871f9cdc.png)

from what I see via print statements, self-check 3 seems to be taking on the previous next service times of self check 2, and self-check 2 has its next  service time completely changed for the last customer: 

![image](https://user-images.githubusercontent.com/103631647/230698702-29b88d2c-2ee1-4cfa-87e5-34a88e30718b.png)

this is how i update my server list in serve event
![image](https://user-images.githubusercontent.com/103631647/230698736-87e10075-ed54-45be-880b-39c565a509e0.png)

cant seem to figure out why it is updating so weirdly though for non human servers

**Comment by ahndrayo00** [comment]
Updating the freeTime of a SelfCheck should be the same as a HumanServer hmm so I dont think the issue lies there

Your selfcheck 2 is serving 10 before it is done serving 8. A few possible issues;

1. Wrong logic when checking if a server is free: check time of arrival vs freeTime of server 
2. Improper updating of queue. Could be that your SelfCheck dont share a common queue OR when you modify the queue, you end up removing more customers than required.

Honestly not too sure on what your issue is. Can you modify 4.in to add more customers while all servers are busy serving (so that you force customers to wait) and see how the output is like? If you need me to send my own modified test case, lemme know.

All the best!!

**Comment by tali-a** [comment]
Thanks so much for the help!! The improper updating of the queue   was caused by something really dumb.. I was removing customers from the wait  queue of all of my selfcheckouts with the same variable name that  I was using to update the available time of the self checkout

**Comment by e0969533** [comment]
Hi! the issue with my output now seems similar to urs, could you elaborate more on how u solved the issue? Thanks!

**Comment by tali-a** [comment]
> Hi! the issue with my output now seems similar to urs, could you elaborate more on how u solved the issue? Thanks!

Hi! when i was updating the queues of each self check out, i was referring to them with the same variable name as the eventual self checkout where i served the customer (updated the next available time) which I fixed by  initializing a new variable and using that  to update  the queues of all the selfcheckouts instead
