### ISSUE TITLE
Lab 8 level 1 succ() method 

### ISSUE THREAD

**Issue by geraldckj** [nus-cs2030/2223-s2#766]
# Summary

Hi all, I'm a little stuck with the succ method. I managed to get it to work by breaking the .orElse() constrain, but I'm not too sure how to reformat my code in order to comply with the restrictions. Would appreciate any help, TIA! 

![image](https://user-images.githubusercontent.com/56596389/230319420-ac9ff069-af39-4f17-8232-35698ce25884.png)

**Comment by tristantanjh** [comment]
hi, according to the api, the map function returns an empty optional if a value isnt present so the orelse isnt necessary :)

**Comment by emilythx** [comment]
hi, you may consider checking if the value is valid, and return an optional.empty() if it isn't :)

**Comment by normantan1** [comment]
Hi gerald, you can return a num which takes in a abstractNum wrapping a mapped optional in it

**Comment by zhanyang01** [comment]
hi i think if the num isnt valid you can just return this which is the invalid num

**Comment by sethteo** [comment]
as tristan said map would return a Optional of the result if the x that you are passing in is valid, so in the case that it was already an optional empty, it will still return an optional empty so there is no need to further check it with filter / orElse as the optional empty passed into the constructor will just give a NaN

**Comment by meljwang** [comment]
Hi, the .orElse isn't necessary I think because assuming:

1. If you are calling the succ() method from an invalid Num, then mapping it will just give you an Optional.empty which when passed to the toString() in the AbstractNum class would give "NaN" 

2. If the Num you are calling succ() method with is valid, then mapping the Optional<Integer> would increase that Integer value inside the Optional by 1.

**Comment by geraldckj** [comment]
Thanks everyone for the help, I got it! 

Solved it by removing the orElse, and creating a new constructor in Num that takes in an optional<Integer>.

I then passed in the value after map into the constructor that takes in optional. 

Hope this thread helps anyone facing the same issue for the succ() method!
