### ISSUE TITLE
approach for add()

### ISSUE THREAD

**Issue by veviana** [nus-cs2030/2223-s2#769]
i created a function and used map to return the new Num, but it violates the constraints as i am using orElse and numeric value in my method. are there other approach i can use to handle the add() method? i was thinking of using loops, but since the parameter is of Num type, i cant loop through it. appreciate any advice for this method!!

**Comment by OwenChanJF** [comment]
Are you referring to level 2? If so, think about how you can use Num to do a loop

E.g, 
Create Num(0) called "counter"
temp = other <- A Num
while counter not equals this 
     temp.succ
     counter.succ
     
Hope this helps!

**Comment by shawncch** [comment]
I used a while loop. Num.zero() as my base value and succ() until equals.(Num other) == true

**Comment by Xuehann** [comment]
I used Stream.iterate with n -> !n.equals() then.reduce
