### ISSUE TITLE
Why does my java Main < test1.in not work

### ISSUE THREAD

**Issue by reinatng10** [nus-cs2030/2223-s2#77]
<img width="224" alt="Screenshot 2023-02-06 at 3 39 24 PM" src="https://user-images.githubusercontent.com/124559667/216912672-b0c7b4f3-467c-4ebf-a63f-79f262919b6d.png">
 
I have opened up all the necessary files but it kept prompting this error.

**Comment by granolaluvr69** [comment]
1. Exit jshell.
2. Compile your Main.java (javac Main.java)
3. Pass your input file into the Main class in the terminal.
<img width="390" alt="Screenshot 2023-02-06 at 4 39 34 PM" src="https://user-images.githubusercontent.com/120318851/216924618-f867d1c3-edcc-42db-b501-dbaaf397b767.png">
lmk if it worked boss

**Comment by danqiye1** [comment]
It doesn't work because you are doing it in Jshell. You should exit jshell and try that command again.

**Comment by sohjoana** [comment]
It only works on vim not jshell.
