### ISSUE TITLE
Questions regarding Ex 4 OrElseGet method error

### ISSUE THREAD

**Issue by aeraeroaer** [nus-cs2030/2223-s2#771]
Hi all, I am a little lost in creating the orElseGet() method for the Maybe exercise, any one know why this error occurs? 

<img width="1194" alt="Screenshot 2023-04-06 at 11 48 24 PM" src="https://user-images.githubusercontent.com/122816576/230432288-4c4af37c-d3b2-4f1a-abe1-ac2c1e0e557f.png">

Here is how I defined it: 
<img width="227" alt="Screenshot 2023-04-06 at 11 54 42 PM" src="https://user-images.githubusercontent.com/122816576/230432799-2a62fc87-40c8-474f-b602-0277be1dc1c6.png">

Thank you very much!

**Comment by Chuacx13** [comment]
Think about the wildcards that u may need to use.

**Comment by linha00** [comment]
you need to use Supplier<? extends T> instead of justSupplier<T> cause mo is Maybe<Object> but the supp is a Supplier<Integer>.

**Comment by kayeugenia** [comment]
use the upper-bounded wildcard ? extends!

**Comment by slimzaza** [comment]
For the type parameter T, it should be <? extends T>, to account for the cases where the input argument's type is of a child class of T

**Comment by chewyxx** [comment]
as mentioned, it should be <? extends T> since generics are invariant

**Comment by Ramanenbh** [comment]
Yup the above becuase think of it using the Producer Extends Consumer super principle especially when they say consider the generic types used or smth

**Comment by aeraeroaer** [comment]
thanks everyone!
