### ISSUE TITLE
Lab 8 level 3 sub method

### ISSUE THREAD

**Issue by Xuehann** [nus-cs2030/2223-s2#772]
Hello, I have encountered this issue where when I do zero.sub(one), it gives -1 instead of NaN. 
I had a negate() method which uses the n function in AbstractNum. I did not check for validity here as if I do so, my sub() method will give an infinite loop. 

It seems my code is considering Num.of(-1) as invalid but not Num.one().negate().

![Screenshot 2023-04-07 005126](https://user-images.githubusercontent.com/122248833/230444730-b39dc403-bc82-4bd1-a0de-7414fcee82a3.png)
![Screenshot 2023-04-07 005336](https://user-images.githubusercontent.com/122248833/230445206-2a73338a-c8cb-45af-96a9-06fc99c24a50.png)

Screenshots (if any)

**Comment by linha00** [comment]
isValid() method just check if opt is empty or not, so when you do Num.one().negative().isValid(): 
it will create a Num.of(1) then change to Num.of(-1) then gives you a true.

for sub(Num count), you can try looping the number with -1 until count is equal to zero:
-1 (flipping the num to negative first then you succ() then lastly you flipping it back to postive)

**Comment by gelalallaal** [comment]
the isvalid() issue is as explained by linha00, for the zero.sub(one), you need to ensure that your sub returns a number >=0 aka check using the valid function in AbstractNum instead of isValid()

**Comment by Xuehann** [comment]
Thank you! I solved it by checking validity of the result before returning it
