### ISSUE TITLE
Lab 8 State Engine Terminated 

### ISSUE THREAD

**Issue by Yew-Wei** [nus-cs2030/2223-s2#774]
![Screenshot 2023-04-07 at 11 21 06 AM](https://user-images.githubusercontent.com/122435876/230534454-53d889c2-10ab-4e92-93ec-a26a9bf3286a.png)

Hi all, I need some guidance regarding this issue. Basically I am using a **stream** with the **iterate method which calls succ()** to increase the counter and an **add method** to add the number with another copy of itself. I'm also aware that there are other threads regarding this issue, with some stating not to call succ() excessively, would you guys mind elaborating more on it? Much thanks in advance! 🙂

**Comment by Xequil1** [comment]
Your add shouldn't use the succ() method as it might take too long, use the static Integer add method instead.

Also try using Jshell to debug as well.

**Comment by Yew-Wei** [comment]
> Your add shouldn't use the succ() method as it might take too long, use the static Integer add method instead.
> 
> Also try using Jshell to debug as well.

Hey Xequil, just to clarify, by static Integer add method you mean the `Function<Integer, Integer> s = x -> x + 1; ` in AbstractNum? If that's the case, wouldn't that be the same as calling succ()?

**Comment by Xequil1** [comment]
The Integer API in java has has a static method that you need and it can be called like this:

Integer.add(a, b)

**Comment by kkaiyu** [comment]
Hi, I faced this problem too and I countered it by including a condition to check if both my numbers are valid before passing in succ(), if not I return an empty Optional.

**Comment by Yew-Wei** [comment]
> The Integer API in java has has a static method that you need and it can be called like this:
> 
> Integer.add(a, b)



> Hi, I faced this problem too and I countered it by including a condition to check if both my numbers are valid before passing in succ(), if not I return an empty Optional.

Hi thank you both for your suggestions. Managed to solve it and realised it was due to an infinite loop for those that are gg through the same issue!
