### ISSUE TITLE
Lab 5.2 Test Case 9

### ISSUE THREAD

**Issue by kcslllll** [nus-cs2030/2223-s2#775]
# Summary

hello! im currently facing the issue where my customer should leave instead of waiting at self check-out 2. i think there is smth wrong with the way i am implementing my self check-out queue (since they all share 1 queue of customers). wld appreicate if anyone can help to give a clearer understanding and hints on how to implement the self-checkout queue. thanks!

## Screenshots

Screenshots (if any)
<img width="554" alt="image" src="https://user-images.githubusercontent.com/122248706/230537849-fc7a786f-211f-45b6-94cd-8f0ec42bde1b.png">

**Comment by trwstin** [comment]
I think there are some suggestions in #716 on how to implement the self-checkout queue.

How are you currently implementing yours? Do you have an individual queue for each self-checkout counter?

**Comment by llaamaaa** [comment]
every who joins the selfcheckout queue should wait at the first self checkout i.e 3 & 4 waits at selfcheckout 1! 

however, once the checkout counter is free, the customer can change "server" and go to next free counter! (waits at self-check 1 but serves by self-check 2)! i think the issue is with tagging the customer to the self-checkout server!

**Comment by jiangen16** [comment]
In my arrive class, when looking for a server to wait for a particular customer, I only loop from serverid = 1 to serverid = k+1 (which is the first self check server). That way, my customers will never wait  in the queue for self check out 2 and later.

**Comment by Aron113** [comment]
for me, i looped through the serverlist to check if there are servers that have a full queue but are free, then update the queue. that way the customer won't just leave if there is a full queue

**Comment by leonardwx** [comment]
hi for me i create a single property of ImList just for the self check queue, if is self check, i will only call this ImList

**Comment by edmundnwl** [comment]
you can loop through your self-checkouts and update each of their queues whenever you want to add or remove a customer from one of their queues

**Comment by allnotavailable** [comment]
There are many implementations that you can do with this problem. One way that I did is just to make the first selfCheck server to have the queue and zero queue for the rest of the other selfChecks.

**Comment by Bwilldo** [comment]
perhaps you might want to check if you update your queue length for self check out properly :)

**Comment by easypzlemonsqueezy** [comment]
yup your customers should only be waiting at self check 1 so you would need to change your implementation to address that. the way i implemented it was having the qmax for the first selfcheck to be as usual and the qmax for subsequent selfcheck to be 0 and i redirected the customers from the selfcheck1 queue to all the other selfchecks

**Comment by koojaylynn** [comment]
hello! for me, i did a for loop to add k servers to the serverlist first to represent the human servers. after that, if there is a self checkout server, i add one more (k + 1) server to represent the first self check out server only.
