### ISSUE TITLE
add + mul + sub error

### ISSUE THREAD

**Issue by jianjiezzz** [nus-cs2030/2223-s2#778]
Anyone know what could be wrong?
![image](https://user-images.githubusercontent.com/119864021/230553338-e9741efe-0663-482f-b0db-274c46a007bc.png)

**Comment by e0970430** [comment]
hello! i face the same problem as you, may i check how did you pass this test case?

**Comment by jianjiezzz** [comment]
> hello! i face the same problem as you, may i check how did you pass this test case?

it is because that my sub method is not working due to the succ() not accepting negative number.
I simply declared another succ2() that works for negative number.
