### ISSUE TITLE
Why Function<? super T,? extends R>?

### ISSUE THREAD

**Issue by Waynelearn** [nus-cs2030/2223-s2#779]
# Description

I am not entirely clear on why the type bounds is the way that it is for Function. Why map from more general to  more specific?

## Topic:

Specific Topics this question is related to (If Any)

## Screenshots

Screenshots (if any)

**Comment by trwstin** [comment]
? super T is the input type.
? extends R is the result type.

If I'm not wrong the two types can be unrelated (i.e. Function<Number, String>), so it's not exactly mapping from a more general to more specific of a particular type? (if that's what you meant)

As for why input is ? super T and the result is ? extends R, a simple way to think of it is using PECS - Producer Extends, Consumer Super.

After all, we are consuming the input to produce the result.

**Comment by edwinhrj** [comment]
recall what your tutors should have gone through in labs - PECS (producer extends, consumer super).

In the case of Function<input T, output O>, think of it like this: 
you can take in any type T object or anything more general (i.e., its superclass), 
while you minimally need to return a type O object or any class that is a subset of the type O object.

**Comment by edmundnwl** [comment]
an example will be we use Function<? super T, ? extends R> as a type definition for a method argument. we can do this because whatever the function does to an object of type T or anything super T can be done on type T and what we do to the output of the function on an R object can be done on any object that extends from R as well.

**Comment by erinchanshining** [comment]
So for Function<? super T, ? extends R>, this wildcard parameter type allows the function to take in T or anything that is a superclass of T and outputs R or any subclass of R. 
For e.g. Function<? super Integer, ? extends Integer>
it makes sense for the function to take in an integer or number, transform this value and then output another integer or something more specific like an odd/even integer. doesn't really make sense to me to transform an integer and output sth more general but im not 100% sure this is just how i try to make sense of it

**Comment by vVicksv** [comment]
Thanks for all the help I was confused about this as well I guess I missed out on PECS :)

**Comment by redcolorbicycle** [comment]
Thanks for the help, I was very confused about this as well!
