### ISSUE TITLE
Lab 5.2 test case 9_11 

### ISSUE THREAD

**Issue by NwaterM** [nus-cs2030/2223-s2#781]
# Summary
Hello everyone! I ran into this error earlier, it seems to be because customer 17 and 18 arrives at the same time. In my arrive-> buffer wait event, I add the new waiting customer to my wait queue of customers and also made all the self-check servers update all their Q to be uniform too. My event comparator compares time and customer ID too, so I am not really sure what could be the problem here as only customer 18 is having this problem... Any insights will be appreciated ^.^ Thank you!

## Description:

Clarifications or details with respect to the issue you are facing

## Code Snippets

Attach code snippets (if any)

## Screenshots

Screenshots (if any)
<img width="971" alt="Screenshot 2023-04-07 at 3 34 11 PM" src="https://user-images.githubusercontent.com/122254436/230564035-1dee67d0-d952-4303-8d19-5d3fd9f7a4f7.png">

**Comment by Naughty123456789** [comment]
Wow i had the same exact issue as you and i was hardstuck for a good few days. I realise that my issue was in CustomerDone. 

initially in my  CustomerDone, when my server is a Self Check Out Counter  - > i set the serverlist  which reverts my server to the old server instead. After removing that one particuluar line - severlist = serverlist.set(index, server).... in my customerDone everything works out fine and i manage to bypass it 

our implementation may be quite different so i dun know whether my input will be useful. 

However what helped me with debugging is this particular testcase provided by a coding god TA

3 5 3 0.000000
0.0
0.14617563814065818
0.2281918004390985
0.2697347687010419
0.3362781798929442
0.5298293617777683
0.5310527982309206
0.7237937576355621
0.911766835391944
1.1012058189245828
1.2886222487037768
1.3680571171407179
1.4375607229813399
1.4963721293821473
1.5976688548473943
1.620862272453926
1.7749694484697613
1.9069479902084454
1.9382973683224147
2.0139377773866256
2.0418903139673756
2.180879909887874
2.3419254641826166
2.342930499381107
2.4475575305387736
2.596354427786237
2.6247589684294224
2.721104628744542
2.830015590523277
2.9454356427981323
2.986418351949845
3.111091114076178
3.1480325321317677
3.1501694143282135
3.1823780790025538
3.2179890483299887
3.326068461286748
3.520835263270488
3.5699205739867472
3.6488247552455917
3.6923451802271288
3.7787465562058364
3.8253777151561033
4.003359465487179
4.011024844151034
4.129500692923622
4.260535413549505
4.2845032220103425
4.414998563389533
4.611863123523392
0 3 3 0.0000000.0
0.146175638140658180.2281918004390985
0.26973476870104190.3362781798929442
0.52982936177776831.1012058189245828
1.28862224870377681.3680571171407179
1.4375607229813399

**Comment by felixit8** [comment]
im not sure why you encounter this problem, as PQ runs sequentially and your comparator should compare the customer number in order already. Sorry i cant be of much help, but do try the aforementioned test case provided, perhaps it can help you solve this issue

**Comment by Q8yi** [comment]
Hello, i think you could check on the queues, it could be possibly, when 18 arrives your queue is still not max hence it waits at selfcheck 3. did u compare against the most updated server queue?

**Comment by jiangen16** [comment]
I was stuck at the same test case too. I realised my mistake was the server used to decrement the queue

My problem was in the nextEvent(), if the usedServer is available and usedServer is a self check server, i decreased currentServer's queue (my wait event takes in an input currentServer), which made sense to me as currentServer is the one which has the queue, not necessarily usedServer when we deal with self checks. However I had the same issue as you for quite a while

I changed from decreasing currentServer's queue to decreasing listOfServers.get(this.server.getServerId() - 1)'s queue, and I passed 5.2. Maybe this is your issue as well

**Comment by aarontxz** [comment]
The event 17 waits at selfcheckout 3 should update the selfcheckout queue immediately, check if you are increasing the time and updating the imlist of servers in the same event. What I did was to have the first wait event immediately returns another wait event with the updated imlist of servers with the same time and then this other wait event can handle the increase in time. Hope this makes sense.

**Comment by NwaterM** [comment]
okay!! i finally found the problem... i had to remove a break from a for loop that updates my self check queues in my serverlist to have the same q.... -.- THANKS FOR ALL THE HELP GUYS! :D
