### ISSUE TITLE
Ex 5 Level 2

### ISSUE THREAD

**Issue by justineeyx** [nus-cs2030/2223-s2#782]
How do i reverse the order of the stream ? currently my code is looking like this
![image](https://user-images.githubusercontent.com/122433748/230568000-31908e04-6e3c-4f8b-90e5-c65f1f4e098e.png)

**Comment by trwstin** [comment]
you have the letters "h", "i".

if you spell "hi" by doing "h" + "i", how would you arrange the concatenation of these two letters to get the reverse which is "ih"
