### ISSUE TITLE
Lab 5.2 Test Case 9_11

### ISSUE THREAD

**Issue by kcslllll** [nus-cs2030/2223-s2#785]
# Summary

hello, i seem to be having an error where my customer should be waiting in the queue but its being served by the self checkout server instead. i think i am already checking for the earliest available time for all the self checkout servers (as seen in the code below). anyone able to help on why im facing this? thanks!

## Screenshots

<img width="524" alt="image" src="https://user-images.githubusercontent.com/122248706/230584234-1cf87e09-fa71-4a75-ae5e-da876f913765.png">
<img width="701" alt="image" src="https://user-images.githubusercontent.com/122248706/230584279-3e471dc1-5081-479c-b098-913dc727f304.png">
<img width="630" alt="image" src="https://user-images.githubusercontent.com/122248706/230584313-deb47530-beb7-42ff-8cd8-8b229f74a902.png">

**Comment by edmundnwl** [comment]
You should check if your wait event timing is correct. customer 13 seems to have a wrong wait event time. customer 13 should have checked if any self-checkouts were available at the time when self-checkout 4 was done serving but it did not. thus, self-check 4 was left available and the next customer to arrive was assigned to it.

**Comment by trwstin** [comment]
you instantantiate nextAvailableTime as 0.0 at the very beginning.

i suspect your if condition (server.nexttimefree() < nextAvailableTime) isn't getting executed, since there isn't gonna be a server with nextAvailableTime < 0.0.

maybe set nextAvailableTime to the nexttimefree() of the first server in the list?

**Comment by Cepheux** [comment]
You should check if the self checkout counters serve each customer immediately once it is done too. Customer 13 should immediately be served if the self checkout counter is done

**Comment by allnotavailable** [comment]
I think that its better to consider if the servers that you are looping through have smaller nextfreetime than the current server in your event. After that you can retrieve that smaller nextfreetime server id from the serverList

**Comment by Bwilldo** [comment]
you might want to check your wait event, under the self check out when returning a new wait event, does it return the earliest self check out end time instead of your current implementation self check out end time :) after solving this, it should be fine!

**Comment by easypzlemonsqueezy** [comment]
as mentioned in #800,  i managed to resolve it by iterating through the self checkouts and finding the self checkout counter with the earliest next available time. you have to change your implementating of wait (and possibly intermediatewait) event(s) to account for the behaviour of self checkout. 

if a customer is waiting at a self checkout and intermediate waits at the same self checkout it may eventually be served at another self checkout

**Comment by tjdbryan** [comment]
Your logic for the loop seems ok, but because you defined nextAvailableTime to be 0.00 at the start, then literally nothing is less than 0.00. Hence, you should re-define it in the for loop to take the nextAvailableTime of the first Server, or take an arbitrarily large value..
