### ISSUE TITLE
Ex 6 Level 4 

### ISSUE THREAD

**Issue by Delocy** [nus-cs2030/2223-s2#786]
Used .thenCompose for the main, could pass the two test cases in CC but when upload got this error. Anyone got any idea what is the issue?
<img width="645" alt="Screenshot 2023-04-07 at 6 25 20 PM" src="https://user-images.githubusercontent.com/94375191/230592988-b3e6b57e-5848-4e2e-89dc-d0afdbb19030.png">

**Comment by jiarui22** [comment]
Did you include the last part of the code sc.close();
        Instant stop = Instant.now();
        System.out.printf("Took %,dms\n", Duration.between(start, stop).toMillis());
in your main?
