### ISSUE TITLE
lab 8 add() method

### ISSUE THREAD

**Issue by gi2328** [nus-cs2030/2223-s2#789]
# Summary

Does anyone know what is wrong? My for loop does not seem to run, or is there another way I could better approach this instead of using a for loop?

## Screenshots

<img width="386" alt="Screenshot 2023-04-07 at 7 30 15 PM" src="https://user-images.githubusercontent.com/113605010/230602021-de8228a7-b839-4432-a46e-b72d3a4b795a.png">

**Comment by clarwen** [comment]
I may be wrong, but the method zero() is a static method and may not be able to assign to Num i? Try Num i = new Num(AbstractNum.zero()) and see if it works

**Comment by notsushiii** [comment]
Hi! I think you can try doing Num i = Num.zero() instead of what you have written (Num i = zero())?
![image](https://user-images.githubusercontent.com/119566170/230604151-84960f6a-be00-460c-8bea-3a9b64a0366b.png)

**Comment by leonardwx** [comment]
try using while loop instead of for loop

**Comment by sushimakerr** [comment]
hi!! using a while loop might be easier, for example outside your loop you create a Num counter that starts from zero, then while counter does not equal to Num other, you .succ() your sum and also .succ() your counter. hope that might help!

**Comment by Xuehann** [comment]
you can add a System.out.println() to test, it could be an infinite loop so it doesn't seem to run
