### ISSUE TITLE
Test case 9_9

### ISSUE THREAD

**Issue by cher212** [nus-cs2030/2223-s2#791]
# Summary
Not sure why the "self-check" disappeared in line 12 and 14, since in line 11 "self-check 1" is printed out fine. Anyone knows whats wrong? :(

## Description:

Clarifications or details with respect to the issue you are facing

## Code Snippets

Attach code snippets (if any)

## Screenshots

Screenshots (if any)
<img width="651" alt="image" src="https://user-images.githubusercontent.com/125173830/230606228-ecf8dcb3-c8b6-4815-aff1-f877792a1b80.png">

**Comment by sushimakerr** [comment]
Customer 3 could be getting served by a human server instead of a self-checkout, maybe check if you have correctly put Customer 3 into the wait queue of self-checkout and not human server?

**Comment by displeasedcat** [comment]
Could it be an issue with your toString() methods?

Your toString() for self check should be "self-check " + self_check_number

**Comment by leonardwx** [comment]
It could be due to the toString method() that is not calling the self check

**Comment by clementlemon02** [comment]
You could be returning a new human server in your serve class

**Comment by user1914** [comment]
maybe your done event is calling the self-check string but your wait event or serve event is not

**Comment by edmundnwl** [comment]
could customer 3 really be served by human server 1?

**Comment by niclee1219** [comment]
i used a getID in selfcheckout and server. this way when u do your tostring, do a getId and it will be different for both selfcheck and server

**Comment by allnotavailable** [comment]
The issue is may probably come from when you update your server you are returning a new Server and not a new selfCheck server. Which result in the selfCheck server attached in your event class is being override by new server that is intended to update your server.
