### ISSUE TITLE
level 3 sub() infinite loop

### ISSUE THREAD

**Issue by veviana** [nus-cs2030/2223-s2#792]
my sub() method seems to be going to infinite loops when i tried the test cases: one.sub(one) and zero.sub(one).  what i did was to take the negate of n and add(this). with this new value, i filtered by AbstractNum.valid, and return a new Num of it. not too sure if it is my add() method that is causing this error but for my add() method, i checked if m and n are valid before adding the value, i tried checking the validity after the operation but there seems to have some error (infinite loops as well) if i do that.

![image](https://user-images.githubusercontent.com/94920324/230607884-a352cc02-9486-4918-ac2e-9b86c25b91ac.png)

**Comment by leonardwx** [comment]
hi i faced the similar issue! what i did was to check for its validity at the add method(), if more than 0, it will return the output else it will be optional.empty()

**Comment by veviana** [comment]
> hi i faced the similar issue! what i did was to check for its validity at the add method(), if more than 0, it will return the output else it will be optional.empty()

does that mean there will be 2 checks? the first is using isValid() on both n and m, and the second is checking of the final added value validity using the predicate valid?

**Comment by leonardwx** [comment]
yes ur right

**Comment by haqanh** [comment]
I think something you can do is to have a validity check in your .of() for your Num. So if you return a negative (invalid) Num, it will just be a Num(Optional.empty) instead

**Comment by veviana** [comment]
thanks guys! managed to solve the issue now after checking the value validity before returning!
