### ISSUE TITLE
Exercise 5 level 1 twin primes 

### ISSUE THREAD

**Issue by ghost1nthemachine** [nus-cs2030/2223-s2#795]
Hmm not sure why my intstream stops at the first two numbers.. Any advice?
![Screenshot 2023-04-07 at 11 24 29 PM](https://user-images.githubusercontent.com/125187978/230634700-cdb7a211-c132-4b5f-baa4-08f8d5bac383.png)

I returned an intstream with range (2,n) after filtering for prime number and the x+-2 

![Screenshot 2023-04-07 at 10 29 10 PM](https://user-images.githubusercontent.com/125187978/230625954-defbb918-be66-4390-b9c4-48a8becb0136.png)

**Comment by normantan1** [comment]
probably made a mistake with one of the alphabet of one of the lambdas u used

**Comment by ghost1nthemachine** [comment]
> probably made a mistake with one of the alphabet of one of the lambdas u used

hm I used x for all the lambdas so not very sure whats wrong

**Comment by calvnleong** [comment]
maybe there was a problem in the isPrime() function?

**Comment by ghost1nthemachine** [comment]
![Screenshot 2023-04-08 at 12 36 38 AM](https://user-images.githubusercontent.com/125187978/230644943-4be04885-9227-4ad0-9f31-24a46f8250ce.png)

my isprime looks ok... is there anything else i might have missed out?

**Comment by sharlynntan** [comment]
maybe for your filter, you can combine the conditions into one filter statement:
filter(x -> isPrime(x) && isPrime(x-2) || isPrime(x) && isPrime(x+2)).

**Comment by edmundnwl** [comment]
I think this has to do with your filters, a twin prime may be a twin prime with a number bigger than it by 2 but not a twin prime with a number smaller than it by 2

**Comment by ghost1nthemachine** [comment]
@sharlynntan @edmundnwl thank you!! that was indeed the issue
