### ISSUE TITLE
I declared s in my if else statements but the error says it is not declared

### ISSUE THREAD

**Issue by calvnleong** [nus-cs2030/2223-s2#80]
# Summary

Description of the question / problem here.
Why is it that my s is said to be not declared despite declaring it in my if else statements. 
## Description:

Clarifications or details with respect to the issue you are facing

## Code Snippets

Attach code snippets (if any)

## Screenshots

<img width="688" alt="image" src="https://user-images.githubusercontent.com/124434962/217171051-2ec4d093-af96-4e92-84e8-7d5ae1269f46.png">

**Comment by ZaresTng** [comment]
You cannot declare inside

**Comment by granolaluvr69** [comment]
Try declaring String s outside the if else statement.

**Comment by e0959170** [comment]
if you declare string s within the if statement, it only exists inside it so when you try to return s outside the if statement, it technically doesn’t exist..

**Comment by hhuilingg** [comment]
yes, declare it outside so that it is a “global” variable for you to return
