### ISSUE TITLE
test case 9_11

### ISSUE THREAD

**Issue by haoyanggggg** [nus-cs2030/2223-s2#803]
cant seem to fix 9_11 

Description of the question / problem here.

hi i cant identify which part of my current code is wrong based on the test output. a really out of nowhere error to me and the fact that out of 70 lines only one line output doesn't match really puzzles me. also can someone give me some insights whether the wrong self checkout counter is related to the waiting time? thanks for any help in adv!

Clarifications or details with respect to the issue you are facing

## Code Snippets

Attach code snippets (if any)

Screenshots (if any)

<img width="662" alt="image" src="https://user-images.githubusercontent.com/124251722/230658612-d6cbedf9-81e9-48af-9b31-24931d28af90.png">

**Comment by Chuacx13** [comment]
Every customer is suppose to initially wait at the first self-check out counter. Only when your intermediate or wait even is called, then you look for the self chjeck out counter with the shorter free time. So perhaps something to do with ur Arrive Event calling the wrong self-checkout ciounter to wait at?

**Comment by haoyanggggg** [comment]
update: i solved it. i accidentally added customer twice to waiting queue, resulting in the next customer seeing a full queue instead of a yet to be full queue. thanku anw!
