### ISSUE TITLE
Perplexing Time Limit Exceeded Issue

### ISSUE THREAD

**Issue by bevteo** [nus-cs2030/2223-s2#807]
Hi, just wanted to ask if anyone else is also facing this puzzling issue. I've been stuck on time limit exceeded for test case 15 for some time now. I've tried copying the test case, experimenting with having 0 HumanServers/ 0 queue/ 0 SelfServers but I always manage to get an output. For context, my Simulator class has a while loop that processes the PQ and only breaks out of the loop when the PQ is empty and the only way for me to print out the final statistics is if it breaks out of this while loop. Additionally, my friend has tried testing the test case on her code that has cleared lab 5.2 and we yield the same output. Could there be other issues that are causing an infinite loop? Or is efficiency of my code something I need to take note of too? Any help would be greatly appreciated.

<img width="360" alt="image" src="https://user-images.githubusercontent.com/122275359/230701155-758bbce1-fb8e-4cfc-aa13-b5e0dadc7815.png">

**Comment by bevteo** [comment]
> i have been given this code by my TA when i was stuck at testcase 11 for TLE, perhaps you could try it out and print in different classes to see wheres the problem. For TLE cases, its probably due to infinite loop and one tip for checking infinite would be to remove the testcases until you dont have an infinite loop to see where the issue starts.
> 
> I think it is more of an implementation / code logic problem where you pass or return wrong things etc. Many of the comments on similar problems mentioned that it would be in your Wait / Check event but mine was actually in my Arrive Event for selfcheckout counters -- you'll really have to check your serverList after every event to see if it changes correctly.
> 
> in your Main.java
> 
> Add this constant,
> 
> private static final Random RNG_SERVE = new Random(2L);
> 
> Then change your serviceTime to: Supplier serviceTime = () -> -Math.log(RNG_SERVE.nextDouble());
> 
> 2 3 2 0.000000 0.0 0.29235127628131635 0.456383600878197 0.5394695374020838 0.6725563597858883 1.0596587235555366 1.062105596461841 1.4475875152711242 1.823533670783888 2.2024116378491656 2.5772444974075537 2.7361142342814357 2.8751214459626797 2.9927442587642945 3.1953377096947886 3.241724544907852 3.5499388969395227 3.813895980416891 3.8765947366448295 4.027875554773251 4.083780627934751 4.361759819775748 4.683850928365233 4.685860998762214 4.895115061077547 5.192708855572474 5.249517936858845 5.442209257489084 5.660031181046554 5.890871285596265 5.97283670389969 6.222182228152356 6.296065064263535 6.300338828656427 6.3647561580051075 6.435978096659977 6.652136922573496 7.041670526540976 7.1398411479734945 7.297649510491183

Thank you so much! I will give this a go :)

**Comment by ahndrayo00** [comment]
Most Time Limit issues are attributed to infinite loops, but mine wasn't.

I had a Time Limit Exceeded issue, where my customers who were queuing for SelfCheckOut counters are only served by the FIRST selfCheckout counter. I.e if there are 3 selfCheck counters, even if the other 2 are free, the customers still wait until the first SelfCheck becomes free then they get served.

So while I wasn't getting an infinite loop, this took too long (the logic was wrong anyway), and it exceeded the time limit.

Try modifying 4.in to add customers arriving while all servers are busy serving to force them to queue and see how they get served. If you need me to elaborate on what I mean here, just lemme know! I can send my modified test case as well

All the best!!

**Comment by niclee1219** [comment]
it could be an issue with an iterimwait/buffer as well. make sure that you are checking for the earliest selfcheckout to serve and update from there.

i tried using chatpgt to help me debug as well, so do give that a go as well!

**Comment by bevteo** [comment]
Update: I manage to figure out the issue just in time :) Turns out the way I was updating the timestamp for my events was an issue. I was passing in the waitTime to my Serve event and I guess maybe somewhere the timestamps were off. Thanks for all the help everyone! Really appreciate it :)
