### ISSUE TITLE
Using Limit for Iteration in Lab 8

### ISSUE THREAD

**Issue by UmpoDumpo** [nus-cs2030/2223-s2#809]
# Description

Hi i used the limit call for the iterate in streams. However, realised only later on we are not suppose to use constants. Did anyone use limit as well? How should modify my method such that I wont be using a constant.

## Topic:

Specific Topics this question is related to (If Any)

## Screenshots

![image](https://user-images.githubusercontent.com/115340765/230703277-5cbe71ed-f725-4de0-ba98-d957d21515d4.png)

**Comment by trickypepe** [comment]
You can use the iterate which takes in a Predicate in addition to the seed and UnaryOperator to avoid using limit().  Then define the Predicate appropriately.

**Comment by ryantangmj** [comment]
since your constant is a zero you can just use Num.zero()

**Comment by aeraeroaer** [comment]
adding on to @ryantangmj , an alternative approach to do this is by using a while loop with a num counter that starts with Num.zero(), and succ() it until you have added 1 to your num by other times. Hope this helps!

**Comment by UmpoDumpo** [comment]
thanks yall!
