### ISSUE TITLE
Lab8 Level3 mul() testcase 3.1

### ISSUE THREAD

**Issue by yueyaozzz** [nus-cs2030/2223-s2#812]
# Summary

Description of the question / problem here.

## Description:

Does this mean my mul() is too inefficient? And why is there a cannot find symbol error?

## Code Snippets

if (!this.isValid() || !num.isValid()) {
            return new Num();
        } else if (this.equals(Num.zero()) || num.equals(Num.zero())) {
            return Num.zero();
        } else {
            Num n1 = Num.one();
            Num n2 = this;
            while (!n1.equals(num)) {
                n2 = n2.add(this);
                n1 = n1.succ();
            }
            return n2;
        }

## Screenshots

<img width="998" alt="Screenshot 2023-04-08 at 1 40 37 PM" src="https://user-images.githubusercontent.com/122427063/230705418-afdeb46a-2bb9-44a8-905c-bcb0cb6f33cf.png">

**Comment by kkaiyu** [comment]
hi you may refer to discussion thread #760 for better clarification!

**Comment by UmpoDumpo** [comment]
hmm not sure what your implementation is but you should consider using functional programming methods like .map(), Streams.iterate(), etc.

**Comment by rachaelwidjaja** [comment]
> hi you may refer to discussion thread #760 for better clarification!

Hii, i tried implementing the solution from that thread but am still facing the same issue as the one posted. Did u manage to solve it using while loop?

**Comment by kkaiyu** [comment]
hi, yes i used a while loop to solve it. i hv 3 conditions:

1. if either one of my Num is invalid, i return an Optional empty
2. if either one of my Num is 0, i return a Num.zero()
3. else run my while loop, which is similar to what thread #760 has discussed

hope this helps!

**Comment by yueyaozzz** [comment]
> hi, yes i used a while loop to solve it. i hv 3 conditions:
> 
> 1. if either one of my Num is invalid, i return an Optional empty
> 2. if either one of my Num is 0, i return a Num.zero()
> 3. else run my while loop, which is similar to what thread [Lab 8 making loops more efficient #760](https://github.com/nus-cs2030/2223-s2/issues/760) has discussed
> 
> hope this helps!


My implementation is the exactly same as yours and I changed to use map in the while loop but it still doesn't work ;)

**Comment by kkaiyu** [comment]
> > hi, yes i used a while loop to solve it. i hv 3 conditions:
> > 
> > 1. if either one of my Num is invalid, i return an Optional empty
> > 2. if either one of my Num is 0, i return a Num.zero()
> > 3. else run my while loop, which is similar to what thread [Lab 8 making loops more efficient #760](https://github.com/nus-cs2030/2223-s2/issues/760) has discussed
> > 
> > hope this helps!
> 
> My implementation is the exactly same as yours and I changed to use map in the while loop but it still doesn't work ;)

hmm maybe the problem lies in your add method?

**Comment by yueyaozzz** [comment]
> hmm maybe the problem lies in your add method?

The implementation is like this. I tried to let it return this or otherNum instead of returning Num(Optional.empty) as mentioned in the other thread, however it doesn't work.
if (!this.isValid() || !num.isValid()) {
            return new Num(Optional.empty());
        }
        Num n1 = Num.zero();
        Num n2 = num;
        while (!n1.equals(this)) {
            n1 = n1.succ();
            n2 = n2.succ();
        }
        return n2;

**Comment by kkaiyu** [comment]
ohh instead of checking if both Num is valid in your if statement, you should have a nested if-else to check the validity of each Num one after another.

if (this.isValid()) {
    if (!n2.isValid()) {return Optional Empty}
    else {your while loop}
} else return Optional Empty

**Comment by yueyaozzz** [comment]
> ohh instead of checking if both Num is valid in your if statement, you should have a nested if-else to check the validity of each Num one after another.
> 
> if (this.isValid()) { if (!num.isValid()) {return Optional Empty} else {your while loop} } else return Optional Empty

do you mean something like this? It still doesn't work for me... or am i doing it wrongly
if (this.isValid()) {
            if (!num.isValid()) {
                return new Num(Optional.empty());
            } else {
                Num n1 = Num.zero();
                Num n2 = num;
                while (!n1.equals(this)) {
                    n1 = n1.succ();
                    n2 = n2.succ();
                }
                return n2;
            }
        } else {
            return new Num(Optional.empty());
        }

**Comment by ahndrayo00** [comment]
Hi!! Multiplication is just addition n number of times. So 3 * 2 is just adding the number 3 to 0, a total of 2 times.

With that logic in mind, if you have m * n,

you can create a for loop that iterates n times, and add m to 0 in each iteration.

Just remember to take into account the edge case where if either n or m is 0, its automatically 0.

Normally, a negative number will result in a different kind of addition as well, but since the context of the question is that there are no negative numbers in Num.java, we don't have to worry about this.

Hope this helps! All the best!!

**Comment by yueyaozzz** [comment]
I solved this issue by rewriting all my three methods (mul add and sub) and changing the ordering for the if-else conditions. tbh I still don't understand how this works and why. Anyway the new logic is  if (two Num isValid) { while loop } else if {!this.isValid return other} else{return this}
