### ISSUE TITLE
Lab 8 instance properties / constants detected error

### ISSUE THREAD

**Issue by Leeeef552** [nus-cs2030/2223-s2#815]
![image](https://user-images.githubusercontent.com/104271512/230711297-fab11a98-9125-47a2-93d5-3d85c26753fa.png)

Anyone else faced this issue?

**Comment by UmpoDumpo** [comment]
Hi! I got this issue as well. Make sure your code doesn't not have constants/magic numbers. Meaning to say you can't put a 0 or a 1 in your methods, instead you need to use the constants already defined in AbstractNum.

For me my constant was in Streams.iterate().limit(). so i used the iterate with three arguments instead and it solved the issue.

**Comment by ayevxn** [comment]
I got this issue when I tried to instantiate a private static final constant attribute; had to workaround by using other methods i.e. zero() and succ()

**Comment by Leeeef552** [comment]
ok thank i understand
