### ISSUE TITLE
Ex 5 How to map the given list

### ISSUE THREAD

**Issue by Huanqing-Mao** [nus-cs2030/2223-s2#818]
Hi for the generateRule():
I have converted the given list into a stream, and I used map to make changes to the stream. However, if I make all the "1"s to be "0", then when it continues to check neighbouring elements, I cannot make the "0"s that qualifies to be alive in the next generation to be "1", because the "1"s are already 0. 

Can I ask whether there are any ways to resolve this issue?

Thanks !

**Comment by ianwonghanli** [comment]
You should not convert the list into a stream. Rather, you should create a new IntStream containing all the index of the list. Then, map the IntStream based on the rules, and then box the mapped IntStream and convert the Stream<Integer> to a new List<Integer>. hope this helps.

**Comment by Huanqing-Mao** [comment]
got it! Thanks :)

**Comment by geraldckj** [comment]
If I were to test my generateRule() method in jshell, how do I go about doing it? I tried using apply() and passing a list into generateRule() but it doesn't work

**Comment by Huanqing-Mao** [comment]
Hi you create a unaryOperator<List<Integer>> object by calling Main.generateRule(), then you use apply() on a list. It should be able to work?

What's the error message?
