### ISSUE TITLE
Failing Lab 2 Test case 6 on CodeCrunch but passing on own terminal.

### ISSUE THREAD

**Issue by edmundnwl** [nus-cs2030/2223-s2#82]
## Description:

ive saved and reuploaded a few times also but its still the same.
any ideas? thanks

## Screenshots
<img width="539" alt="Screenshot 2023-02-07 at 4 17 11 PM" src="https://user-images.githubusercontent.com/94234454/217189477-649ea79c-365e-4fd8-9105-1f1fbf918b14.png">

<img width="255" alt="Screenshot 2023-02-07 at 4 17 42 PM" src="https://user-images.githubusercontent.com/94234454/217189590-4b21ffe8-8471-456a-a0c8-e1aadec85f9f.png">

**Comment by 0liverkong** [comment]
your code doesnt free up the servers that finish AT or before time x, before processing the arrivals that occur at time x.

**Comment by 0liverkong** [comment]
is your threshhold 1E-15?

**Comment by trwstin** [comment]
> is your threshhold 1E-15?

Is there a need for threshold? I didnt use and passed all leh, can explain more

**Comment by ZaresTng** [comment]
Could you send more details of ur code thanks

**Comment by 0liverkong** [comment]
> > is your threshhold 1E-15?
> 
> Is there a need for threshold? I didnt use and passed all leh, can explain more

i use it to check for events that happen in the same time in PQ (like a server freeing up followed by an arrival). i know there might be workarounds like adding a small increment of time (that doesnt show as it gets rounded off) to the arrival so it gets processed later, but i rather not assume that the events will be printed out to 3dp.

to deal with events that occur during exactly the same time i do use event typeids but i dont exactly like it either.

**Comment by trwstin** [comment]
> i use it to check for events that happen in the same time in PQ (like a server freeing up followed by an arrival). i know there might be workarounds like adding a small increment of time (that doesnt show as it gets rounded off) to the arrival so it gets processed later, but i rather not assume that the events will be printed out to 3dp.
> 
> to deal with events that occur during exactly the same time i do use event typeids but i dont exactly like it either.

I see. So we add it to allow processing of certain events that occur at the same time, slightly later? And the point of this is to have a better 'flow' of events?

**Comment by 0liverkong** [comment]
> I see. So we add it to allow processing of certain events that occur at the same time, slightly later? And the point of this is to have a better 'flow' of events?
 
for deciding which events which occur at the same time get process first yes i think that may be viable but im not too sure if that'll work for future labs. would just do some other comparison methods in my comparator class.

think i used a threshold because doubles are wonky when it comes to comparing their equality. so in my code if two doubles are close enough (difference less than threshold) then they're equal.

**Comment by danqiye1** [comment]
It's weird that your server no. is incrementing on codecrunch when the input specifies that there is only one server. One possible reason why your code on your machine works differently than that uploaded to codecrunch is if you have modified the given classes (such as `ImList.java`, `PQ.java`) in any way to make them work locally. On codecrunch we will not use these modified files that you uploaded.

**Comment by trwstin** [comment]
@edmundnwl 
How are you managing your servers during the various events?
I think there might be a problem with your method of updating/getting the next server (i.e. the 'queue' within your serverlist).

**Comment by edmundnwl** [comment]
> 

oh you are right, the problem arose from me adding the newly available servers to the end of the queue. thanks, I solved it
