### ISSUE TITLE
Lab 5.2 test case 9_11

### ISSUE THREAD

**Issue by secretApple** [nus-cs2030/2223-s2#820]
Does anyone know what may have caused this error? Not sure why my self check out 3 is serving multiple customers.
![image](https://user-images.githubusercontent.com/126102015/230720803-e39a524b-e7b4-47a4-ba54-7e815afdd6fb.png)

**Comment by mkim123** [comment]
ensure that you iterate through the list again if your customer continues to wait for self check 3, to assign the customer to self check 4(the one with the lower/lowest donetime)

**Comment by slimzaza** [comment]
Whenever you are executing your wait event, make sure to choose the self check counter with the earliest finish time and assign to that customer waiting in line. This applies to wait events that return another wait or serve event

**Comment by tjdbryan** [comment]
First you have to change your logic to ensure that the customer is served by the SelfCheck with the earliest finish time. You might also want to check your logic on assigning a customer to SelfCheck, because your customers seem to be jumping between SelfChecks.

**Comment by Huanqing-Mao** [comment]
You can create a list out of the self-checks, and then write a comparator to sort out the server that finishes the earliest, then assign your customer to it.

**Comment by secretApple** [comment]
Thanks everyone for the help!
