### ISSUE TITLE
PQ polling issue

### ISSUE THREAD

**Issue by YanQin-Liu** [nus-cs2030/2223-s2#822]
I realised that when polling for event in PQ, the .poll() method can poll the wrong event. 

<img width="1468" alt="Screenshot 2023-04-08 at 8 57 06 PM" src="https://user-images.githubusercontent.com/123805062/230722447-1e0c02ca-cd81-4da9-8d5a-5e49bd768677.png">

As seen from above, the poll method incorrectly polled the event with the higher server number (8 instead of 6)

Example of correct polling (same program):

<img width="1492" alt="Screenshot 2023-04-08 at 8 57 26 PM" src="https://user-images.githubusercontent.com/123805062/230722481-a33e9cd1-2be0-40a2-beee-7aaaa734d8d2.png">

As seen, the poll method correctly polled 11 instead of 13 or 14

Does anyone know how to resolve this issue?

Edit:

There is apparently a 1 d.p difference in eventTime values so PQ is polling the wrong event 

<img width="1461" alt="Screenshot 2023-04-08 at 9 40 06 PM" src="https://user-images.githubusercontent.com/123805062/230724446-bea13c3c-212a-433d-a628-eb0b24114afd.png">

I have changed all my primitive double to object Double and it still does not resolve the issue

Comparator is here: 
<img width="712" alt="Screenshot 2023-04-08 at 9 41 26 PM" src="https://user-images.githubusercontent.com/123805062/230724460-c9a0c61d-8bc5-490f-af81-9204e413c20c.png">

**Comment by liang-zhengxin** [comment]
It could be due to how you compare the events. See if you can make use of Double's compare method. 

https://docs.oracle.com/javase/8/docs/api/java/lang/Double.html#compare-double-double-

**Comment by YanQin-Liu** [comment]
I solved the issue by rounding all the eventTime values to 12 digits instead of 14/15 digits. Hope I dont get marked down for this.
<img width="698" alt="Screenshot 2023-04-08 at 10 16 16 PM" src="https://user-images.githubusercontent.com/123805062/230725993-0c62639f-abec-422d-aac7-d6788554da73.png">
