### ISSUE TITLE
Lab 5.2 index out of bound 

### ISSUE THREAD

**Issue by ugchongg** [nus-cs2030/2223-s2#824]
# Summary

Hi I've been stuck on test case 9_11 for quite some time now. I am getting this index error but I'm not quite sure why as I am trying to get my customer from my queueEvent (which would only be returned if there's a queue) . I'm also only updating the queue whenever I serve from queue or return a waitEvent so the queuelist shld not be emptied prior to my .get() . Anyone perhaps faced the same error and is able to advice me on what's wrong? any help would be appreciated thank you!

## Description:

Clarifications or details with respect to the issue you are facing

## Code Snippets
![image](https://user-images.githubusercontent.com/121675791/230729593-a46ca195-0a5e-41a7-a137-ba7d90113019.png)

Attach code snippets (if any)

## Screenshots

![image](https://user-images.githubusercontent.com/121675791/230729554-ed1bc3f9-3d25-4e08-9410-c86768a1d2bf.png)

**Comment by sp4ce-cowboy** [comment]
You can try referring to #767, it was the same test case and same issue.

**Comment by ugchongg** [comment]
I see thankyouu!
