### ISSUE TITLE
Ex 6 Main java

### ISSUE THREAD

**Issue by clarwen** [nus-cs2030/2223-s2#826]
Hello

After watching the lecture, I still do not know how to modify the Main.java to not include multiple join()

Any hints would be very much appreciated

**Comment by Yihao2001** [comment]
rather than mapping it to completable future of busroute, you might want to map it one step further to strings instead so that you will just have a list of completable future of strings

**Comment by Delocy** [comment]
you can try using thenCompose()

**Comment by granolaluvr69** [comment]
Here's what I did:
1. Streamify the original result
2. Using the collect method, (you can look at the findbusservicesbetween() method in bussg for an example) collect them all into a list of completablefuture<string>  using thencompose

3. Initialise  a new completablefuture<string> which is empty (this is gonna be concatenated with every element of the list in 2)

4. Iterate through the list in 2, and using thencombine to combine every element in 2 with the completablefuture you initialised in 3

(you can refer to the description method in busroutes for an example of how to apply steps 3 and 4.)

5. This is the part where the magic happens. Just call join once and everything will come out.

6. Don't forget the last line where you print the timing.

**Comment by clarwen** [comment]
thanks all, map it from a CompletableFuture<BusRoutes> to a String and print out forEach value of String
