### ISSUE TITLE
Ungraded Exercise 3 Level 1

### ISSUE THREAD

**Issue by koiljat** [nus-cs2030/2223-s2#827]
# Summary
Anyone faced similar issue or know what went wrong here? My code was able to work on jshell when testing.

## Screenshots (if any): 
![image](https://user-images.githubusercontent.com/124496128/230736064-832ab4e1-c842-44d4-946c-8edb55777a90.png)

**Comment by NeoHW** [comment]
hi may i know how did u solve it
