### ISSUE TITLE
Lab 5.2 Failing Test Case 9

### ISSUE THREAD

**Issue by rshalinisai** [nus-cs2030/2223-s2#828]
![image](https://user-images.githubusercontent.com/122519417/230739811-8f5110fb-f5ac-4942-8d40-8c52d6c90027.png)

**Comment by cinobunzz** [comment]
i think the issue lies in that you’re not implementing a consolidated queue for your self check out counters, rather it’s operating similarly to the human servers where there’s a queue for each of the counters 

i didn’t implement my code in this manner but i think many others did, you can try checking out the other issues for inspiration 
rather, i made all customers queue in the queue of the first check out counter. in the wait event, i iterated through all self check out counters to see if any are available at the current time, if they are, a serve event is returned. if none are available, the customer continues to queue at the consolidated queue 

hope this helps!

**Comment by wmingchuan** [comment]
there should only be 1 self check out queue

**Comment by tjdbryan** [comment]
A quick workaround if you don't want to implement another queue for SelfCheck is to make all the SelfCheck queues the same. If your design involves using an ImList of Customers, then just make sure the Customer is added to every single SelfCheck queue to wait. If your design involves using integers to track the queue position, then you just need to increment the currQueueLength by one across all SelfChecks.

**Comment by McFishMealUpsize** [comment]
There are a number of ways to implement the consolidated queue. From your code it seems that you did not implement one consolidated queue for the selfcheckouts. Personally, I created a SelfCheckOutManager class which contained an ImList of Customers (the consolidated queue) and a ImList of SelfCheckOut Counters.

**Comment by ugchongg** [comment]
I only had one self checkout queue too! but I think if you want to keep your implementation of all self checkout queue you can as the rest have mentioned update all the checkout queues whenever you add/remove from counter queues. 

I also implemented a comparator to compare the available time of my counters to make sure my customer is serve by the earliest available counter. hope this helps!

**Comment by rshalinisai** [comment]
right now my implementation is:
- each self checkout has 1 queue 
- i only add n remove from the queue of the first self checkout and the rest of the queues are dummy queues
- when executing ServeEvent, I check which self checkout has the fastest next availability and the customer will be served by that chosen self checkout

**Comment by tjdbryan** [comment]
Hmm your implementation should not be an issue, but are you getting the most updated server information from serverList directly? Or are you using some Server object that is passed into your Events/methods that might not be the most up to date?

**Comment by ahndrayo00** [comment]
You're not getting the queue of the correct selfCheck.

For me, what I did when trying to find a server with an available queue is that I iterate from server 0 (this is likely to be HumanServer) to n. Only if the queue is less than qMax, I return the index of the server (regardless of whether its a HumanServer or SelfCheck).

Now the queues of all my SelfChecks are equally long (I update all of these queues at the same time). Hence, if the first SelfCheck has too long of a queue, iterating through all the SelfChecks will also give the same result. This way, you'll never encounter the issue you are facing now.

Hope this helps. All the best!!

**Comment by Yihao2001** [comment]
> right now my implementation is:
> 
> * each self checkout has 1 queue
> * i only add n remove from the queue of the first self checkout and the rest of the queues are dummy queues
> * when executing ServeEvent, I check which self checkout has the fastest next availability and the customer will be served by that chosen self checkout

your last part of serveevent does not seem to be done properly since it is joining the queue of self check 2 instead of self check 1

**Comment by yinshuennn** [comment]
what i did was other than my first selfcheck having a qmax, I set the qmax of all subsequent selfchecks to be 0, so that when I iterate through my serverlist, the customer can only queue at the first selfcheckout

**Comment by leonardwx** [comment]
i think the issue is not letting the customers wait at the 1st self check. rmb that regardless of what the customer should always wait at the 1st self check which maybe served by other self check eventually

**Comment by rshalinisai** [comment]
i realised my mistake was in ServeEvent where I made a careless mistake which resulted in my ImList<Server> servers not being updated properly!
