### ISSUE TITLE
Ex5 Missing a Javadoc comment. [MissingJavadocMethod]

### ISSUE THREAD

**Issue by Ma-Xizi** [nus-cs2030/2223-s2#831]
Good morning everyone! I have been encountering this checkstyle issue when submitting my Main class that mandates every method to have a Javadoc comment. I have never encountered such issue for mains in other labs or exercises. Is it because I accidentally put public static for the methods?

**Comment by Yihao2001** [comment]
do not make the class a public class

**Comment by Ma-Xizi** [comment]
Thank you!
