### ISSUE TITLE
Anyone knows how to access the java docs using the school lab computer during PA?

### ISSUE THREAD

**Issue by Delocy** [nus-cs2030/2223-s2#832]

**Comment by granolaluvr69** [comment]
There are shortcuts to the javadoc HTML for JDK 17 on the home screen on the home screen of the desktops in school.

**Comment by jon3r4de** [comment]
On the home screen my guy, just click on it an it should open up on the browser

**Comment by territxl** [comment]
On the desktop home screen, there should be microsoft edge icon that says jdk-17... That will direct you to the webpage :)

**Comment by aowz** [comment]
they saved a shortcut on the home screen, should open up a browser to show you the documentation on Microsoft edge

**Comment by fisker22** [comment]
if i rmber correctly, at the desktop screen there is a icon "jdk-17" , click it and youll get it

**Comment by vivyanliew** [comment]
ask ur ta loll
