### ISSUE TITLE
Async Variants of Callback Methods

### ISSUE THREAD

**Issue by ongjunfeng17** [nus-cs2030/2223-s2#835]
Hi, sorry for asking this question 1 week late.

Is anyone able to explain the difference between runAsync vs supplyAsync?

Also, is can I view thenRun/thenRunAsync as thenApply/thenApplyAsync? If so, again, what are the differences between thenRun/thenRunAsync and thenApply/thenApplyAsync?

<img width="314" alt="Screenshot 2023-04-09 at 3 40 50 PM" src="https://user-images.githubusercontent.com/120620166/230760532-2fd06335-aaa6-406b-bc06-480671311fe9.png">

TIA!

**Comment by granolaluvr69** [comment]
runAsync takes in a runnable argument, whereas supplyAsync takes in a supplier. A supplier has a return type, whereas a runnable does not.

**Comment by ongjunfeng17** [comment]
> runAsync takes in a runnable argument, whereas supplyAsync takes in a supplier. A supplier has a return type, whereas a runnable does not.

ahhh understands, tysm!
