### ISSUE TITLE
Test CAse 3 lab 8

### ISSUE THREAD

**Issue by AmanDesai34** [nus-cs2030/2223-s2#836]
# Summary

Description of the question / problem here.

## Description:

Can anyone help me solve this pls

Clarifications or details with respect to the issue you are facing

## Code Snippets
<img width="480" alt="Screenshot 2023-04-09 at 3 47 01 PM" src="https://user-images.githubusercontent.com/124550223/230760769-f4d73586-d8d3-4145-ab5b-30a50d4f2d68.png">

Attach code snippets (if any)

## Screenshots
<img width="311" alt="Screenshot 2023-04-09 at 3 38 19 PM" src="https://user-images.githubusercontent.com/124550223/230760757-e7a6e4ba-dac4-42a9-b3e9-f53a50632c08.png">

Screenshots (if any)

**Comment by AmanDesai34** [comment]
It should be number.getterOpt()......

**Comment by cocopear** [comment]
i think the issue may be that when you add Num result (which is now negative) and the Num curr, your add method may check whether the two Num inputs are valid - and since result is negative, it is invalid, and it would cause the output to be NaN.

**Comment by territxl** [comment]
I think you don't necessarily have to define a get opt method since the optional is protected final :)

**Comment by youthfrost** [comment]
u might wan to check your add method, seems like u checked "this" is Valid, that's why your results become invalid

**Comment by AmanDesai34** [comment]
Thanks guys, it worked!!
