### ISSUE TITLE
how to add check style onto vim? 

### ISSUE THREAD

**Issue by sporobolous** [nus-cs2030/2223-s2#84]
# Summary

Description of the question / problem here.

## Description:

Clarifications or details with respect to the issue you are facing

## Code Snippets

Attach code snippets (if any)

## Screenshots

Screenshots (if any)

**Comment by kyledilao777** [comment]
https://github.com/nus-cs2030/2223-s2/wiki/Setting-Up-CheckStyle

**Comment by EvanCh08** [comment]
Setting up checkstyle can be found through the GitHub link in canvas. Be sure to carefully follow the instructions so that you will not miss anything.

**Comment by sporobolous** [comment]
hi yes I finally got the check style! it was very confusing thanks for the help!
