### ISSUE TITLE
Lab 8 level 5 add method

### ISSUE THREAD

**Issue by joshlimwe** [nus-cs2030/2223-s2#840]
# Summary

## Description:

Hello, when i run my current code for add it returns me 9 : 8 instead for this test case 

jshell> Fraction.of(1, 2).add(Fraction.of(1, 4))
$.. ==> 6 : 8

Is it a problem with my implementation, because to me the math seems correct, thank you!
## Code Snippets

<img width="344" alt="image" src="https://user-images.githubusercontent.com/125873745/230766307-70ff74d2-9005-4e20-9bd9-a5f043deeef5.png">

## Screenshots

Screenshots (if any)

**Comment by Cfyjdfk** [comment]
I would suggest you break your working down into more variables (numerator and denominator) first to see debug easily.

**Comment by emilythx** [comment]
Hi! You may consider checking your Num's add method instead

**Comment by gene2345** [comment]
hello joshlim, i wld suggest breaking your code into smaller chunks so that it is easier to debug

**Comment by territxl** [comment]
I think as mentioned above, consider simplifying your method instead of returning in a single line. I would also recommend checking the methods you have defined in Num class.

**Comment by NwaterM** [comment]
hello joshlimwe i have tried to test ur code for this mtd with my own and it works fine,, i believe it must be because of other methods involved!

**Comment by easypzlemonsqueezy** [comment]
it definitely helps if you break your code down to multiple lines and you can debug from there

**Comment by 12thfret** [comment]
I would suggest not chaining too many optional methods. For instance i broke mine down into Top left and Top right and eventually added the two Optional<Num> to form newNumerator. Minimising the length of your optional method chain might help you see the code clearer. Hope this helps 👍

**Comment by Maxxtucker** [comment]
I also encountered a similar problem before. I think you can check the brackets.
