### ISSUE TITLE
Lab 5.2 Issue

### ISSUE THREAD

**Issue by ctyh4** [nus-cs2030/2223-s2#841]
My SelfCheckout class extends from server and my serverList in simulator consists of the respective self checkout counters. However, this means my SelfCheckout counters do not share the same queue. Instead, each selfCheckout counter has its own queue. How do I fix this?

<img width="633" alt="Screenshot 2023-04-09 at 7 21 06 PM" src="https://user-images.githubusercontent.com/130287496/230770165-11117d11-de60-4334-9b87-d4949c358e22.png">

**Comment by territxl** [comment]
I think you might need to ensure that only a SINGLE self checkout queue is used as the condition to check if another customer can still wait. Considering checking how you will only make reference to the k+1 self checkout queue in your case and the remaining self checkout queues are like a "dummy". Hope this helps!

**Comment by kyledilao777** [comment]
check whether u have prevented ur subsequent self checkouts from taking in any customer!

**Comment by koojaylynn** [comment]
hello! 
in my arrive class, when checking whether the customer should wait or leave, i checked through only (k+1) queues if there are self check out servers. so customers shldnt be able to queue at the other self check out servers!

**Comment by jiangen16** [comment]
in my arrive class, when i check for a queue for the customer to queue in, i only check till the k+1th server. That way, the customer will never wait in a queue that is beyond the 1st self check out

**Comment by sushimakerr** [comment]
hi! maybe check if you have correctly looped through all self-checkout counters' wait queue when you are updating them in your arrive class each time a customer joins the self-checkout queue (since they all must have the same queue)

**Comment by edmundnwl** [comment]
you could have it such that if it is a self-checkout, whenever a customer is being added or removed from the queue, loop through the self-checkouts to update each of their queues

**Comment by aldensiol** [comment]
Personally, what i did was that i defined an abstract method called isSCO() within my parent Server class that returns a boolean depending on the runtime -> Human returns False and SCO returns True

Afterwards, I define a method called getSCOIndex(serverList), which returns an ImList of ALL the SCO servers within a serverList.
Then, I have another method called updateSCO(serverList) which loops through the indexes generated above^^, and updates ALL the SCOs to reflect an addition in the queue whenever a customer Waits

**Comment by aeraeroaer** [comment]
For me, I just stored both the server and SelfCheckoutCounters into a new class called CombinedQueue, which has an imlist of Server and another one of SelfCheckoutCounter, and for the selfCheckoutCounter queue, I just stored it in the first counter of the list, rest is just empty. Hope this helps!
