### ISSUE TITLE
Lab 8 Testcase 3

### ISSUE THREAD

**Issue by sp4ce-cowboy** [nus-cs2030/2223-s2#842]
![image](https://user-images.githubusercontent.com/19762596/230772270-8f3fea60-02fb-4c38-a927-99a9ef23205d.png)

I keep getting this error, anyone have any idea why? All my Num methods check for validity before doing any calculations so I'm not sure why.

**Comment by pluciuspua** [comment]
Hi, encountered a similar error when doing this as well and for myself, the error lied in the constructor of Num. I solved it by manipulating the opt and only calling the Num constuctor when returning the Num instead of applying the function on the num multiple times.

**Comment by easypzlemonsqueezy** [comment]
you need to ensure that your final integer/optional is valid using valid or isvalid() before wrapping it in num, you might need to check the validity of the output before returning it

**Comment by sp4ce-cowboy** [comment]
Thanks guys @pluciuspua @easypzlemonsqueezy
