### ISSUE TITLE
Ex 6, Missing Leading 0s.

### ISSUE THREAD

**Issue by LYEDominic** [nus-cs2030/2223-s2#847]
Hi, I was just wondering if anyone else faced this situation and how did you go about fixing it. Essentially:

![image](https://user-images.githubusercontent.com/124353560/230888192-f9abaa4c-e4df-4280-a205-dba86724cbb5.png)

When try the level 3 test case after implementing Main, the output is missing all of the leading 0s. e.g "08301 Orchard" becomes 8301 and all stop codes like 09023 becomes 09023

Initially I thought it had to do with the implementation of Main:
![image](https://user-images.githubusercontent.com/124353560/230888377-7bdb0f39-d1dd-4637-b7fa-267619d68579.png)

but after changing Integer.valueOf(sc.next()).toString() to just sc.next(), the bus stop number just doesnt exist?

![image](https://user-images.githubusercontent.com/124353560/230888625-a5d41899-188d-45db-be13-8565fb2ac102.png)

In both cases, my code still works for the test case:
![image](https://user-images.githubusercontent.com/124353560/230888753-0ec38d04-d42a-47f0-b1e3-cc5a78d46058.png)

Main code:
![image](https://user-images.githubusercontent.com/124353560/230888970-66c08507-b34d-4029-afc3-0e38d62338b4.png)

**Comment by LYEDominic** [comment]
Nevermind I resubmitted it with the Integer.valueOf intact and finished it on code crunch

**Comment by llaamaaa** [comment]
hi! i got the same issue as you- what did u do to solve it!
