### ISSUE TITLE
Exercise 3, Part 6

### ISSUE THREAD

**Issue by JYeoZS** [nus-cs2030/2223-s2#85]
Hi,

Am a little puzzled by below error thrown:

Based on public test case, should get: ```shape ==> solid-cuboid [2.00 x 2.00 x 2.00] with a mass of 4.00```

In first place, how does Solid Interface link with Shape3D interface as they are 2 different interfaces?

Thanks for the help.

<img width="557" alt="Exercise 3 Error" src="https://user-images.githubusercontent.com/122290983/217294552-134aa5bc-9ed6-4755-8099-f603e1c64372.png">

**Comment by trwstin** [comment]
> In first place, how does Solid Interface link with Shape3D interface as they are 2 different interfaces?

The test case should give you a hint of their relationship, are they really meant to be 2 separate entities?

**Comment by granolaluvr69** [comment]
Solid is a Shape3D, think about how you can extend one interface from another.

**Comment by JYeoZS** [comment]
Hi, thanks for the help. @trwstin @granolaluvr69 were right on what went wrong.

In short.... :rofl:

![549](https://user-images.githubusercontent.com/122290983/217438435-4b377a88-fb61-4412-bb71-c7666c0b35c5.jpeg)
