### ISSUE TITLE
Exercise 4 level 4 or method

### ISSUE THREAD

**Issue by Callieeechen** [nus-cs2030/2223-s2#856]
<img width="461" alt="image" src="https://user-images.githubusercontent.com/122248687/231422861-dd087303-4459-4d27-9a2d-abec4a81315f.png">
<img width="330" alt="image" src="https://user-images.githubusercontent.com/122248687/231422959-d8ed4936-facb-45e7-be93-b81ddff66900.png">
Any one can help me with this error?

**Comment by junhonglow** [comment]
The supplier returns an object of type Maybe, however, in your return statement, your type witness expects an object of type T instead.

**Comment by Maxxtucker** [comment]
Just use suppMaybe.get()

**Comment by leezhanpeng** [comment]
You might want to take a look at #424.

**Comment by slimzaza** [comment]
The supplier returns a Maybe object, so you should access the T value in the Maybe object and use it to return a new Maybe with the static of method

**Comment by ugchongg** [comment]
I experienced this error too, I managed to resolve it by getting the value from my supp.get() and using it to create a new maybe. I think this error is caused by supp.get() returning a maybe with an unknown type (as a result of the wildcard) , hence it would not match the Maybe<T> return type we've specified.

**Comment by e0969533** [comment]
the supplier.get() returns a Maybe<? extends T> object, so u need to unwrap this object and return it in another Maybe object

**Comment by Adem121** [comment]
similar logic is used for flatMap in lvl 5

**Comment by territxl** [comment]
Do check your return type as mentioned by the error output, the object you are returning is of Maybe<? extends T>
