### ISSUE TITLE
Ex 5 Level 4 formatting 

### ISSUE THREAD

**Issue by tali-a** [nus-cs2030/2223-s2#858]
Hello! I can't seem to format my output correctly with each single character being printed on a new line.  i'm not sure how we should be grouping our final output in the gameoflife method
![image](https://user-images.githubusercontent.com/103631647/231430572-be56efc9-daa1-4d93-a132-2c1ebd22a57f.png)
![image](https://user-images.githubusercontent.com/103631647/231430617-7a3e35d2-0ed2-4fbe-a4ad-ca2eaf0f1152.png)

thanks in advance!!

**Comment by codecode24** [comment]
I think every List<Integer> that you create through iterate needs to be reduced to 1 string.

**Comment by tali-a** [comment]
> I think every List that you create through iterate needs to be reduced to 1 string.

Thanks!

**Comment by bobafreshmilk** [comment]
hi, you might want to use .collect(Collectors.joining()) after mapping each integer in the list into "." or "x". This will concatenate the characters into a single string for each list.
