### ISSUE TITLE
cannot update my serverlist

### ISSUE THREAD

**Issue by WILLSONXWX** [nus-cs2030/2223-s2#86]
# Summary

I have tried to update my serverList during my serve event but the outcome is that it is not updated and it is still in such way that every event will go through server 1

## Description:

as the code below, I have using the if condition when event.getIndex = 3 to change it since my serve event index is 3

## Code Snippets

Attach code snippets (if any)

## Screenshots
![Screenshot 2023-02-08 at 12 57 53 AM](https://user-images.githubusercontent.com/123813085/217311962-ab9ba9ff-8032-45d3-b85a-78e6b26b73c3.png)

Screenshots (if any)

**Comment by trwstin** [comment]
Hi, I don't think we are allowed to share screenshots of our code
