### ISSUE TITLE
Confused over Ex 4 Level 5

### ISSUE THREAD

**Issue by ahndrayo00** [nus-cs2030/2223-s2#861]
Honestly really confused with the boundcards and type parameterisation now

Currently am facing this error and this is my code
![image](https://user-images.githubusercontent.com/123559896/231489427-1bedac44-4d85-4858-bb91-b6ffe3788326.png)
![image](https://user-images.githubusercontent.com/123559896/231489518-a1986f97-40e7-484d-90f0-f5798818ca6e.png)

![image](https://user-images.githubusercontent.com/123559896/231489598-47a6ac9c-8132-473c-9113-e55986080ed5.png)
Based on the test case, from what I understand, we are type parameterising the input of the Function as String or anything more general than string (i.e T is String), and output of Function as Object or anything more specific than an Object (i.e U is an object). Hence, based on my wildcards, there shouldn't be an issue. Thus, Idk why I'm facing this problem. 

Do let me know if I have any misconceptions!!

**Comment by user1914** [comment]
i think when you use f.apply(this.get()) you will return a Maybe<? extends U> which is not the same as Maybe<U>

so you would need to get the value of the Maybe<? extends U> and input it into the of method to return a Maybe<U>

**Comment by omarsfs** [comment]
could be worth considering if the f.apply returns an empty optional also

**Comment by granolaluvr69** [comment]
f.apply returns a Maybe<? extends U>, which is not an instance of a Maybe<U>, which is your return type. To fix this, unwrap the object wrapped in the Maybe<? extends U> and create a new Maybe.<U>of(f.apply(this.get()).get()) to be returned.
Hope this helped.

**Comment by ayevxn** [comment]
> f.apply returns a `Maybe<? extends U>`, which is not an instance of a `Maybe<U>`, which is your return type. To fix this, unwrap the object wrapped in the `Maybe<? extends U>` and create a new `Maybe.<U>of(f.apply(this.get()).get())` to be returned. This works because unwrapping the `Maybe<? extends U>` gives you an object that extends U, which can be assigned to U, which can be used in the creation of a `Maybe<U>` object, which guarantees that it is of type `Maybe<U>` before returning it. Hope this helped.

Not OP but thank you for this explanation it really helped to clear things up!

**Comment by ahndrayo00** [comment]
> f.apply returns a `Maybe<? extends U>`, which is not an instance of a `Maybe<U>`, which is your return type. To fix this, unwrap the object wrapped in the `Maybe<? extends U>` and create a new `Maybe.<U>of(f.apply(this.get()).get())` to be returned. This works because unwrapping the `Maybe<? extends U>` gives you an object that extends U, which can be assigned to U, which can be used in the creation of a `Maybe<U>` object, which guarantees that it is of type `Maybe<U>` before returning it. Hope this helped.

Got it thank you so much!
