### ISSUE TITLE
Exercise 5 Level 4 game of life 

### ISSUE THREAD

**Issue by geraldckj** [nus-cs2030/2223-s2#862]
Hi all, I am trying to write the game of life method but im having some trouble compiling in jshell. 

This is my method and the error that pops up. Any help is appreciated, TIA!

![image](https://user-images.githubusercontent.com/56596389/231521760-fff00ef8-8d22-438a-ae2d-a934f14eb67c.png)

![image](https://user-images.githubusercontent.com/56596389/231521645-0334cbef-d5b1-4b75-a39f-abc8bab28948.png)

**Comment by geraldckj** [comment]
> The return type of your gameOfLife is not Stream. You also need to change your stream of “.” and “x” to a String.

Do you have any hints on how to do so? I'm not too sure on the syntax

**Comment by VanyaPriscillia** [comment]
Your gameOfLife returns Stream of Stream of String, so you need to convert your Stream of String to a String

**Comment by geraldckj** [comment]
Manged to solve this by using the .reduce method to reduce my last Stream<String> to a string to return a Stream<String> instead of Stream<Stream<String>>
 
 Thanks @VanyaPriscillia 
 
Found this tutorial really helpful for understanding whats going on in the reduce method, especially with their usage of subtotal and elements as values. 
 
 Hope this thread helps for anyone else stuck. 
 
 https://www.baeldung.com/java-stream-reduce
