### ISSUE TITLE
orElseThrow() does it require a supplier?

### ISSUE THREAD

**Issue by jianjiezzz** [nus-cs2030/2223-s2#867]
![image](https://user-images.githubusercontent.com/119864021/231748460-53de9d4e-9ad3-4d2c-a8c3-faaecb51d91c.png)
In the video, I saw that the coder simply put optional.orElseThrow(), and does'nt need to add a supplier in the argument
When I refer to the API, it shows
**public <X extends Throwable> T orElseThrow(Supplier<? extends X> exceptionSupplier) throws X extends Throwable**
1. which part of this shows that it can have no argument?
2. And btw, is'nt this literally similar to using .get() ?

**Comment by EpicSpirito** [comment]
There is another overloaded orElseThrow method that takes in no argument

**Comment by jianjiezzz** [comment]
> There is another overloaded orElseThrow method that takes in no argument

where can I find it, I couldn't find it in the API page :O

**Comment by jianjiezzz** [comment]
> ![image](https://user-images.githubusercontent.com/122725424/231753947-5685b7e5-eb58-438d-b68c-eef826fb90f7.png)

OHH, I have being looking at java SE 8, which doesnt have it. Thanks so much!
