### ISSUE TITLE
ex 6 main

### ISSUE THREAD

**Issue by xj8423** [nus-cs2030/2223-s2#870]
<img width="647" alt="Screenshot 2023-04-15 at 12 23 28 AM" src="https://user-images.githubusercontent.com/122519244/232101249-3955ab15-fabc-42f9-a728-9091a2bc8425.png">

hi! im facing this problem for ex 6, i have done another map and now have a list of completable future of strings, before calling join at the very end

im not very sure what's wrong, any hints will be greatly appreciated! :')

**Comment by subhadhra-m** [comment]
facing the same error, not sure what's wrong as well!! :((

**Comment by NGx2000** [comment]
> faced the same error, I realised that i commented out the last 3 lines of the code when i submitted. This part onwards. sc.close(); Instant stop = Instant.now();
> 
> Do check if you accidentally did that too!

To add on, make sure that you keep the original code that helps you time your function i.e.
Instant start = Instant.now();
<Your code here>
Instant stop = Instant.now();
System.out.printf("Took %,dms\n", Duration.between(start, stop).toMillis());

**Comment by xj8423** [comment]
thanks!! managed to resolve, turns out i forgot to add in the last few lines
