### ISSUE TITLE
PA2 Level 5

### ISSUE THREAD

**Issue by Xequil1** [nus-cs2030/2223-s2#871]
![image](https://user-images.githubusercontent.com/122268182/232176995-c757ff0c-a9b2-4dd6-8316-6b45baaacd34.png)

Still confused about suppliers. How does wrapping a supplier around T help in this case?

Also, for the fourth argument, isn't this a function that takes in T and returns a pair of T wrapped in a supplier, wont this directly conflict with the previous levels?
` Function<T, Pair<Supplier<T>, Supplier<T>>`

**Comment by granolaluvr69** [comment]
Hi, I have the same issue too, just following this thread.

**Comment by xgkiri** [comment]
Yes, you should change it to Function<T, Pair<Supplier<T>, Supplier<T>>>. And then, you need to modify your solve(bop), left(), right() method as well as the constructors to avoid conflict with the previous levels. (For the constructor in previous levels, you may consider using a lambda to change the input of type Function<T, Pair<T, T>> to the type Function<T, Pair<Supplier<T>, Supplier<T>>>)

**Comment by Xequil1** [comment]
@xgkiri did you solve this already? Did you use some memoization trick? If yes, how did you do it without invoking equals.

**Comment by imkwokyong** [comment]
I was confused because apparently we also need to include the case without the Supplier<T>:
![image](https://user-images.githubusercontent.com/110521168/232187052-a373f119-8760-4644-8160-9b984027498c.png)

**Comment by choongzhanhong** [comment]
In your earlier `of` methods, you can create a Supplier to supply `T problem` and pass that the constructor. You can also modify the subdivider Function in the `of` method

**Comment by nigel-tannn** [comment]
> Yes, you should change it to Function<T, Pair<Supplier, Supplier>>. And then, you need to modify your solve(bop), left(), right() method as well as the constructors to avoid conflict with the previous levels. (For the constructor in previous levels, you may consider using a lambda to change the input of type Function<T, Pair<T, T>> to the type Function<T, Pair<Supplier, Supplier>>)

Can I check how you used the lambda function to change generics for the Function?

**Comment by granolaluvr69** [comment]
> > Yes, you should change it to Function<T, Pair<Supplier, Supplier>>. And then, you need to modify your solve(bop), left(), right() method as well as the constructors to avoid conflict with the previous levels. (For the constructor in previous levels, you may consider using a lambda to change the input of type Function<T, Pair<T, T>> to the type Function<T, Pair<Supplier, Supplier>>)
> 
> Can I check how you used the lambda function to change generics for the Function?

Hi Nigel, you can use the `andThen()` method to change the output of the function.

**Comment by JYeoZS** [comment]
Just saying, you could make use of the constructor to edit the output of Pair<T,T> to Pair<Supplier.., Supplier>...
