### ISSUE TITLE
Incorrect ordering of output when using dnc.solve(bop)

### ISSUE THREAD

**Issue by weitatftw** [nus-cs2030/2223-s2#876]
# Summary
I'm currently facing an issue where CodeCrunch says that the order in which I print out the pairs of values are incorrect (right before using the supplier). I thought that the question said that the order in which the pairs were evaluated might differ from mine and so I didn't really bother much about the ordering in which the lines are outputted. Can anyone help me with this?

## Screenshots (if any): 
<img width="783" alt="Screenshot 2023-04-16 at 1 02 15 AM" src="https://user-images.githubusercontent.com/79369027/232242124-e2c3d6c5-0401-4cff-9e9a-9727d2972db5.png">

**Comment by Aron113** [comment]
i had a similar issue to this. For me it was because my solve(bop) was evaluating the T value by calling the Supplier.

**Comment by weitatftw** [comment]
i managed to solve this issue, thanks for the help!

**Comment by trwstin** [comment]
> i managed to solve this issue, thanks for the help!

yo im facing this issue rn, how did you solve it?

**Comment by weitatftw** [comment]
> > i managed to solve this issue, thanks for the help!
> 
> 
> 
> @weitatftw yo im facing this issue rn, how did you solve it?

i created an overloaded method for both left and right that takes in an optional of the problem and within that method, i used that optional argument to find left and right to eliminate the need to call get() multiple times. so i called the overloaded left() and right() methods in solve(bop) and applied bop on both the method calls in the return statement and it worked fine afterwards

**Comment by ianwonghanli** [comment]
> > > i managed to solve this issue, thanks for the help!
> > 
> > 
> > @weitatftw yo im facing this issue rn, how did you solve it?
> 
> i created an overloaded method for both left and right that takes in an optional of the problem and within that method, i used that optional argument to find left and right to eliminate the need to call get() multiple times. so i called the overloaded left() and right() methods in solve(bop) and applied bop on both the method calls in the return statement and it worked fine afterwards

Hi. Im currently facing the same issue. May I know what is "optional of the problem" is? Would it be the BinaryOperator<R>?

**Comment by trwstin** [comment]
> Hi. Im currently facing the same issue. May I know what is "optional of the problem" is in the overloaded left() and right()? Would it be the BinaryOperator<R>?

I think he is referring to wrapping the 'problem' property of type T in an Optional?

In any case, my issue was that in solve(bop) I created a 'fake' left() and right() method before the return statement where bop is applied. These are just methods which have similar functions as left() and right(), but do not invoke the supplier.

But prematurely instantiating 'fake' right() messes up the depth evaluation thing, so I shifted the creation of the 'fake' right() method within the return statement and the problem was solved.

**Comment by ianwonghanli** [comment]
> > > i managed to solve this issue, thanks for the help!
> > 
> > 
> > @weitatftw yo im facing this issue rn, how did you solve it?
> 
> i created an overloaded method for both left and right that takes in an optional of the problem and within that method, i used that optional argument to find left and right to eliminate the need to call get() multiple times. so i called the overloaded left() and right() methods in solve(bop) and applied bop on both the method calls in the return statement and it worked fine afterwards

Hihi, sorry for more questions, but may I know how to shift the 'fake' right method into the return statement itself. Right now, I create the DnC variable right before the return statement, because my return statement requires the right variable to be utilized twice. It looks like this:

DnC<T,R> left = this.left(optionalT);
DnC<T,R> right= this.right(optionalT);

return binaryFunction.apply(left.solve().orElse(left.solve(binaryFunction).orElseThrow()), right.solve().orElse(right.solve(binaryFunction).orElseThrow()))

**Comment by trwstin** [comment]
> return binaryFunction.apply(left.solve().orElse(left.solve(binaryFunction).orElseThrow()), right.solve().orElse(right.solve(binaryFunction).orElseThrow()))

hmm if you have get() in solve() wouldn't that trigger multiple evaluations when you use it in solve(bop) which also calls get()? 

perhaps you can use a version of it that does not have the .get() call but uses the optionalT.

> but may I know how to shift the 'fake' right method into the return statement itself.

i shifted it in using flatmap and map chains. the approach is quite different from what you have come up with though:

```
<store supplier.get() in a T>;
return <code similar to solve>
    .or( () -> {
        <create fakeLeft as fl>;
        return <call solve(bop) on fl>
            .flatmap( x -> {
                <create fakeRight as fr>;
                return <call solve(bop) on fr>
                    .map( <apply bop on solved fl and solved fr>;
```

**Comment by trickypepe** [comment]
> i shifted it in using flatmap and map chains. the approach is quite different from what you have come up with though:
> 
> ```
> <store supplier.get() in a T>;
> return <code similar to solve>
>     .or( () -> {
>         <create fakeLeft as fl>;
>         return <call solve(bop) on fl>
>             .flatmap( x -> {
>                 <create fakeRight as fr>;
>                 return <call solve(bop) on fr>
>                     .map( <apply bop on solved fl and solved fr> );
> ```

Not the person you're replying to but just wanna say you really helped me out with this! Thank you so much!
