### ISSUE TITLE
Left and Right methods

### ISSUE THREAD

**Issue by rayray39** [nus-cs2030/2223-s2#877]
i have issues implementing the left and right methods, i thought about wrapping inside an Optional but couldnt figure out how to get the pair out and what Optional methods to use. anybody can give me some hints as to how to implement them? Thanks !

**Comment by fy17ohhh** [comment]
you may want to use Optional to filter first and then map; after that do orElse()

**Comment by edmundnwl** [comment]
to get the value out of an Optional you can use orElse, orElseGet, orElseThrow

**Comment by Aron113** [comment]
orElseThrow is useful for this if you want to take the Pair value out of the Optional

**Comment by DavidLawCheng** [comment]
yes wrapping it in an optional is the correct way, you map out the function from the optional, using (x -> x.apply(....)) then after wards you can .map again to take it out from the pair then using orElse() to get it out

**Comment by rayray39** [comment]
yeap i managed to do it using filter and orElse only. Thanks guys
