### ISSUE TITLE
PA2 test case 5

### ISSUE THREAD

**Issue by YyannW** [nus-cs2030/2223-s2#879]
# Summary
hi does anyone have this problem?  I have tried to reduce the number of get() method used, but (5,7) is still evaluated multiple times. any idea about how to solve this issue?

Much thanks.

## Screenshots: 
![image](https://user-images.githubusercontent.com/117875336/232276571-dd0fa3ae-a785-46dc-873b-251116983a41.png)

**Comment by weitatftw** [comment]
hi, i believe that #873 would help too since i managed to reduce the number of times get() is called based on the advice given there

**Comment by Aron113** [comment]
like what was mentioned above, try calling get() only in solve(bop) and assigning it to a variable. Use that variable for the remaining bulk of the method (i.e. creating left and right DnC objects or calling solve() )
