### ISSUE TITLE
Comparator_not_working

### ISSUE THREAD

**Issue by Ervinoreo** [nus-cs2030/2223-s2#88]
# Summary

Hi, I ve an issue on comparator while I was doing the lab. When it is of the same time, our PQ is supposed to return us the one with smaller id customer. But my result sometimes returns me with the correct answer and sometimes does not.

## Description:

For instance, the timestamp 1.600 below works just fine, giving me id 2, then id 5. But timestamp 1.700 does not, it gives me id 6 instead of 3 first. My comparator is smthg like if e1 time == e2 time, then e1 id - e2 id.

## Screenshots

Screenshots (if any)
<img width="253" alt="Screenshot 2023-02-08 at 9 37 47 AM" src="https://user-images.githubusercontent.com/110983457/217406410-cd067288-2a87-4131-87e1-456651ebeb48.png">

**Comment by danqiye1** [comment]
Just to check is your event id the same thing as customer id? Seems like you want to sort by customer id but is instead sorting by event id.

**Comment by Ervinoreo** [comment]
> Just to check is your event id the same thing as customer id? Seems like you want to sort by customer id but is instead sorting by event id.

yes my event will get the customer then get its id
