### ISSUE TITLE
cs2030 finals study tips

### ISSUE THREAD

**Issue by meganyeoyy** [nus-cs2030/2223-s2#882]
Hi guys how should I study for the finals? Kinda feeling a bit demoralised after PA3 but I'm trying to push more towards finals.

**Comment by yanerkoh** [comment]
hi megan! i think you should rewatch the lectures and clarify any doubts. you should also try out the practice papers!! all the best!

**Comment by granolaluvr69** [comment]
Do the mock paper! Really helped my understanding and it helps you get familiarised with the APIs we haven't really touched so far (e.g. List, Stream). 
I would say that it also assesses us on other stuff that we haven't really touched in labs and PAs, like lambda currying, completablefutures, and serves as a good refresher on OOP concepts we haven't touched for a long time. 
It would do you well to take a look at the recitation guides as well, they go pretty in depth into key concepts which will probably be more similar in style to how the papers will assess you.
All the best!

**Comment by keshialimm** [comment]
Hi Megan! I think practising by doing the past year papers will definitely help us all be more familiar with the content taught! Maybe look through lectures and recitations as well. All the best :)

**Comment by Yihao2001** [comment]
Hi Megan, thanks for the advice you gave me for PA, think I will be able to do ok because of it so I am here to return the favour.

I think you should just practice the past year papers and make sure you understand why the answer for each question is so. After that also think of variations of the similar question types and prepare answer templates that could potentially be used since this is an open book examination. Alas, this is an examination and preparation can always be done.

**Comment by chewyxx** [comment]
hi megan! i think you can try looking through the practices / lectures we did and also practice more with past year papers. all the best!!

**Comment by vVicksv** [comment]
Look out for gaps in understanding when doing you're exercises or the mock finals then maybe rewatch lectures for your understanding. All the best!

**Comment by nigel-tannn** [comment]
Hi, you can consider trying out the mock papers that Prof posted on CodeCrunch! The walkthrough is really helpful is covering key concepts I feel

**Comment by zhanyang01** [comment]
I would say clarify any doubts with github forums or TAs before the exam will help

**Comment by UmpoDumpo** [comment]
Going through mock papers 100%, it helps point out which topics you may not be too sure as well.

Atb all :)

**Comment by meganyeoyy** [comment]
thanks everyone! all the best :-)
