### ISSUE TITLE
PA2 Level 4

### ISSUE THREAD

**Issue by chianxintong** [nus-cs2030/2223-s2#883]
# Summary
Hi, can i have some tips on how to implement .solve(BinaryOperator op) ?

## Description 
With reference to #878 , I am planning to use:
return Optional.ofNullable(this.solve())... and then use 

orElseGet
- flatmapping to this.left().solve(op) 
- flatmapping to this.right().solve(op)
- and finally map to apply mtd of the binaryoperator. 

however, i encountered the problem of stackoverflow... how may i prevent this?

**Comment by weitatftw** [comment]
did you remember to include a check if the base case has been hit or not first before using solve() on left and right? i think that the missing base case is causing your code to go on infinitely

**Comment by edmundnwl** [comment]
doesn't solve() return an Optional? if you Optional.ofNullable(this.solve) you might be wrapping an Optional in another Optional and it might be difficult to go from there.

**Comment by Aron113** [comment]
for me, my solve() used the .get() method of the supplier. As such I did not reference the solve() method in my solve(bop) as it would cause the pair to be evaluated more than once.

**Comment by chianxintong** [comment]
> doesn't solve() return an Optional? if you Optional.ofNullable(this.solve) you might be wrapping an Optional in another Optional and it might be difficult to go from there.

omg ... ya...... HAHA i managed to solve it, thank u!
