### ISSUE TITLE
PA2 Level 5 - Failing first dnc.solve(bop) after passing second dnc.solve(bop)

### ISSUE THREAD

**Issue by edwinleck** [nus-cs2030/2223-s2#884]
# Summary
I managed to get the correct output for the second dnc.solve(bop) which uses T wrapped inside a Supplier, but I am not able to pass the first one, which uses dnc without Supplier. Wondering if anyone has faced the same issue?

## Screenshots (if any): 
This is my output for the first dnc
![image](https://user-images.githubusercontent.com/97869599/232573302-85a17df9-ac98-4fb0-9bfa-2d6186d72eb3.png)

My output for the second dnc
![image](https://user-images.githubusercontent.com/97869599/232573517-f984fd2b-0c0d-4003-b2f5-ac44181ae103.png)

**Comment by Aron113** [comment]
perhaps it could be due to the way the Optional is evaluated if the problem is not atomic. does your solve(bop) use a recursive method that solves left first before solving right?

**Comment by Fliprun** [comment]
From the looks of it, your left() function (or substitute for it) used in solve(bop) isn't working properly since it is evaluating (8, 7). Your left() and right() functions (or their substitutes) should check whether the problem is atomic when called to prevent this from happening.

**Comment by edwinleck** [comment]
I managed to figure out the issue, the substitute for both left and right should be done in return, instead of storing it in a new DnC and then calling it in return. This prevents left and right from being evaluated when it is already atomic
