### ISSUE TITLE
Ex 6 main class

### ISSUE THREAD

**Issue by ghost1nthemachine** [nus-cs2030/2223-s2#885]
How do I convert List< CompletableFuture < BusRoutes >> to  List< CompletableFuture < String >> without using join()...

Not sure if im on the right track her

**Comment by granolaluvr69** [comment]
1. Convert the `List<CompletableFuture<BusRoutes>>` into a `Stream<CompletableFuture<BusRoutes>>` using the `.stream()` method on the list.
2. Map every `<CompletableFuture<BusRoutes>>` of the stream to `<CompletableFuture<String>>` using `x -> x.thenCompose(y -> y.description())`.
3. Convert the `Stream<CompletableFuture<String>` into a `List<CompletableFuture<String>>` using the `.toList()` method on the stream.

**Comment by ghost1nthemachine** [comment]
Thank you so much!
