### ISSUE TITLE
general question about finals

### ISSUE THREAD

**Issue by taugwa** [nus-cs2030/2223-s2#886]
hi guys! i understand that for finals we need to type out code on our laptops. i know that the code doesn't need to compile, but can our answers be in pseudocode or do we need to type it in proper java syntax? feel like this was mentioned in lecture/rec before but i can't exactly remember. thanks in advance 👯

**Comment by trwstin** [comment]
i think you should write your code with the intention for it to compile; simply writing in pseudocode may not reflect your understanding of the concepts and applications of certain methods to a satisfactory level.

**Comment by jarenl0ke** [comment]
Yeah, if I am not wrong ultimately whether it compiles that is secondary, what is important is that the code that we write demonstrates our understanding of the concepts and how they are applied. So to me I think in general we need to write it in proper syntax

**Comment by vVicksv** [comment]
I'm quite sure they mainly want to test our logic but having it in proper java syntax and having a compilation is important too.

**Comment by aeraeroaer** [comment]
proper syntax would make your logic much clearer to whoever marks it so i would say it’s quite important as well!

**Comment by taugwa** [comment]
thanks guyss
