### ISSUE TITLE
PA2 Level 4 solve method

### ISSUE THREAD

**Issue by oofpouf** [nus-cs2030/2223-s2#888]
Hello! Not very sure about how to implement the solve method that takes in a binary operator

I understand that recursion is probably the only way to go about doing it, so I tried to solve left and right recursively first, before using the apply method of the binary operator.

However, when trying to solve the left and right sides recursively first via Optional.of(prob.get()).filter(x -> check.test(x)).orElse(...), in my orElse, I wanted to do something like this.left().solve(combine) for the left side. But this will return an optional, instead of the same type as prob.get(), which will give compilation errors. Using this.solve() in Optional.of() also doesn't seem very helpful, since it will give an optional nested in an optional. 

Is there anyway to go about doing this? Thanks!

**Comment by liang-zhengxin** [comment]
You may consider using map after your filter to map it to the left's solve method. The map it again to the binary operator with the second argument of the operator being the right's solve method with `orElse`

If using your current implementation, not sure if using `this.solve().filter(...` will work or not. Also you may need to account for the case in which the problem being atomic. Meaning that both left and right will return `prob.get()` but you can't use `if` or `equals` to check.

**Comment by Aron113** [comment]
likely you wont need to use solve() in solve(bop) since that will cause the supplier to be evaluated twice. If you want the value from the Optional, orElseThrow is helpful.

**Comment by liang-zhengxin** [comment]
> likely you wont need to use solve() in solve(bop) since that will cause the supplier to be evaluated twice. If you want the value from the Optional, orElseThrow is helpful.

Actually a way to get around it is to create any another DnC with the value of the supplier already gotten out in the solve(bop).

**Comment by youthfrost** [comment]
u can have get() in solve() and solve() calls solve(bop), similar to the walkthrough
