### ISSUE TITLE
PA2 Level 6 any ideas why i cant split my left and right

### ISSUE THREAD

**Issue by Delocy** [nus-cs2030/2223-s2#890]
# Summary
Put a summary of the problem here

## Description 
Describe the problem and any details if neceesary

## Idea s
Describe the approach used (if applicable)

## Screenshots (if any): 
Insert Images here if necessary
<img width="723" alt="Screenshot 2023-04-18 at 1 32 52 PM" src="https://user-images.githubusercontent.com/94375191/232680245-ea2e1f88-90e8-43ca-9af2-5814cf8a90ad.png">
<img width="271" alt="Screenshot 2023-04-18 at 1 33 07 PM" src="https://user-images.githubusercontent.com/94375191/232680282-7a2444a4-74aa-4cbf-94d6-ea6df86565e5.png">

**Comment by trwstin** [comment]
what is your expected and actual output?
what is in pred and f?

and i believe you are meant to do everything in the constructor

**Comment by SimonSeeYongsheng** [comment]
You are supposed to do everything in the constructor.

**Comment by Delocy** [comment]
ok solved guys thanks

**Comment by tynkyra** [comment]
Regarding the above comments, can I ask how the pred and functions can be done in the constructor?
For eg, if I do super(list),
if i try to create the pred by doing pred = x -> x.size() == 1
the compiler will give a result that size cannot be found since x is a variable T and not a list

**Comment by Delocy** [comment]
> Regarding the above comments, can I ask how the pred and functions can be done in the constructor?
> 
> For eg, if I do super(list),
> 
> if i try to create the pred by doing pred = x -> x.size() == 1
> 
> the compiler will give a result that size cannot be found since x is a variable T and not a list

Ur referencing shud be with respect to ur constructor with 4 inputs a supplier(T), pred, fn, splitfn
So in this case you can just super(()->list, x -> x.size() == 1, x-> x.get(0), u create ur splitting function which returns a pair of supplier

**Comment by tynkyra** [comment]
okay thanks, that worked for me! Is there any method i can use such that i pass in only super(list)?
