### ISSUE TITLE
ex 6 

### ISSUE THREAD

**Issue by dlyxxx** [nus-cs2030/2223-s2#891]
<img width="281" alt="Screenshot 2023-04-18 at 2 16 41 PM" src="https://user-images.githubusercontent.com/122346543/232687997-76bbdddb-ff8b-48e3-966f-21da645f092e.png">
 im not sure why i got this output even though i followed the walk through

**Comment by davytan07** [comment]
Did you reassign output to output.thenCombine(...) in BusRoutes class?

**Comment by Aron113** [comment]
I had the same error, fixed with the above ^
