### ISSUE TITLE
PA2 Level 6

### ISSUE THREAD

**Issue by Nicknzk** [nus-cs2030/2223-s2#893]
Does anyone know why my answer is so much higher then the correct answer?

<img width="648" alt="Screenshot 2023-04-18 at 5 51 06 PM" src="https://user-images.githubusercontent.com/121552001/232740589-2c44a412-35ff-48ee-9c6e-09886b293890.png">

**Comment by Suraj2P** [comment]
hmm your answer seems to be 10 factorial, are you by any chance multiplying the index of the list and not the number within the list itself?
