### ISSUE TITLE
Ex 5 Lvl 4

### ISSUE THREAD

**Issue by bernicebehby** [nus-cs2030/2223-s2#898]
Does anyone know what is the issue here? would rly appreciate some help
![Screenshot 2023-04-19 at 1 19 05 AM](https://user-images.githubusercontent.com/113932261/232854808-66ccdaf4-7250-4114-8cb3-5aba1661f937.png)

**Comment by Leeeef552** [comment]
im not sure but maybe can try flatMap

**Comment by justineeyx** [comment]
u can try adding a reduce at the end to "concat" the strings together, by starting out with an empty string.

**Comment by granolaluvr69** [comment]
Could you provide more details, like what the return type is and what the snippet of code is trying to achieve?

**Comment by bernicebehby** [comment]
> Could you provide more details, like what the return type is and what the snippet of code is trying to achieve?

<img width="808" alt="Screenshot 2023-04-19 at 11 20 24 AM" src="https://user-images.githubusercontent.com/113932261/232958560-0f746bc8-76f3-4681-a8e2-c82ff5dfea1f.png">

**Comment by bernicebehby** [comment]
> im not sure but maybe can try flatMap
hi yes i just tried this and it helped! now i am just having a problem of each cell being printed out rather than being printed out by rows

**Comment by bernicebehby** [comment]
> Could you provide more details, like what the return type is and what the snippet of code is trying to achieve?

i just changed it to flatmap and there is an output of each cell so now i'm just trying to figure out how to print by rows
<img width="574" alt="Screenshot 2023-04-19 at 11 25 20 AM" src="https://user-images.githubusercontent.com/113932261/232959223-53be8cc1-535f-4d6e-8695-8762e53493ab.png">

**Comment by granolaluvr69** [comment]
You have to start the return statement initializing a Stream<List<Integer>>, which you will then map to a Stream<List<String>> (by using .Stream() on every contained List<Integer> and mapping it to a Stream<String>, and using .toList() to convert it back into a List<String>) , and then you need to map it to a Stream<Stream<String>>, which you will need to convert to a Stream<String> by using the reduce function on the inner Stream<String>. If you want to print out the output by line, you simply need to run the .forEach(x -> System.out.println(x)) method on the Stream<String>.

**Comment by ngshiyingg** [comment]
Hi I faced the same issue! I still used map instead of flatMap but I did .collect(Collector.joining()) 

so like map(x -> x.stream().map(…).collect(…));

**Comment by bernicebehby** [comment]
> Hi I faced the same issue! I still used map instead of flatMap but I did .collect(Collector.joining())
> 
> so like map(x -> x.stream().map(…).collect(…));

ooo thank you! this helped but idk why im having errors when it tries to print the subsequent lines... 


<img width="748" alt="Screenshot 2023-04-19 at 7 40 05 PM" src="https://user-images.githubusercontent.com/113932261/233063798-882f22a6-77ef-4705-85b7-d475dbd01cbc.png">

**Comment by justineeyx** [comment]
> 

means your generate rule has an error somewhere where index = 9

**Comment by ngshiyingg** [comment]
@bernicebehby it could be a careless mistake (as in how u spilt up the cases) in your generateRule() method! 

for me, I didn’t do the if else properly for when the number is 0 (can look at #637 for more details!)

**Comment by aeraeroaer** [comment]
would say it is easier to use map rather than flat map, it’s just that at the end of x.stream(). map(…) you add a reduce method to concat all the strings in that stream into one string, hence not requiring flat map

**Comment by e0969533** [comment]
u should use map 
stream.iterate(...).limit(n).map(x -> (x.stream().map(...)).reduce(...) 
reduce basically concat the strings !

**Comment by bernicebehby** [comment]
> @bernicebehby it could be a careless mistake (as in how u spilt up the cases) in your generateRule() method!
> 
> for me, I didn’t do the if else properly for when the number is 0 (can look at #637 for more details!)

thank you so much i realised i made a careless mistake... rly appreciate the help!
