### ISSUE TITLE
Exercise 6 level 3

### ISSUE THREAD

**Issue by ianwonghanli** [nus-cs2030/2223-s2#899]
Hi all. Ive followed the lecture, implemented the changes in my code and implemented my own version of lvl 4 with the help of other github threads. However, Im stuck at this part in lvl 3 and I do not know why. Help is much appreciated

![Screenshot 2023-04-19 023630](https://user-images.githubusercontent.com/99638949/232872458-5288521b-347d-4f0d-91ee-da954762218b.png)

**Comment by Aron113** [comment]
Perhaps the variable, output, was not reassigned in the description() method of BusRoutes

**Comment by ryantangmj** [comment]
faced the same issue initially, realised that the issue lies in description() of BusRoutes

**Comment by Huanqing-Mao** [comment]
You should assign the variable in description(). If you are stuck, you can look at the recording more carefully (fast forward to the back).

**Comment by ianwonghanli** [comment]
Hi all solved this issue thanks to your help! I recommend checking each variable in the description method if yall encounter this issue!
