### ISSUE TITLE
Why does 5/3= 1

### ISSUE THREAD

**Issue by shakerfries** [nus-cs2030/2223-s2#90]
# Summary
When I type 5/3 I get 1 instead of a decimal
Description of the question / problem here.

## Description:

Clarifications or details with respect to the issue you are facing

## Code Snippets

Attach code snippets (if any)

## Screenshots

Screenshots (if any)

**Comment by calvnleong** [comment]
you should do 5.0/3.0 as the result you want is double.

**Comment by sp4ce-cowboy** [comment]
In java, both `5` and `3` are considered integer operands, therefore, the `/` operator will always return an integer value.

To get the exact value, you need to input either: `5.0/3` or `5/3.0`.

You can also verify the type of value return by setting feedback mode in jshell with `/set feedback verbose`. The below image shows what the outputs look like, and the types returned.

<img width="283" alt="image" src="https://user-images.githubusercontent.com/19762596/217492050-19643437-9478-4daf-9eb9-427b653eb89c.png">

**Comment by shakerfries** [comment]
oh thanks guys

**Comment by e0959170** [comment]
if u divide an integer by an integer java automatically does integer division! to fix this issue js add a .0 behind one or both of the numbers so at least one of them is a double

**Comment by eunicel23** [comment]
by dividing both integers with each other, you will get a integer result. you should include a .0 for one of the integers if you want a double answer!

**Comment by eunicel23** [comment]
by dividing both integers with each other, you will get a integer result. you should include a .0 for one of the integers if you want a double answer
