### ISSUE TITLE
ex 5 level 4 

### ISSUE THREAD

**Issue by tryngmyhardest** [nus-cs2030/2223-s2#900]
How can i separate the lines?

I concat the strings using reduce()

<img width="1231" alt="Screenshot 2023-04-19 at 12 49 37 PM" src="https://user-images.githubusercontent.com/127404598/232970185-fddbc69e-c132-4bef-91d6-6551e9738dc2.png">

**Comment by yugan01** [comment]
are you by chance doing 2 rounds of reduce instead of 1 reduce at the end?

**Comment by kayeugenia** [comment]
i'm not sure how your code was implemented but must make sure that your Stream in gameOfLife returns a Stream.<List<Integer>>, iterate, limit, then .map( x -> x.stream().map(...))
hope this helps!

**Comment by chewyxx** [comment]
i did .map(x -> x.stream().map(y -> y == 1 ? "x" : ".").reduce("", (a,b) -> a + b)), i think ur current code right now reduces the whole stream of strings

**Comment by tryngmyhardest** [comment]
> i did .map(x -> x.stream().map(y -> y == 1 ? "x" : ".").reduce("", (a,b) -> a + b)), i think ur current code right now reduces the whole stream of strings

@chewyxx yeap this was indeed the issue thanks!!
