### ISSUE TITLE
walk-thr video left function not working

### ISSUE THREAD

**Issue by jianjiezzz** [nus-cs2030/2223-s2#902]
3 errors pops out for this method, anyone know what is wrong?

![image](https://user-images.githubusercontent.com/119864021/233019921-07b34714-17c2-47e7-8743-f9f862c13a18.png)

DnC.java:45: error: incompatible types: Pair<Supplier<T>,Supplier<T>> cannot be converted to Pair<T,T>
        Pair<T,T> pair = div.apply(prob);
DnC.java:47: error: incompatible types: T cannot be converted to Supplier<T>
                        return new DnC<T,R>(pair.first(),
DnC.java:50: error: incompatible types: Object cannot be converted to DnC<T,R>
                    })).orElse(this);

**Comment by jianjiezzz** [comment]
> Seems like your pair should be Pair<Supplier < T > , Supplier < T >> in line 6

![image](https://user-images.githubusercontent.com/119864021/233023764-00d329dd-988f-45ff-bebf-1ea94ae99bf1.png)
I got these errors after changing to  Pair<Supplier < T > , Supplier < T >> in line 6 LOL :((

**Comment by Ma-Xizi** [comment]
Oh there is a new announcement about the brackets on Canvas

**Comment by maze508** [comment]
Seems like other formatting issues yea but I believe he already accounted for that error in the announcement. You can just use an IDE to check where your problem is, probably with the rest of your code.

**Comment by jianjiezzz** [comment]
ohh thanks guys, just saw the announcement!
