### ISSUE TITLE
PA2 Method violation error

### ISSUE THREAD

**Issue by justineeyx** [nus-cs2030/2223-s2#906]
Did anyone face this issue, i tried the testcases in jshell and it was all correct. I alr made sure to only have 1 constructor that takes in a list of integers. 
![image](https://user-images.githubusercontent.com/122433748/233066934-b4b9b0ad-e4b8-4970-8eab-a52357a92135.png)

**Comment by trickypepe** [comment]
Maybe you have something other than 1 single constructor in your SumList class?

**Comment by justineeyx** [comment]
> Maybe you have something other than 1 single constructor in your SumList class?

Here is my constructor, i followed the walkthru's method so i dont get why the error comes up
![image](https://user-images.githubusercontent.com/122433748/233069329-c83cfd28-22cb-4d73-a91e-f37a2301d417.png)

**Comment by trickypepe** [comment]
> Here is my constructor, i followed the walkthru's method so i dont get why the error comes up ![image](https://user-images.githubusercontent.com/122433748/233069329-c83cfd28-22cb-4d73-a91e-f37a2301d417.png)

The constructor itself looks correct. I encountered this error when I had a static of() method below, it worked after I removed the extra method.

**Comment by lynettelcl** [comment]
i used listInt just to differentiate so it'll b clearer, and not sure if your last list.size() might be causing your error?

**Comment by lynettelcl** [comment]
> i used listInt just to differentiate so it'll b clearer, and not sure if your last list.size() might be causing your error?

the listInt i used is just like the "i" used in the walkthru vid

**Comment by edmundnwl** [comment]
> Here is my constructor, i followed the walkthru's method so i dont get why the error comes up

at the end of your constructer you suddenly changed z to list. should be z.size()

**Comment by justineeyx** [comment]
okay resolved , thanks everyone!
