### ISSUE TITLE
exercise 5 level 4 

### ISSUE THREAD

**Issue by e0969533** [nus-cs2030/2223-s2#907]
<img width="787" alt="image" src="https://user-images.githubusercontent.com/124663178/233066870-f6f9cc3a-328b-4d32-9ca5-795cf1aa9557.png">

hi, does anyone knows what is this error ?
for this test case it should be a different rule that is used, and i didn't use generateRule() directly in the gameOfLife method.
```
 static Stream<String> gameOfLife(List<Integer> list, UnaryOperator<List<Integer>> rule,int n) {
 43         return Stream.iterate(list, rule)
 44                 .limit(n)
 45                 .map(x -> x.stream().map(y -> y == 1 ? "x" : ".").reduce("", (a,b) -> a + b));
 46     } 
```

**Comment by justineeyx** [comment]
try this
`Stream.iterate(list, rule).limit(n).map(x -> (x.stream().map(y -> (y == 1) ? "x" : ".")).reduce("", (a,b) -> a + b));`

**Comment by e0969533** [comment]
> 


thanku, but it didnt resolve the issue

**Comment by aeraeroaer** [comment]
this would indicate that the rules that you set are not correct, mainly it is not considering the case that when a “dead” cell has to alive neighbours, it will remain dead

**Comment by e0969533** [comment]
thanks guys! i managed to solve the issue that is with generateRule() method !
