### ISSUE TITLE
PA2 test case 5 

### ISSUE THREAD

**Issue by yx420** [nus-cs2030/2223-s2#908]
hi may i know what might be wrong with my solve(bop) method
<img width="608" alt="image" src="https://user-images.githubusercontent.com/122374639/233076475-57c62e4d-f82f-4e2e-b3c2-b4d46dbec104.png">

**Comment by weitatftw** [comment]
your solve(bop) method evaluates pairs repeatedly when it shouldn't, it should only evaluate each unique pair once

**Comment by sethteo** [comment]
> i think overloading solve method would be helpful. this makes sure your .get() only happens one for each solve()/left() and right()

can i ask if you are only overloading your solve() and solve(BinaryOperator)? or do you overload the other methods such as left() and right() as suggested by the walkthrough.
thanks in advance :))

**Comment by kayeugenia** [comment]
> > i think overloading solve method would be helpful. this makes sure your .get() only happens one for each solve()/left() and right()
> 
> can i ask if you are only overloading your solve() and solve(BinaryOperator)? or do you overload the other methods such as left() and right() as suggested by the walkthrough. thanks in advance :))

i followed the walkthru's suggestion. cannot think of any other way to only call .get() once :(

**Comment by edmundnwl** [comment]
you can also have the solve(bop) method do everything if you don't want to overload the right and left methods, just write them inside the solve(bop)

**Comment by yx420** [comment]
thank you guys

**Comment by NeoHW** [comment]
Hi! did you manage to solve it without overloading the methods?
