### ISSUE TITLE
Exercise 3 Level 3

### ISSUE THREAD

**Issue by eesean** [nus-cs2030/2223-s2#91]
Hi all, 

Would like to ask whether anyone has encountered this error before and how should I go about fixing it? I attempted to find volume of Sphere(2.0) but my output is around 25 when it should be around 33, even though I have used the correct formula for volume of spheres.

**Comment by granolaluvr69** [comment]
Hi, try typecasting your sphere volume constant before doing the calculation.
```java
private final double SPHERE_VOLUME_CONSTANT = (double) 4 / 3
```
Like so. The problem is that java assumes that integer division is occurring when you enter 4 / 3 without typecasting either the divisor or the quotient. Hope you have a better understanding now!

**Comment by trwstin** [comment]
could also do 4.0 / 3.0 during assignment

**Comment by eesean** [comment]
Thanks for the insights! Yep managed to fix the code.
