### ISSUE TITLE
level 5 Supplier

### ISSUE THREAD

**Issue by chanjieru** [nus-cs2030/2223-s2#911]
was wondering if it's possible for problem to be `Supplier<Optional<T>>`, as my original implementation for problem is `Optional<T>` so for level 5, I will have to change it to `Supplier<Optional<T>>`. Since the input for `of() `is `Supplier<T>`, that means I will have to call `get()` to wrap it in a new `Supplier<Optional<T>>`, so cmiiw, the Supplier will always be evaluated immediately? Is there any way to get around this?

**Comment by EvanCh08** [comment]
I think Optional<Supplier<T>> would be better, since it follows as well from the ungraded exercise 3 where the expression class uses Optional<Supplier>>.

**Comment by jarenl0ke** [comment]
Agree that think using Optional<Supplier<T>> would be better than the other way around as trying to extract the value from a Supplier<Optional<T>> would be messier.

**Comment by niclee1219** [comment]
i agree with him, u should use supplier<optional>
