### ISSUE TITLE
PA2 level 5

### ISSUE THREAD

**Issue by hhuilingg** [nus-cs2030/2223-s2#913]
hi, may i ask if there's a way to write solve(BinaryOperator<R>) with only one method on left() and right() [no additional methods: left(T) right(T) - without overloading]? thankyou in advance :)

**Comment by edmundnwl** [comment]
you can do everything inside the solve method. ie rewrite the left and right inside the solve

**Comment by hhuilingg** [comment]
> you can do everything inside the solve method. ie rewrite the left and right inside the solve

sorry, i'm not so sure how should i do it?

**Comment by stxe09** [comment]
I think what the previous comment means is that you define a left(T), right(T) within the solve method, so technically, you're not overloading.

But you still have to create new left(T), right(T) methods, if I understand correctly. so that would still affect your similarity score to the same extent I feel

**Comment by hhuilingg** [comment]
> I think what the previous comment means is that you define a left(T), right(T) within the solve method, so technically, you're not overloading.
> 
> 
> 
> But you still have to create new left(T), right(T) methods, if I understand correctly. so that would still affect your similarity score to the same extent I feel

ahh alright :( thankyou so much!!

**Comment by mkim123** [comment]
you could write the left and right methods directly in the solve(bop) method - meaning paste the code from your left and right method in place of the left() and right() initially in your solve(bop) method, this will prevent the.get() from calling multiple times and work with the same problem
