### ISSUE TITLE
Exercise 6

### ISSUE THREAD

**Issue by yuzujy** [nus-cs2030/2223-s2#914]
hi i am quite confused with the whole CompletableFuture in exercise 6. Can anyone give hints on how to go about the main class? thanks

**Comment by stxe09** [comment]
for the main, class, the main challenge is only using join() once. if you submit into code crunch with multiple joins, grading will terminate. 

follow the lecture closely, and adapt the solution (the proposed one had multiple joins). you can look as the closed discussions for this!!

**Comment by NeoHW** [comment]
could consider using thencombine() to store it as a string

**Comment by briannoelkesuma** [comment]
for this, try using thencombine() or thencompose() and make use of a single join() at the end. hope this helps!
