### ISSUE TITLE
AY22/23 S1 Final Assessment Q2 requirements

### ISSUE THREAD

**Issue by nathankkh** [nus-cs2030/2223-s2#916]
For question 2 of the Nov/Dec 2022 paper, the constraints are -
> each method body should begin with a return;
> there should be no additional helper methods;
> do not use any form of looping or branching constructs;
> use the two-argument reduce method.

However, the walkthrough doesn't use the `reduce` method - wouldn't this be penalised?
![image](https://user-images.githubusercontent.com/115643118/233284940-3afe2cb9-38e0-4bc7-a853-a287e668593f.png)

**Comment by yugan01** [comment]
I interpreted the question as saying if we want to use any reduce methods, we can only use the 2-argument reduce method.
