### ISSUE TITLE
AY21/22 Sem 2 Finals Solutions

### ISSUE THREAD

**Issue by UmpoDumpo** [nus-cs2030/2223-s2#917]
Hmm it seems that the canvas final mock paper (AY21/22 Sem 2) doesn't provide any solution. The walkthrough appears to be AY21/22 Sem 1 not sem 2. Does anyone know where to find solutions for AY21/22 Sem 2?

**Comment by cweisong** [comment]
believe they said they'll release the review closer to the end of this week

**Comment by gelalallaal** [comment]
bump its out nows prof made an announcement

**Comment by UmpoDumpo** [comment]
> bump its out nows prof made an announcement

hmm did he? i don't see anything new on canvas

**Comment by dmidula** [comment]
The walkthrough vid for AY21/22S2 has been uploaded under Web Lectures

**Comment by UmpoDumpo** [comment]
> The walkthrough vid for AY21/22S2 has been uploaded under Web Lectures

see it now thanks!
