### ISSUE TITLE
EX 6 Main?

### ISSUE THREAD

**Issue by Cfyjdfk** [nus-cs2030/2223-s2#923]
![Screenshot 2023-04-21 at 1 53 33 AM](https://user-images.githubusercontent.com/58412687/233448500-2d28c0b0-bf1e-4529-ba90-47df17884a8d.png)

Not sure whats going on. Can anyone help?

```

 public static void main(String[] args) {
        Instant start = Instant.now();
        Scanner sc = new Scanner(System.in);
        List<CompletableFuture<BusRoutes>> result = sc.useDelimiter("\n").tokens()
            .map(s -> processQuery(s))
            .toList();

        result.stream().map(x -> x.thenCompose(y -> y.description()))
            .forEach(z -> System.out.println(z));
        
        Instant stop = Instant.now();
        System.out.printf("Took %,dms\n", Duration.between(start, stop).toMillis());
        sc.close();
    }

```

**Comment by NeoHW** [comment]
did you add in the timings at the end of your ans?

**Comment by tjdbryan** [comment]
`"Took %,dms\n"`

Here, your String formatting is off! 😣

**Comment by Cfyjdfk** [comment]
alright solved it, thanks all

**Comment by cher212** [comment]
Hi how did you solve it?

**Comment by Cfyjdfk** [comment]
> Hi how did you solve it?

just needed to call z.join() and edit the "%" to "%i".

**Comment by vanessakohh** [comment]
that's interesting because mine worked with just %, without the "i"

**Comment by haoyanggggg** [comment]
hi where did u put your join()? im facing the same exact issue as u

**Comment by geraldckj** [comment]
Same mine worked without the i

**Comment by kciruos** [comment]
Does anyone know why the "i" is needed?
