### ISSUE TITLE
PA2 level 6 cannot find symbol error

### ISSUE THREAD

**Issue by gracico** [nus-cs2030/2223-s2#934]
# Summary
Hi, I tried implementing the code given in the walkthrough but it doesn't compile. Does anyone know what the issue is?

## Screenshots (if any): 
<img width="724" alt="Screenshot 2023-04-22 at 6 01 50 PM" src="https://user-images.githubusercontent.com/122587013/233777342-ed46480b-146a-44a0-ad53-af01a2a2e211.png">

**Comment by haqanh** [comment]
Have you typecasted your pair to the context of level 6 (like List<Integer>?) iirc that was the problem I faced

**Comment by territxl** [comment]
You should check that in your constructor in SumList, the input types corresponds to how you have defined your constructor in DnC. Hope this helps!
