### ISSUE TITLE
AY 21/22 Q4 MapElse

### ISSUE THREAD

**Issue by shawncch** [nus-cs2030/2223-s2#936]
Hi all, may I know what is the recommended implementation for mapIf and mapElse in Q4? I returned a new IfElse for my mapIf method, by composing my current predicate with the new one. 

But for mapElse I created another constructor to take in an optional predicate for the alternative predicate (div400), my apply method then applies this alt predicate if the current predicate returns an empty optional

**Comment by granolaluvr69** [comment]
Personally, for mapIf I used the `and()` method to return an IfElse with a predicate that is the logical conjunction of the existing predicate and the predicate of the incoming ifElse, and for mapElse, I used predicate's `or()` method to return the logical disjunction of the current predicate and the predicate of the incoming IfElse. 
Hope this helps!

**Comment by sp4ce-cowboy** [comment]
You can try using the default 'or' method in the Predicate interface.
