### ISSUE TITLE
PA2 Test Case 6

### ISSUE THREAD

**Issue by sp4ce-cowboy** [nus-cs2030/2223-s2#937]
Hi I seem to be having some problem with the last test case, I'm not too sure why even though I followed all the walkthrough video instructions.

<img width="1086" alt="image" src="https://user-images.githubusercontent.com/19762596/233785373-c340ce19-848c-405f-afd9-d6cf4e2c8ad5.png">

This test case is the same one in the Level 6 on CodeCrunch where `SumList sumlist = new SumList(List.of(1, 2, 3, 4, 5))` I think

**Comment by Aron113** [comment]
does your function return the integer in the list if the list has length of one only?
