### ISSUE TITLE
annoymous inner class

### ISSUE THREAD

**Issue by NeoHW** [nus-cs2030/2223-s2#939]
hi! can anyone explain what is an anonymous inner class used for and why do we use it?

**Comment by granolaluvr69** [comment]
[Here's](https://www.youtube.com/watch?v=DwtPWZn6T1A&ab_channel=CodingwithJohn) a video that might help.

To sum up,
Anonymous inner classes are used when you want to create a class that is a subtype of a class that is specified by the user.

`static Maybe<T> of(T thing) {
    return new Maybe<T>(){
        //method headers, attributes, etc
    };`

Anonymous inner classes are also used when you only want to be able to instantiate the class once and have its functionality and attributes abstracted from the client, like when you don't want to be able to call `.of()` on a maybe object that you have instantiated before to change it's attributes. You can refer to AY2122S2's Q3 and AY2223S1's Q4 for an example of such questions, or attempt exercise 4, maybe plus, for more practice. 

Hope this helps!

**Comment by Nicknzk** [comment]
<img width="470" alt="Screenshot 2023-04-23 at 10 32 04 PM" src="https://user-images.githubusercontent.com/121552001/233845825-feb50b99-6f6b-4bad-a496-b7519eff1527.png">
Regarding the implementation of anonymous inner class, can i check why is it that created the static empty() method as interfaces by right shouldnt allow instantiation?

also do any of yall have the complete method of how to do anonymous inner class as i believe this one didnt fully work during the lecture

**Comment by Hannybunny2001** [comment]
The inner class can perhaps be used to prevent cyclic dependencies as seen in the lecture notes (for the static of methods)

**Comment by tjdbryan** [comment]
@NeoHW great question!

**Comment by JustinGohkh** [comment]
helps prevent cyclic dependencies!
