### ISSUE TITLE
Time Limit Exceeded  

### ISSUE THREAD

**Issue by sporobolous** [nus-cs2030/2223-s2#94]
# Summary

Time Limit Exceeded, not sure why,

## Description:

I am having issues with using the Pair and PQ, need help in correcting my code as well.. I have checked my other Event files and there are fine... its just time part I think ><

## Code Snippets

while (!eventPQ.isEmpty()) {
            Event event1 = eventPQ.poll().first();
           
            Pair<Event, ImList<Server>> status = event1.executeEvent(serverList);
            Event event2 = status.first();
            serverList = status.second();

            String event1String = event1.toString();

            if (event1String != "end") {
                eventPQ = eventPQ.add(event2);
                eventOutput = eventOutput.add(event1);
            }
        }

## Screenshots

Screenshots (if any)

**Comment by yueqianh** [comment]
Hi! Did you update your queue after items are extracted from it? If not, it could have caused an infinite loop.

**Comment by leezhanpeng** [comment]
When you execute `Event event1 = eventPQ.poll().first();` , you did not actually update eventPQ since it is immutable.
Remember to do `eventPQ = event1.second()` . Hope it helps!

**Comment by leezhanpeng** [comment]
When you execute Event event1 = eventPQ.poll().first(); , you did not actually update eventPQ since it is immutable.
My suggestion is to to do poll your event as a pair first, then initialise event1. That way you can use .second() to update your PQ. Hope it helps!

**Comment by leezhanpeng** [comment]
When you execute `Event event1 = eventPQ.poll().first(); `, you did not actually update eventPQ since it is immutable.
My suggestion is to poll your PQ as a pair first, then initialise event1. That way you can use .second() to update your PQ. Hope it helps!

**Comment by gelalallaal** [comment]
You will need to update the PQ after using .poll(), if not the first event is never removed from the PQ in your simulator, and your pq will never be empty

**Comment by kayeugenia** [comment]
i faced the same issue last time, even though i already updated my PQ using .second(). my problem was fixed after i realised that my "leave" and "done" events were never removed from PQ even after I execute those two

**Comment by SimonSeeYongsheng** [comment]
I think you are not updating the PQ correctly

**Comment by sporobolous** [comment]
## Code Snippets

        while (!eventPQ.isEmpty()) {

            Pair<Event, PQ<Event>> eventFirst = eventPQ.poll();
            Event event1 = eventFirst.first();
            eventPQ = eventFirst.second();

            Pair<Event, ImList<Server>> status = event1.executeEvent(serverList);
            Event event2 = status.first();
            serverList = status.second();

            String event1String = event1.toString();

            if (event1String != "end") {
                eventPQ = eventPQ.add(event2);
                eventOutput = eventOutput.add(event1);
            }
        }

## Comments:
What about this code? I did this but I still get error :((

**Comment by sporobolous** [comment]
> i faced the same issue last time, even though i already updated my PQ using .second(). my problem was fixed after i realised that my "leave" and "done" events were never removed from PQ even after I execute those two

how did u change the code?

**Comment by LYEDominic** [comment]
I think you might be stuck in the while loop. I can't say for sure I understand how your code works but from what I'm seeing, the code will never end as your PQ will always be left with the "end" event. Hence, you'll be stuck at while(true), resulting in an infinite loop.

**Comment by imkwokyong** [comment]
I don't know whether this resolves the error, but I think you should use .equals() to compare two Strings instead of "==".

**Comment by LYEDominic** [comment]
Hi, I'm not exactly sure how your code works but it seems like you're stuck in the while loop forever. The problem might arise from eventPQ = eventPQ.add(event2). The code might not ever detect the "end" and keeps adding events into the PQ.

**Comment by sporobolous** [comment]
hi everyone thank you for your help! I managed to find where I was looping at!
