### ISSUE TITLE
Exercise 4 equals method

### ISSUE THREAD

**Issue by eesean** [nus-cs2030/2223-s2#940]
Hi all,

Would like to ask for advice as to how to correctly implement the equals method? Currently what I check for is 1) the other object is an instance of Maybe, 2) this == other and 3) if the toStrings are the same but this.isEmpty() is true (meaning empty Maybe).

I managed to clear the test cases given for level 1 but can't seem to pass the following test case in codecrunch:

<img width="464" alt="Screenshot 2023-04-22 224942" src="https://user-images.githubusercontent.com/110977266/233791719-ac85f42c-232b-42cc-b693-1f42fe4b59b9.png">

**Comment by bdonong** [comment]
Hi! I think instead of checking if the toStrings are the same, you could instead check if the value inside is the same. Something like `this.get().equals(other.get())`. You can try referring to the maybe context lecture since the equals method is quite similar.

**Comment by eesean** [comment]
Hi yep forgot that there is a similar implementation gone through in lecture, thanks!
