### ISSUE TITLE
PA2 test case 5

### ISSUE THREAD

**Issue by joshlimwe** [nus-cs2030/2223-s2#942]
# Summary
Supplier.get() called too many times

## Description 
Hello! For level 5 i changed all my "T problem" to "Supplier<T> problem", and for my right left and solve(bop) methods i changed "problem" to "problem.get()" shown in the code below, I would think that problem.get() would only be called once within the left right and solve(bop) methods themselves? Some suggestions on Github suggested creating a method that calls problem.get() and then using that value in an overloaded method, but i am a bit confused as to how that solves the problem. Thank you!

## Idea s
Describe the approach used (if applicable)

## Screenshots (if any): 
<img width="505" alt="image" src="https://user-images.githubusercontent.com/125873745/233794666-d1a8ea93-0f65-4871-9739-92e53978bd34.png">

**Comment by weitatftw** [comment]
having an overloaded method for left() and right() methods that takes in the problem.get() variable as an argument would eliminate the need for you to call problem.get() in your overloaded left() and right() methods, hence reducing the number of calls to get() which solves the issue of having too many calls to get()

**Comment by joshlimwe** [comment]
i see, thank you!

> having an overloaded method for left() and right() methods that takes in the problem.get() variable as an argument would eliminate the need for you to call problem.get() in your overloaded left() and right() methods, hence reducing the number of calls to get() which solves the issue of having too many calls to get() since you would be using the result of a call to problem.get() as an argument rather than calling problem.get() multiple times
