### ISSUE TITLE
PA2 Test Case 5

### ISSUE THREAD

**Issue by coderlimjingcheng** [nus-cs2030/2223-s2#944]
Hi everyone! I followed the walkthrough video for almost all of the parts, and when I run it on codecrunch I got this error in test case 5, where my (5,7) is being evaluated out of nowhere. Any help would be greatly appreciated.

<img width="910" alt="image" src="https://user-images.githubusercontent.com/124959195/233800784-fb490e5e-6be9-4f98-a7de-f6eb7b423d23.png">

This is the implementation of my left() (my right is the mostly the same, but pair.first() is replaced with pair.second()):

<img width="797" alt="image" src="https://user-images.githubusercontent.com/124959195/233800863-83fc57d8-1e3e-4320-b558-f7a455f8f94f.png">

This is the implementation of my solve:

<img width="593" alt="image" src="https://user-images.githubusercontent.com/124959195/233800929-3068e994-2b52-4ce6-8772-f16b3b5eb591.png">

**Comment by granolaluvr69** [comment]
Hi coderlimjingcheng, the problem probably lies with calling .get() in your static of method which accepts a `Function<T, Pair<Supplier<T>, Supplier<T>>>`.

cheers mate.

**Comment by Aron113** [comment]
your function recursively calls left and right and solve(bop) which uses .get() again. Try creating a variable at the start by calling .get() and using that variable for the rest of the implementation

**Comment by coderlimjingcheng** [comment]
Alright thanks guys, managed to resolve it!
