### ISSUE TITLE
Ex 5 task 1 - how to start?

### ISSUE THREAD

**Issue by gracico** [nus-cs2030/2223-s2#945]
I'm really unfamiliar with streams. Would appreciate any tips on how to implement the twinprime int stream

Currently, I have a closed range intstream and filtered for the prime numbers. 
How can I proceed to check for pairs though?

**Comment by jacoblimjy** [comment]
you need to add another criteria inside filter to check that x-2 or x+2 isPrime

**Comment by ringleading** [comment]
use the isPrime code from one of the recs, think its either 7 or somewhere around there
afterwards filter it again to make sure it's paired (like what jacob said above, either -2 or +2 is a prime)

**Comment by ringleading** [comment]
think of Streams as loops, literally:
if you have a List `exampleList` of [1,2,3,4,5], doing `exampleList.stream()` will return a Stream of elements 1, 2, 3, 4, 5. and from there on it's just like your Optionals, map it to a new value or filter with a predicate etc

**Comment by AmanDesai34** [comment]
You should use a method to check if a number is a prime. I believe the streams recitation has that and you can use that and the other method would be the logic condition using filter

**Comment by e0969533** [comment]
create a isPrime method to check if int n is prime, then can use filter to only filter out isPrime numbers and twinPrimes

**Comment by haqanh** [comment]
You can try having a helper method to check for prime (we went through isPrime in recitation iirc)

**Comment by gene2345** [comment]
you should use a helper method isPrime

**Comment by haphuong1810103** [comment]
you can use method isPrime with the use of IntStream and noneMatch, then you can use this to check that x-2 and x+2 isPrime

**Comment by omarsfs** [comment]
try using isPrime and filter

**Comment by jarenl0ke** [comment]
You can make use of a helper method isPrime() and filter it using it as a Predicate

**Comment by ugchongg** [comment]
you can try filtering twice, one to check if x is a prime number and another to check if the x+2/x-2 is a prime number

**Comment by dmidula** [comment]
You can filter to check if x is prime and if (x + 2) is prime or (x - 2) is prime. You can use isPrime() to help. The isPrime() method can be found in recitation 8.

**Comment by jiangen16** [comment]
I used a isPrime() to check if x is prime, as well as another filter to check if (x+2) or (x-2) is prime
