### ISSUE TITLE
Ex6 level 4

### ISSUE THREAD

**Issue by Maxxtucker** [nus-cs2030/2223-s2#947]
Hi, does anyone encounter the same problem? What is the cause of the problem, and how to solve this?
![image](https://user-images.githubusercontent.com/122298287/233824580-2acb8686-5a57-4b9f-84fc-401a9d718669.png)

**Comment by ringleading** [comment]
see #930

**Comment by Maxxtucker** [comment]
> 
@ringleading I try this res.stream().forEach(x -> System.out.println(x.thenCompose(a -> a.description()).join())); but the same error occurs. May I know how do you solve this problem

**Comment by ringleading** [comment]
> > 
> 
> @ringleading I try this res.stream().forEach(x -> System.out.println(x.thenCompose(a -> a.description()).join())); but the same error occurs. May I know how do you solve this problem

did you include the last few lines to stop the instant and print out the time taken?

**Comment by minhphongle** [comment]
i also have this problem as well have you managed to solve it yet?

**Comment by Maxxtucker** [comment]
> i also have this problem as well have you managed to solve it yet?

You have to include the time taken, using duration.

**Comment by ahndrayo00** [comment]
Hii I faced this issue too; the problem was that you were not printing the time. Make sure to stop the instant after printing out everything, then print the time out! Remember to import Duration too! The code can just copy from the original main code
