### ISSUE TITLE
Mock AY22/23 Q1

### ISSUE THREAD

**Issue by stxe09** [nus-cs2030/2223-s2#953]
How do we make sure there aren't cyclic dependencies?

These are givens:
- Class User uses Bot for join(Bot) method
- Class Bot is initiated with class User

Is this not already a form of cyclic dependency? any hints on how to solve this?

**Comment by ugchongg** [comment]
facing the same problem here...

**Comment by Nicknzk** [comment]
I believe the solution is to create an interface eg. UserInterface

then in the bot, replace all User with UserInterface

**Comment by stxe09** [comment]
hm ok i'll try that thanks!

**Comment by cweisong** [comment]
adding on to @Nicknzk's comment, (1) you can try making User class implement the new interface & (2) Bot class to use the new interface during initialisation and subsequent methods

**Comment by stxe09** [comment]
okay thanks!!
