### ISSUE TITLE
Ex 6 Level 3

### ISSUE THREAD

**Issue by secretApple** [nus-cs2030/2223-s2#955]
Followed the walkthrough but can't figure out what I missed out, what could have caused this error?

![image](https://user-images.githubusercontent.com/126102015/233847711-12cff796-998f-4507-99b6-5d3a69378d23.png)

**Comment by ringleading** [comment]
did u join the CF strings in the description methods after combining

**Comment by secretApple** [comment]
i found my mistake in the description method as you said thank you!!!
