### ISSUE TITLE
Exercise 2

### ISSUE THREAD

**Issue by hhuilingg** [nus-cs2030/2223-s2#96]
Are we not allowed to use comparator API in exercises? 
![Error for Comparator API](https://user-images.githubusercontent.com/66964985/218053371-417df371-8eae-4d32-82b5-e829d3984f0a.jpg)

**Comment by fy17ohhh** [comment]
I think for exercise 2 you do not need Comparator

**Comment by hhuilingg** [comment]
then what if i need to sort?

**Comment by fy17ohhh** [comment]
> then what if i need to sort
just checked my code for ex2, I think for ex2 there's no need to sort. you will be able to get desired output by natural ordering

**Comment by ashleyang2001** [comment]
Hi, we are not allowed to use Comparator for this exercise apparently. If you used .set() instead of .remove() for your activeservices list, then you can make a method to do a simple sort (like bubble sort) to get the output in level3.jsh.

**Comment by aa01xx** [comment]
Hi, we are not allowed to use Comparator for this exercise apparently. If you used .set() instead of .remove() for your activeservices list, then you can make a method to do a simple sort (like bubble sort) to get the output in level3.jsh.

**Comment by guanquann** [comment]
#97

**Comment by hhuilingg** [comment]
Thankyou everyone! would also like to add on here that we need to be very careful when using .remove() in a loop as there may be changes in index
