### ISSUE TITLE
Imports

### ISSUE THREAD

**Issue by ongjunfeng17** [nus-cs2030/2223-s2#961]
Hi, for the final exams, does anyone know if it is necessary for us to include import statements? Or are import statements simply for us to do our own debugging / testing? 

TIA!

**Comment by reinatng10** [comment]
Hello, I dont think you need to include any import statements unless stated by the question. We wont have to compile our codes during the exam as it wld be manually checked for correctness.

**Comment by vVicksv** [comment]
It's for your own testing, for finals there is not any requirement to import anything

**Comment by minhphongle** [comment]
idt we have to include improt statements! hope that helps

**Comment by leezhanpeng** [comment]
Iirc prof mentioned that your code will likely not be compiled on their end. So import only if you are testing it on your side!

**Comment by sohjoana** [comment]
Just clarified with my TA, there is no need to import :)

**Comment by aeraeroaer** [comment]
nope, imports are not necessary, hope this helps!

**Comment by NeoHW** [comment]
nope!

**Comment by ongjunfeng17** [comment]
Thanks everyone!
