### ISSUE TITLE
Github handle collection form

### ISSUE THREAD

**Issue by aeraeroaer** [nus-cs2030/2223-s2#962]
Hi all, does anyone have the link to github handle collection? I cant seem to find it anywhere. Thank you!

**Comment by weitatftw** [comment]
https://forms.gle/NYjH6c8wfGjhYs4U9

**Comment by timothysashimi** [comment]
i found this: https://forms.gle/NYjH6c8wfGjhYs4U9

**Comment by aeraeroaer** [comment]
thank you!
