### ISSUE TITLE
Can lazy evaluation be done without using stream?

### ISSUE THREAD

**Issue by pxlanleh** [nus-cs2030/2223-s2#964]
Was doing a Past Year qn when I came across a problem with lazy evaluation. May I know if lazy evaluation can be done without Streams? If so, how can it be done? Thanks!

**Comment by poon-zx** [comment]
hey pxlanleh, great question! I think that lazy evaluation is usually done using a supplier, typically defined using a lambda expression like this: () -> ... Hope this helped and happy to answer any follow-up question you have :)

**Comment by e0969489** [comment]
Hope this helps!

**Comment by reinatng10** [comment]
Hello! I think the notes covered lazy evaluation concept for supplier and stream's intermediate operations.
