### ISSUE TITLE
1819 Sem 1 Q3

### ISSUE THREAD

**Issue by JYeoZS** [nus-cs2030/2223-s2#965]
Hi, any ideas how to solve this question?

Basically, collections are not allowed to be used. Need to get first and last term of a stream in one pipeline.

Much thanks.
<img width="389" alt="Screenshot 2023-04-26 at 8 50 09 AM" src="https://user-images.githubusercontent.com/122290983/234438558-2ea3ab6d-6de9-4ec4-a990-9d3ac81b9f5b.png">

**Comment by jorwong** [comment]
For this question you could consider mapping each integer in the instream into a MinMax object

**Comment by JYeoZS** [comment]
Hi, but the minMax object needs to have:
1. First number in stream
2. last number in stream

Not possible to map: MinMax(x,x), where x is each integer in stream.

**Comment by jorwong** [comment]
Hi, it is possible to map by doing this map(x -> new minMax(x,x))...
it doesn't necessarily have to be the first number and last number in the stream

**Comment by JYeoZS** [comment]
Hi, would this provide the wrong output, as -123 and 456 is the first and last number in stream?

The output could end up as Optional[-123, -123] or otherwise, anything but 2 different numbers.

Thanks.

<img width="321" alt="Screenshot 2023-04-26 at 9 13 23 AM" src="https://user-images.githubusercontent.com/122290983/234440966-834bab63-5e97-4148-bf3c-91aa5f9990ab.png">

**Comment by jorwong** [comment]
What I did was 
- map every int in the stream to a minMax Object
- use reduce to compare 2 minMax objects and output a new minMax with the min & max values of two minMax Object

**Comment by JYeoZS** [comment]
Ah tried that worked... Much thanks.

Didn't realise the min and max were not private final.... haiz...
