### ISSUE TITLE
annonymous inner class

### ISSUE THREAD

**Issue by wjkb** [nus-cs2030/2223-s2#966]
what are the purposes of annonymous inner class?

**Comment by Chuacx13** [comment]
1) to create an instance of the class
2) prevent static methods from being called anywhere in the pipeline

**Comment by emmannyyy** [comment]
From what I've gathered, here are some potential use cases:

1. Anonymous classes can be used to avoid cyclic dependencies. 
Anonymous classes can be used to instantiate **abstract classes**, and subsequently, override methods, to create other anonymous classes within them. This can be very useful for avoiding cyclic dependencies. 

2. Anonymous classes are useful for instantiating SAM interfaces. 
-> e.g: we can create an anonymous class for Comparators.

3. Coupled with interfaces that have static methods (e.g: factory methods like of()), anonymous classes can be used to ensure that instances of a class no longer have any static methods that are callable. (this was one of the exercises, Maybe plus)


Not too sure if there are any other good use cases apart from these, but if you do think of any, please let me know :-)

**Comment by bawowo** [comment]
There are different reasons to use anonymous inner class
Some useful advantages of anonymous inner class is that 
1. Avoid cyclic dependencies, there will be no cyclic dependency (all the classes are within the same class)
2. For instantiating SAM interfaces 
3. Anonymous inner classes can be used to define small, self-contained tasks that can be run asynchronously in a separate thread

**Comment by ianwonghanli** [comment]
As seen in the mock paper question 4, we can use anonymous inner class to prevent the initialisation of multiple methods of the same name and return type.

Such as:

interface ImList<E> ... {
   static <E> ImList<E> of() {
      return new ImList<E>(){
        // list of public methods of ImList
      };
    }
}

We can see that ImList.<E>of() would generate a new ImList class with the specified methods. However, if the inner class does not have a of() method, ImList<E>of().of() would return an error
