### ISSUE TITLE
Finals grading format

### ISSUE THREAD

**Issue by Leeeef552** [nus-cs2030/2223-s2#967]
does anyone know how we will be graded for the finals?

will we be graded on how close / how similar we are to the final solution / based on design or like if its wrong its entirely wrong?

**Comment by reinatng10** [comment]
Hello! My TA told me that it will be manually marked for correctness and there will be method marks for your code. Hope this helps:)

**Comment by kaiyanggg** [comment]
I think it might be marked based on logic, ie prof said that the code does not need to compile but if the idea is correct and fits the restrictions it should be fine

**Comment by Leeeef552** [comment]
Ok! thanks for the responses
