### ISSUE TITLE
ex2 level 3.jsh

### ISSUE THREAD

**Issue by jayson237** [nus-cs2030/2223-s2#97]
Hi, I was wondering what are we suppose to do for the Cruise exercise, especially level 3

**Comment by WXUXIN** [comment]
For level 3, create a .jsh file that contains a function serveCruises. You should do the following: 
1.) Create empty lists (Active, Expired, etc ...)
2.) For each cruise in the list of cruises, loop thorugh the ACTIVE queue and find a way to transfer the expired services (Arrival time of incoming cruise >= service end time of service) into the EXPIRED queue.

2a.) For each cruise in the list of cruises, for the number of loaders required, check if there are expired services in EXPIRED queue. If there is, you want to make that service active by serving the new cruise. If the EXPIRED queue is empty, you want to create a new service with a new loader, and put it in the ACTIVE queue. Make sure to also add each service update (be it changing from expired service to active or creating a new service into a list you want to return)

**Comment by aa01xx** [comment]
To add on,
For level 4 and 5 you would then have to use inheritance to perform polymorphism and overriding some methods such that you don't have to modify your other classes.

**Comment by hhuilingg** [comment]
hi, you may want to change the subject to EX2 level 3 instead :)

**Comment by jayson237** [comment]
okay thanks

**Comment by jayson237** [comment]
What does it mean to have an active service or expired service?

**Comment by hhuilingg** [comment]
> What does it mean to have an active service or expired service?
> 
> 

having 2 lists (active & expired) so that we can transfer the service from one list to another

**Comment by jayson237** [comment]
i see, and what does it actually mean to be active, is it service done or others?

**Comment by hhuilingg** [comment]
> i see, and what does it actually mean to be active, is it service done or others?

active is to check if the service has been completed, if yes it will be transferred to expired.

expired is to reactive the loader with new cruise (which is also mean a new service) and this new service will now transfer to active
