### ISSUE TITLE
Lab 3 NoSuchElementException in CodeCrunch

### ISSUE THREAD

**Issue by imkwokyong** [nus-cs2030/2223-s2#99]
# Summary

Code works fine in Docker, throws exception in CodeCrunch

## Description:

Hi everyone, I am facing this issue where my code passes the test cases in my container but keep throwing NoSuchElementException in CodeCrunch. May I know where is the problem?

I suspect it has something to do with the Supplier but I can't find a way to fix it. (getServiceTime() uses this.serviceTime.get() as specified in the Lab pdf)

## Screenshots

![image](https://user-images.githubusercontent.com/110521168/218133155-8f2c4133-93fa-4141-88d8-6bb7b13da8c0.png)

![image](https://user-images.githubusercontent.com/110521168/218132735-90568ce6-e769-4621-a473-38d1911cca6f.png)

**Comment by wongjingwen** [comment]
Are you able to print out the objects/elements in the list? It seems like the NoSuchElementException may be due to the data structure being empty or the next element is requested after reaching the end of the structure. 

Are you using ArrayList to store your data?

**Comment by imkwokyong** [comment]
Yes, I am able to print out the elements. 
I only use the data structures that are given, i.e. ImList, PQ and Pair.

**Comment by imkwokyong** [comment]
Now the error output changed again...
![image](https://user-images.githubusercontent.com/110521168/218152182-47d5ffa2-ddd9-4782-aee5-1f13cf5fb293.png)

But I only called getServiceTime() in my ServeEvent class, so I don't understand what went wrong...

**Comment by imkwokyong** [comment]
Issue found (accidentally called getServiceTime() somewhere else)
